/*
SET NOEXEC OFF;
--*/ SET NOEXEC ON;
GO

USE master;
GO

DROP DATABASE IF EXISTS WWIDWH;
GO

CREATE DATABASE [WWIDWH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WWIDWH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\WWIDWH.mdf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WWIDWH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\WWIDWH_log.ldf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
GO

USE WWIDWH;
GO
