/*
SET NOEXEC OFF;
--*/ SET NOEXEC ON;
GO

USE WWIDWH;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Landing') EXEC('CREATE SCHEMA Landing AUTHORIZATION dbo;');
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Staging') EXEC('CREATE SCHEMA Staging AUTHORIZATION dbo;');
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Dim') EXEC('CREATE SCHEMA Dim AUTHORIZATION dbo;');
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Fact') EXEC('CREATE SCHEMA Fact AUTHORIZATION dbo;');
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Bridge') EXEC('CREATE SCHEMA Bridge AUTHORIZATION dbo;');
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'Updt') EXEC('CREATE SCHEMA Updt AUTHORIZATION dbo;');
GO
