CREATE TABLE [METRAPQ].[QuoteRilevate] (
    [N]                                                       BIGINT          NOT NULL,
    [HistoricalHashKey]                                       VARBINARY (20)  NULL,
    [ChangeHashKey]                                           VARBINARY (20)  NULL,
    [InsertDatetime]                                          DATETIME        NOT NULL,
    [UpdateDatetime]                                          DATETIME        NOT NULL,
    [IsDeleted]                                               BIT             NULL,
    [DataCollaudo]                                            SMALLDATETIME   NULL,
    [IDClassificazioneProdotto]                               NVARCHAR (50)   NULL,
    [ClassificazioneProdottoImpostata]                        BIT             NULL,
    [NumeroLotto]                                             NVARCHAR (15)   NULL,
    [InserimentoManuale]                                      BIT             NULL,
    [Cliente]                                                 NVARCHAR (150)  NULL,
    [RiferimentoCliente]                                      NVARCHAR (150)  NULL,
    [CodiceCliente]                                           NVARCHAR (50)   NULL,
    [Campionatura]                                            BIT             NULL,
    [CampionaturaTipo]                                        NVARCHAR (50)   NULL,
    [Pressa]                                                  NVARCHAR (50)   NULL,
    [OperatoreCollaudo]                                       NVARCHAR (50)   NULL,
    [Quantometro]                                             NVARCHAR (20)   NULL,
    [AspettoSuperficiale]                                     NVARCHAR (100)  NULL,
    [PesoTeorico]                                             REAL            NULL,
    [PesoCalcolato]                                           REAL            NULL,
    [Peso]                                                    REAL            NULL,
    [CodiceMetra]                                             NVARCHAR (12)   NULL,
    [BarraMatrice]                                            INT             NULL,
    [DataEstrusione]                                          SMALLDATETIME   NULL,
    [Rugosimetro]                                             NVARCHAR (50)   NULL,
    [Calibro]                                                 NVARCHAR (50)   NULL,
    [MacchinaDiMisura]                                        NVARCHAR (50)   NULL,
    [Rotondimetro]                                            NVARCHAR (50)   NULL,
    [MotivoNonConformita]                                     NVARCHAR (4000) NULL,
    [etichettaMotivoNonConformita]                            NVARCHAR (200)  NULL,
    [Rullare]                                                 BIT             NULL,
    [Rullato]                                                 BIT             NULL,
    [Scartare]                                                BIT             NULL,
    [RipetereTT]                                              BIT             NULL,
    [SelezionareRicontrollare]                                BIT             NULL,
    [AccettatoInDeroga]                                       BIT             NULL,
    [Altro]                                                   BIT             NULL,
    [ControlloImballoEseguito]                                BIT             NULL,
    [DecisioniPreseAzioniCorrettive]                          NVARCHAR (4000) NULL,
    [EsitoRilavorazione]                                      NVARCHAR (4000) NULL,
    [Conformità]                                              NVARCHAR (2)    NULL,
    [FirmaRilavorazione]                                      NVARCHAR (50)   NULL,
    [ControllatoDa]                                           NVARCHAR (40)   NULL,
    [IdoneoAllaSpedizione]                                    BIT             NULL,
    [IdoneoControlloCliente]                                  BIT             NULL,
    [DataSvincolo]                                            SMALLDATETIME   NULL,
    [CollaudoCliente]                                         BIT             NULL,
    [BilletteDaEstrudere]                                     SMALLINT        NULL,
    [BilletteEstruse]                                         SMALLINT        NULL,
    [Eliminata]                                               BIT             NULL,
    [Riconciliato]                                            BIT             NULL,
    [EstrusioneEsterna]                                       BIT             NULL,
    [EstrusioneEsternaNumeroDDT]                              NVARCHAR (50)   NULL,
    [EstrusioneEsternaDataDDT]                                DATETIME        NULL,
    [EstrusioneEsternaFornitore]                              NVARCHAR (50)   NULL,
    [CaratteristicheMeccanicheNonConformi]                    NVARCHAR (500)  NULL,
    [LegaPredefinita]                                         NVARCHAR (50)   NULL,
    [LegaPredefinita_IDClassificazioneCaratteristiche]        NVARCHAR (50)   NULL,
    [StatoFisicoPredefinito]                                  NVARCHAR (50)   NULL,
    [StatoFisicoPredefinito_IDClassificazioneCaratteristiche] NVARCHAR (50)   NULL,
    [DurezzaMaxRichiesta]                                     REAL            NULL,
    [DurezzaMaxRichiesta_IDClassificazioneCaratteristiche]    NVARCHAR (50)   NULL,
    [DurezzaMinRichiesta]                                     REAL            NULL,
    [DurezzaMinRichiesta_IDClassificazioneCaratteristiche]    NVARCHAR (50)   NULL,
    [RMRichiesto]                                             REAL            NULL,
    [RmRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RPRichiesto]                                             REAL            NULL,
    [RpRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [ARichiesto]                                              REAL            NULL,
    [ARichiesto_IDClassificazioneCaratteristiche]             NVARCHAR (50)   NULL,
    [ARichiestoTipo]                                          NVARCHAR (10)   NULL,
    [RARichiesto]                                             REAL            NULL,
    [RaRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RTRichiesto]                                             REAL            NULL,
    [RtRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RZRichiesto]                                             REAL            NULL,
    [RzRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RMaxRichiesto]                                           REAL            NULL,
    [RmaxRichiesto_IDClassificazioneCaratteristiche]          NVARCHAR (50)   NULL,
    [Sistema]                                                 NVARCHAR (200)  NULL,
    [SistemaID]                                               NVARCHAR (50)   NULL,
    [Serie]                                                   NVARCHAR (200)  NULL,
    [SerieID]                                                 NVARCHAR (50)   NULL,
    [Commessa]                                                NVARCHAR (500)  NULL,
    [NumeroCommessa]                                          NVARCHAR (50)   NULL,
    [ResponsabileAvvioProduzione]                             NVARCHAR (250)  NULL,
    [OpportunitaNumero]                                       NVARCHAR (255)  NULL,
    [OpportunitaDescrizione]                                  NVARCHAR (255)  NULL,
    [OpportunitaIDSaleforce]                                  NVARCHAR (255)  NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_METRAPQ_QuoteRilevate_BusinessKey]
    ON [METRAPQ].[QuoteRilevate]([N] ASC);
GO

ALTER TABLE [METRAPQ].[QuoteRilevate]
    ADD CONSTRAINT [PK_METRAPQ_QuoteRilevate] PRIMARY KEY CLUSTERED ([UpdateDatetime] ASC, [N] ASC);
GO

