CREATE TABLE [METRAPQ].[QuoteRichieste] (
    [NumeroProgressivo]                                       INT             NOT NULL,
    [HistoricalHashKey]                                       VARBINARY (20)  NULL,
    [ChangeHashKey]                                           VARBINARY (20)  NULL,
    [InsertDatetime]                                          DATETIME        NOT NULL,
    [UpdateDatetime]                                          DATETIME        NOT NULL,
    [IsDeleted]                                               BIT             NULL,
    [CodiceMetra]                                             NVARCHAR (50)   NOT NULL,
    [Revisione]                                               INT             NOT NULL,
    [UltimaModifica]                                          NVARCHAR (50)   NULL,
    [DataModificaArchivio]                                    SMALLDATETIME   NULL,
    [IDClassificazioneProdotto]                               NVARCHAR (50)   NULL,
    [Ascona]                                                  BIT             NULL,
    [Strappo]                                                 BIT             NULL,
    [Dima]                                                    BIT             NULL,
    [numeroCassetto]                                          NVARCHAR (2)    NULL,
    [CertificatiRichiesti]                                    BIT             NULL,
    [particolareDiSicurezza]                                  BIT             NULL,
    [prodottoStandard]                                        NVARCHAR (200)  NULL,
    [rullatura]                                               BIT             NULL,
    [ControlloUltrasuoni]                                     BIT             NULL,
    [marcareBarre]                                            BIT             NULL,
    [AssegnareLotto]                                          BIT             NULL,
    [NoteRGQ]                                                 NVARCHAR (MAX)  NULL,
    [SegnalazioniContestazioni]                               NVARCHAR (MAX)  NULL,
    [ScorrimentoT]                                            SMALLINT        NULL,
    [NormaTolleranze]                                         NVARCHAR (20)   NULL,
    [LegaPredefinita]                                         NVARCHAR (50)   NULL,
    [LegaPredefinita_IDClassificazioneCaratteristiche]        NVARCHAR (50)   NULL,
    [StatoFisicoPredefinito]                                  NVARCHAR (50)   NULL,
    [StatoFisicoPredefinito_IDClassificazioneCaratteristiche] NVARCHAR (50)   NULL,
    [DurezzaMaxRichiesta]                                     REAL            NULL,
    [DurezzaMaxRichiesta_IDClassificazioneCaratteristiche]    NVARCHAR (50)   NULL,
    [DurezzaMinRichiesta]                                     REAL            NULL,
    [DurezzaMinRichiesta_IDClassificazioneCaratteristiche]    NVARCHAR (50)   NULL,
    [RMRichiesto]                                             REAL            NULL,
    [RmRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RPRichiesto]                                             REAL            NULL,
    [RpRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [ARichiesto]                                              REAL            NULL,
    [ARichiesto_IDClassificazioneCaratteristiche]             NVARCHAR (50)   NULL,
    [ARichiestoTipo]                                          NVARCHAR (10)   NULL,
    [RARichiesto]                                             REAL            NULL,
    [RaRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RTRichiesto]                                             REAL            NULL,
    [RtRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RZRichiesto]                                             REAL            NULL,
    [RzRichiesto_IDClassificazioneCaratteristiche]            NVARCHAR (50)   NULL,
    [RMaxRichiesto]                                           REAL            NULL,
    [RmaxRichiesto_IDClassificazioneCaratteristiche]          NVARCHAR (50)   NULL,
    [NormaCaratteristicheMeccaniche]                          NVARCHAR (50)   NULL,
    [NormaProveDurezza]                                       NVARCHAR (50)   NULL,
    [NormaProveDiTrazione]                                    NVARCHAR (50)   NULL,
    [NormaRugosita]                                           NVARCHAR (50)   NULL,
    [TolleranzaCommercialeDelPesoSup]                         NUMERIC (18, 2) NULL,
    [TolleranzaCommercialeDelPesoInf]                         NUMERIC (18, 2) NULL,
    [Sistema]                                                 NVARCHAR (200)  NULL,
    [SistemaID]                                               NVARCHAR (50)   NULL,
    [Serie]                                                   NVARCHAR (200)  NULL,
    [SerieID]                                                 NVARCHAR (50)   NULL,
    [Commessa]                                                NVARCHAR (500)  NULL,
    [NumeroCommessa]                                          NVARCHAR (50)   NULL,
    [NormaProprietaMeccaniche]                                NVARCHAR (50)   NULL,
    [OpportunitaNumero]                                       NVARCHAR (255)  NULL,
    [OpportunitaDescrizione]                                  NVARCHAR (255)  NULL,
    [OpportunitaIDSaleforce]                                  NVARCHAR (255)  NULL,
    [TipoDurezza]                                             NVARCHAR (50)   NULL
);
GO

ALTER TABLE [METRAPQ].[QuoteRichieste]
    ADD CONSTRAINT [PK_METRAPQ_QuoteRichieste] PRIMARY KEY CLUSTERED ([UpdateDatetime] ASC, [NumeroProgressivo] ASC);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_METRAPQ_QuoteRichieste_BusinessKey]
    ON [METRAPQ].[QuoteRichieste]([NumeroProgressivo] ASC);
GO

