
CREATE VIEW AX2009.BOMCALCTABLE_CalcoloDBAView
AS
SELECT
	-- Chiavi
	BCT.DATAAREAID,		-- IDAzienda
	BCT.PRICECALCID,	-- IDCalcoloDBA
	BCT.RECID,			-- PKCalcoloDBA

	-- Dimensioni
	BCT.ITEMID,			-- IDArticoloConfigurato
	BCT.TRANSDATE		-- DataTransazione

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.BOMCALCTABLE BCT
INNER JOIN (
	SELECT DISTINCT
		DATAAREAID,
		PRICECALCID
	FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.INVENTITEMPRICE
	WHERE DATAAREAID IN (N'mspa', N'imet', N'mrag', N'malu')

	UNION

	SELECT DISTINCT
		DATAAREAID,
		PRICECALCID
	FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.INVENTITEMPRICESIM
	WHERE DATAAREAID IN (N'mspa', N'imet', N'mrag', N'malu')
) PCIV ON BCT.DATAAREAID = PCIV.DATAAREAID AND BCT.PRICECALCID = PCIV.PRICECALCID
WHERE BCT.TRANSDATE >= CAST('20230101' AS DATETIME);
GO

