
CREATE VIEW AX2009.BOMVERSION_VersioneDBAView
AS
SELECT
	-- Chiavi
	DATAAREAID,	-- IDAzienda
	BOMID,		-- IDVersioneDBA
	RECID,		-- PKVersioneDBA

	-- Dimensioni
	TODATE,		-- DataFineValidita
	FROMDATE,	-- DataInizioValidita
	ITEMID		-- IDArticoloConfigurato

FROM (
	SELECT
		DATAAREAID,
		BOMID,
		RECID,
		TODATE,
		FROMDATE,
		ITEMID,
		ROW_NUMBER() OVER (PARTITION BY DATAAREAID, ITEMID, FROMDATE, TODATE ORDER BY BOMID DESC) AS rn

	FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.BOMVERSION
	WHERE ACTIVE = 1
		AND APPROVED = 1
) BVD
WHERE BVD.rn = 1;
GO

