
CREATE VIEW AX2009.COMMISSIONSALESREP_AgenteView
AS
SELECT
	-- Chiavi
	DATAAREAID,		-- IDAzienda
	GROUPID,		-- IDGruppoVendite
	EMPLID,		-- IDDipendente
	RECID		-- IDAgente

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.COMMISSIONSALESREP;
GO

