
CREATE VIEW AX2009.DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizziView
AS
SELECT
	-- Chiavi
	DATAAREAID,		-- IDAzienda
	PARTYADDRESSRELATIONSHIPRECID,		-- PKIndirizzoRubrica
	ADDRESSRECID,		-- PKIndirizzo
	REFCOMPANYID,		-- IDAziendaRiferimento
	RECID		-- PKMappingIndirizzi

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.DIRPARTYADDRESSRELATIONSHI1066;
GO

