/**
 * @view AX2009.INVENTPOSTING_Changes

*/
CREATE   VIEW AX2009.INVENTPOSTING_Changes
AS
WITH HistoryDetail
AS (
    SELECT
        DATAAREAID,
        INVENTACCOUNTTYPE,
        ITEMCODE,
        ITEMRELATION,
        CUSTVENDCODE,
        CUSTVENDRELATION,
        TAXGROUPID,
        COSTCODE,
        COSTRELATION,
        FROMDATE,
        TODATE,
        LEDGERACCOUNTID,
        IsActive,
        ROW_NUMBER() OVER (PARTITION BY DATAAREAID,
            INVENTACCOUNTTYPE,
            ITEMCODE,
            ITEMRELATION,
            CUSTVENDCODE,
            CUSTVENDRELATION,
            TAXGROUPID,
            COSTCODE,
            COSTRELATION
        ORDER BY FROMDATE, TODATE) AS rn

    FROM AX2009.INVENTPOSTING_History
)
SELECT TOP (100) PERCENT
    HD0.DATAAREAID,
    HD0.INVENTACCOUNTTYPE,
    HD0.ITEMCODE,
    HD0.ITEMRELATION,
    HD0.CUSTVENDCODE,
    HD0.CUSTVENDRELATION,
    HD0.TAXGROUPID,
    HD0.COSTCODE,
    HD0.COSTRELATION,
    HD0.FROMDATE AS FROMDATE_Old,
    HD0.TODATE AS TODATE_Old,
    HD0.LEDGERACCOUNTID AS LEDGERACCOUNTID_Old,
    HD0.IsActive AS IsActive_Old,
    HD1.FROMDATE AS FROMDATE_New,
    HD1.TODATE AS TODATE_New,
    HD1.LEDGERACCOUNTID AS LEDGERACCOUNTID_New,
    HD1.IsActive AS IsActive_New

FROM HistoryDetail HD0
INNER JOIN HistoryDetail HD1 ON HD1.DATAAREAID = HD0.DATAAREAID
    AND HD1.INVENTACCOUNTTYPE = HD0.INVENTACCOUNTTYPE
    AND HD1.ITEMCODE = HD0.ITEMCODE
    AND HD1.ITEMRELATION = HD0.ITEMRELATION
    AND HD1.CUSTVENDCODE = HD0.CUSTVENDCODE
    AND HD1.CUSTVENDRELATION = HD0.CUSTVENDRELATION
    AND HD1.TAXGROUPID = HD0.TAXGROUPID
    AND HD1.COSTCODE = HD0.COSTCODE
    AND HD1.COSTRELATION = HD0.COSTRELATION
    AND HD1.rn = HD0.rn + 1
ORDER BY HD0.DATAAREAID,
    HD0.INVENTACCOUNTTYPE,
    HD0.ITEMCODE,
    HD0.ITEMRELATION,
    HD0.CUSTVENDCODE,
    HD0.CUSTVENDRELATION,
    HD0.TAXGROUPID,
    HD0.COSTCODE,
    HD0.COSTRELATION,
    HD0.rn;
GO

GRANT SELECT
    ON OBJECT::[AX2009].[INVENTPOSTING_Changes] TO [checkdata]
    AS [dbo];
GO

