
CREATE VIEW AX2009.INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscaleView
AS
SELECT
	-- Chiavi
	DATAAREAID,		-- IDAzienda
	JOURNALID,		-- IDGiornaleLIFOFiscale
	RECID,		-- PKGiornaleLIFOFiscale

	-- Dimensioni
	DESCRIPTION		-- GiornaleLIFOFiscale

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.INVENTFISCALLIFOJOURNALTABLE;
GO

