
CREATE VIEW AX2009.INVENTTABLE_ArticoloConfiguratoView
AS
SELECT
    -- Chiavi
    DATAAREAID,        -- IDAzienda
    ITEMID,        -- IDArticoloConfigurato
    RECID,        -- PKArticoloConfigurato

    -- Dimensioni
    ITEMGROUPID,        -- IDArticoloGruppoArticoli
    ITEMNAME,        -- ArticoloConfigurato
    ITEMTYPE,        -- IDTipoDiArticolo [enum ItemType]
    REQGROUPID,        -- IDGruppoCopertura
    PRIMARYVENDORID,        -- IDFornitore
    DIMENSION,        -- IDAreaGeografica
    DIMENSION2_,        -- IDProdottoVendita
    DIMENSION3_,        -- IDProdottoAcquisto
    DIMENSION4_,        -- IDFaseDiGruppo
    DIMENSION5_,        -- IDInfraGruppo
    DIMENSION6_,        -- IDMacroArea
    INTRACODE,        -- VoceDoganale
    PBAITEMAUTOGENERATED,        -- IsGeneratoAutomaticamente
    STOPEXPLODE,        -- IsInterrompiEsplosione
    COMMISSIONGROUPID,        -- IDGruppoProvvigioni
    FISCALLIFOAVOIDCALC,        -- IsEvitaCalcoloLIFO
    BOMCALCGROUPID,        -- IDGruppoCalcoloDBA
    PBAITEMCONFIGURABLE,        -- IsConfigurabile
    NETWEIGHT_KG,        -- PesoNetto
    NPOPBAREFITEMID,        -- IDArticolo
    NPOASITEMALIAS,        -- AliasAS400
    NPOINVENTITEMTYPE,        -- IDTipoArticolo
    NPOWRKCTRGROUPID,        -- IDMatrice
    NPOINVENTABCCODE,        -- GruppoABC
    NPOITEMLENGTH,        -- LunghezzaBarraDescrizione
    NPOITEMFINISHINGID,        -- IDFinitura
    NPOREVENUERAWTYPE,        -- IsArticoloRicavoPerGrezzo
    NPOREVENUEGROUPID,        -- IDGruppoRicavi
    NCESCRAPITEMID,        -- IDArticoloScarto
    CONVERT(DATE, CREATEDDATETIME) AS CREATEDDATETIME        -- DataCreazione

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.INVENTTABLE
WHERE ITEMID <> N'';
GO

