
CREATE VIEW AX2009.LEDGERTABLE_ContoCoGeView
AS
SELECT
	-- Chiavi
	LT.DATAAREAID,		-- IDAzienda
	LT.ACCOUNTNUM,		-- IDContoCoGe
	LT.RECID,		-- PKContoCoGe

	-- Dimensioni
	LT.ACCOUNTNAME,		-- ContoCoGe
    COALESCE(LAC.ACCOUNTCATEGORY, CASE WHEN LT.ACCOUNTCATEGORYREF = N'' THEN N'' ELSE N'<???>' END) AS ACCOUNTCATEGORY -- CategoriaCoGe

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.LEDGERTABLE LT
LEFT JOIN [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.LEDGERACCOUNTCATEGORY LAC ON LAC.DATAAREAID = LT.DATAAREAID AND LAC.ACCOUNTCATEGORYREF = LT.ACCOUNTCATEGORYREF;
GO

