
CREATE VIEW AX2009.METWMSORDERTRANSPLANNED_PianificazionePrelieviView
AS
SELECT
    -- Chiavi
    RECID,        -- PKPianificazionePrelievi

    -- Misure
    REQPOID,        -- REQPOID
    CRSNUM,        -- CRSNUM
    CRSEXPEDITIONSTATUS,        -- CRSEXPEDITIONSTATUS
    COVERINGBASIS,        -- COVERINGBASIS
    ANALYSISTYPE,        -- ANALYSISTYPE
    INCLUDEINBOUNDDOCK,        -- INCLUDEINBOUNDDOCK
    SHIPMENTTYPE,        -- SHIPMENTTYPE
    PROCESSNUM,        -- PROCESSNUM
    PICKINGSTATUS,        -- PICKINGSTATUS
    REMAINONHANDQTY,        -- REMAINONHANDQTY
    REMAINPHYSICAL,        -- REMAINPHYSICAL
    REMAINSALESPHYSICAL,        -- REMAINSALESPHYSICAL
    PICKINGROUTEID,        -- PICKINGROUTEID
    SHIPMENTID,        -- SHIPMENTID
    PICKINGROUTEEXPEDITIONSTATUS,        -- PICKINGROUTEEXPEDITIONSTATUS
    INVENTLOCATIONID,        -- INVENTLOCATIONID
    WORKSPACE,        -- WORKSPACE
    DLVSTATIONID,        -- DLVSTATIONID
    DLVAREAID,        -- DLVAREAID
    QTY,        -- QTY
    ORDERTYPE,        -- ORDERTYPE
    WMSORDERTRANSEXPEDITIONSTATUS,        -- WMSORDERTRANSEXPEDITIONSTATUS
    ITEMID,        -- ITEMID
    ORDERID,        -- ORDERID
    INVENTDIMID,        -- INVENTDIMID
    DLVDATE,        -- DLVDATE
    INVENTTRANSID,        -- INVENTTRANSID
    INVENTTRANSTYPE,        -- INVENTTRANSTYPE
    INVENTTRANSREFID,        -- INVENTTRANSREFID
    CUSTOMER,        -- CUSTOMER
    DELIVERYADDRESS,        -- DELIVERYADDRESS
    KASTOID,        -- KASTOID
    SALESIDSPLIT,        -- SALESIDSPLIT
    DATAAREAID,        -- DATAAREAID
    PICKAVAILABLE,        -- PICKAVAILABLE
    INVENTITEMTYPE,        -- INVENTITEMTYPE
    ITEMFINISHINGIDFINAL,        -- ITEMFINISHINGIDFINAL
    ITEMFINISHINGID,        -- ITEMFINISHINGID
    INVENTLOCATIONIDTO,        -- INVENTLOCATIONIDTO
    LINENUM,        -- LINENUM
    SALESID,        -- SALESID
    INVENTDIMIDONHAND,        -- INVENTDIMIDONHAND
    SHIPMENTTABLEINIT        -- SHIPMENTTABLEINIT

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.METWMSORDERTRANSPLANNED;
GO

