
CREATE VIEW AX2009.NPOPRODUCTIONTAG_CartellinoProduzioneView
AS
SELECT
	-- Chiavi
	DATAAREAID,		-- IDAzienda
	PRODID,		-- OrdineProduzione
	RECID,		-- PKCartellinoProduzione

	-- Dimensioni
	SALESID,		-- OrdineCliente
	SALESLINENUM,		-- NumeroRiga
	MASTERWRKCTRID,		-- IDPressa
	CUSTNAME,		-- Cliente
	GROUPWRKCTRID,		-- GROUPWRKCTRID
	SALESLENGTH,		-- SALESLENGTH
	CUSTACCOUNT,		-- IDCliente
	WRKCTRID,		-- WRKCTRID
	WRKCTRNAME,		-- WRKCTRNAME
	PRODLENGTH,		-- PRODLENGTH
	PRESETMASTERWRKCTRID,		-- PRESETMASTERWRKCTRID
	WRKHOLENUM,		-- WRKHOLENUM
	WRKPULLOUT,		-- WRKPULLOUT
	WRKBOLSTER,		-- WRKBOLSTER
	WRKSUBBOLSTER,		-- WRKSUBBOLSTER
	PRODQTY,		-- PRODQTY
	SALESQTY,		-- SALESQTY
	WRKWEIGHTPROFILE,		-- WRKWEIGHTPROFILE
	SALESTOTKG,		-- SALESTOTKG
	PRESETBILLLENGTH,		-- PRESETBILLLENGTH
	SALESRESERVATION,		-- SALESRESERVATION [enum NoYes]
	SALESHEATTREATMENT,		-- SALESHEATTREATMENT
	SALESALLOYID,		-- SALESALLOYID
	PRODALLOYID,		-- PRODALLOYID
	PRODHEATTREATMENT,		-- PRODHEATTREATMENT
	TAGFINISHING,		-- TAGFINISHING
	PRODFINISHING,		-- PRODFINISHING
	TYPEFINISHING,		-- TYPEFINISHING
	WRKSIZE,		-- WRKSIZE
	WRKTYPE,		-- WRKTYPE
	PRESETBILLQTY,		-- PRESETBILLQTY
	PRODDATE,		-- PRODDATE
	SALESDATE,		-- SALESDATE
	SALESPRIORITY,		-- SALESPRIORITY [enum NoYes]
	SALESSECURITY,		-- SALESSECURITY [enum NoYes]
	REPRINT,		-- IsRistampa [enum NoYes]
	GROUPWRKCTRNAME,		-- GROUPWRKCTRNAME
	PRESETBILLWEIGHT,		-- PRESETBILLWEIGHT
	PRESETBILLTEMP,		-- PRESETBILLTEMP
	PRESETESTRBACKLENGTH,		-- PRESETESTRBACKLENGTH
	PRESETESTRGROSSKGH,		-- PRESETESTRGROSSKGH
	PRESETESTRNETKGH,		-- PRESETESTRNETKGH
	PRESETESTRSPEEDMIN,		-- PRESETESTRSPEEDMIN
	PRESETESTRSPEEDMAX,		-- PRESETESTRSPEEDMAX
	PRESETESTRPRESSLENGTH,		-- PRESETESTRPRESSLENGTH
	PRESETESTRCROP,		-- PRESETESTRCROP
	PRESETESTRHOTSAWPOSITION,		-- PRESETESTRHOTSAWPOSITION
	PRESETWRKCTRID,		-- PRESETWRKCTRID
	PRESETBARLENGTH,		-- PRESETBARLENGTH
	SALESWEEK,		-- SALESWEEK
	PRODWEEK,		-- PRODWEEK
	PRESETINFO,		-- PRESETINFO
	PRESETWRKCTRNUM,		-- PRESETWRKCTRNUM
	MASTERWRKCTRNAME,		-- MASTERWRKCTRNAME
	PRESETQTYPERBAR,		-- PRESETQTYPERBAR
	SALESFINISHING,		-- SALESFINISHING
	SALESCUSTOMERFINISHING,		-- SALESCUSTOMERFINISHING
	PRODBILLQTY,		-- PRODBILLQTY
	PRODBILLLENGTH,		-- PRODBILLLENGTH
	PRINTED,		-- IsStampato [enum NoYes]
	PRINTEDDATETIME,		-- PRINTEDDATETIME
	PRINTEDDATETIMETZID,		-- PRINTEDDATETIMETZID
	PRINTEDBY,		-- PRINTEDBY
	MODIFIEDDATETIME,		-- MODIFIEDDATETIME
	RECVERSION,		-- RECVERSION
	WRKFILLWEIGHT,		-- WRKFILLWEIGHT
	TAGFINISHINGTYPE,		-- TAGFINISHINGTYPE
	PRESETBARSINBILLET,		-- PRESETBARSINBILLET
	STATUSUSE,		-- IDStatoMatrice [enum NPOWrkStatusType]
	PRESETLOCKPACKING,		-- IsBloccoImballo [enum NoYes]
	PRESETVERIFIED,		-- IsDatiVerificati [enum NoYes]
	PRESETFIRSTBILLLENGTH		-- PRESETFIRSTBILLLENGTH

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.NPOPRODUCTIONTAG;
GO

