
CREATE VIEW AX2009.SHIPCARRIERTABLE_VettoreView
AS
SELECT
	-- Chiavi
	DATAAREAID,		-- IDAzienda
	CARRIERID,		-- IDVettore
	RECID,		-- PKVettore

	-- Dimensioni
	CARRIERNAME		-- Vettore

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.SHIPCARRIERTABLE;
GO

