
CREATE VIEW AX2009.SRSANALYSISENUMS_EtichettaView
AS
SELECT
	-- Chiavi
	AE.ENUMNAME,		-- NomeEtichetta
	AE.ENUMITEMVALUE,		-- IDEtichetta
	AE.LANGUAGEID,		-- IDLingua
	AE.RECID,		-- PKEtichetta

	-- Dimensioni
	AE.ENUMITEMLABEL		-- Etichetta

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.SRSANALYSISENUMS AE
WHERE AE.LANGUAGEID = N'it';
GO

