
CREATE VIEW AX2009.TAXBOOKSECTION_SezionaleIVAView
AS
SELECT
	-- Chiavi
	DATAAREAID,		-- IDAzienda
	TAXBOOKSECTIONID,		-- IDSezionaleIVA
	RECID,		-- PKSezionaleIVA

	-- Dimensioni
	NAME		-- SezionaleIVA

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.TAXBOOKSECTION;
GO

