
CREATE VIEW AX2009.TIMEZONESLIST_FusoOrarioView
AS
SELECT
	-- Chiavi
	TZENUM,		-- IDFusoOrario
	RECID,		-- PKFusoOrario

	-- Dimensioni
	TIMEZONEKEYNAME,		-- FusoOrario
	ENUMNAME		-- ENUMNAME

FROM [AXSQL\AX2009].AX2009_METRA_LIVE.dbo.TIMEZONESLIST;
GO

