
/**
 * @table METRAPQ.QuoteRilevate
 * @description 

 * @depends [dbo].[Quote Rilevate]

SELECT TOP 1 * FROM [SQL2014\DB2014].MetraPQ.[dbo].[Quote Rilevate]
*/

CREATE   VIEW METRAPQ.QuoteRilevateView
AS
SELECT
	-- Chiavi
    T.N,

    -- Campi per data warehouse
	CONVERT(VARBINARY(20), HASHBYTES('MD5', CONCAT(
        T.N,
		' '
	))) AS HistoricalHashKey,
	CONVERT(VARBINARY(20), HASHBYTES('MD5', CONCAT(
        T.DataCollaudo,
        T.IDClassificazioneProdotto,
        T.ClassificazioneProdottoImpostata,
        T.NumeroLotto,
        T.InserimentoManuale,
        T.Cliente,
        T.RiferimentoCliente,
        T.CodiceCliente,
        T.Campionatura,
        T.CampionaturaTipo,
        T.Pressa,
        T.OperatoreCollaudo,
        T.Quantometro,
        T.AspettoSuperficiale,
        T.PesoTeorico,
        T.PesoCalcolato,
        T.Peso,
        T.CodiceMetra,
        T.BarraMatrice,
        T.DataEstrusione,
        T.Rugosimetro,
        T.Calibro,
        T.MacchinaDiMisura,
        T.Rotondimetro,
        T.MotivoNonConformita,
        T.etichettaMotivoNonConformita,
        T.Rullare,
        T.Rullato,
        T.Scartare,
        T.RipetereTT,
        T.SelezionareRicontrollare,
        T.AccettatoInDeroga,
        T.Altro,
        T.ControlloImballoEseguito,
        T.DecisioniPreseAzioniCorrettive,
        T.EsitoRilavorazione,
        T.Conformità,
        T.FirmaRilavorazione,
        T.ControllatoDa,
        T.IdoneoAllaSpedizione,
        T.IdoneoControlloCliente,
        T.DataSvincolo,
        T.CollaudoCliente,
        T.BilletteDaEstrudere,
        T.BilletteEstruse,
        T.Eliminata,
        T.Riconciliato,
        T.EstrusioneEsterna,
        T.EstrusioneEsternaNumeroDDT,
        T.EstrusioneEsternaDataDDT,
        T.EstrusioneEsternaFornitore,
        T.CaratteristicheMeccanicheNonConformi,
        T.LegaPredefinita,
        T.LegaPredefinita_IDClassificazioneCaratteristiche,
        T.StatoFisicoPredefinito,
        T.StatoFisicoPredefinito_IDClassificazioneCaratteristiche,
        T.DurezzaMaxRichiesta,
        T.DurezzaMaxRichiesta_IDClassificazioneCaratteristiche,
        T.DurezzaMinRichiesta,
        T.DurezzaMinRichiesta_IDClassificazioneCaratteristiche,
        T.RMRichiesto,
        T.RmRichiesto_IDClassificazioneCaratteristiche,
        T.RPRichiesto,
        T.RpRichiesto_IDClassificazioneCaratteristiche,
        T.ARichiesto,
        T.ARichiesto_IDClassificazioneCaratteristiche,
        T.ARichiestoTipo,
        T.RARichiesto,
        T.RaRichiesto_IDClassificazioneCaratteristiche,
        T.RTRichiesto,
        T.RtRichiesto_IDClassificazioneCaratteristiche,
        T.RZRichiesto,
        T.RzRichiesto_IDClassificazioneCaratteristiche,
        T.RMaxRichiesto,
        T.RmaxRichiesto_IDClassificazioneCaratteristiche,
        T.Sistema,
        T.SistemaID,
        T.Serie,
        T.SerieID,
        T.Commessa,
        T.NumeroCommessa,
        T.ResponsabileAvvioProduzione,
        T.OpportunitaNumero,
        T.OpportunitaDescrizione,
        T.OpportunitaIDSaleforce,
		' '
	))) AS ChangeHashKey,
    CURRENT_TIMESTAMP AS InsertDatetime,
    CURRENT_TIMESTAMP AS UpdateDatetime,
    CAST(0 AS BIT) AS IsDeleted,

    -- Attributi
    T.DataCollaudo,
    T.IDClassificazioneProdotto,
    T.ClassificazioneProdottoImpostata,
    T.NumeroLotto,
    T.InserimentoManuale,
    T.Cliente,
    T.RiferimentoCliente,
    T.CodiceCliente,
    T.Campionatura,
    T.CampionaturaTipo,
    T.Pressa,
    T.OperatoreCollaudo,
    T.Quantometro,
    T.AspettoSuperficiale,
    T.PesoTeorico,
    T.PesoCalcolato,
    T.Peso,
    T.CodiceMetra,
    T.BarraMatrice,
    T.DataEstrusione,
    T.Rugosimetro,
    T.Calibro,
    T.MacchinaDiMisura,
    T.Rotondimetro,
    T.MotivoNonConformita,
    T.etichettaMotivoNonConformita,
    T.Rullare,
    T.Rullato,
    T.Scartare,
    T.RipetereTT,
    T.SelezionareRicontrollare,
    T.AccettatoInDeroga,
    T.Altro,
    T.ControlloImballoEseguito,
    T.DecisioniPreseAzioniCorrettive,
    T.EsitoRilavorazione,
    T.Conformità,
    T.FirmaRilavorazione,
    T.ControllatoDa,
    T.IdoneoAllaSpedizione,
    T.IdoneoControlloCliente,
    T.DataSvincolo,
    T.CollaudoCliente,
    T.BilletteDaEstrudere,
    T.BilletteEstruse,
    T.Eliminata,
    T.Riconciliato,
    T.EstrusioneEsterna,
    T.EstrusioneEsternaNumeroDDT,
    T.EstrusioneEsternaDataDDT,
    T.EstrusioneEsternaFornitore,
    T.CaratteristicheMeccanicheNonConformi,
    T.LegaPredefinita,
    T.LegaPredefinita_IDClassificazioneCaratteristiche,
    T.StatoFisicoPredefinito,
    T.StatoFisicoPredefinito_IDClassificazioneCaratteristiche,
    T.DurezzaMaxRichiesta,
    T.DurezzaMaxRichiesta_IDClassificazioneCaratteristiche,
    T.DurezzaMinRichiesta,
    T.DurezzaMinRichiesta_IDClassificazioneCaratteristiche,
    T.RMRichiesto,
    T.RmRichiesto_IDClassificazioneCaratteristiche,
    T.RPRichiesto,
    T.RpRichiesto_IDClassificazioneCaratteristiche,
    T.ARichiesto,
    T.ARichiesto_IDClassificazioneCaratteristiche,
    T.ARichiestoTipo,
    T.RARichiesto,
    T.RaRichiesto_IDClassificazioneCaratteristiche,
    T.RTRichiesto,
    T.RtRichiesto_IDClassificazioneCaratteristiche,
    T.RZRichiesto,
    T.RzRichiesto_IDClassificazioneCaratteristiche,
    T.RMaxRichiesto,
    T.RmaxRichiesto_IDClassificazioneCaratteristiche,
    T.Sistema,
    T.SistemaID,
    T.Serie,
    T.SerieID,
    T.Commessa,
    T.NumeroCommessa,
    T.ResponsabileAvvioProduzione,
    T.OpportunitaNumero,
    T.OpportunitaDescrizione,
    T.OpportunitaIDSaleforce

FROM (
    SELECT
        [N°] AS N,
        [Data collaudo] AS DataCollaudo,
        IDClassificazioneProdotto,
        ClassificazioneProdottoImpostata,
        NumeroLotto,
        InserimentoManuale,
        Cliente,
        [Riferimento Cliente] AS RiferimentoCliente,
        [Codice Cliente] AS CodiceCliente,
        Campionatura,
        CampionaturaTipo,
        Pressa,
        [Operatore collaudo] AS OperatoreCollaudo,
        Quantometro,
        [Aspetto superficiale] AS AspettoSuperficiale,
        PesoTeorico,
        PesoCalcolato,
        Peso,
        [Codice Metra] AS CodiceMetra,
        [Barra matrice] AS BarraMatrice,
        [Data di estrusione] AS DataEstrusione,
        Rugosimetro,
        Calibro,
        [Macchina di misura] AS MacchinaDiMisura,
        Rotondimetro,
        [Motivo della non conformità] AS MotivoNonConformita,
        etichettaMotivoNonConformita,
        Rullare,
        Rullato,
        Scartare,
        [Ripetere TT] AS RipetereTT,
        [Selezionare/ricontrollare] AS SelezionareRicontrollare,
        [Accettato in deroga] AS AccettatoInDeroga,
        Altro,
        ControlloImballoEseguito,
        [Decisioni prese e azioni correttive] AS DecisioniPreseAzioniCorrettive,
        [Esito rilavorazione] AS EsitoRilavorazione,
        Conformità,
        [Firma rilavorazione] AS FirmaRilavorazione,
        [Controllato da] AS ControllatoDa,
        [Idoneo alla spedizione] AS IdoneoAllaSpedizione,
        IdoneoControlloCliente,
        [Data svincolo] AS DataSvincolo,
        [Collaudo Cliente] AS CollaudoCliente,
        [Billette da estrudere] AS BilletteDaEstrudere,
        [Billette estruse] AS BilletteEstruse,
        Eliminata,
        Riconciliato,
        EstrusioneEsterna,
        EstrusioneEsternaNumeroDDT,
        EstrusioneEsternaDataDDT,
        EstrusioneEsternaFornitore,
        CaratteristicheMeccanicheNonConformi,
        LegaPredefinita,
        LegaPredefinita_IDClassificazioneCaratteristiche,
        StatoFisicoPredefinito,
        StatoFisicoPredefinito_IDClassificazioneCaratteristiche,
        [Durezza Max richiesta] AS DurezzaMaxRichiesta,
        DurezzaMaxRichiesta_IDClassificazioneCaratteristiche,
        [Durezza min richiesta] AS DurezzaMinRichiesta,
        DurezzaMinRichiesta_IDClassificazioneCaratteristiche,
        [Rm richiesto] AS RMRichiesto,
        RmRichiesto_IDClassificazioneCaratteristiche,
        [Rp richiesto] AS RPRichiesto,
        RpRichiesto_IDClassificazioneCaratteristiche,
        [A richiesto] AS ARichiesto,
        ARichiesto_IDClassificazioneCaratteristiche,
        ARichiestoTipo,
        [Ra richiesto] AS RARichiesto,
        RaRichiesto_IDClassificazioneCaratteristiche,
        [Rt richiesto] AS RTRichiesto,
        RtRichiesto_IDClassificazioneCaratteristiche,
        [Rz richiesto] AS RZRichiesto,
        RzRichiesto_IDClassificazioneCaratteristiche,
        [Rmax richiesto] AS RMaxRichiesto,
        RmaxRichiesto_IDClassificazioneCaratteristiche,
        Sistema,
        SistemaID,
        Serie,
        SerieID,
        Commessa,
        NumeroCommessa,
        ResponsabileAvvioProduzione,
        OpportunitaNumero,
        OpportunitaDescrizione,
        OpportunitaIDSaleforce

    FROM [SQL2014\DB2014].MetraPQ.[dbo].[Quote Rilevate]
) T;
GO

