
CREATE PROCEDURE AX2009.usp_Merge_CUSTINVOICETABLE_FattureClienteTestoLibero
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.CUSTINVOICETABLE_FattureClienteTestoLibero', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTINVOICETABLE_FattureClienteTestoLibero;
    EXEC AX2009.usp_AddIndexes_CUSTINVOICETABLE_FattureClienteTestoLibero;
END;

MERGE INTO AX2009.CUSTINVOICETABLE_FattureClienteTestoLibero AS TGT
USING AX2009.CUSTINVOICETABLE_FattureClienteTestoLiberoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVOICEDATE = TGT.INVOICEDATE AND SRC.INVOICEID = TGT.INVOICEID AND SRC.NUMBERSEQUENCEGROUP = TGT.NUMBERSEQUENCEGROUP
WHEN MATCHED AND (TGT.DLVCOUNTRYREGIONID <> SRC.DLVCOUNTRYREGIONID)
  THEN UPDATE SET TGT.DLVCOUNTRYREGIONID = SRC.DLVCOUNTRYREGIONID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVOICEDATE, INVOICEID, NUMBERSEQUENCEGROUP, RECID, DLVCOUNTRYREGIONID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTINVOICETABLE_FattureClienteTestoLibero' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVOICEDATE = ' + CAST(COALESCE(inserted.INVOICEDATE, deleted.INVOICEDATE) AS NVARCHAR) + ' - ' + 'INVOICEID = ' + CAST(COALESCE(inserted.INVOICEID, deleted.INVOICEID) AS NVARCHAR) + ' - ' + 'NUMBERSEQUENCEGROUP = ' + CAST(COALESCE(inserted.NUMBERSEQUENCEGROUP, deleted.NUMBERSEQUENCEGROUP) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

