
CREATE PROCEDURE AX2009.usp_Merge_PRICEDISCGROUP_GruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PRICEDISCGROUP_GruppoPrezzi', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_PRICEDISCGROUP_GruppoPrezzi;
	EXEC AX2009.usp_AddIndexes_PRICEDISCGROUP_GruppoPrezzi;
END;

MERGE INTO AX2009.PRICEDISCGROUP_GruppoPrezzi AS TGT
USING AX2009.PRICEDISCGROUP_GruppoPrezziView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.MODULE = TGT.MODULE AND SRC.GROUPID = TGT.GROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, MODULE, GROUPID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.PRICEDISCGROUP_GruppoPrezzi' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'MODULE = ' + CAST(COALESCE(inserted.MODULE, deleted.MODULE) AS NVARCHAR) + ' - ' + 'GROUPID = ' + CAST(COALESCE(inserted.GROUPID, deleted.GROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

