
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDTRANS_TransazioniFornitore
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_VENDTRANS_TransazioniFornitore_DATAAREAID_VOUCHER_INCLUDE ON AX2009.VENDTRANS_TransazioniFornitore ([DATAAREAID],[VOUCHER]) INCLUDE ([INVOICE],[DOCUMENTDATE],[PAYMMODE],[MODIFIEDTRANSACTIONID]);

END;
GO

