
CREATE PROCEDURE AX2009.usp_Merge_TAXTABLE_CodiceIVA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.TAXTABLE_CodiceIVA', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_TAXTABLE_CodiceIVA;
	EXEC AX2009.usp_AddIndexes_TAXTABLE_CodiceIVA;
END;

MERGE INTO AX2009.TAXTABLE_CodiceIVA AS TGT
USING AX2009.TAXTABLE_CodiceIVAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TAXCODE = TGT.TAXCODE
WHEN MATCHED AND (TGT.TAXNAME <> SRC.TAXNAME)
  THEN UPDATE SET TGT.TAXNAME = SRC.TAXNAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TAXCODE, RECID, TAXNAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.TAXTABLE_CodiceIVA' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TAXCODE = ' + CAST(COALESCE(inserted.TAXCODE, deleted.TAXCODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

