
CREATE PROCEDURE AX2009.usp_Merge_DIRPARTYTABLE_Rubrica
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DIRPARTYTABLE_Rubrica', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_DIRPARTYTABLE_Rubrica;
    EXEC AX2009.usp_AddIndexes_DIRPARTYTABLE_Rubrica;
END;

MERGE INTO AX2009.DIRPARTYTABLE_Rubrica AS TGT
USING AX2009.DIRPARTYTABLE_RubricaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PARTYID = TGT.PARTYID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.NPODIRPARTYTABLEGROUPID <> SRC.NPODIRPARTYTABLEGROUPID)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.NPODIRPARTYTABLEGROUPID = SRC.NPODIRPARTYTABLEGROUPID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PARTYID, RECID, NAME, NPODIRPARTYTABLEGROUPID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.DIRPARTYTABLE_Rubrica' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PARTYID = ' + CAST(COALESCE(inserted.PARTYID, deleted.PARTYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

