
CREATE PROCEDURE AX2009.usp_AddIndexes_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura_ ON AX2009.METPAINTINGSETUPTABLE_ParametriLineaVerniciatura () INCLUDE();

END;
GO

