
CREATE PROCEDURE AX2009.usp_Merge_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo;
	EXEC AX2009.usp_AddIndexes_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo;
END;

MERGE INTO AX2009.NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo AS TGT
USING AX2009.NPOPBAROUTEFINISHING_ArticoloFinituraValoriCicloView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.FINISHINGID = TGT.FINISHINGID AND SRC.OPRNUM = TGT.OPRNUM
WHEN MATCHED AND (TGT.OPRID <> SRC.OPRID OR TGT.WRKCTRID <> SRC.WRKCTRID)
  THEN UPDATE SET TGT.OPRID = SRC.OPRID, TGT.WRKCTRID = SRC.WRKCTRID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, FINISHINGID, OPRNUM, RECID, OPRID, WRKCTRID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'FINISHINGID = ' + CAST(COALESCE(inserted.FINISHINGID, deleted.FINISHINGID) AS NVARCHAR) + ' - ' + 'OPRNUM = ' + CAST(COALESCE(inserted.OPRNUM, deleted.OPRNUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

