
CREATE PROCEDURE AX2009.usp_Merge_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile;
	EXEC AX2009.usp_AddIndexes_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile;
END;

MERGE INTO AX2009.LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile AS TGT
USING AX2009.LEDGERJOURNALTABLE_GiornaliRegistrazioneContabileView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.JOURNALNUM = TGT.JOURNALNUM
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, JOURNALNUM, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'JOURNALNUM = ' + CAST(COALESCE(inserted.JOURNALNUM, deleted.JOURNALNUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

