
CREATE PROCEDURE AX2009.usp_Merge_NPOCUSTPROJECT_Commessa
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.NPOCUSTPROJECT_Commessa', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOCUSTPROJECT_Commessa;
    EXEC AX2009.usp_AddIndexes_NPOCUSTPROJECT_Commessa;
END;

MERGE INTO AX2009.NPOCUSTPROJECT_Commessa AS TGT
USING AX2009.NPOCUSTPROJECT_CommessaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CUSTACCOUNT = TGT.CUSTACCOUNT AND SRC.PROJECTCODE = TGT.PROJECTCODE
WHEN MATCHED AND (TGT.DOCUMENTDESCRIPTION <> SRC.DOCUMENTDESCRIPTION OR TGT.VENDPROJECTID <> SRC.VENDPROJECTID OR TGT.TOTALQTY <> SRC.TOTALQTY OR TGT.METCOVERAGETYPE <> SRC.METCOVERAGETYPE)
  THEN UPDATE SET TGT.DOCUMENTDESCRIPTION = SRC.DOCUMENTDESCRIPTION, TGT.VENDPROJECTID = SRC.VENDPROJECTID, TGT.TOTALQTY = SRC.TOTALQTY, TGT.METCOVERAGETYPE = SRC.METCOVERAGETYPE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CUSTACCOUNT, PROJECTCODE, RECID, DOCUMENTDESCRIPTION, VENDPROJECTID, TOTALQTY, METCOVERAGETYPE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOCUSTPROJECT_Commessa' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CUSTACCOUNT = ' + CAST(COALESCE(inserted.CUSTACCOUNT, deleted.CUSTACCOUNT) AS NVARCHAR) + ' - ' + 'PROJECTCODE = ' + CAST(COALESCE(inserted.PROJECTCODE, deleted.PROJECTCODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

