
CREATE PROCEDURE AX2009.usp_Create_NPOWORKSTATIONAREA_AreaDiLavoro
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOWORKSTATIONAREA_AreaDiLavoro (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    AREAID        NVARCHAR(25) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DEPARTMENTID        NVARCHAR(30) NOT NULL


    -- Constraint
    CONSTRAINT PK_NPOWORKSTATIONAREA_AreaDiLavoro PRIMARY KEY CLUSTERED (
        DATAAREAID,
        AREAID
    )
);

END;
GO

