
CREATE PROCEDURE AX2009.usp_Create_INVENTTXT_ArticoloTraduzione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTTXT_ArticoloTraduzione (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	LANGUAGEID		NVARCHAR(7) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TXT		NVARCHAR(1000) NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTTXT_ArticoloTraduzione PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		LANGUAGEID
	)
);

END;
GO

