
CREATE PROCEDURE AX2009.usp_Create_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard (
	-- Chiavi
	DATAAREAID  CHAR(4) NOT NULL,
	ITEMID  NVARCHAR(20) NOT NULL,
	RECID  BIGINT NOT NULL,

	-- Dimensioni
	ANODIZINGCLASS  SMALLINT NOT NULL


	-- Constraint
	CONSTRAINT PK_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID
	)
);

END;
GO

