
CREATE PROCEDURE AX2009.usp_AddIndexes_SALESPOOL_PoolVendite
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SALESPOOL_PoolVendite_ ON AX2009.SALESPOOL_PoolVendite () INCLUDE();

END;
GO

