
CREATE PROCEDURE AX2009.usp_AddIndexes_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione_ ON AX2009.METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione () INCLUDE();

END;
GO

