
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPRODUCTIONLOT_Lotti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPRODUCTIONLOT_Lotti_ ON AX2009.NPOPRODUCTIONLOT_Lotti () INCLUDE();

END;
GO

