
CREATE PROCEDURE AX2009.usp_Merge_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita;
    EXEC AX2009.usp_AddIndexes_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita;
END;

MERGE INTO AX2009.SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita AS TGT
USING AX2009.SMMBUSRELSALESDISTRICTGROUP_ZonaDiVenditaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SALESDISTRICTID = TGT.SALESDISTRICTID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SALESDISTRICTID, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SALESDISTRICTID = ' + CAST(COALESCE(inserted.SALESDISTRICTID, deleted.SALESDISTRICTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

