CREATE PROCEDURE AX2009.usp_Create_BOMCALCTRANS_CalcoloDBA_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.BOMCALCTRANS_CalcoloDBA_Riga (
	-- Chiavi
	DATAAREAID			CHAR(4) NOT NULL,
	PRICECALCID			NVARCHAR(20) NOT NULL,
	LINENUM				NUMERIC(28, 12) NOT NULL,
	RECID				BIGINT NOT NULL,

	-- Dimensioni
	COSTGROUPID			NVARCHAR(10) NOT NULL,
	LEVEL_				INT NOT NULL,
	QTY					NUMERIC(28, 12) NOT NULL,
	COSTPRICE			NUMERIC(28, 12) NOT NULL,
	TRANSDATE			DATE NOT NULL,
	KEY1				NVARCHAR(20) NOT NULL,
	KEY2				NVARCHAR(10) NOT NULL,
	KEY3				NVARCHAR(20) NOT NULL,
	CONSUMPTIONVARIABLE	NUMERIC(28, 12) NOT NULL,
	OPRNUM				INT NOT NULL,
	CALCTYPE			SMALLINT NOT NULL,
	COSTPRICEUNIT		NUMERIC(28, 12) NOT NULL,
	COSTPRICEQTY		NUMERIC(28, 12) NOT NULL,
	COSTMARKUPQTY		NUMERIC(28, 12) NOT NULL,

	PARENTRECID			BIGINT NOT NULL CONSTRAINT DFT_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_PARENTRECID DEFAULT (0),
	IsFoglia			BIT NOT NULL CONSTRAINT DFT_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_IsFoglia DEFAULT (1),
	SERVICEITEMRECID	BIGINT NOT NULL CONSTRAINT DFT_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_SERVICEITEMRECID DEFAULT (0),

    CONSUMPTIONCONSTANT NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_BOMCALCTRANS_CalcoloDBA_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PRICECALCID,
		LINENUM
	)
);

END;
GO

