
CREATE PROCEDURE AX2009.usp_Merge_NPOBOETOTALTABLEMONTH_Insoluti_Mese
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOBOETOTALTABLEMONTH_Insoluti_Mese', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOBOETOTALTABLEMONTH_Insoluti_Mese;
	EXEC AX2009.usp_AddIndexes_NPOBOETOTALTABLEMONTH_Insoluti_Mese;
END;

MERGE INTO AX2009.NPOBOETOTALTABLEMONTH_Insoluti_Mese AS TGT
USING AX2009.NPOBOETOTALTABLEMONTH_Insoluti_MeseView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.YR = TGT.YR AND SRC.MONTH = TGT.MONTH AND SRC.CUSTACCOUNT = TGT.CUSTACCOUNT AND SRC.MACROAREA = TGT.MACROAREA AND SRC.EMPLID = TGT.EMPLID AND SRC.TRANSTYPE = TGT.TRANSTYPE
WHEN MATCHED AND (TGT.NUMBERDRAWN <> SRC.NUMBERDRAWN OR TGT.NUMBERPROTESTED <> SRC.NUMBERPROTESTED OR TGT.AMOUNTDRAWN <> SRC.AMOUNTDRAWN OR TGT.AMOUNTPROTESTED <> SRC.AMOUNTPROTESTED)
  THEN UPDATE SET TGT.NUMBERDRAWN = SRC.NUMBERDRAWN, TGT.NUMBERPROTESTED = SRC.NUMBERPROTESTED, TGT.AMOUNTDRAWN = SRC.AMOUNTDRAWN, TGT.AMOUNTPROTESTED = SRC.AMOUNTPROTESTED
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, YR, MONTH, CUSTACCOUNT, MACROAREA, EMPLID, TRANSTYPE, RECID, NUMBERDRAWN, NUMBERPROTESTED, AMOUNTDRAWN, AMOUNTPROTESTED)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOBOETOTALTABLEMONTH_Insoluti_Mese' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'YR = ' + CAST(COALESCE(inserted.YR, deleted.YR) AS NVARCHAR) + ' - ' + 'MONTH = ' + CAST(COALESCE(inserted.MONTH, deleted.MONTH) AS NVARCHAR) + ' - ' + 'CUSTACCOUNT = ' + CAST(COALESCE(inserted.CUSTACCOUNT, deleted.CUSTACCOUNT) AS NVARCHAR) + ' - ' + 'MACROAREA = ' + CAST(COALESCE(inserted.MACROAREA, deleted.MACROAREA) AS NVARCHAR) + ' - ' + 'EMPLID = ' + CAST(COALESCE(inserted.EMPLID, deleted.EMPLID) AS NVARCHAR) + ' - ' + 'TRANSTYPE = ' + CAST(COALESCE(inserted.TRANSTYPE, deleted.TRANSTYPE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

