
CREATE PROCEDURE AX2009.usp_AddIndexes_TAXBOOKSECTION_SezionaleIVA
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_TAXBOOKSECTION_SezionaleIVA_ ON AX2009.TAXBOOKSECTION_SezionaleIVA () INCLUDE();

END;
GO

