
CREATE PROCEDURE AX2009.usp_Create_INVENTITEMGROUP_GruppoArticoli
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTITEMGROUP_GruppoArticoli (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMGROUPID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTITEMGROUP_GruppoArticoli PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMGROUPID
	)
);

END;
GO

