
CREATE PROCEDURE AX2009.usp_Create_NPOITEMSERIES_Serie
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOITEMSERIES_Serie (
	-- Chiavi
	SERIESID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	SYSTEMID		NVARCHAR(20) NOT NULL,
	SERIESIDAS400		NVARCHAR(20) NOT NULL,
	OBSOLETE		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOITEMSERIES_Serie PRIMARY KEY CLUSTERED (
		SERIESID
	)
);

END;
GO

