
CREATE PROCEDURE AX2009.usp_Create_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    DELIVERYDATE        DATE NOT NULL,
    PACKINGSLIPID        NVARCHAR(20) NOT NULL,
    WMSPALLETID        NVARCHAR(18) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    COMPANYSALESID        NVARCHAR(20) NOT NULL,
    INTERCOMPANYSALESID        NVARCHAR(20) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,

    -- Misure
    QTY        NUMERIC(28, 12) NOT NULL,
    QTY2UM        NUMERIC(28, 12) NOT NULL,
    PACKEDQTY        NUMERIC(28, 12) NOT NULL,
    PACKEDQTY2UM        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet PRIMARY KEY CLUSTERED (
        DATAAREAID,
        INVENTTRANSID,
        DELIVERYDATE,
        PACKINGSLIPID,
        WMSPALLETID,
        RECID
    )
);

END;
GO

