
CREATE PROCEDURE AX2009.usp_Create_WMSPICKINGROUTE_CicloPrelievo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.WMSPICKINGROUTE_CicloPrelievo (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PICKINGROUTEID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	EXPEDITIONSTATUS		SMALLINT NOT NULL,
	CURRENTPICKPALLETID		NVARCHAR(18) NOT NULL,
	NPOWORKSPACE		INT NOT NULL,
	NPODLVSTATIONID		NVARCHAR(10) NOT NULL,
	NPOCRSNUMID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_WMSPICKINGROUTE_CicloPrelievo PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PICKINGROUTEID
	)
);

END;
GO

