
CREATE PROCEDURE AX2009.usp_Merge_NPOITEMSERIES_Serie
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOITEMSERIES_Serie', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOITEMSERIES_Serie;
	EXEC AX2009.usp_AddIndexes_NPOITEMSERIES_Serie;
END;

MERGE INTO AX2009.NPOITEMSERIES_Serie AS TGT
USING AX2009.NPOITEMSERIES_SerieView (nolock) AS SRC
ON SRC.SERIESID = TGT.SERIESID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.SYSTEMID <> SRC.SYSTEMID OR TGT.SERIESIDAS400 <> SRC.SERIESIDAS400 OR TGT.OBSOLETE <> SRC.OBSOLETE)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.SYSTEMID = SRC.SYSTEMID, TGT.SERIESIDAS400 = SRC.SERIESIDAS400, TGT.OBSOLETE = SRC.OBSOLETE
WHEN NOT MATCHED
  THEN INSERT VALUES (SERIESID, RECID, NAME, SYSTEMID, SERIESIDAS400, OBSOLETE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOITEMSERIES_Serie' AS full_olap_table_name,
	'SERIESID = ' + CAST(COALESCE(inserted.SERIESID, deleted.SERIESID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

