
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTINVOICEJOUR_FattureCliente
AS
BEGIN
SET NOCOUNT ON;

CREATE UNIQUE NONCLUSTERED INDEX IX_AX2009_CUSTINVOICEJOUR_FattureCliente_RECID ON [AX2009].[CUSTINVOICEJOUR_FattureCliente] ([RECID])

END;
GO

