
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPBAFINISHINGRELATION_FinituraAttributo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPBAFINISHINGRELATION_FinituraAttributo_ ON AX2009.NPOPBAFINISHINGRELATION_FinituraAttributo () INCLUDE();

END;
GO

