
CREATE PROCEDURE AX2009.usp_Create_ADDRESSCOUNTRYREGION_Nazione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ADDRESSCOUNTRYREGION_Nazione (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    COUNTRYREGIONID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    TYPE        SMALLINT NOT NULL,
    ISOCODE        NVARCHAR(2) NOT NULL,
    NAME        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_ADDRESSCOUNTRYREGION_Nazione PRIMARY KEY CLUSTERED (
        DATAAREAID,
        COUNTRYREGIONID
    )
);

END;
GO

