
CREATE PROCEDURE AX2009.usp_Merge_NPOITEMSYSTEM_Sistema
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOITEMSYSTEM_Sistema', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOITEMSYSTEM_Sistema;
	EXEC AX2009.usp_AddIndexes_NPOITEMSYSTEM_Sistema;
END;

MERGE INTO AX2009.NPOITEMSYSTEM_Sistema AS TGT
USING AX2009.NPOITEMSYSTEM_SistemaView (nolock) AS SRC
ON SRC.SYSTEMID = TGT.SYSTEMID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.SECTORTYPE <> SRC.SECTORTYPE)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.SECTORTYPE = SRC.SECTORTYPE
WHEN NOT MATCHED
  THEN INSERT VALUES (SYSTEMID, RECID, NAME, SECTORTYPE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOITEMSYSTEM_Sistema' AS full_olap_table_name,
	'SYSTEMID = ' + CAST(COALESCE(inserted.SYSTEMID, deleted.SYSTEMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

