
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOBOETOTALTABLE_Insoluti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOBOETOTALTABLE_Insoluti_ ON AX2009.NPOBOETOTALTABLE_Insoluti () INCLUDE();

END;
GO

