
CREATE PROCEDURE AX2009.usp_Merge_WMSTRANSPORT_TrasportiPallet
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WMSTRANSPORT_TrasportiPallet', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_WMSTRANSPORT_TrasportiPallet;
	EXEC AX2009.usp_AddIndexes_WMSTRANSPORT_TrasportiPallet;
END;

MERGE INTO AX2009.WMSTRANSPORT_TrasportiPallet AS TGT
USING AX2009.WMSTRANSPORT_TrasportiPalletView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSPORTID = TGT.TRANSPORTID AND SRC.WMSPALLETID = TGT.WMSPALLETID
WHEN MATCHED AND (TGT.FROMLOCATION <> SRC.FROMLOCATION OR TGT.TOLOCATION <> SRC.TOLOCATION OR TGT.OPERATOR <> SRC.OPERATOR OR TGT.EXPEDITIONSTATUS <> SRC.EXPEDITIONSTATUS OR TGT.SHIPMENTID <> SRC.SHIPMENTID OR TGT.FROMINVENTLOCATIONID <> SRC.FROMINVENTLOCATIONID OR TGT.TOINVENTLOCATIONID <> SRC.TOINVENTLOCATIONID OR TGT.TOTALQTY <> SRC.TOTALQTY)
  THEN UPDATE SET TGT.FROMLOCATION = SRC.FROMLOCATION, TGT.TOLOCATION = SRC.TOLOCATION, TGT.OPERATOR = SRC.OPERATOR, TGT.EXPEDITIONSTATUS = SRC.EXPEDITIONSTATUS, TGT.SHIPMENTID = SRC.SHIPMENTID, TGT.FROMINVENTLOCATIONID = SRC.FROMINVENTLOCATIONID, TGT.TOINVENTLOCATIONID = SRC.TOINVENTLOCATIONID, TGT.TOTALQTY = SRC.TOTALQTY
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSPORTID, WMSPALLETID, RECID, FROMLOCATION, TOLOCATION, OPERATOR, EXPEDITIONSTATUS, SHIPMENTID, FROMINVENTLOCATIONID, TOINVENTLOCATIONID, TOTALQTY)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.WMSTRANSPORT_TrasportiPallet' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSPORTID = ' + CAST(COALESCE(inserted.TRANSPORTID, deleted.TRANSPORTID) AS NVARCHAR) + ' - ' + 'WMSPALLETID = ' + CAST(COALESCE(inserted.WMSPALLETID, deleted.WMSPALLETID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

