
CREATE PROCEDURE AX2009.usp_AddIndexes_PRODTABLE_OrdiniProduzione
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_PRODTABLE_OrdiniProduzione_DATAAREAID_INVENTREFTYPE_INVENTREFID ON [AX2009].[PRODTABLE_OrdiniProduzione] ([DATAAREAID],[INVENTREFTYPE],[INVENTREFID]);
CREATE NONCLUSTERED INDEX IX_AX2009_PRODTABLE_OrdiniProduzione_DATAAREAID_NPOBOMPALLETID_INCLUDE ON [AX2009].[PRODTABLE_OrdiniProduzione] ([DATAAREAID],[NPOBOMPALLETID]) INCLUDE ([PRODID],[PRODSTATUS]);
CREATE NONCLUSTERED INDEX IX_AX2009_PRODTABLE_OrdiniProduzione_PRODSTATUS_INCLUDE ON AX2009.PRODTABLE_OrdiniProduzione (PRODSTATUS) INCLUDE (ITEMID, SCHEDSTART, INVENTREFTYPE, INVENTREFID, COLLECTREFPRODID, QTYSCHED);

END;
GO

