
CREATE PROCEDURE AX2009.usp_Create_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	SALESID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	CONFIRMBLOCKED		BIT NOT NULL,
	UNLOCKCAUSAL		NVARCHAR(10) NOT NULL,
	PACKINGBLOCKED		BIT NOT NULL,
	PICKINGBLOCKED		BIT NOT NULL,
	INVOICEBLOCKED		BIT NOT NULL,
	CREATEDDATETIME		DATETIME NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido PRIMARY KEY CLUSTERED (
		DATAAREAID,
		SALESID,
		RECID
	)
);

END;
GO

