
CREATE PROCEDURE AX2009.usp_Create_MARKUPTRANS_TransazioniSpeseAccessorie
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.MARKUPTRANS_TransazioniSpeseAccessorie (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSTABLEID		INT NOT NULL,
	TRANSRECID		BIGINT NOT NULL,
	LINENUM		NUMERIC(28, 12) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	MARKUPCODE		NVARCHAR(10) NOT NULL,
	TRANSDATE		DATE NOT NULL,
	TXT		NVARCHAR(100) NOT NULL,

	-- Misure
	CURRENCYCODE		NVARCHAR(3) NOT NULL,
	VALUE		NUMERIC(28, 12) NOT NULL,
	CALCULATEDAMOUNT		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_MARKUPTRANS_TransazioniSpeseAccessorie PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSTABLEID,
		TRANSRECID,
		LINENUM
	)
);

END;
GO

