
CREATE PROCEDURE AX2009.usp_Create_DLVREASON_CausaleConsegna
AS
BEGIN
	SET NOCOUNT ON;

	CREATE TABLE AX2009.DLVREASON_CausaleConsegna (
		-- Chiavi
		DATAAREAID  CHAR(4) NOT NULL,
		CODE  NVARCHAR(10) NOT NULL,
		RECID  BIGINT NOT NULL,

		-- Dimensioni
		TXT  NVARCHAR(60) NOT NULL,
		FREE  BIT NOT NULL,
		NPODLVLINETYPE  SMALLINT NOT NULL,
		NPOCONTRACTWORK  BIT NOT NULL


		-- Constraint
		CONSTRAINT PK_DLVREASON_CausaleConsegna PRIMARY KEY CLUSTERED (
			DATAAREAID,
			CODE
		)
	);

END;
GO

