
CREATE PROCEDURE AX2009.usp_Merge_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga;
	EXEC AX2009.usp_AddIndexes_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga;
END;

MERGE INTO AX2009.INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga AS TGT
USING AX2009.INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.JOURNALID = TGT.JOURNALID AND SRC.ITEMGROUP = TGT.ITEMGROUP AND SRC.LINENUM = TGT.LINENUM
WHEN MATCHED AND (TGT.ITEMID <> SRC.ITEMID OR TGT.FISCALLIFOGROUPID <> SRC.FISCALLIFOGROUPID OR TGT.YR <> SRC.YR OR TGT.UNITID <> SRC.UNITID OR TGT.REMAINQTY <> SRC.REMAINQTY OR TGT.UNITVALUE <> SRC.UNITVALUE)
  THEN UPDATE SET TGT.ITEMID = SRC.ITEMID, TGT.FISCALLIFOGROUPID = SRC.FISCALLIFOGROUPID, TGT.YR = SRC.YR, TGT.UNITID = SRC.UNITID, TGT.REMAINQTY = SRC.REMAINQTY, TGT.UNITVALUE = SRC.UNITVALUE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, JOURNALID, ITEMGROUP, LINENUM, RECID, ITEMID, FISCALLIFOGROUPID, YR, UNITID, REMAINQTY, UNITVALUE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'JOURNALID = ' + CAST(COALESCE(inserted.JOURNALID, deleted.JOURNALID) AS NVARCHAR) + ' - ' + 'ITEMGROUP = ' + CAST(COALESCE(inserted.ITEMGROUP, deleted.ITEMGROUP) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

