
CREATE PROCEDURE AX2009.usp_Merge_BOM_VersioneDBA_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.BOM_VersioneDBA_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_BOM_VersioneDBA_Riga;
	EXEC AX2009.usp_AddIndexes_BOM_VersioneDBA_Riga;
END;

MERGE INTO AX2009.BOM_VersioneDBA_Riga AS TGT
USING AX2009.BOM_VersioneDBA_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BOMID = TGT.BOMID AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ITEMID <> SRC.ITEMID OR TGT.BOMQTY <> SRC.BOMQTY OR TGT.FROMDATE <> SRC.FROMDATE OR TGT.TODATE <> SRC.TODATE OR TGT.INVENTDIMID <> SRC.INVENTDIMID)
  THEN UPDATE SET TGT.ITEMID = SRC.ITEMID, TGT.BOMQTY = SRC.BOMQTY, TGT.FROMDATE = SRC.FROMDATE, TGT.TODATE = SRC.TODATE, TGT.INVENTDIMID = SRC.INVENTDIMID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BOMID, LINENUM, RECID, ITEMID, BOMQTY, FROMDATE, TODATE, INVENTDIMID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.BOM_VersioneDBA_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BOMID = ' + CAST(COALESCE(inserted.BOMID, deleted.BOMID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

