
CREATE PROCEDURE AX2009.usp_Merge_CASHDISC_ScontoCassa
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CASHDISC_ScontoCassa', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CASHDISC_ScontoCassa;
    EXEC AX2009.usp_AddIndexes_CASHDISC_ScontoCassa;
END;

MERGE INTO AX2009.CASHDISC_ScontoCassa AS TGT
USING AX2009.CASHDISC_ScontoCassaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CASHDISCCODE = TGT.CASHDISCCODE
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CASHDISCCODE, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CASHDISC_ScontoCassa' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CASHDISCCODE = ' + CAST(COALESCE(inserted.CASHDISCCODE, deleted.CASHDISCCODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

