
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDSETTLEMENT_LiquidazioniFornitore
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_VENDSETTLEMENT_LiquidazioniFornitore_ ON AX2009.VENDSETTLEMENT_LiquidazioniFornitore () INCLUDE();

END;
GO

