
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido_ ON AX2009.NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido () INCLUDE();

END;
GO

