
CREATE PROCEDURE AX2009.usp_Create_NPOBOETOTALTABLE_Insoluti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOBOETOTALTABLE_Insoluti (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CUSTACCOUNT		NVARCHAR(20) NOT NULL,
	MACROAREA		NVARCHAR(10) NOT NULL,
	EMPLID		NVARCHAR(20) NOT NULL,
	TRANSTYPE		SMALLINT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	STARTYRMTHDATE		DATE NOT NULL,

	-- Misure
	NUMBERPROTESTED		INT NOT NULL,
	NUMBERDRAWN		INT NOT NULL,
	AMOUNTDRAWN		NUMERIC(28, 12) NOT NULL,
	AMOUNTPROTESTED		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_NPOBOETOTALTABLE_Insoluti PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CUSTACCOUNT,
		MACROAREA,
		EMPLID,
		TRANSTYPE
	)
);

END;
GO

