
CREATE PROCEDURE AX2009.usp_Merge_LEDGERTRANS_TransazioniContabili
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.LEDGERTRANS_TransazioniContabili', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_LEDGERTRANS_TransazioniContabili;
    EXEC AX2009.usp_AddIndexes_LEDGERTRANS_TransazioniContabili;
END;

MERGE INTO AX2009.LEDGERTRANS_TransazioniContabili AS TGT
USING AX2009.LEDGERTRANS_TransazioniContabiliView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.VOUCHER = TGT.VOUCHER AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ACCOUNTNUM <> SRC.ACCOUNTNUM OR TGT.TXT <> SRC.TXT OR TGT.TRANSTYPE <> SRC.TRANSTYPE OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.POSTING <> SRC.POSTING OR TGT.PERIODCODE <> SRC.PERIODCODE OR TGT.OPERATIONSTAX <> SRC.OPERATIONSTAX OR TGT.LEDGERPOSTINGJOURNALID <> SRC.LEDGERPOSTINGJOURNALID OR TGT.TAXREFID <> SRC.TAXREFID OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.NPOVALUEDATE <> SRC.NPOVALUEDATE OR TGT.NPOCUSTVENDAC <> SRC.NPOCUSTVENDAC OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_ OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.AMOUNTCUR <> SRC.AMOUNTCUR OR TGT.AMOUNTMST <> SRC.AMOUNTMST OR TGT.QTY <> SRC.QTY)
  THEN UPDATE SET TGT.ACCOUNTNUM = SRC.ACCOUNTNUM, TGT.TXT = SRC.TXT, TGT.TRANSTYPE = SRC.TRANSTYPE, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.POSTING = SRC.POSTING, TGT.PERIODCODE = SRC.PERIODCODE, TGT.OPERATIONSTAX = SRC.OPERATIONSTAX, TGT.LEDGERPOSTINGJOURNALID = SRC.LEDGERPOSTINGJOURNALID, TGT.TAXREFID = SRC.TAXREFID, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.NPOVALUEDATE = SRC.NPOVALUEDATE, TGT.NPOCUSTVENDAC = SRC.NPOCUSTVENDAC, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.AMOUNTCUR = SRC.AMOUNTCUR, TGT.AMOUNTMST = SRC.AMOUNTMST, TGT.QTY = SRC.QTY
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSDATE, VOUCHER, RECID, ACCOUNTNUM, TXT, TRANSTYPE, DIMENSION, DIMENSION2_, DIMENSION3_, POSTING, PERIODCODE, OPERATIONSTAX, LEDGERPOSTINGJOURNALID, TAXREFID, CREATEDDATETIME, NPOVALUEDATE, NPOCUSTVENDAC, DIMENSION4_, DIMENSION5_, DIMENSION6_, CURRENCYCODE, AMOUNTCUR, AMOUNTMST, QTY)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.LEDGERTRANS_TransazioniContabili' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'VOUCHER = ' + CAST(COALESCE(inserted.VOUCHER, deleted.VOUCHER) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

