
CREATE PROCEDURE AX2009.usp_Merge_VENDINVOICETRANS_FattureFornitore_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.VENDINVOICETRANS_FattureFornitore_Riga', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_VENDINVOICETRANS_FattureFornitore_Riga;
    EXEC AX2009.usp_AddIndexes_VENDINVOICETRANS_FattureFornitore_Riga;
END;

MERGE INTO AX2009.VENDINVOICETRANS_FattureFornitore_Riga AS TGT
USING AX2009.VENDINVOICETRANS_FattureFornitore_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PURCHID = TGT.PURCHID AND SRC.INVOICEID = TGT.INVOICEID AND SRC.INVOICEDATE = TGT.INVOICEDATE AND SRC.NUMBERSEQUENCEGROUP = TGT.NUMBERSEQUENCEGROUP AND SRC.INTERNALINVOICEID = TGT.INTERNALINVOICEID AND SRC.LINENUM = TGT.LINENUM
WHEN MATCHED AND (TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.ITEMID <> SRC.ITEMID OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.ORIGPURCHID <> SRC.ORIGPURCHID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_ OR TGT.PURCHUNIT <> SRC.PURCHUNIT OR TGT.QTY <> SRC.QTY OR TGT.INVENTQTY <> SRC.INVENTQTY OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.LINEAMOUNT <> SRC.LINEAMOUNT OR TGT.LINEAMOUNTMST <> SRC.LINEAMOUNTMST OR TGT.PURCHPRICE <> SRC.PURCHPRICE OR TGT.PRICEUNIT <> SRC.PRICEUNIT OR TGT.DISCPERCENT <> SRC.DISCPERCENT OR TGT.DISCAMOUNT <> SRC.DISCAMOUNT)
  THEN UPDATE SET TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.ITEMID = SRC.ITEMID, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.ORIGPURCHID = SRC.ORIGPURCHID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_, TGT.PURCHUNIT = SRC.PURCHUNIT, TGT.QTY = SRC.QTY, TGT.INVENTQTY = SRC.INVENTQTY, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.LINEAMOUNT = SRC.LINEAMOUNT, TGT.LINEAMOUNTMST = SRC.LINEAMOUNTMST, TGT.PURCHPRICE = SRC.PURCHPRICE, TGT.PRICEUNIT = SRC.PRICEUNIT, TGT.DISCPERCENT = SRC.DISCPERCENT, TGT.DISCAMOUNT = SRC.DISCAMOUNT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PURCHID, INVOICEID, INVOICEDATE, NUMBERSEQUENCEGROUP, INTERNALINVOICEID, LINENUM, RECID, INVENTTRANSID, ITEMID, DIMENSION, DIMENSION2_, DIMENSION3_, ORIGPURCHID, INVENTDIMID, DIMENSION4_, DIMENSION5_, DIMENSION6_, PURCHUNIT, QTY, INVENTQTY, CURRENCYCODE, LINEAMOUNT, LINEAMOUNTMST, PURCHPRICE, PRICEUNIT, DISCPERCENT, DISCAMOUNT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.VENDINVOICETRANS_FattureFornitore_Riga' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PURCHID = ' + CAST(COALESCE(inserted.PURCHID, deleted.PURCHID) AS NVARCHAR) + ' - ' + 'INVOICEID = ' + CAST(COALESCE(inserted.INVOICEID, deleted.INVOICEID) AS NVARCHAR) + ' - ' + 'INVOICEDATE = ' + CAST(COALESCE(inserted.INVOICEDATE, deleted.INVOICEDATE) AS NVARCHAR) + ' - ' + 'NUMBERSEQUENCEGROUP = ' + CAST(COALESCE(inserted.NUMBERSEQUENCEGROUP, deleted.NUMBERSEQUENCEGROUP) AS NVARCHAR) + ' - ' + 'INTERNALINVOICEID = ' + CAST(COALESCE(inserted.INTERNALINVOICEID, deleted.INTERNALINVOICEID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

