
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTINVOICETRANS_FattureCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_CUSTINVOICETRANS_FattureCliente_Riga_DATAAREAID_INVENTTRANSID_ORIGSALESID_INCLUDE ON [AX2009].[CUSTINVOICETRANS_FattureCliente_Riga] ([DATAAREAID],[INVENTTRANSID],[ORIGSALESID]) INCLUDE ([INVOICEDATE],[INVOICEID],[SALESID],[RECID],[QTY],[LINEAMOUNTMST])

END;
GO

