
CREATE PROCEDURE AX2009.usp_Create_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	MNGTYPE		SMALLINT NOT NULL,
	FROMDATE		DATE NOT NULL,
    RECID       BIGINT NOT NULL,

	-- Misure
	AMOUNT		DECIMAL(28, 12) NOT NULL


	-- Constraint
	CONSTRAINT PK_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio PRIMARY KEY CLUSTERED (
		DATAAREAID,
		MNGTYPE,
		FROMDATE
	)
);

END;
GO

