
CREATE PROCEDURE AX2009.usp_Create_NPOCUSTPROJECT_Commessa
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOCUSTPROJECT_Commessa (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    CUSTACCOUNT        NVARCHAR(20) NOT NULL,
    PROJECTCODE        NVARCHAR(40) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DOCUMENTDESCRIPTION        NVARCHAR(70) NOT NULL,
    VENDPROJECTID        NVARCHAR(20) NOT NULL,

    -- Misure
    TOTALQTY        NUMERIC(28, 12) NOT NULL,
    METCOVERAGETYPE        SMALLINT NOT NULL

    -- Constraint
    CONSTRAINT PK_NPOCUSTPROJECT_Commessa PRIMARY KEY CLUSTERED (
        DATAAREAID,
        CUSTACCOUNT,
        PROJECTCODE
    )
);

END;
GO

