
CREATE PROCEDURE AX2009.usp_Create_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	JOURNALNUM		NVARCHAR(10) NOT NULL,
	LINENUM		NUMERIC(28, 12) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	VENDTRANSID		BIGINT NOT NULL,
	PAYMENT		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		JOURNALNUM,
		LINENUM,
		RECID
	)
);

END;
GO

