
CREATE PROCEDURE AX2009.usp_AddIndexes_COSTINGVERSION_VersioneDeterminazioneCosti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_COSTINGVERSION_VersioneDeterminazioneCosti_ ON AX2009.COSTINGVERSION_VersioneDeterminazioneCosti () INCLUDE();

END;
GO

