
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte_ ON AX2009.INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte () INCLUDE();

END;
GO

