
CREATE PROCEDURE AX2009.usp_Merge_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.METPRICECALCITEMSETUP_CalcoloPrezzi_Extra', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra;
    EXEC AX2009.usp_AddIndexes_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra;
END;

MERGE INTO AX2009.METPRICECALCITEMSETUP_CalcoloPrezzi_Extra AS TGT
USING AX2009.METPRICECALCITEMSETUP_CalcoloPrezzi_ExtraView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.REFTABLEID = TGT.REFTABLEID AND SRC.REFRECID = TGT.REFRECID
WHEN MATCHED AND (TGT.PRIMARYVENDORID <> SRC.PRIMARYVENDORID OR TGT.STOPEXPLODEITEM <> SRC.STOPEXPLODEITEM OR TGT.BOMCALCGROUPID <> SRC.BOMCALCGROUPID OR TGT.STOPEXPLODEBOMCALCGROUP <> SRC.STOPEXPLODEBOMCALCGROUP)
  THEN UPDATE SET TGT.PRIMARYVENDORID = SRC.PRIMARYVENDORID, TGT.STOPEXPLODEITEM = SRC.STOPEXPLODEITEM, TGT.BOMCALCGROUPID = SRC.BOMCALCGROUPID, TGT.STOPEXPLODEBOMCALCGROUP = SRC.STOPEXPLODEBOMCALCGROUP
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, REFTABLEID, REFRECID, RECID, PRIMARYVENDORID, STOPEXPLODEITEM, BOMCALCGROUPID, STOPEXPLODEBOMCALCGROUP)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METPRICECALCITEMSETUP_CalcoloPrezzi_Extra' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'REFTABLEID = ' + CAST(COALESCE(inserted.REFTABLEID, deleted.REFTABLEID) AS NVARCHAR) + ' - ' + 'REFRECID = ' + CAST(COALESCE(inserted.REFRECID, deleted.REFRECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

