
CREATE PROCEDURE AX2009.usp_Create_DIRPARTYTABLE_Rubrica
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.DIRPARTYTABLE_Rubrica (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PARTYID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    NAME        NVARCHAR(60) NOT NULL,
    NPODIRPARTYTABLEGROUPID        NVARCHAR(10) NOT NULL


    -- Constraint
    CONSTRAINT PK_DIRPARTYTABLE_Rubrica PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PARTYID
    )
);

END;
GO

