
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga_ ON AX2009.INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga () INCLUDE();

END;
GO

