
CREATE PROCEDURE AX2009.usp_Merge_MARKUPTRANS_TransazioniSpeseAccessorie
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.MARKUPTRANS_TransazioniSpeseAccessorie', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_MARKUPTRANS_TransazioniSpeseAccessorie;
	EXEC AX2009.usp_AddIndexes_MARKUPTRANS_TransazioniSpeseAccessorie;
END;

MERGE INTO AX2009.MARKUPTRANS_TransazioniSpeseAccessorie AS TGT
USING AX2009.MARKUPTRANS_TransazioniSpeseAccessorieView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSTABLEID = TGT.TRANSTABLEID AND SRC.TRANSRECID = TGT.TRANSRECID AND SRC.LINENUM = TGT.LINENUM
WHEN MATCHED AND (TGT.MARKUPCODE <> SRC.MARKUPCODE OR TGT.TRANSDATE <> SRC.TRANSDATE OR TGT.TXT <> SRC.TXT OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.VALUE <> SRC.VALUE OR TGT.CALCULATEDAMOUNT <> SRC.CALCULATEDAMOUNT)
  THEN UPDATE SET TGT.MARKUPCODE = SRC.MARKUPCODE, TGT.TRANSDATE = SRC.TRANSDATE, TGT.TXT = SRC.TXT, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.VALUE = SRC.VALUE, TGT.CALCULATEDAMOUNT = SRC.CALCULATEDAMOUNT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSTABLEID, TRANSRECID, LINENUM, RECID, MARKUPCODE, TRANSDATE, TXT, CURRENCYCODE, VALUE, CALCULATEDAMOUNT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.MARKUPTRANS_TransazioniSpeseAccessorie' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSTABLEID = ' + CAST(COALESCE(inserted.TRANSTABLEID, deleted.TRANSTABLEID) AS NVARCHAR) + ' - ' + 'TRANSRECID = ' + CAST(COALESCE(inserted.TRANSRECID, deleted.TRANSRECID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

