
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPACKINGITEMS_Pacchi_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPACKINGITEMS_Pacchi_Riga_ ON AX2009.NPOPACKINGITEMS_Pacchi_Riga () INCLUDE();

END;
GO

