
CREATE PROCEDURE AX2009.usp_AddIndexes_BOMVERSION_VersioneDBA
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_BOMVERSION_VersioneDBA_DATAAREAID_ITEMID_BOMID ON [AX2009].[BOMVERSION_VersioneDBA] ([DATAAREAID],[ITEMID],[BOMID])

END;
GO

