
CREATE PROCEDURE AX2009.usp_Create_TAXBOOKSECTION_SezionaleIVA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.TAXBOOKSECTION_SezionaleIVA (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TAXBOOKSECTIONID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_TAXBOOKSECTION_SezionaleIVA PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TAXBOOKSECTIONID
	)
);

END;
GO

