
CREATE PROCEDURE AX2009.usp_Merge_TAXDATA_DettaglioIVA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.TAXDATA_DettaglioIVA', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_TAXDATA_DettaglioIVA;
	EXEC AX2009.usp_AddIndexes_TAXDATA_DettaglioIVA;
END;

MERGE INTO AX2009.TAXDATA_DettaglioIVA AS TGT
USING AX2009.TAXDATA_DettaglioIVAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TAXCODE = TGT.TAXCODE AND SRC.TAXFROMDATE = TGT.TAXFROMDATE AND SRC.TAXTODATE = TGT.TAXTODATE
WHEN MATCHED AND (TGT.VATEXEMPTPCT <> SRC.VATEXEMPTPCT)
  THEN UPDATE SET TGT.VATEXEMPTPCT = SRC.VATEXEMPTPCT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TAXCODE, TAXFROMDATE, TAXTODATE, RECID, VATEXEMPTPCT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.TAXDATA_DettaglioIVA' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TAXCODE = ' + CAST(COALESCE(inserted.TAXCODE, deleted.TAXCODE) AS NVARCHAR) + ' - ' + 'TAXFROMDATE = ' + CAST(COALESCE(inserted.TAXFROMDATE, deleted.TAXFROMDATE) AS NVARCHAR) + ' - ' + 'TAXTODATE = ' + CAST(COALESCE(inserted.TAXTODATE, deleted.TAXTODATE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

