
CREATE PROCEDURE AX2009.usp_Create_ADDRESSSTATE_Regione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ADDRESSSTATE_Regione (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	COUNTRYREGIONID		NVARCHAR(10) NOT NULL,
	STATEID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_ADDRESSSTATE_Regione PRIMARY KEY CLUSTERED (
		DATAAREAID,
		COUNTRYREGIONID,
		STATEID
	)
);

END;
GO

