
CREATE PROCEDURE AX2009.usp_Create_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	FINISHINGID		NVARCHAR(10) NOT NULL,
	OPRNUM		INT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	OPRID		NVARCHAR(10) NOT NULL,
	WRKCTRID		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		FINISHINGID,
		OPRNUM
	)
);

END;
GO

