
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTRANSFERJOUR_OrdiniTrasferimento
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTRANSFERJOUR_OrdiniTrasferimento_ ON AX2009.INVENTTRANSFERJOUR_OrdiniTrasferimento () INCLUDE();

END;
GO

