
CREATE PROCEDURE AX2009.usp_Merge_NPOPACKINGSLIPPALLETINFO_DDTPallet
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPACKINGSLIPPALLETINFO_DDTPallet', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOPACKINGSLIPPALLETINFO_DDTPallet;
	EXEC AX2009.usp_AddIndexes_NPOPACKINGSLIPPALLETINFO_DDTPallet;
END;

MERGE INTO AX2009.NPOPACKINGSLIPPALLETINFO_DDTPallet AS TGT
USING AX2009.NPOPACKINGSLIPPALLETINFO_DDTPalletView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.DELIVERYDATE = TGT.DELIVERYDATE AND SRC.PACKINGSLIPID = TGT.PACKINGSLIPID AND SRC.INVENTTRANSID = TGT.INVENTTRANSID AND SRC.WMSPALLETID = TGT.WMSPALLETID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.TRANSREFID <> SRC.TRANSREFID OR TGT.REFTABLEID <> SRC.REFTABLEID OR TGT.INVOICERECID <> SRC.INVOICERECID OR TGT.WEIGHT <> SRC.WEIGHT)
  THEN UPDATE SET TGT.TRANSREFID = SRC.TRANSREFID, TGT.REFTABLEID = SRC.REFTABLEID, TGT.INVOICERECID = SRC.INVOICERECID, TGT.WEIGHT = SRC.WEIGHT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, DELIVERYDATE, PACKINGSLIPID, INVENTTRANSID, WMSPALLETID, RECID, TRANSREFID, REFTABLEID, INVOICERECID, WEIGHT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOPACKINGSLIPPALLETINFO_DDTPallet' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'DELIVERYDATE = ' + CAST(COALESCE(inserted.DELIVERYDATE, deleted.DELIVERYDATE) AS NVARCHAR) + ' - ' + 'PACKINGSLIPID = ' + CAST(COALESCE(inserted.PACKINGSLIPID, deleted.PACKINGSLIPID) AS NVARCHAR) + ' - ' + 'INVENTTRANSID = ' + CAST(COALESCE(inserted.INVENTTRANSID, deleted.INVENTTRANSID) AS NVARCHAR) + ' - ' + 'WMSPALLETID = ' + CAST(COALESCE(inserted.WMSPALLETID, deleted.WMSPALLETID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

