
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita_INVENTDIMID_INVENTDIMIDDEFAULT ON AX2009.INVENTITEMSALESSETUP_ArticoloImpostazioniVendita (INVENTDIMID, INVENTDIMIDDEFAULT);

END;
GO

