
CREATE PROCEDURE AX2009.usp_Merge_CUSTINVOICETRANS_FattureCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.CUSTINVOICETRANS_FattureCliente_Riga', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTINVOICETRANS_FattureCliente_Riga;
    EXEC AX2009.usp_AddIndexes_CUSTINVOICETRANS_FattureCliente_Riga;
END;

MERGE INTO AX2009.CUSTINVOICETRANS_FattureCliente_Riga AS TGT
USING AX2009.CUSTINVOICETRANS_FattureCliente_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVOICEDATE = TGT.INVOICEDATE AND SRC.INVOICEID = TGT.INVOICEID AND SRC.SALESID = TGT.SALESID AND SRC.NUMBERSEQUENCEGROUP = TGT.NUMBERSEQUENCEGROUP AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.ITEMID <> SRC.ITEMID OR TGT.NAME <> SRC.NAME OR TGT.SALESGROUP <> SRC.SALESGROUP OR TGT.LEDGERACCOUNT <> SRC.LEDGERACCOUNT OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.ORIGSALESID <> SRC.ORIGSALESID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_ OR TGT.SALESUNIT <> SRC.SALESUNIT OR TGT.QTY <> SRC.QTY OR TGT.INVENTQTY <> SRC.INVENTQTY OR TGT.NPOQTYSHIPPED <> SRC.NPOQTYSHIPPED OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.LINEAMOUNT <> SRC.LINEAMOUNT OR TGT.LINEAMOUNTMST <> SRC.LINEAMOUNTMST OR TGT.SALESPRICE <> SRC.SALESPRICE OR TGT.PRICEUNIT <> SRC.PRICEUNIT OR TGT.DISCPERCENT <> SRC.DISCPERCENT OR TGT.DISCAMOUNT <> SRC.DISCAMOUNT OR TGT.METSYSSALESPRICE <> SRC.METSYSSALESPRICE OR TGT.METSYSLINEDISC <> SRC.METSYSLINEDISC OR TGT.METSYSLINEPERCENT <> SRC.METSYSLINEPERCENT OR TGT.METVENDPROJECTID <> SRC.METVENDPROJECTID OR TGT.METMETALCOVERPRICEKG <> SRC.METMETALCOVERPRICEKG OR TGT.METPROJECTCODE <> SRC.METPROJECTCODE OR TGT.SUMLINEDISC <> SRC.SUMLINEDISC OR TGT.SUMLINEDISCMST <> SRC.SUMLINEDISCMST)
  THEN UPDATE SET TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.ITEMID = SRC.ITEMID, TGT.NAME = SRC.NAME, TGT.SALESGROUP = SRC.SALESGROUP, TGT.LEDGERACCOUNT = SRC.LEDGERACCOUNT, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.ORIGSALESID = SRC.ORIGSALESID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_, TGT.SALESUNIT = SRC.SALESUNIT, TGT.QTY = SRC.QTY, TGT.INVENTQTY = SRC.INVENTQTY, TGT.NPOQTYSHIPPED = SRC.NPOQTYSHIPPED, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.LINEAMOUNT = SRC.LINEAMOUNT, TGT.LINEAMOUNTMST = SRC.LINEAMOUNTMST, TGT.SALESPRICE = SRC.SALESPRICE, TGT.PRICEUNIT = SRC.PRICEUNIT, TGT.DISCPERCENT = SRC.DISCPERCENT, TGT.DISCAMOUNT = SRC.DISCAMOUNT, TGT.METSYSSALESPRICE = SRC.METSYSSALESPRICE, TGT.METSYSLINEDISC = SRC.METSYSLINEDISC, TGT.METSYSLINEPERCENT = SRC.METSYSLINEPERCENT, TGT.METVENDPROJECTID = SRC.METVENDPROJECTID, TGT.METMETALCOVERPRICEKG = SRC.METMETALCOVERPRICEKG, TGT.METPROJECTCODE = SRC.METPROJECTCODE, TGT.SUMLINEDISC = SRC.SUMLINEDISC, TGT.SUMLINEDISCMST = SRC.SUMLINEDISCMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVOICEDATE, INVOICEID, SALESID, NUMBERSEQUENCEGROUP, LINENUM, RECID, INVENTTRANSID, ITEMID, NAME, SALESGROUP, LEDGERACCOUNT, DIMENSION, DIMENSION2_, DIMENSION3_, ORIGSALESID, INVENTDIMID, DIMENSION4_, DIMENSION5_, DIMENSION6_, SALESUNIT, QTY, INVENTQTY, NPOQTYSHIPPED, CURRENCYCODE, LINEAMOUNT, LINEAMOUNTMST, SALESPRICE, PRICEUNIT, DISCPERCENT, DISCAMOUNT, METSYSSALESPRICE, METSYSLINEDISC, METSYSLINEPERCENT, METVENDPROJECTID, METMETALCOVERPRICEKG, METPROJECTCODE, SUMLINEDISC, SUMLINEDISCMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTINVOICETRANS_FattureCliente_Riga' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVOICEDATE = ' + CAST(COALESCE(inserted.INVOICEDATE, deleted.INVOICEDATE) AS NVARCHAR) + ' - ' + 'INVOICEID = ' + CAST(COALESCE(inserted.INVOICEID, deleted.INVOICEID) AS NVARCHAR) + ' - ' + 'SALESID = ' + CAST(COALESCE(inserted.SALESID, deleted.SALESID) AS NVARCHAR) + ' - ' + 'NUMBERSEQUENCEGROUP = ' + CAST(COALESCE(inserted.NUMBERSEQUENCEGROUP, deleted.NUMBERSEQUENCEGROUP) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

