
CREATE PROCEDURE AX2009.usp_Merge_SHIPCARRIERCOMPANY_SocietaSpedizioni
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SHIPCARRIERCOMPANY_SocietaSpedizioni', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_SHIPCARRIERCOMPANY_SocietaSpedizioni;
	EXEC AX2009.usp_AddIndexes_SHIPCARRIERCOMPANY_SocietaSpedizioni;
END;

MERGE INTO AX2009.SHIPCARRIERCOMPANY_SocietaSpedizioni AS TGT
USING AX2009.SHIPCARRIERCOMPANY_SocietaSpedizioniView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CARRIERNAME = TGT.CARRIERNAME
WHEN MATCHED AND (TGT.VENDACCOUNT <> SRC.VENDACCOUNT)
  THEN UPDATE SET TGT.VENDACCOUNT = SRC.VENDACCOUNT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CARRIERNAME, RECID, VENDACCOUNT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.SHIPCARRIERCOMPANY_SocietaSpedizioni' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CARRIERNAME = ' + CAST(COALESCE(inserted.CARRIERNAME, deleted.CARRIERNAME) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

