CREATE PROCEDURE AX2009.usp_Merge_CUSTTABLE_Cliente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.CUSTTABLE_Cliente', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTTABLE_Cliente;
    EXEC AX2009.usp_AddIndexes_CUSTTABLE_Cliente;
END;

MERGE INTO AX2009.CUSTTABLE_Cliente AS TGT
USING AX2009.CUSTTABLE_ClienteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.CUSTGROUP <> SRC.CUSTGROUP OR TGT.LINEDISC <> SRC.LINEDISC OR TGT.PAYMTERMID <> SRC.PAYMTERMID OR TGT.CASHDISC <> SRC.CASHDISC OR TGT.SALESGROUP <> SRC.SALESGROUP OR TGT.BLOCKED <> SRC.BLOCKED OR TGT.VATNUM <> SRC.VATNUM OR TGT.COUNTRYREGIONID <> SRC.COUNTRYREGIONID OR TGT.STATE <> SRC.STATE OR TGT.COUNTY <> SRC.COUNTY OR TGT.STATISTICSGROUP <> SRC.STATISTICSGROUP OR TGT.PAYMMODE <> SRC.PAYMMODE OR TGT.SALESPOOLID <> SRC.SALESPOOLID OR TGT.CITY <> SRC.CITY OR TGT.FISCALCODE <> SRC.FISCALCODE OR TGT.CUSTCLASSIFICATIONID <> SRC.CUSTCLASSIFICATIONID OR TGT.PARTYTYPE <> SRC.PARTYTYPE OR TGT.PARTYID <> SRC.PARTYID OR TGT.SALESDISTRICTID <> SRC.SALESDISTRICTID OR TGT.SEGMENTID <> SRC.SEGMENTID OR TGT.SUBSEGMENTID <> SRC.SUBSEGMENTID OR TGT.MAINCONTACTID <> SRC.MAINCONTACTID OR TGT.NPOCUSTGROUPID <> SRC.NPOCUSTGROUPID OR TGT.CreatedDate <> SRC.CreatedDate)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.CUSTGROUP = SRC.CUSTGROUP, TGT.LINEDISC = SRC.LINEDISC, TGT.PAYMTERMID = SRC.PAYMTERMID, TGT.CASHDISC = SRC.CASHDISC, TGT.SALESGROUP = SRC.SALESGROUP, TGT.BLOCKED = SRC.BLOCKED, TGT.VATNUM = SRC.VATNUM, TGT.COUNTRYREGIONID = SRC.COUNTRYREGIONID, TGT.STATE = SRC.STATE, TGT.COUNTY = SRC.COUNTY, TGT.STATISTICSGROUP = SRC.STATISTICSGROUP, TGT.PAYMMODE = SRC.PAYMMODE, TGT.SALESPOOLID = SRC.SALESPOOLID, TGT.CITY = SRC.CITY, TGT.FISCALCODE = SRC.FISCALCODE, TGT.CUSTCLASSIFICATIONID = SRC.CUSTCLASSIFICATIONID, TGT.PARTYTYPE = SRC.PARTYTYPE, TGT.PARTYID = SRC.PARTYID, TGT.SALESDISTRICTID = SRC.SALESDISTRICTID, TGT.SEGMENTID = SRC.SEGMENTID, TGT.SUBSEGMENTID = SRC.SUBSEGMENTID, TGT.MAINCONTACTID = SRC.MAINCONTACTID, TGT.NPOCUSTGROUPID = SRC.NPOCUSTGROUPID, TGT.CreatedDate = SRC.CreatedDate
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ACCOUNTNUM, RECID, NAME, CUSTGROUP, LINEDISC, PAYMTERMID, CASHDISC, SALESGROUP, BLOCKED, VATNUM, COUNTRYREGIONID, STATE, COUNTY, STATISTICSGROUP, PAYMMODE, SALESPOOLID, CITY, FISCALCODE, CUSTCLASSIFICATIONID, PARTYTYPE, PARTYID, SALESDISTRICTID, SEGMENTID, SUBSEGMENTID, MAINCONTACTID, NPOCUSTGROUPID, CreatedDate)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTTABLE_Cliente' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

