
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTPACKINGSLIPJOUR_DDTCliente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTPACKINGSLIPJOUR_DDTCliente_ ON AX2009.CUSTPACKINGSLIPJOUR_DDTCliente () INCLUDE();

END;
GO

