
CREATE PROCEDURE AX2009.usp_Merge_NPOITEMFAMILIES_FamigliaArticolo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOITEMFAMILIES_FamigliaArticolo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOITEMFAMILIES_FamigliaArticolo;
	EXEC AX2009.usp_AddIndexes_NPOITEMFAMILIES_FamigliaArticolo;
END;

MERGE INTO AX2009.NPOITEMFAMILIES_FamigliaArticolo AS TGT
USING AX2009.NPOITEMFAMILIES_FamigliaArticoloView (nolock) AS SRC
ON SRC.FAMILYID = TGT.FAMILYID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (FAMILYID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOITEMFAMILIES_FamigliaArticolo' AS full_olap_table_name,
	'FAMILYID = ' + CAST(COALESCE(inserted.FAMILYID, deleted.FAMILYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

