
CREATE PROCEDURE AX2009.usp_Merge_VENDPAYMMODETABLE_MetodoPagamentoFornitore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.VENDPAYMMODETABLE_MetodoPagamentoFornitore', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_VENDPAYMMODETABLE_MetodoPagamentoFornitore;
	EXEC AX2009.usp_AddIndexes_VENDPAYMMODETABLE_MetodoPagamentoFornitore;
END;

MERGE INTO AX2009.VENDPAYMMODETABLE_MetodoPagamentoFornitore AS TGT
USING AX2009.VENDPAYMMODETABLE_MetodoPagamentoFornitoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PAYMMODE = TGT.PAYMMODE
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PAYMMODE, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.VENDPAYMMODETABLE_MetodoPagamentoFornitore' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PAYMMODE = ' + CAST(COALESCE(inserted.PAYMMODE, deleted.PAYMMODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

