
CREATE PROCEDURE AX2009.usp_AddIndexes_BOMCALCGROUP_GruppoCalcoloDBA
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_BOMCALCGROUP_GruppoCalcoloDBA_ ON AX2009.BOMCALCGROUP_GruppoCalcoloDBA () INCLUDE();

END;
GO

