
CREATE PROCEDURE AX2009.usp_AddIndexes_ADDRESS_Indirizzo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ADDRESS_Indirizzo_ ON AX2009.ADDRESS_Indirizzo () INCLUDE();

END;
GO

