
CREATE PROCEDURE AX2009.usp_AddIndexes_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile_ ON AX2009.LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile () INCLUDE();

END;
GO

