
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTITEMGROUP_GruppoArticoli
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTITEMGROUP_GruppoArticoli_ ON AX2009.INVENTITEMGROUP_GruppoArticoli () INCLUDE();

END;
GO

