
CREATE PROCEDURE AX2009.usp_Merge_CUSTPACKINGSLIPTRANS_DDTCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTPACKINGSLIPTRANS_DDTCliente_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTPACKINGSLIPTRANS_DDTCliente_Riga;
	EXEC AX2009.usp_AddIndexes_CUSTPACKINGSLIPTRANS_DDTCliente_Riga;
END;

MERGE INTO AX2009.CUSTPACKINGSLIPTRANS_DDTCliente_Riga AS TGT
USING AX2009.CUSTPACKINGSLIPTRANS_DDTCliente_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.DELIVERYDATE = TGT.DELIVERYDATE AND SRC.PACKINGSLIPID = TGT.PACKINGSLIPID AND SRC.SALESID = TGT.SALESID AND SRC.NPOLINENUM = TGT.NPOLINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.ITEMID <> SRC.ITEMID OR TGT.ORIGSALESID <> SRC.ORIGSALESID OR TGT.NPOCONTRACTWORKTRANSID <> SRC.NPOCONTRACTWORKTRANSID OR TGT.SALESUNIT <> SRC.SALESUNIT OR TGT.QTY <> SRC.QTY OR TGT.INVENTQTY <> SRC.INVENTQTY OR TGT.ORDERED <> SRC.ORDERED OR TGT.REMAIN <> SRC.REMAIN OR TGT.NPOCONTRACTWORKQTY <> SRC.NPOCONTRACTWORKQTY OR TGT.NPOQTYSHIPPED <> SRC.NPOQTYSHIPPED OR TGT.NPOCONTRACTWORKSECQTY <> SRC.NPOCONTRACTWORKSECQTY OR TGT.VALUEMST <> SRC.VALUEMST)
  THEN UPDATE SET TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.ITEMID = SRC.ITEMID, TGT.ORIGSALESID = SRC.ORIGSALESID, TGT.NPOCONTRACTWORKTRANSID = SRC.NPOCONTRACTWORKTRANSID, TGT.SALESUNIT = SRC.SALESUNIT, TGT.QTY = SRC.QTY, TGT.INVENTQTY = SRC.INVENTQTY, TGT.ORDERED = SRC.ORDERED, TGT.REMAIN = SRC.REMAIN, TGT.NPOCONTRACTWORKQTY = SRC.NPOCONTRACTWORKQTY, TGT.NPOQTYSHIPPED = SRC.NPOQTYSHIPPED, TGT.NPOCONTRACTWORKSECQTY = SRC.NPOCONTRACTWORKSECQTY, TGT.VALUEMST = SRC.VALUEMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, DELIVERYDATE, PACKINGSLIPID, SALESID, NPOLINENUM, RECID, INVENTTRANSID, ITEMID, ORIGSALESID, NPOCONTRACTWORKTRANSID, SALESUNIT, QTY, INVENTQTY, ORDERED, REMAIN, NPOCONTRACTWORKQTY, NPOQTYSHIPPED, NPOCONTRACTWORKSECQTY, VALUEMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTPACKINGSLIPTRANS_DDTCliente_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'DELIVERYDATE = ' + CAST(COALESCE(inserted.DELIVERYDATE, deleted.DELIVERYDATE) AS NVARCHAR) + ' - ' + 'PACKINGSLIPID = ' + CAST(COALESCE(inserted.PACKINGSLIPID, deleted.PACKINGSLIPID) AS NVARCHAR) + ' - ' + 'SALESID = ' + CAST(COALESCE(inserted.SALESID, deleted.SALESID) AS NVARCHAR) + ' - ' + 'NPOLINENUM = ' + CAST(COALESCE(inserted.NPOLINENUM, deleted.NPOLINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

