
CREATE PROCEDURE AX2009.usp_Create_VENDPAYMMODETABLE_MetodoPagamentoFornitore
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.VENDPAYMMODETABLE_MetodoPagamentoFornitore (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PAYMMODE		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_VENDPAYMMODETABLE_MetodoPagamentoFornitore PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PAYMMODE
	)
);

END;
GO

