
CREATE PROCEDURE AX2009.usp_AddIndexes_RETURNDISPOSITIONCODE_CodiceSmaltimento
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_RETURNDISPOSITIONCODE_CodiceSmaltimento_ ON AX2009.RETURNDISPOSITIONCODE_CodiceSmaltimento () INCLUDE();

END;
GO

