
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOWORKCALENDARDATELINE_DataLavorativa_Turno
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOWORKCALENDARDATELINE_DataLavorativa_Turno_ ON AX2009.NPOWORKCALENDARDATELINE_DataLavorativa_Turno () INCLUDE();

END;
GO

