
CREATE PROCEDURE AX2009.usp_AddIndexes_BOM_VersioneDBA_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_BOM_VersioneDBA_Riga_DATAAREAID_ITEMID_INCLUDE ON AX2009.BOM_VersioneDBA_Riga (DATAAREAID, ITEMID) INCLUDE (BOMID);

END;
GO

