
CREATE PROCEDURE AX2009.usp_Merge_BOMVERSION_VersioneDBA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.BOMVERSION_VersioneDBA', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_BOMVERSION_VersioneDBA;
	EXEC AX2009.usp_AddIndexes_BOMVERSION_VersioneDBA;
END;

MERGE INTO AX2009.BOMVERSION_VersioneDBA AS TGT
USING AX2009.BOMVERSION_VersioneDBAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BOMID = TGT.BOMID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.TODATE <> SRC.TODATE OR TGT.FROMDATE <> SRC.FROMDATE OR TGT.ITEMID <> SRC.ITEMID)
  THEN UPDATE SET TGT.TODATE = SRC.TODATE, TGT.FROMDATE = SRC.FROMDATE, TGT.ITEMID = SRC.ITEMID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BOMID, RECID, TODATE, FROMDATE, ITEMID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.BOMVERSION_VersioneDBA' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BOMID = ' + CAST(COALESCE(inserted.BOMID, deleted.BOMID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

