
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOITEMSERIES_Serie
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOITEMSERIES_Serie_ ON AX2009.NPOITEMSERIES_Serie () INCLUDE();

END;
GO

