
CREATE PROCEDURE AX2009.usp_Merge_INVENTTABLEMODULE_ArticoloUnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTTABLEMODULE_ArticoloUnitaDiMisura', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTTABLEMODULE_ArticoloUnitaDiMisura;
	EXEC AX2009.usp_AddIndexes_INVENTTABLEMODULE_ArticoloUnitaDiMisura;
END;

MERGE INTO AX2009.INVENTTABLEMODULE_ArticoloUnitaDiMisura AS TGT
USING AX2009.INVENTTABLEMODULE_ArticoloUnitaDiMisuraView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.MODULETYPE = TGT.MODULETYPE
WHEN MATCHED AND (TGT.UNITID <> SRC.UNITID OR TGT.PRICE <> SRC.PRICE OR TGT.PRICEUNIT <> SRC.PRICEUNIT OR TGT.MARKUP <> SRC.MARKUP OR TGT.PRICEQTY <> SRC.PRICEQTY OR TGT.NPOSECONDINVENTUNITID <> SRC.NPOSECONDINVENTUNITID OR TGT.NPOSECONDUNITACTIVE <> SRC.NPOSECONDUNITACTIVE)
  THEN UPDATE SET TGT.UNITID = SRC.UNITID, TGT.PRICE = SRC.PRICE, TGT.PRICEUNIT = SRC.PRICEUNIT, TGT.MARKUP = SRC.MARKUP, TGT.PRICEQTY = SRC.PRICEQTY, TGT.NPOSECONDINVENTUNITID = SRC.NPOSECONDINVENTUNITID, TGT.NPOSECONDUNITACTIVE = SRC.NPOSECONDUNITACTIVE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, MODULETYPE, RECID, UNITID, PRICE, PRICEUNIT, MARKUP, PRICEQTY, NPOSECONDINVENTUNITID, NPOSECONDUNITACTIVE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTTABLEMODULE_ArticoloUnitaDiMisura' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'MODULETYPE = ' + CAST(COALESCE(inserted.MODULETYPE, deleted.MODULETYPE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

