
CREATE PROCEDURE AX2009.usp_Merge_NPOCRSTABLE_RiepilogoCRS
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOCRSTABLE_RiepilogoCRS', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOCRSTABLE_RiepilogoCRS;
	EXEC AX2009.usp_AddIndexes_NPOCRSTABLE_RiepilogoCRS;
END;

MERGE INTO AX2009.NPOCRSTABLE_RiepilogoCRS AS TGT
USING AX2009.NPOCRSTABLE_RiepilogoCRSView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CRSNUM = TGT.CRSNUM
WHEN MATCHED AND (TGT.EXPEDITIONSTATUS <> SRC.EXPEDITIONSTATUS OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.COVERINGBASIS <> SRC.COVERINGBASIS OR TGT.STATIONID <> SRC.STATIONID OR TGT.AREAID <> SRC.AREAID)
  THEN UPDATE SET TGT.EXPEDITIONSTATUS = SRC.EXPEDITIONSTATUS, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.COVERINGBASIS = SRC.COVERINGBASIS, TGT.STATIONID = SRC.STATIONID, TGT.AREAID = SRC.AREAID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CRSNUM, RECID, EXPEDITIONSTATUS, CREATEDDATETIME, COVERINGBASIS, STATIONID, AREAID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOCRSTABLE_RiepilogoCRS' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CRSNUM = ' + CAST(COALESCE(inserted.CRSNUM, deleted.CRSNUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

