CREATE PROCEDURE AX2009.usp_Merge_BOMCALCTRANS_CalcoloDBA_Riga (
    @SkipMerge BIT = 1
)
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.BOMCALCTRANS_CalcoloDBA_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_BOMCALCTRANS_CalcoloDBA_Riga;
	EXEC AX2009.usp_AddIndexes_BOMCALCTRANS_CalcoloDBA_Riga;
END;

IF (@SkipMerge = CAST(0 AS BIT))
BEGIN

WITH TGT
AS (
    SELECT *
    FROM AX2009.BOMCALCTRANS_CalcoloDBA_Riga
    WHERE TRANSDATE >= CAST('20230101' AS DATE)
)
MERGE INTO TGT
USING AX2009.BOMCALCTRANS_CalcoloDBA_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PRICECALCID = TGT.PRICECALCID AND SRC.LINENUM = TGT.LINENUM
WHEN MATCHED AND (TGT.COSTGROUPID <> SRC.COSTGROUPID OR TGT.LEVEL_ <> SRC.LEVEL_ OR TGT.QTY <> SRC.QTY OR TGT.COSTPRICE <> SRC.COSTPRICE OR TGT.TRANSDATE <> SRC.TRANSDATE OR TGT.KEY1 <> SRC.KEY1 OR TGT.KEY2 <> SRC.KEY2 OR TGT.KEY3 <> SRC.KEY3 OR TGT.CONSUMPTIONVARIABLE <> SRC.CONSUMPTIONVARIABLE OR TGT.OPRNUM <> SRC.OPRNUM OR TGT.CALCTYPE <> SRC.CALCTYPE OR TGT.COSTPRICEUNIT <> SRC.COSTPRICEUNIT OR TGT.COSTPRICEQTY <> SRC.COSTPRICEQTY OR TGT.COSTMARKUPQTY <> SRC.COSTMARKUPQTY OR TGT.CONSUMPTIONCONSTANT <> SRC.CONSUMPTIONCONSTANT)
  THEN UPDATE SET TGT.COSTGROUPID = SRC.COSTGROUPID, TGT.LEVEL_ = SRC.LEVEL_, TGT.QTY = SRC.QTY, TGT.COSTPRICE = SRC.COSTPRICE, TGT.TRANSDATE = SRC.TRANSDATE, TGT.KEY1 = SRC.KEY1, TGT.KEY2 = SRC.KEY2, TGT.KEY3 = SRC.KEY3, TGT.CONSUMPTIONVARIABLE = SRC.CONSUMPTIONVARIABLE, TGT.OPRNUM = SRC.OPRNUM, TGT.CALCTYPE = SRC.CALCTYPE, TGT.COSTPRICEUNIT = SRC.COSTPRICEUNIT, TGT.COSTPRICEQTY = SRC.COSTPRICEQTY, TGT.COSTMARKUPQTY = SRC.COSTMARKUPQTY, TGT.CONSUMPTIONCONSTANT = SRC.CONSUMPTIONCONSTANT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PRICECALCID, LINENUM, RECID, COSTGROUPID, LEVEL_, QTY, COSTPRICE, TRANSDATE, KEY1, KEY2, KEY3, CONSUMPTIONVARIABLE, OPRNUM, CALCTYPE, COSTPRICEUNIT, COSTPRICEQTY, COSTMARKUPQTY, 0, 1, 0, CONSUMPTIONCONSTANT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.BOMCALCTRANS_CalcoloDBA_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PRICECALCID = ' + CAST(COALESCE(inserted.PRICECALCID, deleted.PRICECALCID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;

END;
GO

