
CREATE PROCEDURE AX2009.usp_Create_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOITEMPRICEGROUP_ArticoloGruppoPrezzi (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ITEMPRICEGROUPID		NVARCHAR(10) NOT NULL,
	REVITEMID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		RECID
	)
);

END;
GO

