
CREATE PROCEDURE AX2009.usp_AddIndexes_WMSPICKINGROUTE_CicloPrelievo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WMSPICKINGROUTE_CicloPrelievo_ ON AX2009.WMSPICKINGROUTE_CicloPrelievo () INCLUDE();

END;
GO

