
CREATE PROCEDURE AX2009.usp_Create_DLVTERM_TerminiConsegna
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.DLVTERM_TerminiConsegna (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CODE		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TXT		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_DLVTERM_TerminiConsegna PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CODE
	)
);

END;
GO

