
CREATE PROCEDURE AX2009.usp_Create_CUSTPACKINGSLIPTRANS_DDTCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTPACKINGSLIPTRANS_DDTCliente_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	DELIVERYDATE		DATE NOT NULL,
	PACKINGSLIPID		NVARCHAR(20) NOT NULL,
	SALESID		NVARCHAR(20) NOT NULL,
	NPOLINENUM		INT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	INVENTTRANSID		NVARCHAR(20) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	ORIGSALESID		NVARCHAR(20) NOT NULL,
	NPOCONTRACTWORKTRANSID		NVARCHAR(20) NOT NULL,

	-- Misure
	SALESUNIT		NVARCHAR(10) NOT NULL,
	QTY		NUMERIC(28, 12) NOT NULL,
	INVENTQTY		NUMERIC(28, 12) NOT NULL,
	ORDERED		NUMERIC(28, 12) NOT NULL,
	REMAIN		NUMERIC(28, 12) NOT NULL,
	NPOCONTRACTWORKQTY		NUMERIC(28, 12) NOT NULL,
	NPOQTYSHIPPED		NUMERIC(28, 12) NOT NULL,
	NPOCONTRACTWORKSECQTY		NUMERIC(28, 12) NOT NULL,
	VALUEMST		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_CUSTPACKINGSLIPTRANS_DDTCliente_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		DELIVERYDATE,
		PACKINGSLIPID,
		SALESID,
		NPOLINENUM,
		RECID
	)
);

END;
GO

