
CREATE PROCEDURE AX2009.usp_Merge_UNITCONVERT_ConversioneUnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.UNITCONVERT_ConversioneUnitaDiMisura', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_UNITCONVERT_ConversioneUnitaDiMisura;
	EXEC AX2009.usp_AddIndexes_UNITCONVERT_ConversioneUnitaDiMisura;
END;

MERGE INTO AX2009.UNITCONVERT_ConversioneUnitaDiMisura AS TGT
USING AX2009.UNITCONVERT_ConversioneUnitaDiMisuraView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.FROMUNIT = TGT.FROMUNIT AND SRC.TOUNIT = TGT.TOUNIT
WHEN MATCHED AND (TGT.FACTOR <> SRC.FACTOR OR TGT.MARKUP <> SRC.MARKUP OR TGT.ROUNDOFF <> SRC.ROUNDOFF)
  THEN UPDATE SET TGT.FACTOR = SRC.FACTOR, TGT.MARKUP = SRC.MARKUP, TGT.ROUNDOFF = SRC.ROUNDOFF
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, FROMUNIT, TOUNIT, RECID, FACTOR, MARKUP, ROUNDOFF)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.UNITCONVERT_ConversioneUnitaDiMisura' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'FROMUNIT = ' + CAST(COALESCE(inserted.FROMUNIT, deleted.FROMUNIT) AS NVARCHAR) + ' - ' + 'TOUNIT = ' + CAST(COALESCE(inserted.TOUNIT, deleted.TOUNIT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

