
CREATE PROCEDURE AX2009.usp_AddIndexes_PRODBOM_OrdiniProduzione_DBA
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_PRODBOM_OrdiniProduzione_DBA_PRODLINETYPE_REMAINBOMPHYSICAL_INCLUDE ON AX2009.PRODBOM_OrdiniProduzione_DBA (PRODLINETYPE, REMAINBOMPHYSICAL) INCLUDE (ITEMID, INVENTTRANSID);

END;
GO

