
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione_ ON AX2009.NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione () INCLUDE();

END;
GO

