
CREATE PROCEDURE AX2009.usp_Create_VENDTRANSOPEN_TransazioniFornitoreAperte
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.VENDTRANSOPEN_TransazioniFornitoreAperte (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSDATE		DATE NOT NULL,
	ACCOUNTNUM		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	REFRECID		BIGINT NOT NULL,
	DUEDATE		DATE NOT NULL,

	-- Misure
	AMOUNTCUR		NUMERIC(28, 12) NOT NULL,
	AMOUNTMST		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_VENDTRANSOPEN_TransazioniFornitoreAperte PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSDATE,
		ACCOUNTNUM,
		RECID
	)
);

END;
GO

