CREATE PROCEDURE AX2009.usp_Create_NPOSALESCREDITGROUP_ClienteFidoDiGruppo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOSALESCREDITGROUP_ClienteFidoDiGruppo (
    -- Chiavi
    CUSTOMERCODE        SMALLINT NOT NULL,
    CUSTOMERRELATION        NVARCHAR(20) NOT NULL,
    DATEFROM        DATE NOT NULL,
    DATETO        DATE NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    REASONID        NVARCHAR(10) NOT NULL,

    -- Misure
    AMOUNT        NUMERIC(28, 12) NOT NULL,
    INSURANCEAMOUNT        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_NPOSALESCREDITGROUP_ClienteFidoDiGruppo PRIMARY KEY CLUSTERED (
        CUSTOMERCODE,
        CUSTOMERRELATION,
        DATEFROM,
        DATETO,
        RECID
    )
);

END;
GO

