
CREATE PROCEDURE AX2009.usp_Merge_COMMISSIONSALESGROUP_GruppoVendite
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.COMMISSIONSALESGROUP_GruppoVendite', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_COMMISSIONSALESGROUP_GruppoVendite;
	EXEC AX2009.usp_AddIndexes_COMMISSIONSALESGROUP_GruppoVendite;
END;

MERGE INTO AX2009.COMMISSIONSALESGROUP_GruppoVendite AS TGT
USING AX2009.COMMISSIONSALESGROUP_GruppoVenditeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.GROUPID = TGT.GROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, GROUPID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.COMMISSIONSALESGROUP_GruppoVendite' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'GROUPID = ' + CAST(COALESCE(inserted.GROUPID, deleted.GROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

