
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTITEMPRICESIM_PrezzoArticoliInSospeso
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTITEMPRICESIM_PrezzoArticoliInSospeso_ ON AX2009.INVENTITEMPRICESIM_PrezzoArticoliInSospeso () INCLUDE();

END;
GO

