
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA_ ON AX2009.NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA () INCLUDE();

END;
GO

