
CREATE PROCEDURE AX2009.usp_AddIndexes_BOMCALCTABLE_CalcoloDBA
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_BOMCALCTABLE_CalcoloDBA_ ON AX2009.BOMCALCTABLE_CalcoloDBA () INCLUDE();

END;
GO

