
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDTABLE_Fornitore
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_VENDTABLE_Fornitore_ ON AX2009.VENDTABLE_Fornitore () INCLUDE();

END;
GO

