
CREATE PROCEDURE AX2009.usp_AddIndexes_ROUTE_Ciclo_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ROUTE_Ciclo_Riga_ ON AX2009.ROUTE_Ciclo_Riga () INCLUDE();

END;
GO

