
CREATE PROCEDURE AX2009.usp_Merge_NPOITEMSUBFAMILIES_SottofamigliaArticolo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOITEMSUBFAMILIES_SottofamigliaArticolo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOITEMSUBFAMILIES_SottofamigliaArticolo;
	EXEC AX2009.usp_AddIndexes_NPOITEMSUBFAMILIES_SottofamigliaArticolo;
END;

MERGE INTO AX2009.NPOITEMSUBFAMILIES_SottofamigliaArticolo AS TGT
USING AX2009.NPOITEMSUBFAMILIES_SottofamigliaArticoloView (nolock) AS SRC
ON SRC.SUBFAMILYID = TGT.SUBFAMILYID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.FAMILYID <> SRC.FAMILYID)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.FAMILYID = SRC.FAMILYID
WHEN NOT MATCHED
  THEN INSERT VALUES (SUBFAMILYID, RECID, NAME, FAMILYID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOITEMSUBFAMILIES_SottofamigliaArticolo' AS full_olap_table_name,
	'SUBFAMILYID = ' + CAST(COALESCE(inserted.SUBFAMILYID, deleted.SUBFAMILYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

