
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTSUM_ScorteDisponibili
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTSUM_ScorteDisponibili_ ON AX2009.INVENTSUM_ScorteDisponibili () INCLUDE();

END;
GO

