
CREATE PROCEDURE AX2009.usp_Merge_NPOWORKSTATIONAREA_AreaDiLavoro
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOWORKSTATIONAREA_AreaDiLavoro', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOWORKSTATIONAREA_AreaDiLavoro;
    EXEC AX2009.usp_AddIndexes_NPOWORKSTATIONAREA_AreaDiLavoro;
END;

MERGE INTO AX2009.NPOWORKSTATIONAREA_AreaDiLavoro AS TGT
USING AX2009.NPOWORKSTATIONAREA_AreaDiLavoroView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.AREAID = TGT.AREAID
WHEN MATCHED AND (TGT.DEPARTMENTID <> SRC.DEPARTMENTID)
  THEN UPDATE SET TGT.DEPARTMENTID = SRC.DEPARTMENTID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, AREAID, RECID, DEPARTMENTID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOWORKSTATIONAREA_AreaDiLavoro' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'AREAID = ' + CAST(COALESCE(inserted.AREAID, deleted.AREAID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

