
CREATE PROCEDURE AX2009.usp_Merge_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo;
    EXEC AX2009.usp_AddIndexes_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo;
END;

MERGE INTO AX2009.CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo AS TGT
USING AX2009.CUSTVENDEXTERNALITEM_DescrizioneEsternaArticoloView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.INVENTDIMID = TGT.INVENTDIMID AND SRC.MODULETYPE = TGT.MODULETYPE AND SRC.CUSTVENDRELATION = TGT.CUSTVENDRELATION
WHEN MATCHED AND (TGT.EXTERNALITEMTXT <> SRC.EXTERNALITEMTXT OR TGT.EXTERNALITEMID <> SRC.EXTERNALITEMID)
  THEN UPDATE SET TGT.EXTERNALITEMTXT = SRC.EXTERNALITEMTXT, TGT.EXTERNALITEMID = SRC.EXTERNALITEMID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, INVENTDIMID, MODULETYPE, CUSTVENDRELATION, RECID, EXTERNALITEMTXT, EXTERNALITEMID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'INVENTDIMID = ' + CAST(COALESCE(inserted.INVENTDIMID, deleted.INVENTDIMID) AS NVARCHAR) + ' - ' + 'MODULETYPE = ' + CAST(COALESCE(inserted.MODULETYPE, deleted.MODULETYPE) AS NVARCHAR) + ' - ' + 'CUSTVENDRELATION = ' + CAST(COALESCE(inserted.CUSTVENDRELATION, deleted.CUSTVENDRELATION) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

