
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOSCRAPCAUSE_CausaleScarto
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOSCRAPCAUSE_CausaleScarto_ ON AX2009.NPOSCRAPCAUSE_CausaleScarto () INCLUDE();

END;
GO

