
CREATE PROCEDURE AX2009.usp_AddIndexes_WMSORDER_OrdiniMagazzino
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WMSORDER_OrdiniMagazzino_ ON AX2009.WMSORDER_OrdiniMagazzino () INCLUDE();

END;
GO

