
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTRANSFERLINE_OrdiniTrasferimento_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTRANSFERLINE_OrdiniTrasferimento_Riga_ ON AX2009.INVENTTRANSFERLINE_OrdiniTrasferimento_Riga () INCLUDE();

END;
GO

