
CREATE PROCEDURE AX2009.usp_Merge_AIFENDPOINT_AIFEndPoint
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.AIFENDPOINT_AIFEndPoint', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_AIFENDPOINT_AIFEndPoint;
    EXEC AX2009.usp_AddIndexes_AIFENDPOINT_AIFEndPoint;
END;

MERGE INTO AX2009.AIFENDPOINT_AIFEndPoint AS TGT
USING AX2009.AIFENDPOINT_AIFEndPointView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ENDPOINTID = TGT.ENDPOINTID
WHEN MATCHED AND (TGT.INTERCOMPANYCOMPANYID <> SRC.INTERCOMPANYCOMPANYID OR TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.INTERCOMPANYCOMPANYID = SRC.INTERCOMPANYCOMPANYID, TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ENDPOINTID, RECID, INTERCOMPANYCOMPANYID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.AIFENDPOINT_AIFEndPoint' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ENDPOINTID = ' + CAST(COALESCE(inserted.ENDPOINTID, deleted.ENDPOINTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

