
CREATE PROCEDURE AX2009.usp_Create_VENDSETTLEMENT_LiquidazioniFornitore
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.VENDSETTLEMENT_LiquidazioniFornitore (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSDATE		DATE NOT NULL,
	OFFSETTRANSVOUCHER		NVARCHAR(20) NOT NULL,
	ACCOUNTNUM		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TRANSRECID		BIGINT NOT NULL,
	DUEDATE		DATE NOT NULL,
	TRANSCOMPANY		CHAR(4) NOT NULL,

	-- Misure
	SETTLEAMOUNTCUR		NUMERIC(28, 12) NOT NULL,
	SETTLEAMOUNTMST		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_VENDSETTLEMENT_LiquidazioniFornitore PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSDATE,
		OFFSETTRANSVOUCHER,
		ACCOUNTNUM,
		RECID
	)
);

END;
GO

