
CREATE PROCEDURE AX2009.usp_Create_SMMBUSRELSEGMENTGROUP_Segmento
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SMMBUSRELSEGMENTGROUP_Segmento (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    SEGMENTID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DESCRIPTION        NVARCHAR(60) NOT NULL,
    BUSINESSSECTORID        NVARCHAR(20) NOT NULL


    -- Constraint
    CONSTRAINT PK_SMMBUSRELSEGMENTGROUP_Segmento PRIMARY KEY CLUSTERED (
        DATAAREAID,
        SEGMENTID
    )
);

END;
GO

