
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDINVOICETRANS_FattureFornitore_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_VENDINVOICETRANS_FattureFornitore_Riga_DATAAREAID_INVENTTRANSID_ORIGPURCHID ON [AX2009].[VENDINVOICETRANS_FattureFornitore_Riga] ([DATAAREAID],[INVENTTRANSID],[ORIGPURCHID])

END;
GO

