
CREATE PROCEDURE AX2009.usp_AddIndexes_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard_ ON AX2009.METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard () INCLUDE();

END;
GO

