
CREATE PROCEDURE AX2009.usp_AddIndexes_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio_ ON AX2009.METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio () INCLUDE();

END;
GO

