
CREATE PROCEDURE AX2009.usp_Merge_CUSTTRANSOPEN_TransazioniClienteAperte
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTTRANSOPEN_TransazioniClienteAperte', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTTRANSOPEN_TransazioniClienteAperte;
	EXEC AX2009.usp_AddIndexes_CUSTTRANSOPEN_TransazioniClienteAperte;
END;

MERGE INTO AX2009.CUSTTRANSOPEN_TransazioniClienteAperte AS TGT
USING AX2009.CUSTTRANSOPEN_TransazioniClienteAperteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM AND SRC.DUEDATE = TGT.DUEDATE AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.REFRECID <> SRC.REFRECID OR TGT.TRANSDATE <> SRC.TRANSDATE OR TGT.AMOUNTCUR <> SRC.AMOUNTCUR OR TGT.AMOUNTMST <> SRC.AMOUNTMST)
  THEN UPDATE SET TGT.REFRECID = SRC.REFRECID, TGT.TRANSDATE = SRC.TRANSDATE, TGT.AMOUNTCUR = SRC.AMOUNTCUR, TGT.AMOUNTMST = SRC.AMOUNTMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ACCOUNTNUM, DUEDATE, RECID, REFRECID, TRANSDATE, AMOUNTCUR, AMOUNTMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTTRANSOPEN_TransazioniClienteAperte' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) + ' - ' + 'DUEDATE = ' + CAST(COALESCE(inserted.DUEDATE, deleted.DUEDATE) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

