
CREATE PROCEDURE AX2009.usp_AddIndexes_METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi_ ON AX2009.METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi () INCLUDE();

END;
GO

