
CREATE PROCEDURE AX2009.usp_AddIndexes_SRSANALYSISENUMS_Etichetta
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SRSANALYSISENUMS_Etichetta_ ON AX2009.SRSANALYSISENUMS_Etichetta () INCLUDE();

END;
GO

