
CREATE PROCEDURE AX2009.usp_Merge_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating;
	EXEC AX2009.usp_AddIndexes_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating;
END;

MERGE INTO AX2009.NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating AS TGT
USING AX2009.NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRatingView (nolock) AS SRC
ON SRC.PARTYID = TGT.PARTYID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.RATINGREFTYPE <> SRC.RATINGREFTYPE OR TGT.RATINGREFID <> SRC.RATINGREFID OR TGT.RATINGID <> SRC.RATINGID OR TGT.DATEFROM <> SRC.DATEFROM OR TGT.DATETO <> SRC.DATETO)
  THEN UPDATE SET TGT.RATINGREFTYPE = SRC.RATINGREFTYPE, TGT.RATINGREFID = SRC.RATINGREFID, TGT.RATINGID = SRC.RATINGID, TGT.DATEFROM = SRC.DATEFROM, TGT.DATETO = SRC.DATETO
WHEN NOT MATCHED
  THEN INSERT VALUES (PARTYID, RECID, RATINGREFTYPE, RATINGREFID, RATINGID, DATEFROM, DATETO)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating' AS full_olap_table_name,
	'PARTYID = ' + CAST(COALESCE(inserted.PARTYID, deleted.PARTYID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

