
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi_ ON AX2009.NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi () INCLUDE ();

END;
GO

