
CREATE PROCEDURE AX2009.usp_Create_ROUTEOPRTABLE_Operazione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ROUTEOPRTABLE_Operazione (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	OPRID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	NPOREVENUEGROUP		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_ROUTEOPRTABLE_Operazione PRIMARY KEY CLUSTERED (
		DATAAREAID,
		OPRID
	)
);

END;
GO

