
CREATE PROCEDURE AX2009.usp_AddIndexes_UNIT_UnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_UNIT_UnitaDiMisura_ ON AX2009.UNIT_UnitaDiMisura () INCLUDE();

END;
GO

