
CREATE PROCEDURE AX2009.usp_AddIndexes_TIMEZONESLIST_FusoOrario
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_TIMEZONESLIST_FusoOrario_ ON AX2009.TIMEZONESLIST_FusoOrario () INCLUDE();

END;
GO

