
CREATE PROCEDURE AX2009.usp_Create_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPACKINGSLIPEXTERNAL_DDTTerzeParti (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	DELIVERYDATE		DATE NOT NULL,
	PACKINGCODE		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	REFDATAAREAID		NVARCHAR(4) NOT NULL,
	DELIVERYNAME		NVARCHAR(60) NOT NULL,
	DELIVERYADDRESS		NVARCHAR(250) NOT NULL,
	JOURNEYID		NVARCHAR(20) NOT NULL,
	DLVMODEID		NVARCHAR(10) NOT NULL,
	DELIVERYCOUNTY		NVARCHAR(10) NOT NULL,
	DELIVERYCOUNTRYREGIONID		NVARCHAR(10) NOT NULL,
	DELIVERYSTATEID		NVARCHAR(10) NOT NULL,

	-- Misure
	WEIGHT		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti PRIMARY KEY CLUSTERED (
		DATAAREAID,
		DELIVERYDATE,
		PACKINGCODE,
		RECID
	)
);

END;
GO

