
CREATE PROCEDURE AX2009.usp_Create_INVENTLOCATION_Magazzino
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTLOCATION_Magazzino (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    INVENTSITEID        NVARCHAR(10) NOT NULL,
    INVENTLOCATIONID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    REQCALENDARID        NVARCHAR(10) NOT NULL,
    VENDACCOUNT        NVARCHAR(20) NOT NULL


    -- Constraint
    CONSTRAINT PK_INVENTLOCATION_Magazzino PRIMARY KEY CLUSTERED (
        DATAAREAID,
        INVENTSITEID,
        INVENTLOCATIONID
    )
);

END;
GO

