
CREATE PROCEDURE AX2009.usp_Create_COMMISSIONSALESREP_Agente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.COMMISSIONSALESREP_Agente (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	GROUPID		NVARCHAR(10) NOT NULL,
	EMPLID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni


	-- Constraint
	CONSTRAINT PK_COMMISSIONSALESREP_Agente PRIMARY KEY CLUSTERED (
		DATAAREAID,
		GROUPID,
		EMPLID
	)
);

END;
GO

