
CREATE PROCEDURE AX2009.usp_Merge_PRICEDISCTABLE_AccordiPrezzi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PRICEDISCTABLE_AccordiPrezzi', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_PRICEDISCTABLE_AccordiPrezzi;
    EXEC AX2009.usp_AddIndexes_PRICEDISCTABLE_AccordiPrezzi;
END;

MERGE INTO AX2009.PRICEDISCTABLE_AccordiPrezzi AS TGT
USING AX2009.PRICEDISCTABLE_AccordiPrezziView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.RELATION = TGT.RELATION AND SRC.ITEMCODE = TGT.ITEMCODE AND SRC.ACCOUNTCODE = TGT.ACCOUNTCODE AND SRC.ITEMRELATION = TGT.ITEMRELATION AND SRC.ACCOUNTRELATION = TGT.ACCOUNTRELATION AND SRC.QUANTITYAMOUNT = TGT.QUANTITYAMOUNT AND SRC.FROMDATE = TGT.FROMDATE AND SRC.TODATE = TGT.TODATE AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.UNITID <> SRC.UNITID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.PERCENT1 <> SRC.PERCENT1 OR TGT.PERCENT2 <> SRC.PERCENT2 OR TGT.CURRENCY <> SRC.CURRENCY OR TGT.AMOUNT <> SRC.AMOUNT OR TGT.PRICEUNIT <> SRC.PRICEUNIT OR TGT.MARKUP <> SRC.MARKUP)
  THEN UPDATE SET TGT.UNITID = SRC.UNITID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.PERCENT1 = SRC.PERCENT1, TGT.PERCENT2 = SRC.PERCENT2, TGT.CURRENCY = SRC.CURRENCY, TGT.AMOUNT = SRC.AMOUNT, TGT.PRICEUNIT = SRC.PRICEUNIT, TGT.MARKUP = SRC.MARKUP
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, RELATION, ITEMCODE, ACCOUNTCODE, ITEMRELATION, ACCOUNTRELATION, QUANTITYAMOUNT, FROMDATE, TODATE, RECID, UNITID, INVENTDIMID, PERCENT1, PERCENT2, CURRENCY, AMOUNT, PRICEUNIT, MARKUP)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.PRICEDISCTABLE_AccordiPrezzi' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'RELATION = ' + CAST(COALESCE(inserted.RELATION, deleted.RELATION) AS NVARCHAR) + ' - ' + 'ITEMCODE = ' + CAST(COALESCE(inserted.ITEMCODE, deleted.ITEMCODE) AS NVARCHAR) + ' - ' + 'ACCOUNTCODE = ' + CAST(COALESCE(inserted.ACCOUNTCODE, deleted.ACCOUNTCODE) AS NVARCHAR) + ' - ' + 'ITEMRELATION = ' + CAST(COALESCE(inserted.ITEMRELATION, deleted.ITEMRELATION) AS NVARCHAR) + ' - ' + 'ACCOUNTRELATION = ' + CAST(COALESCE(inserted.ACCOUNTRELATION, deleted.ACCOUNTRELATION) AS NVARCHAR) + ' - ' + 'QUANTITYAMOUNT = ' + CAST(COALESCE(inserted.QUANTITYAMOUNT, deleted.QUANTITYAMOUNT) AS NVARCHAR) + ' - ' + 'FROMDATE = ' + CAST(COALESCE(inserted.FROMDATE, deleted.FROMDATE) AS NVARCHAR) + ' - ' + 'TODATE = ' + CAST(COALESCE(inserted.TODATE, deleted.TODATE) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

