
CREATE PROCEDURE AX2009.usp_Create_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    SALESDISTRICTID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DESCRIPTION        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita PRIMARY KEY CLUSTERED (
        DATAAREAID,
        SALESDISTRICTID
    )
);

END;
GO

