
CREATE PROCEDURE AX2009.usp_AddIndexes_SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale_ ON AX2009.SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale () INCLUDE();

END;
GO

