
CREATE PROCEDURE AX2009.usp_Create_INVENTPOSTING_RegistrazioneMagazzino
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTPOSTING_RegistrazioneMagazzino (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    INVENTACCOUNTTYPE        INT NOT NULL,
    ITEMCODE        INT NOT NULL,
    ITEMRELATION        NVARCHAR(20) NOT NULL,
    CUSTVENDCODE        INT NOT NULL,
    CUSTVENDRELATION        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    TAXGROUPID        NVARCHAR(10) NOT NULL,
    LEDGERACCOUNTID        NVARCHAR(20) NOT NULL,
    COSTCODE        INT NOT NULL,
    COSTRELATION        NVARCHAR(10) NOT NULL


    -- Constraint
    CONSTRAINT PK_INVENTPOSTING_RegistrazioneMagazzino PRIMARY KEY CLUSTERED (
        DATAAREAID,
        INVENTACCOUNTTYPE,
        ITEMCODE,
        ITEMRELATION,
        CUSTVENDCODE,
        CUSTVENDRELATION
    )
);

END;
GO

