
CREATE PROCEDURE AX2009.usp_Create_NPOSCRAP_DichiarazioniScarto
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOSCRAP_DichiarazioniScarto (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    LOTID        NVARCHAR(15) NOT NULL,
    PACKINGID        NVARCHAR(18) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    WMSLOCATIONID        NVARCHAR(10) NOT NULL,
    INVENTLOCATIONID        NVARCHAR(10) NOT NULL,
    SCRAPCAUSEID        NVARCHAR(10) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    BASKETNO        NVARCHAR(18) NOT NULL,
    WORKSTATIONID        NVARCHAR(20) NOT NULL,
    SCRAPTYPE        SMALLINT NOT NULL,
    INVENTREFID        NVARCHAR(20) NOT NULL,
    INVENTREFTYPE        SMALLINT NOT NULL,
    CREATEDDATETIME        DATETIME NOT NULL,
    ITEMLENGTH        NUMERIC(28, 12) NOT NULL,

    -- Misure
    QTY        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_NPOSCRAP_DichiarazioniScarto PRIMARY KEY CLUSTERED (
        DATAAREAID,
        LOTID,
        PACKINGID,
        RECID
    )
);

END;
GO

