
CREATE PROCEDURE AX2009.usp_Create_NPOITEMTYPE_ArticoloGruppoTipoArticolo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOITEMTYPE_ArticoloGruppoTipoArticolo (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMTYPE		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	STRUCTUALGROUP		SMALLINT NOT NULL,
	ACCESSORYITEM		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOITEMTYPE_ArticoloGruppoTipoArticolo PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMTYPE
	)
);

END;
GO

