
CREATE PROCEDURE AX2009.usp_Merge_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte;
	EXEC AX2009.usp_AddIndexes_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte;
END;

MERGE INTO AX2009.INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte AS TGT
USING AX2009.INVENTITEMINVENTSETUP_ArticoloImpostazioniScorteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.INVENTDIMID = TGT.INVENTDIMID
WHEN MATCHED AND (TGT.INVENTDIMIDDEFAULT <> SRC.INVENTDIMIDDEFAULT)
  THEN UPDATE SET TGT.INVENTDIMIDDEFAULT = SRC.INVENTDIMIDDEFAULT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, INVENTDIMID, RECID, INVENTDIMIDDEFAULT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'INVENTDIMID = ' + CAST(COALESCE(inserted.INVENTDIMID, deleted.INVENTDIMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

