
CREATE PROCEDURE AX2009.usp_Merge_INVENTLOCATION_Magazzino
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTLOCATION_Magazzino', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_INVENTLOCATION_Magazzino;
    EXEC AX2009.usp_AddIndexes_INVENTLOCATION_Magazzino;
END;

MERGE INTO AX2009.INVENTLOCATION_Magazzino AS TGT
USING AX2009.INVENTLOCATION_MagazzinoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVENTSITEID = TGT.INVENTSITEID AND SRC.INVENTLOCATIONID = TGT.INVENTLOCATIONID
WHEN MATCHED AND (TGT.REQCALENDARID <> SRC.REQCALENDARID OR TGT.VENDACCOUNT <> SRC.VENDACCOUNT)
  THEN UPDATE SET TGT.REQCALENDARID = SRC.REQCALENDARID, TGT.VENDACCOUNT = SRC.VENDACCOUNT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVENTSITEID, INVENTLOCATIONID, RECID, REQCALENDARID, VENDACCOUNT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.INVENTLOCATION_Magazzino' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVENTSITEID = ' + CAST(COALESCE(inserted.INVENTSITEID, deleted.INVENTSITEID) AS NVARCHAR) + ' - ' + 'INVENTLOCATIONID = ' + CAST(COALESCE(inserted.INVENTLOCATIONID, deleted.INVENTLOCATIONID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

