
CREATE PROCEDURE AX2009.usp_Merge_NPOWORKSTATION_PostazioneDiLavoro
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.NPOWORKSTATION_PostazioneDiLavoro', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOWORKSTATION_PostazioneDiLavoro;
    EXEC AX2009.usp_AddIndexes_NPOWORKSTATION_PostazioneDiLavoro;
END;

MERGE INTO AX2009.NPOWORKSTATION_PostazioneDiLavoro AS TGT
USING AX2009.NPOWORKSTATION_PostazioneDiLavoroView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.WORKSTATIONID = TGT.WORKSTATIONID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.WMSLOCATIONID <> SRC.WMSLOCATIONID OR TGT.EMPLID <> SRC.EMPLID OR TGT.INVENTLOCATIONID <> SRC.INVENTLOCATIONID OR TGT.WRKCTRID <> SRC.WRKCTRID OR TGT.GROUPWRKCTRID <> SRC.GROUPWRKCTRID OR TGT.AREAID <> SRC.AREAID OR TGT.INVENTSITEID <> SRC.INVENTSITEID OR TGT.WORKSTATIONNAME <> SRC.WORKSTATIONNAME)
  THEN UPDATE SET TGT.WMSLOCATIONID = SRC.WMSLOCATIONID, TGT.EMPLID = SRC.EMPLID, TGT.INVENTLOCATIONID = SRC.INVENTLOCATIONID, TGT.WRKCTRID = SRC.WRKCTRID, TGT.GROUPWRKCTRID = SRC.GROUPWRKCTRID, TGT.AREAID = SRC.AREAID, TGT.INVENTSITEID = SRC.INVENTSITEID, TGT.WORKSTATIONNAME = SRC.WORKSTATIONNAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, WORKSTATIONID, RECID, WMSLOCATIONID, EMPLID, INVENTLOCATIONID, WRKCTRID, GROUPWRKCTRID, AREAID, INVENTSITEID, WORKSTATIONNAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOWORKSTATION_PostazioneDiLavoro' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'WORKSTATIONID = ' + CAST(COALESCE(inserted.WORKSTATIONID, deleted.WORKSTATIONID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

