
CREATE PROCEDURE AX2009.usp_AddIndexes_TAXTABLE_CodiceIVA
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_TAXTABLE_CodiceIVA_ ON AX2009.TAXTABLE_CodiceIVA () INCLUDE();

END;
GO

