
CREATE PROCEDURE AX2009.usp_Merge_SMMBUSSECTORGROUP_SettoreCommerciale
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SMMBUSSECTORGROUP_SettoreCommerciale', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_SMMBUSSECTORGROUP_SettoreCommerciale;
    EXEC AX2009.usp_AddIndexes_SMMBUSSECTORGROUP_SettoreCommerciale;
END;

MERGE INTO AX2009.SMMBUSSECTORGROUP_SettoreCommerciale AS TGT
USING AX2009.SMMBUSSECTORGROUP_SettoreCommercialeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BUSINESSSECTORID = TGT.BUSINESSSECTORID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BUSINESSSECTORID, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.SMMBUSSECTORGROUP_SettoreCommerciale' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BUSINESSSECTORID = ' + CAST(COALESCE(inserted.BUSINESSSECTORID, deleted.BUSINESSSECTORID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

