
CREATE PROCEDURE AX2009.usp_Create_ASSETTRANS_AmmortamentoCespiti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ASSETTRANS_AmmortamentoCespiti (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    ASSETID        NVARCHAR(20) NOT NULL,
    VOUCHER        NVARCHAR(20) NOT NULL,
    TRANSDATE        DATE NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    TXT        NVARCHAR(60) NOT NULL,
    DIMENSION        NVARCHAR(10) NOT NULL,
    DIMENSION2_        NVARCHAR(10) NOT NULL,
    DIMENSION3_        NVARCHAR(10) NOT NULL,
    TRANSTYPE        SMALLINT NOT NULL,
    ASSETGROUP        NVARCHAR(10) NOT NULL,
    DIMENSION4_        NVARCHAR(10) NOT NULL,
    DIMENSION5_        NVARCHAR(10) NOT NULL,
    DIMENSION6_        NVARCHAR(10) NOT NULL,

    -- Misure
    CURRENCYCODE        NVARCHAR(3) NOT NULL,
    AMOUNTCUR        NUMERIC(28, 12) NOT NULL,
    AMOUNTMST        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_ASSETTRANS_AmmortamentoCespiti PRIMARY KEY CLUSTERED (
        DATAAREAID,
        ASSETID,
        VOUCHER,
        TRANSDATE,
        RECID
    )
);

END;
GO

