
CREATE PROCEDURE AX2009.usp_Create_SYSCOMPANYUSERINFO_RelazioneUtente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SYSCOMPANYUSERINFO_RelazioneUtente (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	USERID		NVARCHAR(5) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	EMPLID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_SYSCOMPANYUSERINFO_RelazioneUtente PRIMARY KEY CLUSTERED (
		DATAAREAID,
		USERID
	)
);

END;
GO

