
CREATE PROCEDURE AX2009.usp_Create_CUSTINVOICETRANS_FattureCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTINVOICETRANS_FattureCliente_Riga (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    INVOICEDATE        DATE NOT NULL,
    INVOICEID        NVARCHAR(20) NOT NULL,
    SALESID        NVARCHAR(20) NOT NULL,
    NUMBERSEQUENCEGROUP        NVARCHAR(10) NOT NULL,
    LINENUM        NUMERIC(28, 12) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    NAME        NVARCHAR(1000) NOT NULL,
    SALESGROUP        NVARCHAR(10) NOT NULL,
    LEDGERACCOUNT        NVARCHAR(20) NOT NULL,
    DIMENSION        NVARCHAR(10) NOT NULL,
    DIMENSION2_        NVARCHAR(10) NOT NULL,
    DIMENSION3_        NVARCHAR(10) NOT NULL,
    ORIGSALESID        NVARCHAR(20) NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,
    DIMENSION4_        NVARCHAR(10) NOT NULL,
    DIMENSION5_        NVARCHAR(10) NOT NULL,
    DIMENSION6_        NVARCHAR(10) NOT NULL,

    -- Misure
    SALESUNIT        NVARCHAR(10) NOT NULL,
    QTY        NUMERIC(28, 12) NOT NULL,
    INVENTQTY        NUMERIC(28, 12) NOT NULL,
    NPOQTYSHIPPED        NUMERIC(28, 12) NOT NULL,
    CURRENCYCODE        NVARCHAR(3) NOT NULL,
    LINEAMOUNT        NUMERIC(28, 12) NOT NULL,
    LINEAMOUNTMST        NUMERIC(28, 12) NOT NULL,
    SALESPRICE        NUMERIC(28, 12) NOT NULL,
    PRICEUNIT        NUMERIC(28, 12) NOT NULL,
    DISCPERCENT        NUMERIC(28, 12) NOT NULL,
    DISCAMOUNT        NUMERIC(28, 12) NOT NULL,
    METSYSSALESPRICE        NUMERIC(28, 12) NOT NULL,
    METSYSLINEDISC        NUMERIC(28, 12) NOT NULL,
    METSYSLINEPERCENT        NUMERIC(28, 12) NOT NULL,

    -- Copertura metallo (integrare in Dimensioni)
    METVENDPROJECTID        NVARCHAR(20) NOT NULL,
    METMETALCOVERPRICEKG        NUMERIC(28, 12) NOT NULL,
    METPROJECTCODE        NVARCHAR(40) NOT NULL,
    SUMLINEDISC        NUMERIC(28, 12) NOT NULL,
    SUMLINEDISCMST        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_CUSTINVOICETRANS_FattureCliente_Riga PRIMARY KEY CLUSTERED (
        DATAAREAID,
        INVOICEDATE,
        INVOICEID,
        SALESID,
        NUMBERSEQUENCEGROUP,
        LINENUM,
        RECID
    )
);

END;
GO

