
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna_ ON AX2009.NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna () INCLUDE();

END;
GO

