
CREATE PROCEDURE AX2009.usp_Merge_SYSCOMPANYUSERINFO_RelazioneUtente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SYSCOMPANYUSERINFO_RelazioneUtente', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_SYSCOMPANYUSERINFO_RelazioneUtente;
	EXEC AX2009.usp_AddIndexes_SYSCOMPANYUSERINFO_RelazioneUtente;
END;

MERGE INTO AX2009.SYSCOMPANYUSERINFO_RelazioneUtente AS TGT
USING AX2009.SYSCOMPANYUSERINFO_RelazioneUtenteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.USERID = TGT.USERID
WHEN MATCHED AND (TGT.EMPLID <> SRC.EMPLID)
  THEN UPDATE SET TGT.EMPLID = SRC.EMPLID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, USERID, RECID, EMPLID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.SYSCOMPANYUSERINFO_RelazioneUtente' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'USERID = ' + CAST(COALESCE(inserted.USERID, deleted.USERID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

