
CREATE PROCEDURE AX2009.usp_Merge_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga;
	EXEC AX2009.usp_AddIndexes_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga;
END;

MERGE INTO AX2009.INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga AS TGT
USING AX2009.INVENTTRANSFERJOURLINE_OrdiniTrasferimento_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSFERID = TGT.TRANSFERID AND SRC.VOUCHERID = TGT.VOUCHERID AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.ITEMID <> SRC.ITEMID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.TRANSDATE <> SRC.TRANSDATE OR TGT.NPOINVENTPACKINGSLIPID <> SRC.NPOINVENTPACKINGSLIPID OR TGT.UNITID <> SRC.UNITID OR TGT.QTYRECEIVED <> SRC.QTYRECEIVED OR TGT.QTYSHIPPED <> SRC.QTYSHIPPED OR TGT.QTYSCRAPPED <> SRC.QTYSCRAPPED)
  THEN UPDATE SET TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.ITEMID = SRC.ITEMID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.TRANSDATE = SRC.TRANSDATE, TGT.NPOINVENTPACKINGSLIPID = SRC.NPOINVENTPACKINGSLIPID, TGT.UNITID = SRC.UNITID, TGT.QTYRECEIVED = SRC.QTYRECEIVED, TGT.QTYSHIPPED = SRC.QTYSHIPPED, TGT.QTYSCRAPPED = SRC.QTYSCRAPPED
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSFERID, VOUCHERID, LINENUM, RECID, INVENTTRANSID, ITEMID, INVENTDIMID, TRANSDATE, NPOINVENTPACKINGSLIPID, UNITID, QTYRECEIVED, QTYSHIPPED, QTYSCRAPPED)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSFERID = ' + CAST(COALESCE(inserted.TRANSFERID, deleted.TRANSFERID) AS NVARCHAR) + ' - ' + 'VOUCHERID = ' + CAST(COALESCE(inserted.VOUCHERID, deleted.VOUCHERID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

