
CREATE PROCEDURE AX2009.usp_Create_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia (
	-- Chiavi
	ITEMID		NVARCHAR(20) NOT NULL,
	SUBFAMILYID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	FAMILYID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia PRIMARY KEY CLUSTERED (
		ITEMID,
		SUBFAMILYID
	)
);

END;
GO

