
CREATE PROCEDURE AX2009.usp_Create_CUSTPAYMMODETABLE_MetodoPagamentoCliente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTPAYMMODETABLE_MetodoPagamentoCliente (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PAYMMODE		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	NPOPAYMTYPE		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_CUSTPAYMMODETABLE_MetodoPagamentoCliente PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PAYMMODE
	)
);

END;
GO

