
CREATE PROCEDURE AX2009.usp_Merge_WMSPALLET_Pallet
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WMSPALLET_Pallet', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_WMSPALLET_Pallet;
    EXEC AX2009.usp_AddIndexes_WMSPALLET_Pallet;
END;

MERGE INTO AX2009.WMSPALLET_Pallet AS TGT
USING AX2009.WMSPALLET_PalletView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.WMSPALLETID = TGT.WMSPALLETID
WHEN MATCHED AND (TGT.WMSLOCATIONID <> SRC.WMSLOCATIONID OR TGT.INVENTLOCATIONID <> SRC.INVENTLOCATIONID OR TGT.NPOBUILDDATE <> SRC.NPOBUILDDATE OR TGT.NPODESTROYED <> SRC.NPODESTROYED OR TGT.NPOLASTINVENTLOCATIONIDWEIGHT <> SRC.NPOLASTINVENTLOCATIONIDWEIGHT OR TGT.NPOLASTWORKSTATIONIDWEIGHT <> SRC.NPOLASTWORKSTATIONIDWEIGHT OR TGT.NPOLASTWORKSTATIONAREAIDWEIGHT <> SRC.NPOLASTWORKSTATIONAREAIDWEIGHT OR TGT.NPOPALLETNETWEIGHT <> SRC.NPOPALLETNETWEIGHT OR TGT.NPOPALLETGROSSWEIGHT <> SRC.NPOPALLETGROSSWEIGHT OR TGT.NPOPALLETTAREWEIGHT <> SRC.NPOPALLETTAREWEIGHT)
  THEN UPDATE SET TGT.WMSLOCATIONID = SRC.WMSLOCATIONID, TGT.INVENTLOCATIONID = SRC.INVENTLOCATIONID, TGT.NPOBUILDDATE = SRC.NPOBUILDDATE, TGT.NPODESTROYED = SRC.NPODESTROYED, TGT.NPOLASTINVENTLOCATIONIDWEIGHT = SRC.NPOLASTINVENTLOCATIONIDWEIGHT, TGT.NPOLASTWORKSTATIONIDWEIGHT = SRC.NPOLASTWORKSTATIONIDWEIGHT, TGT.NPOLASTWORKSTATIONAREAIDWEIGHT = SRC.NPOLASTWORKSTATIONAREAIDWEIGHT, TGT.NPOPALLETNETWEIGHT = SRC.NPOPALLETNETWEIGHT, TGT.NPOPALLETGROSSWEIGHT = SRC.NPOPALLETGROSSWEIGHT, TGT.NPOPALLETTAREWEIGHT = SRC.NPOPALLETTAREWEIGHT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, WMSPALLETID, RECID, WMSLOCATIONID, INVENTLOCATIONID, NPOBUILDDATE, NPODESTROYED, NPOLASTINVENTLOCATIONIDWEIGHT, NPOLASTWORKSTATIONIDWEIGHT, NPOLASTWORKSTATIONAREAIDWEIGHT, NPOPALLETNETWEIGHT, NPOPALLETGROSSWEIGHT, NPOPALLETTAREWEIGHT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.WMSPALLET_Pallet' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'WMSPALLETID = ' + CAST(COALESCE(inserted.WMSPALLETID, deleted.WMSPALLETID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

