
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet_DATAAREAID_WMSPALLETID_DELIVERYDATE ON AX2009.NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet (DATAAREAID,WMSPALLETID,DELIVERYDATE);

END;
GO

