
CREATE PROCEDURE AX2009.usp_Merge_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga;
	EXEC AX2009.usp_AddIndexes_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga;
END;

MERGE INTO AX2009.CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga AS TGT
USING AX2009.CUSTBILLOFEXCHANGETRANS_EffettiAttivi_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BILLOFEXCHANGEID = TGT.BILLOFEXCHANGEID AND SRC.SEQNUM = TGT.SEQNUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.STATUS <> SRC.STATUS OR TGT.TRANSDATE <> SRC.TRANSDATE OR TGT.DUEDATE <> SRC.DUEDATE OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.AMOUNTCUR <> SRC.AMOUNTCUR)
  THEN UPDATE SET TGT.STATUS = SRC.STATUS, TGT.TRANSDATE = SRC.TRANSDATE, TGT.DUEDATE = SRC.DUEDATE, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.AMOUNTCUR = SRC.AMOUNTCUR
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BILLOFEXCHANGEID, SEQNUM, RECID, STATUS, TRANSDATE, DUEDATE, CURRENCYCODE, AMOUNTCUR)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BILLOFEXCHANGEID = ' + CAST(COALESCE(inserted.BILLOFEXCHANGEID, deleted.BILLOFEXCHANGEID) AS NVARCHAR) + ' - ' + 'SEQNUM = ' + CAST(COALESCE(inserted.SEQNUM, deleted.SEQNUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

