
CREATE PROCEDURE AX2009.usp_Create_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	JOURNALID		NVARCHAR(10) NOT NULL,
	ITEMGROUP		INT NOT NULL,
	LINENUM		NUMERIC(28, 12) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ITEMID		NVARCHAR(20) NOT NULL,
	FISCALLIFOGROUPID		NVARCHAR(10) NOT NULL,
	YR		INT NOT NULL,

	-- Misure
	UNITID		NVARCHAR(10) NOT NULL,
	REMAINQTY		NUMERIC(28, 12) NOT NULL,
	UNITVALUE		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		JOURNALID,
		ITEMGROUP,
		LINENUM
	)
);

END;
GO

