
CREATE PROCEDURE AX2009.usp_AddIndexes_COMPANYINFO_InformazioniAzienda
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_COMPANYINFO_InformazioniAzienda_ ON AX2009.COMPANYINFO_InformazioniAzienda () INCLUDE();

END;
GO

