
CREATE PROCEDURE AX2009.usp_Merge_NPOPBAFINISHINGRELATION_FinituraAttributo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPBAFINISHINGRELATION_FinituraAttributo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOPBAFINISHINGRELATION_FinituraAttributo;
	EXEC AX2009.usp_AddIndexes_NPOPBAFINISHINGRELATION_FinituraAttributo;
END;

MERGE INTO AX2009.NPOPBAFINISHINGRELATION_FinituraAttributo AS TGT
USING AX2009.NPOPBAFINISHINGRELATION_FinituraAttributoView (nolock) AS SRC
ON SRC.FINISHINGID = TGT.FINISHINGID AND SRC.IDDETAIL = TGT.IDDETAIL AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.DETAILDESCRIPTION <> SRC.DETAILDESCRIPTION OR TGT.DETAILLEVEL <> SRC.DETAILLEVEL)
  THEN UPDATE SET TGT.DETAILDESCRIPTION = SRC.DETAILDESCRIPTION, TGT.DETAILLEVEL = SRC.DETAILLEVEL
WHEN NOT MATCHED
  THEN INSERT VALUES (FINISHINGID, IDDETAIL, RECID, DETAILDESCRIPTION, DETAILLEVEL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOPBAFINISHINGRELATION_FinituraAttributo' AS full_olap_table_name,
	'FINISHINGID = ' + CAST(COALESCE(inserted.FINISHINGID, deleted.FINISHINGID) AS NVARCHAR) + ' - ' + 'IDDETAIL = ' + CAST(COALESCE(inserted.IDDETAIL, deleted.IDDETAIL) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

