
CREATE PROCEDURE AX2009.usp_AddIndexes_BANKACCOUNTTABLE_ContoBancario
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_BANKACCOUNTTABLE_ContoBancario_ ON AX2009.BANKACCOUNTTABLE_ContoBancario () INCLUDE();

END;
GO

