
CREATE PROCEDURE AX2009.usp_Create_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite (
	-- Chiavi
	DATAAREAID  CHAR(4) NOT NULL,
	GROUPIDAS  NVARCHAR(10) NOT NULL,
	RECID  BIGINT NOT NULL,

	-- Dimensioni
	GROUPID  NVARCHAR(10) NOT NULL,
	NAME  NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite PRIMARY KEY CLUSTERED (
		DATAAREAID,
		GROUPIDAS
	)
);

END;
GO

