
CREATE PROCEDURE AX2009.usp_Create_INVENTITEMPRICESIM_PrezzoArticoliInSospeso
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTITEMPRICESIM_PrezzoArticoliInSospeso (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	VERSIONID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	FROMDATE		DATE NOT NULL,
	PRICETYPE		SMALLINT NOT NULL,
	INVENTDIMID		NVARCHAR(20) NOT NULL,
	PRICEUNIT		NUMERIC(28, 12) NOT NULL,
	PRICECALCID		NVARCHAR(20) NOT NULL,
	UNITID		NVARCHAR(10) NOT NULL,
	PRICEALLOCATEMARKUP		BIT NOT NULL,

	-- Misure
	PRICE		NUMERIC(28, 12) NOT NULL,
	PRICEQTY		NUMERIC(28, 12) NOT NULL,
	MARKUP		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_INVENTITEMPRICESIM_PrezzoArticoliInSospeso PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		VERSIONID,
		RECID
	)
);

END;
GO

