
CREATE PROCEDURE AX2009.usp_Create_WMSPALLET_Pallet
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.WMSPALLET_Pallet (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    WMSPALLETID        NVARCHAR(18) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    WMSLOCATIONID        NVARCHAR(10) NOT NULL,
    INVENTLOCATIONID        NVARCHAR(10) NOT NULL,
    NPOBUILDDATE        DATE NOT NULL,
    NPODESTROYED        BIT NOT NULL,
    NPOLASTINVENTLOCATIONIDWEIGHT        NVARCHAR(10) NOT NULL,
    NPOLASTWORKSTATIONIDWEIGHT        NVARCHAR(20) NOT NULL,
    NPOLASTWORKSTATIONAREAIDWEIGHT        NVARCHAR(25) NOT NULL,

    -- Misure
    NPOPALLETNETWEIGHT        NUMERIC(28, 12) NOT NULL,
    NPOPALLETGROSSWEIGHT        NUMERIC(28, 12) NOT NULL,
    NPOPALLETTAREWEIGHT        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_WMSPALLET_Pallet PRIMARY KEY CLUSTERED (
        DATAAREAID,
        WMSPALLETID
    )
);

END;
GO

