
CREATE PROCEDURE AX2009.usp_AddIndexes_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica_ ON AX2009.DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica () INCLUDE();

END;
GO

