
CREATE PROCEDURE AX2009.usp_Merge_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet;
    EXEC AX2009.usp_AddIndexes_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet;
END;

MERGE INTO AX2009.NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet AS TGT
USING AX2009.NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPalletView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVENTTRANSID = TGT.INVENTTRANSID AND SRC.DELIVERYDATE = TGT.DELIVERYDATE AND SRC.PACKINGSLIPID = TGT.PACKINGSLIPID AND SRC.WMSPALLETID = TGT.WMSPALLETID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.COMPANYSALESID <> SRC.COMPANYSALESID OR TGT.INTERCOMPANYSALESID <> SRC.INTERCOMPANYSALESID OR TGT.ITEMID <> SRC.ITEMID OR TGT.QTY <> SRC.QTY OR TGT.QTY2UM <> SRC.QTY2UM OR TGT.PACKEDQTY <> SRC.PACKEDQTY OR TGT.PACKEDQTY2UM <> SRC.PACKEDQTY2UM)
  THEN UPDATE SET TGT.COMPANYSALESID = SRC.COMPANYSALESID, TGT.INTERCOMPANYSALESID = SRC.INTERCOMPANYSALESID, TGT.ITEMID = SRC.ITEMID, TGT.QTY = SRC.QTY, TGT.QTY2UM = SRC.QTY2UM, TGT.PACKEDQTY = SRC.PACKEDQTY, TGT.PACKEDQTY2UM = SRC.PACKEDQTY2UM
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVENTTRANSID, DELIVERYDATE, PACKINGSLIPID, WMSPALLETID, RECID, COMPANYSALESID, INTERCOMPANYSALESID, ITEMID, QTY, QTY2UM, PACKEDQTY, PACKEDQTY2UM)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVENTTRANSID = ' + CAST(COALESCE(inserted.INVENTTRANSID, deleted.INVENTTRANSID) AS NVARCHAR) + ' - ' + 'DELIVERYDATE = ' + CAST(COALESCE(inserted.DELIVERYDATE, deleted.DELIVERYDATE) AS NVARCHAR) + ' - ' + 'PACKINGSLIPID = ' + CAST(COALESCE(inserted.PACKINGSLIPID, deleted.PACKINGSLIPID) AS NVARCHAR) + ' - ' + 'WMSPALLETID = ' + CAST(COALESCE(inserted.WMSPALLETID, deleted.WMSPALLETID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

