
CREATE PROCEDURE AX2009.usp_Merge_VENDTRANSOPEN_TransazioniFornitoreAperte
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.VENDTRANSOPEN_TransazioniFornitoreAperte', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_VENDTRANSOPEN_TransazioniFornitoreAperte;
	EXEC AX2009.usp_AddIndexes_VENDTRANSOPEN_TransazioniFornitoreAperte;
END;

MERGE INTO AX2009.VENDTRANSOPEN_TransazioniFornitoreAperte AS TGT
USING AX2009.VENDTRANSOPEN_TransazioniFornitoreAperteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.REFRECID <> SRC.REFRECID OR TGT.DUEDATE <> SRC.DUEDATE OR TGT.AMOUNTCUR <> SRC.AMOUNTCUR OR TGT.AMOUNTMST <> SRC.AMOUNTMST)
  THEN UPDATE SET TGT.REFRECID = SRC.REFRECID, TGT.DUEDATE = SRC.DUEDATE, TGT.AMOUNTCUR = SRC.AMOUNTCUR, TGT.AMOUNTMST = SRC.AMOUNTMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSDATE, ACCOUNTNUM, RECID, REFRECID, DUEDATE, AMOUNTCUR, AMOUNTMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.VENDTRANSOPEN_TransazioniFornitoreAperte' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

