
CREATE PROCEDURE AX2009.usp_Merge_TAXTRANS_TransazioniIVA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.TAXTRANS_TransazioniIVA', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_TAXTRANS_TransazioniIVA;
    EXEC AX2009.usp_AddIndexes_TAXTRANS_TransazioniIVA;
END;

MERGE INTO AX2009.TAXTRANS_TransazioniIVA AS TGT
USING AX2009.TAXTRANS_TransazioniIVAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.VOUCHER = TGT.VOUCHER AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.SOURCE <> SRC.SOURCE OR TGT.TAXCODE <> SRC.TAXCODE OR TGT.ACCOUNTNUM <> SRC.ACCOUNTNUM OR TGT.TAXDIRECTION <> SRC.TAXDIRECTION OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.TAXGROUP <> SRC.TAXGROUP OR TGT.TAXBOOKID <> SRC.TAXBOOKID OR TGT.TAXBOOKSECTIONID <> SRC.TAXBOOKSECTIONID OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_ OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.SOURCECURRENCYCODE <> SRC.SOURCECURRENCYCODE OR TGT.SOURCEBASEAMOUNTCUR <> SRC.SOURCEBASEAMOUNTCUR OR TGT.SOURCETAXAMOUNTCUR <> SRC.SOURCETAXAMOUNTCUR OR TGT.SOURCEREGULATEAMOUNTCUR <> SRC.SOURCEREGULATEAMOUNTCUR OR TGT.TAXBASEAMOUNTCUR <> SRC.TAXBASEAMOUNTCUR OR TGT.TAXAMOUNTCUR <> SRC.TAXAMOUNTCUR OR TGT.TAXINCOSTPRICECUR <> SRC.TAXINCOSTPRICECUR OR TGT.TAXINCOSTPRICEMST <> SRC.TAXINCOSTPRICEMST)
  THEN UPDATE SET TGT.SOURCE = SRC.SOURCE, TGT.TAXCODE = SRC.TAXCODE, TGT.ACCOUNTNUM = SRC.ACCOUNTNUM, TGT.TAXDIRECTION = SRC.TAXDIRECTION, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.TAXGROUP = SRC.TAXGROUP, TGT.TAXBOOKID = SRC.TAXBOOKID, TGT.TAXBOOKSECTIONID = SRC.TAXBOOKSECTIONID, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.SOURCECURRENCYCODE = SRC.SOURCECURRENCYCODE, TGT.SOURCEBASEAMOUNTCUR = SRC.SOURCEBASEAMOUNTCUR, TGT.SOURCETAXAMOUNTCUR = SRC.SOURCETAXAMOUNTCUR, TGT.SOURCEREGULATEAMOUNTCUR = SRC.SOURCEREGULATEAMOUNTCUR, TGT.TAXBASEAMOUNTCUR = SRC.TAXBASEAMOUNTCUR, TGT.TAXAMOUNTCUR = SRC.TAXAMOUNTCUR, TGT.TAXINCOSTPRICECUR = SRC.TAXINCOSTPRICECUR, TGT.TAXINCOSTPRICEMST = SRC.TAXINCOSTPRICEMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSDATE, VOUCHER, RECID, SOURCE, TAXCODE, ACCOUNTNUM, TAXDIRECTION, DIMENSION, DIMENSION2_, DIMENSION3_, TAXGROUP, TAXBOOKID, TAXBOOKSECTIONID, DIMENSION4_, DIMENSION5_, DIMENSION6_, CURRENCYCODE, SOURCECURRENCYCODE, SOURCEBASEAMOUNTCUR, SOURCETAXAMOUNTCUR, SOURCEREGULATEAMOUNTCUR, TAXBASEAMOUNTCUR, TAXAMOUNTCUR, TAXINCOSTPRICECUR, TAXINCOSTPRICEMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.TAXTRANS_TransazioniIVA' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'VOUCHER = ' + CAST(COALESCE(inserted.VOUCHER, deleted.VOUCHER) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

