
CREATE PROCEDURE AX2009.usp_Create_CUSTSETTLEMENT_LiquidazioniCliente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTSETTLEMENT_LiquidazioniCliente (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSRECID		BIGINT NOT NULL,
	TRANSDATE		DATE NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	OFFSETTRANSVOUCHER		NVARCHAR(20) NOT NULL,
	DUEDATE		DATE NOT NULL,
	OFFSETCOMPANY		NVARCHAR(4) NOT NULL,
	OFFSETACCOUNTNUM		NVARCHAR(20) NOT NULL,

	-- Misure
	SETTLEAMOUNTCUR		NUMERIC(28, 12) NOT NULL,
	SETTLEAMOUNTMST		NUMERIC(28, 12) NOT NULL,
	EXCHADJUSTMENT		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_CUSTSETTLEMENT_LiquidazioniCliente PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSRECID,
		TRANSDATE,
		RECID
	)
);

END;
GO

