
CREATE PROCEDURE AX2009.usp_Merge_ROUTEOPR_RelazioneOperativa
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ROUTEOPR_RelazioneOperativa', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_ROUTEOPR_RelazioneOperativa;
	EXEC AX2009.usp_AddIndexes_ROUTEOPR_RelazioneOperativa;
END;

MERGE INTO AX2009.ROUTEOPR_RelazioneOperativa AS TGT
USING AX2009.ROUTEOPR_RelazioneOperativaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMCODE = TGT.ITEMCODE AND SRC.ITEMRELATION = TGT.ITEMRELATION AND SRC.ROUTECODE = TGT.ROUTECODE AND SRC.ROUTERELATION = TGT.ROUTERELATION AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.OPRID <> SRC.OPRID OR TGT.WRKCTRID <> SRC.WRKCTRID)
  THEN UPDATE SET TGT.OPRID = SRC.OPRID, TGT.WRKCTRID = SRC.WRKCTRID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMCODE, ITEMRELATION, ROUTECODE, ROUTERELATION, RECID, OPRID, WRKCTRID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.ROUTEOPR_RelazioneOperativa' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMCODE = ' + CAST(COALESCE(inserted.ITEMCODE, deleted.ITEMCODE) AS NVARCHAR) + ' - ' + 'ITEMRELATION = ' + CAST(COALESCE(inserted.ITEMRELATION, deleted.ITEMRELATION) AS NVARCHAR) + ' - ' + 'ROUTECODE = ' + CAST(COALESCE(inserted.ROUTECODE, deleted.ROUTECODE) AS NVARCHAR) + ' - ' + 'ROUTERELATION = ' + CAST(COALESCE(inserted.ROUTERELATION, deleted.ROUTERELATION) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

