
CREATE PROCEDURE AX2009.usp_Merge_RETURNREASONCODE_MotivoReso
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.RETURNREASONCODE_MotivoReso', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_RETURNREASONCODE_MotivoReso;
    EXEC AX2009.usp_AddIndexes_RETURNREASONCODE_MotivoReso;
END;

MERGE INTO AX2009.RETURNREASONCODE_MotivoReso AS TGT
USING AX2009.RETURNREASONCODE_MotivoResoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.REASONCODEID = TGT.REASONCODEID
WHEN MATCHED AND (TGT.REASONCODEGROUPID <> SRC.REASONCODEGROUPID OR TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.REASONCODEGROUPID = SRC.REASONCODEGROUPID, TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, REASONCODEID, RECID, REASONCODEGROUPID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.RETURNREASONCODE_MotivoReso' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'REASONCODEID = ' + CAST(COALESCE(inserted.REASONCODEID, deleted.REASONCODEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

