
CREATE PROCEDURE AX2009.usp_Create_CUSTTRANSOPEN_TransazioniClienteAperte
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTTRANSOPEN_TransazioniClienteAperte (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ACCOUNTNUM		NVARCHAR(20) NOT NULL,
	DUEDATE		DATE NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	REFRECID		BIGINT NOT NULL,
	TRANSDATE		DATE NOT NULL,

	-- Misure
	AMOUNTCUR		NUMERIC(28, 12) NOT NULL,
	AMOUNTMST		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_CUSTTRANSOPEN_TransazioniClienteAperte PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ACCOUNTNUM,
		DUEDATE,
		RECID
	)
);

END;
GO

