
CREATE PROCEDURE AX2009.usp_Create_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	MASTERWRKCTRID		NVARCHAR(10) NOT NULL,
	WRKCTRID		NVARCHAR(10) NOT NULL,
	BARLENGTH		NUMERIC(28, 12) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ESTRBACKLENGTH		NUMERIC(28, 12) NOT NULL,
	ISGROUP		BIT NOT NULL,
	FIRSTBILLLENGTH		NUMERIC(28, 12) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione PRIMARY KEY CLUSTERED (
		DATAAREAID,
		MASTERWRKCTRID,
		WRKCTRID,
		BARLENGTH
	)
);

END;
GO

