
CREATE PROCEDURE AX2009.usp_Merge_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente;
    EXEC AX2009.usp_AddIndexes_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente;
END;

MERGE INTO AX2009.SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente AS TGT
USING AX2009.SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendenteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.EMPLID = TGT.EMPLID AND SRC.RESPONSIBILITYID = TGT.RESPONSIBILITYID AND SRC.REFTABLEID = TGT.REFTABLEID AND SRC.REFRECID = TGT.REFRECID
--WHEN MATCHED AND ()
--  THEN UPDATE SET 
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, EMPLID, RESPONSIBILITYID, REFTABLEID, REFRECID, RECID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'EMPLID = ' + CAST(COALESCE(inserted.EMPLID, deleted.EMPLID) AS NVARCHAR) + ' - ' + 'RESPONSIBILITYID = ' + CAST(COALESCE(inserted.RESPONSIBILITYID, deleted.RESPONSIBILITYID) AS NVARCHAR) + ' - ' + 'REFTABLEID = ' + CAST(COALESCE(inserted.REFTABLEID, deleted.REFTABLEID) AS NVARCHAR) + ' - ' + 'REFRECID = ' + CAST(COALESCE(inserted.REFRECID, deleted.REFRECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

