
CREATE PROCEDURE AX2009.usp_AddIndexes_MARKUPTABLE_CodiceSpeseVarie
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_MARKUPTABLE_CodiceSpeseVarie_ ON AX2009.MARKUPTABLE_CodiceSpeseVarie () INCLUDE();

END;
GO

