
CREATE PROCEDURE AX2009.usp_Create_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    REFRECID        BIGINT NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni

    -- Misure
    PRIMARYVENDORID        NVARCHAR(40) NOT NULL,
    STOPEXPLODEBOMCALCGROUP        BIT NOT NULL,
    STOPEXPLODEITEM        BIT NOT NULL

    -- Constraint
    CONSTRAINT PK_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra PRIMARY KEY CLUSTERED (
        DATAAREAID,
        REFRECID
    )
);

END;
GO

