
CREATE PROCEDURE AX2009.usp_AddIndexes_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione_ ON AX2009.METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione () INCLUDE();

END;
GO

