
CREATE PROCEDURE AX2009.usp_Merge_MARKUPTABLE_CodiceSpeseVarie
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.MARKUPTABLE_CodiceSpeseVarie', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_MARKUPTABLE_CodiceSpeseVarie;
	EXEC AX2009.usp_AddIndexes_MARKUPTABLE_CodiceSpeseVarie;
END;

MERGE INTO AX2009.MARKUPTABLE_CodiceSpeseVarie AS TGT
USING AX2009.MARKUPTABLE_CodiceSpeseVarieView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.MODULETYPE = TGT.MODULETYPE AND SRC.MARKUPCODE = TGT.MARKUPCODE
WHEN MATCHED AND (TGT.TXT <> SRC.TXT OR TGT.CUSTPOSTING <> SRC.CUSTPOSTING OR TGT.CUSTACCOUNT <> SRC.CUSTACCOUNT OR TGT.VENDPOSTING <> SRC.VENDPOSTING OR TGT.VENDACCOUNT <> SRC.VENDACCOUNT OR TGT.CUSTTYPE <> SRC.CUSTTYPE OR TGT.VENDTYPE <> SRC.VENDTYPE)
  THEN UPDATE SET TGT.TXT = SRC.TXT, TGT.CUSTPOSTING = SRC.CUSTPOSTING, TGT.CUSTACCOUNT = SRC.CUSTACCOUNT, TGT.VENDPOSTING = SRC.VENDPOSTING, TGT.VENDACCOUNT = SRC.VENDACCOUNT, TGT.CUSTTYPE = SRC.CUSTTYPE, TGT.VENDTYPE = SRC.VENDTYPE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, MODULETYPE, MARKUPCODE, RECID, TXT, CUSTPOSTING, CUSTACCOUNT, VENDPOSTING, VENDACCOUNT, CUSTTYPE, VENDTYPE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.MARKUPTABLE_CodiceSpeseVarie' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'MODULETYPE = ' + CAST(COALESCE(inserted.MODULETYPE, deleted.MODULETYPE) AS NVARCHAR) + ' - ' + 'MARKUPCODE = ' + CAST(COALESCE(inserted.MARKUPCODE, deleted.MARKUPCODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

