
CREATE PROCEDURE AX2009.usp_Create_PBAREUSEBOMROUTE_StringaDiRicerca
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.PBAREUSEBOMROUTE_StringaDiRicerca (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    BOMID        NVARCHAR(20) NOT NULL,
    ROUTEID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    SEARCHSTRING        NVARCHAR(870) NOT NULL


    -- Constraint
    CONSTRAINT PK_PBAREUSEBOMROUTE_StringaDiRicerca PRIMARY KEY CLUSTERED (
        DATAAREAID,
        BOMID,
        ROUTEID
    )
);

END;
GO

