
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTINVOICELINE_FattureClienteTestoLibero_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTINVOICELINE_FattureClienteTestoLibero_Riga_ ON AX2009.CUSTINVOICELINE_FattureClienteTestoLibero_Riga () INCLUDE();

END;
GO

