
CREATE PROCEDURE AX2009.usp_Merge_NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice;
    EXEC AX2009.usp_AddIndexes_NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice;
END;

MERGE INTO AX2009.NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice AS TGT
USING AX2009.NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatriceView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.WRKCTRID = TGT.WRKCTRID
WHEN MATCHED AND (TGT.MASTERWRKCTRID <> SRC.MASTERWRKCTRID OR TGT.BILLETDIAMETER <> SRC.BILLETDIAMETER OR TGT.HOLENUM <> SRC.HOLENUM OR TGT.SUBWRKCTRID <> SRC.SUBWRKCTRID OR TGT.PULLOUT <> SRC.PULLOUT OR TGT.BOLSTER <> SRC.BOLSTER OR TGT.SUBBOLSTER <> SRC.SUBBOLSTER OR TGT.WRKCTRPACKAGETYPE <> SRC.WRKCTRPACKAGETYPE OR TGT.PACKAGEDIAMETER <> SRC.PACKAGEDIAMETER OR TGT.PACKAGEHEIGHT <> SRC.PACKAGEHEIGHT OR TGT.STATUSUSE <> SRC.STATUSUSE OR TGT.NETWEIGHT <> SRC.NETWEIGHT OR TGT.NETWEIGHTSUB <> SRC.NETWEIGHTSUB OR TGT.LASTTRANSDATE <> SRC.LASTTRANSDATE OR TGT.APPROVALDATE <> SRC.APPROVALDATE OR TGT.ANNULDATE <> SRC.ANNULDATE OR TGT.NPOINVOICINGMODE <> SRC.NPOINVOICINGMODE OR TGT.RECEIPTDATE <> SRC.RECEIPTDATE OR TGT.SAMPLINGDATE <> SRC.SAMPLINGDATE OR TGT.DIESTEELLOT <> SRC.DIESTEELLOT OR TGT.SPINDLESTEELLOT <> SRC.SPINDLESTEELLOT OR TGT.SODAVOLUME <> SRC.SODAVOLUME OR TGT.SODAALKG <> SRC.SODAALKG OR TGT.NOTES <> SRC.NOTES OR TGT.SODASUBVOLUME <> SRC.SODASUBVOLUME OR TGT.QTYGOOD <> SRC.QTYGOOD OR TGT.QTYGOODSECONDARYUM <> SRC.QTYGOODSECONDARYUM)
  THEN UPDATE SET TGT.MASTERWRKCTRID = SRC.MASTERWRKCTRID, TGT.BILLETDIAMETER = SRC.BILLETDIAMETER, TGT.HOLENUM = SRC.HOLENUM, TGT.SUBWRKCTRID = SRC.SUBWRKCTRID, TGT.PULLOUT = SRC.PULLOUT, TGT.BOLSTER = SRC.BOLSTER, TGT.SUBBOLSTER = SRC.SUBBOLSTER, TGT.WRKCTRPACKAGETYPE = SRC.WRKCTRPACKAGETYPE, TGT.PACKAGEDIAMETER = SRC.PACKAGEDIAMETER, TGT.PACKAGEHEIGHT = SRC.PACKAGEHEIGHT, TGT.STATUSUSE = SRC.STATUSUSE, TGT.NETWEIGHT = SRC.NETWEIGHT, TGT.NETWEIGHTSUB = SRC.NETWEIGHTSUB, TGT.LASTTRANSDATE = SRC.LASTTRANSDATE, TGT.APPROVALDATE = SRC.APPROVALDATE, TGT.ANNULDATE = SRC.ANNULDATE, TGT.NPOINVOICINGMODE = SRC.NPOINVOICINGMODE, TGT.RECEIPTDATE = SRC.RECEIPTDATE, TGT.SAMPLINGDATE = SRC.SAMPLINGDATE, TGT.DIESTEELLOT = SRC.DIESTEELLOT, TGT.SPINDLESTEELLOT = SRC.SPINDLESTEELLOT, TGT.SODAVOLUME = SRC.SODAVOLUME, TGT.SODAALKG = SRC.SODAALKG, TGT.NOTES = SRC.NOTES, TGT.SODASUBVOLUME = SRC.SODASUBVOLUME, TGT.QTYGOOD = SRC.QTYGOOD, TGT.QTYGOODSECONDARYUM = SRC.QTYGOODSECONDARYUM
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, WRKCTRID, RECID, MASTERWRKCTRID, BILLETDIAMETER, HOLENUM, SUBWRKCTRID, PULLOUT, BOLSTER, SUBBOLSTER, WRKCTRPACKAGETYPE, PACKAGEDIAMETER, PACKAGEHEIGHT, STATUSUSE, NETWEIGHT, NETWEIGHTSUB, LASTTRANSDATE, APPROVALDATE, ANNULDATE, NPOINVOICINGMODE, RECEIPTDATE, SAMPLINGDATE, DIESTEELLOT, SPINDLESTEELLOT, SODAVOLUME, SODAALKG, NOTES, SODASUBVOLUME, QTYGOOD, QTYGOODSECONDARYUM)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'WRKCTRID = ' + CAST(COALESCE(inserted.WRKCTRID, deleted.WRKCTRID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

