
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTABLEMODULE_ArticoloUnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTABLEMODULE_ArticoloUnitaDiMisura_MODULETYPE_INCLUDE ON AX2009.INVENTTABLEMODULE_ArticoloUnitaDiMisura ([MODULETYPE]) INCLUDE ([PRICE],[PRICEUNIT]);

END;
GO

