
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDTRANSOPEN_TransazioniFornitoreAperte
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_VENDTRANSOPEN_TransazioniFornitoreAperte_ ON AX2009.VENDTRANSOPEN_TransazioniFornitoreAperte () INCLUDE();

END;
GO

