
CREATE PROCEDURE AX2009.usp_AddIndexes_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente_ ON AX2009.SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente () INCLUDE();

END;
GO

