
CREATE PROCEDURE AX2009.usp_AddIndexes_COMMISSIONSALESGROUP_GruppoVendite
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_COMMISSIONSALESGROUP_GruppoVendite_ ON AX2009.COMMISSIONSALESGROUP_GruppoVendite () INCLUDE();

END;
GO

