
CREATE PROCEDURE AX2009.usp_Merge_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking;
	EXEC AX2009.usp_AddIndexes_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking;
END;

MERGE INTO AX2009.METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking AS TGT
USING AX2009.METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPickingView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVENTITEMTYPE = TGT.INVENTITEMTYPE AND SRC.FROMDATE = TGT.FROMDATE AND SRC.FILTERCODE = TGT.FILTERCODE AND SRC.CUSTACCOUNT = TGT.CUSTACCOUNT
WHEN MATCHED AND (TGT.PRICEPERUNIT <> SRC.PRICEPERUNIT OR TGT.PRICEPERSECONDUNIT <> SRC.PRICEPERSECONDUNIT)
  THEN UPDATE SET TGT.PRICEPERUNIT = SRC.PRICEPERUNIT, TGT.PRICEPERSECONDUNIT = SRC.PRICEPERSECONDUNIT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVENTITEMTYPE, FROMDATE, FILTERCODE, CUSTACCOUNT, RECID, PRICEPERUNIT, PRICEPERSECONDUNIT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVENTITEMTYPE = ' + CAST(COALESCE(inserted.INVENTITEMTYPE, deleted.INVENTITEMTYPE) AS NVARCHAR) + ' - ' + 'FROMDATE = ' + CAST(COALESCE(inserted.FROMDATE, deleted.FROMDATE) AS NVARCHAR) + ' - ' + 'FILTERCODE = ' + CAST(COALESCE(inserted.FILTERCODE, deleted.FILTERCODE) AS NVARCHAR) + ' - ' + 'CUSTACCOUNT = ' + CAST(COALESCE(inserted.CUSTACCOUNT, deleted.CUSTACCOUNT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

