
CREATE PROCEDURE AX2009.usp_AddIndexes_ASSETGROUP_GruppoCespiti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ASSETGROUP_GruppoCespiti_ ON AX2009.ASSETGROUP_GruppoCespiti () INCLUDE();

END;
GO

