
CREATE PROCEDURE AX2009.usp_Create_NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    WRKCTRID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    MASTERWRKCTRID        NVARCHAR(10) NOT NULL,
    BILLETDIAMETER        NUMERIC(28, 12) NOT NULL,
    HOLENUM        INT NOT NULL,
    SUBWRKCTRID        NVARCHAR(20) NOT NULL,
    PULLOUT        NVARCHAR(20) NOT NULL,
    BOLSTER        NVARCHAR(20) NOT NULL,
    SUBBOLSTER        NVARCHAR(20) NOT NULL,
    WRKCTRPACKAGETYPE        INT NOT NULL,
    PACKAGEDIAMETER        NUMERIC(28, 12) NOT NULL,
    PACKAGEHEIGHT        NUMERIC(28, 12) NOT NULL,
    STATUSUSE        INT NOT NULL,
    NETWEIGHT        NUMERIC(28, 12) NOT NULL,
    NETWEIGHTSUB        NUMERIC(28, 12) NOT NULL,
    LASTTRANSDATE        DATETIME NOT NULL,
    APPROVALDATE        DATETIME NOT NULL,
    ANNULDATE        DATETIME NOT NULL,
    NPOINVOICINGMODE        INT NOT NULL,
    RECEIPTDATE        DATETIME NOT NULL,
    SAMPLINGDATE        DATETIME NOT NULL,
    DIESTEELLOT        NVARCHAR(30) NOT NULL,
    SPINDLESTEELLOT        NVARCHAR(30) NOT NULL,
    SODAVOLUME        NUMERIC(28, 12) NOT NULL,
    SODAALKG        NUMERIC(28, 12) NOT NULL,
    NOTES        NVARCHAR(1000),
    SODASUBVOLUME        NUMERIC(28, 12) NOT NULL,

    -- Misure
    QTYGOOD        NUMERIC(28, 12) NOT NULL,
    QTYGOODSECONDARYUM        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice PRIMARY KEY CLUSTERED (
        DATAAREAID,
        WRKCTRID
    )
);

END;
GO

