
CREATE PROCEDURE AX2009.usp_Merge_NPOITEMSERIESRELATION_ArticoliSerie
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOITEMSERIESRELATION_ArticoliSerie', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOITEMSERIESRELATION_ArticoliSerie;
	EXEC AX2009.usp_AddIndexes_NPOITEMSERIESRELATION_ArticoliSerie;
END;

MERGE INTO AX2009.NPOITEMSERIESRELATION_ArticoliSerie AS TGT
USING AX2009.NPOITEMSERIESRELATION_ArticoliSerieView (nolock) AS SRC
ON SRC.ITEMID = TGT.ITEMID AND SRC.SERIESID = TGT.SERIESID
WHEN MATCHED AND (TGT.PRODUCTTYPEID <> SRC.PRODUCTTYPEID)
  THEN UPDATE SET TGT.PRODUCTTYPEID = SRC.PRODUCTTYPEID
WHEN NOT MATCHED
  THEN INSERT VALUES (ITEMID, SERIESID, RECID, PRODUCTTYPEID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOITEMSERIESRELATION_ArticoliSerie' AS full_olap_table_name,
	'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'SERIESID = ' + CAST(COALESCE(inserted.SERIESID, deleted.SERIESID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

