
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTITEMLOCATION_ArticoloDimensioneInventariale
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTITEMLOCATION_ArticoloDimensioneInventariale_ ON AX2009.INVENTITEMLOCATION_ArticoloDimensioneInventariale () INCLUDE();

END;
GO

