
CREATE PROCEDURE AX2009.usp_Create_REQGROUP_GruppoCopertura
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.REQGROUP_GruppoCopertura (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	REQGROUPID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	NPOSTOCKMANAGEDITEM		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_REQGROUP_GruppoCopertura PRIMARY KEY CLUSTERED (
		DATAAREAID,
		REQGROUPID
	)
);

END;
GO

