
CREATE PROCEDURE AX2009.usp_Merge_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SMMBUSRELSUBSEGMENTGROUP_Sottosegmento', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento;
    EXEC AX2009.usp_AddIndexes_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento;
END;

MERGE INTO AX2009.SMMBUSRELSUBSEGMENTGROUP_Sottosegmento AS TGT
USING AX2009.SMMBUSRELSUBSEGMENTGROUP_SottosegmentoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SEGMENTID = TGT.SEGMENTID AND SRC.SUBSEGMENTID = TGT.SUBSEGMENTID
WHEN MATCHED AND (TGT.SUBSEGMENTDESCRIPTION <> SRC.SUBSEGMENTDESCRIPTION)
  THEN UPDATE SET TGT.SUBSEGMENTDESCRIPTION = SRC.SUBSEGMENTDESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SEGMENTID, SUBSEGMENTID, RECID, SUBSEGMENTDESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.SMMBUSRELSUBSEGMENTGROUP_Sottosegmento' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SEGMENTID = ' + CAST(COALESCE(inserted.SEGMENTID, deleted.SEGMENTID) AS NVARCHAR) + ' - ' + 'SUBSEGMENTID = ' + CAST(COALESCE(inserted.SUBSEGMENTID, deleted.SUBSEGMENTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

