
CREATE PROCEDURE AX2009.usp_Merge_SALESPOOL_PoolVendite
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SALESPOOL_PoolVendite', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_SALESPOOL_PoolVendite;
	EXEC AX2009.usp_AddIndexes_SALESPOOL_PoolVendite;
END;

MERGE INTO AX2009.SALESPOOL_PoolVendite AS TGT
USING AX2009.SALESPOOL_PoolVenditeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SALESPOOLID = TGT.SALESPOOLID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SALESPOOLID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.SALESPOOL_PoolVendite' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SALESPOOLID = ' + CAST(COALESCE(inserted.SALESPOOLID, deleted.SALESPOOLID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

