
CREATE PROCEDURE AX2009.usp_AddIndexes_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra_ ON AX2009.METPRICECALCITEMSETUP_CalcoloPrezzi_Extra () INCLUDE();

END;
GO

