
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDINVOICEJOUR_FattureFornitore
AS
BEGIN
SET NOCOUNT ON;

CREATE UNIQUE NONCLUSTERED INDEX IX_AX2009_VENDINVOICEJOUR_FattureFornitore_RECID ON [AX2009].[VENDINVOICEJOUR_FattureFornitore] ([RECID])

END;
GO

