
CREATE PROCEDURE AX2009.usp_AddIndexes_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga_DATAAREAID_VENDTRANSID_INCLUDE ON AX2009.LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga ([DATAAREAID],[VENDTRANSID]) INCLUDE ([PAYMENT]);

END;
GO

