
CREATE PROCEDURE AX2009.usp_Create_BOMCALCTABLE_CalcoloDBA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.BOMCALCTABLE_CalcoloDBA (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PRICECALCID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ITEMID		NVARCHAR(20) NOT NULL,
	TRANSDATE		DATE NOT NULL


	-- Constraint
	CONSTRAINT PK_BOMCALCTABLE_CalcoloDBA PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PRICECALCID
	)
);

END;
GO

