
CREATE PROCEDURE AX2009.usp_Create_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.AIFENDPOINTCONSTRAINT_AIFEndPointConstraint (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    ENDPOINTID        NVARCHAR(30) NOT NULL,
    CONSTRAINTID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    CONSTRAINTTYPE        SMALLINT NOT NULL


    -- Constraint
    CONSTRAINT PK_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint PRIMARY KEY CLUSTERED (
        DATAAREAID,
        ENDPOINTID,
        CONSTRAINTID
    )
);

END;
GO

