
CREATE PROCEDURE AX2009.usp_Create_NPOPRODUCTIONTAG_CartellinoProduzione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPRODUCTIONTAG_CartellinoProduzione (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PRODID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    SALESID        NVARCHAR(20) NOT NULL,
    SALESLINENUM        INT NOT NULL,
    MASTERWRKCTRID        NVARCHAR(10) NOT NULL,
    CUSTNAME        NVARCHAR(100) NOT NULL,
    GROUPWRKCTRID        NVARCHAR(20) NOT NULL,
    SALESLENGTH        NUMERIC(28, 12) NOT NULL,
    CUSTACCOUNT        NVARCHAR(20) NOT NULL,
    WRKCTRID        NVARCHAR(10) NOT NULL,
    WRKCTRNAME        NVARCHAR(60) NOT NULL,
    PRODLENGTH        NUMERIC(28, 12) NOT NULL,
    PRESETMASTERWRKCTRID        NVARCHAR(10) NOT NULL,
    WRKHOLENUM        INT NOT NULL,
    WRKPULLOUT        NVARCHAR(10) NOT NULL,
    WRKBOLSTER        NVARCHAR(10) NOT NULL,
    WRKSUBBOLSTER        NVARCHAR(10) NOT NULL,
    PRODQTY        NUMERIC(28, 12) NOT NULL,
    SALESQTY        NUMERIC(28, 12) NOT NULL,
    WRKWEIGHTPROFILE        NUMERIC(28, 12) NOT NULL,
    SALESTOTKG        NUMERIC(28, 12) NOT NULL,
    PRESETBILLLENGTH        NUMERIC(28, 12) NOT NULL,
    SALESRESERVATION        BIT NOT NULL,
    SALESHEATTREATMENT        NVARCHAR(10) NOT NULL,
    SALESALLOYID        NVARCHAR(20) NOT NULL,
    PRODALLOYID        NVARCHAR(20) NOT NULL,
    PRODHEATTREATMENT        NVARCHAR(10) NOT NULL,
    TAGFINISHING        NVARCHAR(20) NOT NULL,
    PRODFINISHING        NVARCHAR(20) NOT NULL,
    TYPEFINISHING        NVARCHAR(20) NOT NULL,
    WRKSIZE        NVARCHAR(15) NOT NULL,
    WRKTYPE        NVARCHAR(10) NOT NULL,
    PRESETBILLQTY        INT NOT NULL,
    PRODDATE        DATETIME NOT NULL,
    SALESDATE        DATETIME NOT NULL,
    SALESPRIORITY        BIT NOT NULL,
    SALESSECURITY        BIT NOT NULL,
    REPRINT        BIT NOT NULL,
    GROUPWRKCTRNAME        NVARCHAR(60) NOT NULL,
    PRESETBILLWEIGHT        NUMERIC(28, 12) NOT NULL,
    PRESETBILLTEMP        NUMERIC(28, 12) NOT NULL,
    PRESETESTRBACKLENGTH        NUMERIC(28, 12) NOT NULL,
    PRESETESTRGROSSKGH        NUMERIC(28, 12) NOT NULL,
    PRESETESTRNETKGH        NUMERIC(28, 12) NOT NULL,
    PRESETESTRSPEEDMIN        NUMERIC(28, 12) NOT NULL,
    PRESETESTRSPEEDMAX        NUMERIC(28, 12) NOT NULL,
    PRESETESTRPRESSLENGTH        NUMERIC(28, 12) NOT NULL,
    PRESETESTRCROP        NUMERIC(28, 12) NOT NULL,
    PRESETESTRHOTSAWPOSITION        NUMERIC(28, 12) NOT NULL,
    PRESETWRKCTRID        NVARCHAR(10) NOT NULL,
    PRESETBARLENGTH        NUMERIC(28, 12) NOT NULL,
    SALESWEEK        NVARCHAR(7) NOT NULL,
    PRODWEEK        NVARCHAR(7) NOT NULL,
    PRESETINFO        NVARCHAR(255) NOT NULL,
    PRESETWRKCTRNUM        INT NOT NULL,
    MASTERWRKCTRNAME        NVARCHAR(60) NOT NULL,
    PRESETQTYPERBAR        NUMERIC(28, 12) NOT NULL,
    SALESFINISHING        NVARCHAR(20) NOT NULL,
    SALESCUSTOMERFINISHING        NVARCHAR(20) NOT NULL,
    PRODBILLQTY        INT NOT NULL,
    PRODBILLLENGTH        NUMERIC(28, 12) NOT NULL,
    PRINTED        BIT NOT NULL,
    PRINTEDDATETIME        DATETIME NOT NULL,
    PRINTEDDATETIMETZID        INT NOT NULL,
    PRINTEDBY        NVARCHAR(10) NOT NULL,
    MODIFIEDDATETIME        DATETIME NOT NULL,
    RECVERSION        INT NOT NULL,
    WRKFILLWEIGHT        NUMERIC(28, 12) NOT NULL,
    TAGFINISHINGTYPE        NVARCHAR(100) NOT NULL,
    PRESETBARSINBILLET        NUMERIC(28, 12) NOT NULL,
    STATUSUSE        SMALLINT NOT NULL,
    PRESETLOCKPACKING        BIT NOT NULL,
    PRESETVERIFIED        BIT NOT NULL,
    PRESETFIRSTBILLLENGTH        NUMERIC(28, 12) NOT NULL


    -- Constraint
    CONSTRAINT PK_NPOPRODUCTIONTAG_CartellinoProduzione PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PRODID
    )
);

END;
GO

