
CREATE PROCEDURE AX2009.usp_Merge_INVENTSUM_ScorteDisponibili
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTSUM_ScorteDisponibili', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTSUM_ScorteDisponibili;
	EXEC AX2009.usp_AddIndexes_INVENTSUM_ScorteDisponibili;
END;

MERGE INTO AX2009.INVENTSUM_ScorteDisponibili AS TGT
USING AX2009.INVENTSUM_ScorteDisponibiliView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVENTDIMID = TGT.INVENTDIMID AND SRC.ITEMID = TGT.ITEMID
WHEN MATCHED AND (TGT.PHYSICALINVENT <> SRC.PHYSICALINVENT OR TGT.NPOPHYSICALINVENT2UM <> SRC.NPOPHYSICALINVENT2UM OR TGT.POSTEDQTY <> SRC.POSTEDQTY OR TGT.RECEIVED <> SRC.RECEIVED OR TGT.DEDUCTED <> SRC.DEDUCTED OR TGT.REGISTERED <> SRC.REGISTERED OR TGT.PICKED <> SRC.PICKED OR TGT.ONORDER <> SRC.ONORDER OR TGT.RESERVORDERED <> SRC.RESERVORDERED OR TGT.RESERVPHYSICAL <> SRC.RESERVPHYSICAL)
  THEN UPDATE SET TGT.PHYSICALINVENT = SRC.PHYSICALINVENT, TGT.NPOPHYSICALINVENT2UM = SRC.NPOPHYSICALINVENT2UM, TGT.POSTEDQTY = SRC.POSTEDQTY, TGT.RECEIVED = SRC.RECEIVED, TGT.DEDUCTED = SRC.DEDUCTED, TGT.REGISTERED = SRC.REGISTERED, TGT.PICKED = SRC.PICKED, TGT.ONORDER = SRC.ONORDER, TGT.RESERVORDERED = SRC.RESERVORDERED, TGT.RESERVPHYSICAL = SRC.RESERVPHYSICAL
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVENTDIMID, ITEMID, RECID, PHYSICALINVENT, NPOPHYSICALINVENT2UM, POSTEDQTY, RECEIVED, DEDUCTED, REGISTERED, PICKED, ONORDER, RESERVORDERED, RESERVPHYSICAL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTSUM_ScorteDisponibili' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVENTDIMID = ' + CAST(COALESCE(inserted.INVENTDIMID, deleted.INVENTDIMID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

