
CREATE PROCEDURE AX2009.usp_Merge_REQGROUP_GruppoCopertura
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.REQGROUP_GruppoCopertura', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_REQGROUP_GruppoCopertura;
	EXEC AX2009.usp_AddIndexes_REQGROUP_GruppoCopertura;
END;

MERGE INTO AX2009.REQGROUP_GruppoCopertura AS TGT
USING AX2009.REQGROUP_GruppoCoperturaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.REQGROUPID = TGT.REQGROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.NPOSTOCKMANAGEDITEM <> SRC.NPOSTOCKMANAGEDITEM)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.NPOSTOCKMANAGEDITEM = SRC.NPOSTOCKMANAGEDITEM
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, REQGROUPID, RECID, NAME, NPOSTOCKMANAGEDITEM)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.REQGROUP_GruppoCopertura' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'REQGROUPID = ' + CAST(COALESCE(inserted.REQGROUPID, deleted.REQGROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

