
CREATE PROCEDURE AX2009.usp_Create_NPOPACKINGSLIPPALLETINFO_DDTPallet
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPACKINGSLIPPALLETINFO_DDTPallet (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	DELIVERYDATE		DATE NOT NULL,
	PACKINGSLIPID		NVARCHAR(20) NOT NULL,
	INVENTTRANSID		NVARCHAR(20) NOT NULL,
	WMSPALLETID		NVARCHAR(18) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TRANSREFID		NVARCHAR(20) NOT NULL,
	REFTABLEID		INT NOT NULL,
	INVOICERECID		BIGINT NOT NULL,

	-- Misure
	WEIGHT		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_NPOPACKINGSLIPPALLETINFO_DDTPallet PRIMARY KEY CLUSTERED (
		DATAAREAID,
		DELIVERYDATE,
		PACKINGSLIPID,
		INVENTTRANSID,
		WMSPALLETID,
		RECID
	)
);

END;
GO

