
CREATE PROCEDURE AX2009.usp_Create_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	INVENTDIMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	INVENTDIMIDDEFAULT		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		INVENTDIMID
	)
);

END;
GO

