
CREATE PROCEDURE AX2009.usp_Merge_DATAAREA_Azienda
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DATAAREA_Azienda', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_DATAAREA_Azienda;
	EXEC AX2009.usp_AddIndexes_DATAAREA_Azienda;
END;

MERGE INTO AX2009.DATAAREA_Azienda AS TGT
USING AX2009.DATAAREA_AziendaView (nolock) AS SRC
ON SRC.ID = TGT.ID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.ISVIRTUAL <> SRC.ISVIRTUAL OR TGT.TIMEZONE <> SRC.TIMEZONE)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.ISVIRTUAL = SRC.ISVIRTUAL, TGT.TIMEZONE = SRC.TIMEZONE
WHEN NOT MATCHED
  THEN INSERT VALUES (ID, RECID, NAME, ISVIRTUAL, TIMEZONE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.DATAAREA_Azienda' AS full_olap_table_name,
	'ID = ' + CAST(COALESCE(inserted.ID, deleted.ID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

