
CREATE PROCEDURE AX2009.usp_Merge_VENDSETTLEMENT_LiquidazioniFornitore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.VENDSETTLEMENT_LiquidazioniFornitore', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_VENDSETTLEMENT_LiquidazioniFornitore;
	EXEC AX2009.usp_AddIndexes_VENDSETTLEMENT_LiquidazioniFornitore;
END;

MERGE INTO AX2009.VENDSETTLEMENT_LiquidazioniFornitore AS TGT
USING AX2009.VENDSETTLEMENT_LiquidazioniFornitoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.OFFSETTRANSVOUCHER = TGT.OFFSETTRANSVOUCHER AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.TRANSRECID <> SRC.TRANSRECID OR TGT.DUEDATE <> SRC.DUEDATE OR TGT.TRANSCOMPANY <> SRC.TRANSCOMPANY OR TGT.SETTLEAMOUNTCUR <> SRC.SETTLEAMOUNTCUR OR TGT.SETTLEAMOUNTMST <> SRC.SETTLEAMOUNTMST)
  THEN UPDATE SET TGT.TRANSRECID = SRC.TRANSRECID, TGT.DUEDATE = SRC.DUEDATE, TGT.TRANSCOMPANY = SRC.TRANSCOMPANY, TGT.SETTLEAMOUNTCUR = SRC.SETTLEAMOUNTCUR, TGT.SETTLEAMOUNTMST = SRC.SETTLEAMOUNTMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSDATE, OFFSETTRANSVOUCHER, ACCOUNTNUM, RECID, TRANSRECID, DUEDATE, TRANSCOMPANY, SETTLEAMOUNTCUR, SETTLEAMOUNTMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.VENDSETTLEMENT_LiquidazioniFornitore' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'OFFSETTRANSVOUCHER = ' + CAST(COALESCE(inserted.OFFSETTRANSVOUCHER, deleted.OFFSETTRANSVOUCHER) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

