
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti_ ON AX2009.NPOPACKINGSLIPEXTERNAL_DDTTerzeParti () INCLUDE();

END;
GO

