
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTBATCH_Colata
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTBATCH_Colata_ ON AX2009.INVENTBATCH_Colata () INCLUDE();

END;
GO

