
CREATE PROCEDURE AX2009.usp_AddIndexes_WMSORDERTRANS_OrdiniMagazzino_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_WMSORDERTRANS_OrdiniMagazzino_Riga_DATAAREAID_INVENTTRANSID_EXPEDITIONSTATUS_QTY ON AX2009.WMSORDERTRANS_OrdiniMagazzino_Riga (DATAAREAID,INVENTTRANSID,EXPEDITIONSTATUS,QTY);

END;
GO

