
CREATE PROCEDURE AX2009.usp_Merge_COSTINGVERSION_VersioneDeterminazioneCosti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.COSTINGVERSION_VersioneDeterminazioneCosti', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_COSTINGVERSION_VersioneDeterminazioneCosti;
	EXEC AX2009.usp_AddIndexes_COSTINGVERSION_VersioneDeterminazioneCosti;
END;

MERGE INTO AX2009.COSTINGVERSION_VersioneDeterminazioneCosti AS TGT
USING AX2009.COSTINGVERSION_VersioneDeterminazioneCostiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.VERSIONID = TGT.VERSIONID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.LASTUPDATE <> SRC.LASTUPDATE OR TGT.LASTACTIVATION <> SRC.LASTACTIVATION)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.LASTUPDATE = SRC.LASTUPDATE, TGT.LASTACTIVATION = SRC.LASTACTIVATION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, VERSIONID, RECID, NAME, LASTUPDATE, LASTACTIVATION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.COSTINGVERSION_VersioneDeterminazioneCosti' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'VERSIONID = ' + CAST(COALESCE(inserted.VERSIONID, deleted.VERSIONID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

