
CREATE PROCEDURE AX2009.usp_AddIndexes_ADDRESSCOUNTRYREGION_Nazione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ADDRESSCOUNTRYREGION_Nazione_ ON AX2009.ADDRESSCOUNTRYREGION_Nazione () INCLUDE();

END;
GO

