
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOITEMSERIESRELATION_ArticoliSerie
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_NPOITEMSERIESRELATION_ArticoliSerie_SERIESID_ITEMID_INCLUDE ON AX2009.NPOITEMSERIESRELATION_ArticoliSerie (SERIESID, ITEMID) INCLUDE(PRODUCTTYPEID);

END;
GO

