
CREATE PROCEDURE AX2009.usp_Create_RETURNREASONCODE_MotivoReso
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.RETURNREASONCODE_MotivoReso (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    REASONCODEID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    REASONCODEGROUPID        NVARCHAR(10) NOT NULL,
    DESCRIPTION        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_RETURNREASONCODE_MotivoReso PRIMARY KEY CLUSTERED (
        DATAAREAID,
        REASONCODEID
    )
);

END;
GO

