
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPACKINGTAG_Pacchi_Etichetta
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPACKINGTAG_Pacchi_Etichetta_ ON AX2009.NPOPACKINGTAG_Pacchi_Etichetta () INCLUDE();

END;
GO

