
CREATE PROCEDURE AX2009.usp_Create_LEDGERTABLE_ContoCoGe
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.LEDGERTABLE_ContoCoGe (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ACCOUNTNUM		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ACCOUNTNAME		NVARCHAR(60) NOT NULL,
    ACCOUNTCATEGORY     NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_LEDGERTABLE_ContoCoGe PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ACCOUNTNUM
	)
);

END;
GO

