
CREATE PROCEDURE AX2009.usp_Merge_NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili;
    EXEC AX2009.usp_AddIndexes_NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili;
END;

MERGE INTO AX2009.NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili AS TGT
USING AX2009.NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfiliView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID
WHEN MATCHED AND (TGT.STRUCTURALITEMTYPE <> SRC.STRUCTURALITEMTYPE OR TGT.MNGTYPE <> SRC.MNGTYPE OR TGT.SECTORTYPE <> SRC.SECTORTYPE OR TGT.SERIESID <> SRC.SERIESID OR TGT.CATEGORYID <> SRC.CATEGORYID OR TGT.PERIMETER <> SRC.PERIMETER OR TGT.AREA <> SRC.AREA OR TGT.DIAMETER <> SRC.DIAMETER OR TGT.ROLLING <> SRC.ROLLING OR TGT.TEAROFFSTRIP <> SRC.TEAROFFSTRIP OR TGT.SECURITY <> SRC.SECURITY OR TGT.ALLOYID <> SRC.ALLOYID OR TGT.CUSTACCOUNT <> SRC.CUSTACCOUNT OR TGT.PHYSICALSTATEALLOYID <> SRC.PHYSICALSTATEALLOYID OR TGT.MAXLENGTH <> SRC.MAXLENGTH OR TGT.MINLENGTH <> SRC.MINLENGTH OR TGT.STANDARDLENGTH <> SRC.STANDARDLENGTH OR TGT.NOSTDQTYLEADTIME <> SRC.NOSTDQTYLEADTIME OR TGT.STRUCTURALWEIGHT <> SRC.STRUCTURALWEIGHT OR TGT.MAXQUANTITY <> SRC.MAXQUANTITY OR TGT.MINQUANTITY <> SRC.MINQUANTITY OR TGT.USEDINCATALOG <> SRC.USEDINCATALOG OR TGT.MERIDIANNUMBER <> SRC.MERIDIANNUMBER OR TGT.STRUCTURALGLAZING <> SRC.STRUCTURALGLAZING OR TGT.ASSEMBLYPASSES <> SRC.ASSEMBLYPASSES OR TGT.WIDTH <> SRC.WIDTH OR TGT.HEIGHT <> SRC.HEIGHT OR TGT.PAINTINGHOOKS <> SRC.PAINTINGHOOKS)
  THEN UPDATE SET TGT.STRUCTURALITEMTYPE = SRC.STRUCTURALITEMTYPE, TGT.MNGTYPE = SRC.MNGTYPE, TGT.SECTORTYPE = SRC.SECTORTYPE, TGT.SERIESID = SRC.SERIESID, TGT.CATEGORYID = SRC.CATEGORYID, TGT.PERIMETER = SRC.PERIMETER, TGT.AREA = SRC.AREA, TGT.DIAMETER = SRC.DIAMETER, TGT.ROLLING = SRC.ROLLING, TGT.TEAROFFSTRIP = SRC.TEAROFFSTRIP, TGT.SECURITY = SRC.SECURITY, TGT.ALLOYID = SRC.ALLOYID, TGT.CUSTACCOUNT = SRC.CUSTACCOUNT, TGT.PHYSICALSTATEALLOYID = SRC.PHYSICALSTATEALLOYID, TGT.MAXLENGTH = SRC.MAXLENGTH, TGT.MINLENGTH = SRC.MINLENGTH, TGT.STANDARDLENGTH = SRC.STANDARDLENGTH, TGT.NOSTDQTYLEADTIME = SRC.NOSTDQTYLEADTIME, TGT.STRUCTURALWEIGHT = SRC.STRUCTURALWEIGHT, TGT.MAXQUANTITY = SRC.MAXQUANTITY, TGT.MINQUANTITY = SRC.MINQUANTITY, TGT.USEDINCATALOG = SRC.USEDINCATALOG, TGT.MERIDIANNUMBER = SRC.MERIDIANNUMBER, TGT.STRUCTURALGLAZING = SRC.STRUCTURALGLAZING, TGT.ASSEMBLYPASSES = SRC.ASSEMBLYPASSES, TGT.WIDTH = SRC.WIDTH, TGT.HEIGHT = SRC.HEIGHT, TGT.PAINTINGHOOKS = SRC.PAINTINGHOOKS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, RECID, STRUCTURALITEMTYPE, MNGTYPE, SECTORTYPE, SERIESID, CATEGORYID, PERIMETER, AREA, DIAMETER, ROLLING, TEAROFFSTRIP, SECURITY, ALLOYID, CUSTACCOUNT, PHYSICALSTATEALLOYID, MAXLENGTH, MINLENGTH, STANDARDLENGTH, NOSTDQTYLEADTIME, STRUCTURALWEIGHT, MAXQUANTITY, MINQUANTITY, USEDINCATALOG, MERIDIANNUMBER, STRUCTURALGLAZING, ASSEMBLYPASSES, WIDTH, HEIGHT, PAINTINGHOOKS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

