
CREATE PROCEDURE AX2009.usp_Create_SALESLINE_OrdiniCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SALESLINE_OrdiniCliente_Riga (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    SALESID        NVARCHAR(20) NOT NULL,
    NPOLINENUM        INT NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    ITEMID        NVARCHAR(20) NOT NULL,
    SALESSTATUS        SMALLINT NOT NULL,
    NAME        NVARCHAR(1000) NOT NULL,
    EXTERNALITEMID        NVARCHAR(30) NOT NULL,
    DIMENSION        NVARCHAR(10) NOT NULL,
    DIMENSION2_        NVARCHAR(10) NOT NULL,
    DIMENSION3_        NVARCHAR(10) NOT NULL,
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    UNDERDELIVERYPCT        NUMERIC(28, 12) NOT NULL,
    OVERDELIVERYPCT        NUMERIC(28, 12) NOT NULL,
    INVENTREFTRANSID        NVARCHAR(20) NOT NULL,
    INVENTREFTYPE        SMALLINT NOT NULL,
    INVENTREFID        NVARCHAR(20) NOT NULL,
    INTERCOMPANYORIGIN        SMALLINT NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,
    CUSTOMERLINENUM        INT NOT NULL,
    SHIPPINGDATEREQUESTED        DATE NOT NULL,
    SHIPPINGDATECONFIRMED        DATE NOT NULL,
    CREATEDDATETIME        DATETIME NOT NULL,
    NPODLVREASON        NVARCHAR(10) NOT NULL,
    NPOFINISHINGID        NVARCHAR(10) NOT NULL,
    NPOOTHERINFO        SMALLINT NOT NULL,
    NPOPHYSICALSTATEALLOYID        NVARCHAR(10) NOT NULL,
    NPOLENGTH        NUMERIC(28, 12) NOT NULL,
    NPOALLOYID        NVARCHAR(20) NOT NULL,
    NPOPBAINTERCOMPANYBOMITEMID        NVARCHAR(20) NOT NULL,
    NPOCONTRACTWORKTRANSID        NVARCHAR(20) NOT NULL,
    NPOREVENUEREFTRANSID        NVARCHAR(20) NOT NULL,
    NPOREVENUESALESLINE        SMALLINT NOT NULL,
    NPOWRKCTRGROUPID        NVARCHAR(10) NOT NULL,
    NPOWRKCTRCHARGES        BIT NOT NULL,
    NPOINTERCOMPANYORIGINALSALESID        NVARCHAR(20) NOT NULL,
    NPOINTERCOMPANYORIGINALCU30041        NVARCHAR(20) NOT NULL,
    NPOINTERCOMPANYORIGINALIN30042        NVARCHAR(20) NOT NULL,
    DIMENSION4_        NVARCHAR(10) NOT NULL,
    DIMENSION5_        NVARCHAR(10) NOT NULL,
    DIMENSION6_        NVARCHAR(10) NOT NULL,
    NCEPROFILEFINISHWEIGHTCHECKED        BIT NOT NULL,
    NCEREQUISITIONTYPE        SMALLINT NOT NULL,
    NPOWRKCTRREFPURCHID        NVARCHAR(20) NOT NULL,

    -- Misure
    SALESUNIT        NVARCHAR(10) NOT NULL,
    SALESQTY        NUMERIC(28, 12) NOT NULL,
    NPOSALESUNIT        NVARCHAR(10) NOT NULL,
    NPOSALESQTY        NUMERIC(28, 12) NOT NULL,
    QTYORDERED        NUMERIC(28, 12) NOT NULL,
    REMAINSALESPHYSICAL        NUMERIC(28, 12) NOT NULL,
    REMAININVENTPHYSICAL        NUMERIC(28, 12) NOT NULL,
    REMAINSALESFINANCIAL        NUMERIC(28, 12) NOT NULL,
    CURRENCYCODE        NVARCHAR(3) NOT NULL,
    LINEAMOUNT        NUMERIC(28, 12) NOT NULL,
    SALESPRICE        NUMERIC(28, 12) NOT NULL,
    PRICEUNIT        NUMERIC(28, 12) NOT NULL,
    LINEPERCENT        NUMERIC(28, 12) NOT NULL,
    LINEDISC        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_SALESLINE_OrdiniCliente_Riga PRIMARY KEY CLUSTERED (
        DATAAREAID,
        SALESID,
        NPOLINENUM,
        RECID
    )
);

END;
GO

