
CREATE PROCEDURE AX2009.usp_Merge_EMPLTABLE_Dipendente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.EMPLTABLE_Dipendente', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_EMPLTABLE_Dipendente;
	EXEC AX2009.usp_AddIndexes_EMPLTABLE_Dipendente;
END;

MERGE INTO AX2009.EMPLTABLE_Dipendente AS TGT
USING AX2009.EMPLTABLE_DipendenteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.EMPLID = TGT.EMPLID
WHEN MATCHED AND (TGT.PARTYID <> SRC.PARTYID OR TGT.PBAUSERPROFILE <> SRC.PBAUSERPROFILE OR TGT.DIMENSION6_ <> SRC.DIMENSION6_)
  THEN UPDATE SET TGT.PARTYID = SRC.PARTYID, TGT.PBAUSERPROFILE = SRC.PBAUSERPROFILE, TGT.DIMENSION6_ = SRC.DIMENSION6_
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, EMPLID, RECID, PARTYID, PBAUSERPROFILE, DIMENSION6_)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.EMPLTABLE_Dipendente' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'EMPLID = ' + CAST(COALESCE(inserted.EMPLID, deleted.EMPLID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

