
CREATE PROCEDURE AX2009.usp_Create_INVENTSUM_ScorteDisponibili
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTSUM_ScorteDisponibili (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	INVENTDIMID		NVARCHAR(20) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni

	-- Misure
	PHYSICALINVENT		NUMERIC(28, 12) NOT NULL,
	NPOPHYSICALINVENT2UM		NUMERIC(28, 12) NOT NULL,
	POSTEDQTY		NUMERIC(28, 12) NOT NULL,
	RECEIVED		NUMERIC(28, 12) NOT NULL,
	DEDUCTED		NUMERIC(28, 12) NOT NULL,
	REGISTERED		NUMERIC(28, 12) NOT NULL,
	PICKED		NUMERIC(28, 12) NOT NULL,
	ONORDER		NUMERIC(28, 12) NOT NULL,
	RESERVORDERED		NUMERIC(28, 12) NOT NULL,
	RESERVPHYSICAL		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_INVENTSUM_ScorteDisponibili PRIMARY KEY CLUSTERED (
		DATAAREAID,
		INVENTDIMID,
		ITEMID
	)
);

END;
GO

