
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione_ ON AX2009.NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione () INCLUDE();

END;
GO

