
CREATE PROCEDURE AX2009.usp_Create_NPOITEMSERIESRELATION_ArticoliSerie
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOITEMSERIESRELATION_ArticoliSerie (
	-- Chiavi
	ITEMID		NVARCHAR(20) NOT NULL,
	SERIESID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	PRODUCTTYPEID		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOITEMSERIESRELATION_ArticoliSerie PRIMARY KEY CLUSTERED (
		ITEMID,
		SERIESID
	)
);

END;
GO

