
CREATE PROCEDURE AX2009.usp_Create_METSALESCREDITREASONTABLE_CausaleFido
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METSALESCREDITREASONTABLE_CausaleFido (
    -- Chiavi
    DATAAREAID        NVARCHAR(8) NOT NULL,
    REASONID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni

    -- Misure
    DESCRIPTION        NVARCHAR(120) NOT NULL

    -- Constraint
    CONSTRAINT PK_METSALESCREDITREASONTABLE_CausaleFido PRIMARY KEY CLUSTERED (
        DATAAREAID,
        REASONID
    )
);

END;
GO

