
CREATE PROCEDURE AX2009.usp_Create_INTRASTATTRANSPORTMODE_Trasporto
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INTRASTATTRANSPORTMODE_Trasporto (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    TRANSPORTCODE        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DESCRIPTION        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_INTRASTATTRANSPORTMODE_Trasporto PRIMARY KEY CLUSTERED (
        DATAAREAID,
        TRANSPORTCODE
    )
);

END;
GO

