CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTITEMPRICE_PrezzoArticoli
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_INVENTITEMPRICE_PrezzoArticoli_DATAAREAID_ITEMID_INCLUDE ON AX2009.INVENTITEMPRICE_PrezzoArticoli (DATAAREAID, ITEMID) INCLUDE (PRICECALCID, ACTIVATIONDATE);

END;
GO

