
CREATE PROCEDURE AX2009.usp_Merge_METSALESCREDITREASONTABLE_CausaleFido
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.METSALESCREDITREASONTABLE_CausaleFido', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METSALESCREDITREASONTABLE_CausaleFido;
    EXEC AX2009.usp_AddIndexes_METSALESCREDITREASONTABLE_CausaleFido;
END;

MERGE INTO AX2009.METSALESCREDITREASONTABLE_CausaleFido AS TGT
USING AX2009.METSALESCREDITREASONTABLE_CausaleFidoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.REASONID = TGT.REASONID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, REASONID, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METSALESCREDITREASONTABLE_CausaleFido' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'REASONID = ' + CAST(COALESCE(inserted.REASONID, deleted.REASONID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

