
CREATE PROCEDURE AX2009.usp_AddIndexes_SALESTABLE_OrdiniCliente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SALESTABLE_OrdiniCliente_ ON AX2009.SALESTABLE_OrdiniCliente () INCLUDE();

END;
GO

