
CREATE PROCEDURE AX2009.usp_Create_DIMENSIONS_DimensioneContabile
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.DIMENSIONS_DimensioneContabile (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	DIMENSIONCODE		TINYINT NOT NULL,
	NUM		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DESCRIPTION		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_DIMENSIONS_DimensioneContabile PRIMARY KEY CLUSTERED (
		DATAAREAID,
		DIMENSIONCODE,
		NUM
	)
);

END;
GO

