
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOCUSTPROJECT_Commessa
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOCUSTPROJECT_Commessa_ ON AX2009.NPOCUSTPROJECT_Commessa () INCLUDE();

END;
GO

