
CREATE PROCEDURE AX2009.usp_Merge_TAXBOOKSECTION_SezionaleIVA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.TAXBOOKSECTION_SezionaleIVA', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_TAXBOOKSECTION_SezionaleIVA;
	EXEC AX2009.usp_AddIndexes_TAXBOOKSECTION_SezionaleIVA;
END;

MERGE INTO AX2009.TAXBOOKSECTION_SezionaleIVA AS TGT
USING AX2009.TAXBOOKSECTION_SezionaleIVAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TAXBOOKSECTIONID = TGT.TAXBOOKSECTIONID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TAXBOOKSECTIONID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.TAXBOOKSECTION_SezionaleIVA' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TAXBOOKSECTIONID = ' + CAST(COALESCE(inserted.TAXBOOKSECTIONID, deleted.TAXBOOKSECTIONID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

