CREATE PROCEDURE AX2009.usp_Create_CUSTINVOICETABLE_FattureClienteTestoLibero
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTINVOICETABLE_FattureClienteTestoLibero (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    INVOICEDATE        DATE NOT NULL,
    INVOICEID        NVARCHAR(20) NOT NULL,
    NUMBERSEQUENCEGROUP        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DLVCOUNTRYREGIONID        NVARCHAR(10) NOT NULL


    -- Constraint
    CONSTRAINT PK_CUSTINVOICETABLE_FattureClienteTestoLibero PRIMARY KEY CLUSTERED (
        DATAAREAID,
        INVOICEDATE,
        INVOICEID,
        NUMBERSEQUENCEGROUP
    )
);

END;
GO

