
CREATE PROCEDURE AX2009.usp_AddIndexes_INTRASTATTRANSPORTMODE_Trasporto
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INTRASTATTRANSPORTMODE_Trasporto_ ON AX2009.INTRASTATTRANSPORTMODE_Trasporto () INCLUDE();

END;
GO

