
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOITEMTYPE_ArticoloGruppoTipoArticolo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOITEMTYPE_ArticoloGruppoTipoArticolo_ ON AX2009.NPOITEMTYPE_ArticoloGruppoTipoArticolo () INCLUDE();

END;
GO

