
CREATE PROCEDURE AX2009.usp_Merge_NPOJOURNEYTABLE_Viaggi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.NPOJOURNEYTABLE_Viaggi', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOJOURNEYTABLE_Viaggi;
    EXEC AX2009.usp_AddIndexes_NPOJOURNEYTABLE_Viaggi;
END;

MERGE INTO AX2009.NPOJOURNEYTABLE_Viaggi AS TGT
USING AX2009.NPOJOURNEYTABLE_ViaggiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.JOURNEYID = TGT.JOURNEYID
WHEN MATCHED AND (TGT.DELIVERYDATE <> SRC.DELIVERYDATE OR TGT.DLVMODE <> SRC.DLVMODE OR TGT.DELIVERYNUM <> SRC.DELIVERYNUM OR TGT.FUELSURCHARGE <> SRC.FUELSURCHARGE OR TGT.JOURNEYKM <> SRC.JOURNEYKM OR TGT.JOURNEYCOST <> SRC.JOURNEYCOST OR TGT.REFCHANNEL <> SRC.REFCHANNEL)
  THEN UPDATE SET TGT.DELIVERYDATE = SRC.DELIVERYDATE, TGT.DLVMODE = SRC.DLVMODE, TGT.DELIVERYNUM = SRC.DELIVERYNUM, TGT.FUELSURCHARGE = SRC.FUELSURCHARGE, TGT.JOURNEYKM = SRC.JOURNEYKM, TGT.JOURNEYCOST = SRC.JOURNEYCOST, TGT.REFCHANNEL = SRC.REFCHANNEL
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, JOURNEYID, RECID, DELIVERYDATE, DLVMODE, DELIVERYNUM, FUELSURCHARGE, JOURNEYKM, JOURNEYCOST, REFCHANNEL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOJOURNEYTABLE_Viaggi' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'JOURNEYID = ' + CAST(COALESCE(inserted.JOURNEYID, deleted.JOURNEYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

