
CREATE PROCEDURE AX2009.usp_Merge_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTITEMSALESSETUP_ArticoloImpostazioniVendita', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita;
	EXEC AX2009.usp_AddIndexes_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita;
END;

MERGE INTO AX2009.INVENTITEMSALESSETUP_ArticoloImpostazioniVendita AS TGT
USING AX2009.INVENTITEMSALESSETUP_ArticoloImpostazioniVenditaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.INVENTDIMIDDEFAULT <> SRC.INVENTDIMIDDEFAULT OR TGT.OVERRIDE <> SRC.OVERRIDE OR TGT.NPOSALESMTSQTYMAX <> SRC.NPOSALESMTSQTYMAX OR TGT.LEADTIME <> SRC.LEADTIME)
  THEN UPDATE SET TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.INVENTDIMIDDEFAULT = SRC.INVENTDIMIDDEFAULT, TGT.OVERRIDE = SRC.OVERRIDE, TGT.NPOSALESMTSQTYMAX = SRC.NPOSALESMTSQTYMAX, TGT.LEADTIME = SRC.LEADTIME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, RECID, INVENTDIMID, INVENTDIMIDDEFAULT, OVERRIDE, NPOSALESMTSQTYMAX, LEADTIME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTITEMSALESSETUP_ArticoloImpostazioniVendita' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

