
CREATE PROCEDURE AX2009.usp_Merge_NPOPRODUCTIONLOT_Lotti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPRODUCTIONLOT_Lotti', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOPRODUCTIONLOT_Lotti;
	EXEC AX2009.usp_AddIndexes_NPOPRODUCTIONLOT_Lotti;
END;

MERGE INTO AX2009.NPOPRODUCTIONLOT_Lotti AS TGT
USING AX2009.NPOPRODUCTIONLOT_LottiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.LOTID = TGT.LOTID
WHEN MATCHED AND (TGT.MASTERWRKCTRID <> SRC.MASTERWRKCTRID OR TGT.LINEARKG <> SRC.LINEARKG OR TGT.LOTDATE <> SRC.LOTDATE OR TGT.LOTDATETIME <> SRC.LOTDATETIME)
  THEN UPDATE SET TGT.MASTERWRKCTRID = SRC.MASTERWRKCTRID, TGT.LINEARKG = SRC.LINEARKG, TGT.LOTDATE = SRC.LOTDATE, TGT.LOTDATETIME = SRC.LOTDATETIME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, LOTID, RECID, MASTERWRKCTRID, LINEARKG, LOTDATE, LOTDATETIME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOPRODUCTIONLOT_Lotti' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'LOTID = ' + CAST(COALESCE(inserted.LOTID, deleted.LOTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

