
CREATE PROCEDURE AX2009.usp_Create_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PARTYADDRESSRELATIONSHIPRECID		BIGINT NOT NULL,
	ADDRESSRECID		BIGINT NOT NULL,
	REFCOMPANYID		CHAR(4) NOT NULL,
	RECID		BIGINT NOT NULL

	-- Dimensioni


	-- Constraint
	CONSTRAINT PK_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PARTYADDRESSRELATIONSHIPRECID,
		ADDRESSRECID,
		REFCOMPANYID
	)
);

END;
GO

