
CREATE PROCEDURE AX2009.usp_Create_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPBAFINISHINGLEADTIME_LeadTimeFinitura (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    FINISHINGID        NVARCHAR(10) NOT NULL,
    SECTORTYPE        SMALLINT NOT NULL,
    VENDACCOUNT        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    LEADTIME        INT NOT NULL,
    STOCKMANAGEDITEM        BIT NOT NULL


    -- Constraint
    CONSTRAINT PK_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura PRIMARY KEY CLUSTERED (
        DATAAREAID,
        FINISHINGID,
        SECTORTYPE,
        VENDACCOUNT
    )
);

END;
GO

