
CREATE PROCEDURE AX2009.usp_Merge_CUSTCONFIRMJOUR_ConfermaOrdineCliente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTCONFIRMJOUR_ConfermaOrdineCliente', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTCONFIRMJOUR_ConfermaOrdineCliente;
    EXEC AX2009.usp_AddIndexes_CUSTCONFIRMJOUR_ConfermaOrdineCliente;
END;

MERGE INTO AX2009.CUSTCONFIRMJOUR_ConfermaOrdineCliente AS TGT
USING AX2009.CUSTCONFIRMJOUR_ConfermaOrdineClienteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CONFIRMID = TGT.CONFIRMID
WHEN MATCHED AND (TGT.CONFIRMDATE <> SRC.CONFIRMDATE OR TGT.SALESID <> SRC.SALESID)
  THEN UPDATE SET TGT.CONFIRMDATE = SRC.CONFIRMDATE, TGT.SALESID = SRC.SALESID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CONFIRMID, RECID, CONFIRMDATE, SALESID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTCONFIRMJOUR_ConfermaOrdineCliente' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CONFIRMID = ' + CAST(COALESCE(inserted.CONFIRMID, deleted.CONFIRMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

