
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOCRSTABLE_RiepilogoCRS
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOCRSTABLE_RiepilogoCRS_ ON AX2009.NPOCRSTABLE_RiepilogoCRS () INCLUDE();

END;
GO

