
CREATE PROCEDURE AX2009.usp_Merge_VENDGROUP_FornitoreGruppo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.VENDGROUP_FornitoreGruppo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_VENDGROUP_FornitoreGruppo;
	EXEC AX2009.usp_AddIndexes_VENDGROUP_FornitoreGruppo;
END;

MERGE INTO AX2009.VENDGROUP_FornitoreGruppo AS TGT
USING AX2009.VENDGROUP_FornitoreGruppoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.VENDGROUP = TGT.VENDGROUP
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, VENDGROUP, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.VENDGROUP_FornitoreGruppo' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'VENDGROUP = ' + CAST(COALESCE(inserted.VENDGROUP, deleted.VENDGROUP) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

