
CREATE PROCEDURE AX2009.usp_AddIndexes_BANKREMITTANCEFILESCUST_FileRimesseClienti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_BANKREMITTANCEFILESCUST_FileRimesseClienti_ ON AX2009.BANKREMITTANCEFILESCUST_FileRimesseClienti () INCLUDE();

END;
GO

