
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOBOETOTALTABLEMONTH_Insoluti_Mese
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOBOETOTALTABLEMONTH_Insoluti_Mese_ ON AX2009.NPOBOETOTALTABLEMONTH_Insoluti_Mese () INCLUDE();

END;
GO

