
CREATE PROCEDURE AX2009.usp_Create_BOMVERSION_VersioneDBA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.BOMVERSION_VersioneDBA (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	BOMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TODATE		DATE NOT NULL,
	FROMDATE		DATE NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_BOMVERSION_VersioneDBA PRIMARY KEY CLUSTERED (
		DATAAREAID,
		BOMID,
		RECID
	)
);

END;
GO

