
CREATE PROCEDURE AX2009.usp_Create_COMMISSIONSALESGROUP_GruppoVendite
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.COMMISSIONSALESGROUP_GruppoVendite (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	GROUPID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_COMMISSIONSALESGROUP_GruppoVendite PRIMARY KEY CLUSTERED (
		DATAAREAID,
		GROUPID
	)
);

END;
GO

