
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPACKING_Pacchi
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_NPOPACKING_Pacchi_DATAAREAID_CLOSED_DESTROYED_SCRAPPACKAGE_LOTID ON [AX2009].[NPOPACKING_Pacchi] ([DATAAREAID],[CLOSED],[DESTROYED],[SCRAPPACKAGE],[LOTID]);

END;
GO

