
CREATE PROCEDURE AX2009.usp_Merge_INVENTBATCH_Colata
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTBATCH_Colata', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_INVENTBATCH_Colata;
    EXEC AX2009.usp_AddIndexes_INVENTBATCH_Colata;
END;

MERGE INTO AX2009.INVENTBATCH_Colata AS TGT
USING AX2009.INVENTBATCH_ColataView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.INVENTBATCHID = TGT.INVENTBATCHID
WHEN MATCHED AND (TGT.PRODDATE <> SRC.PRODDATE OR TGT.METLOGLENGTH <> SRC.METLOGLENGTH OR TGT.METINVENTSIZEID <> SRC.METINVENTSIZEID OR TGT.METINVENTCOLORID <> SRC.METINVENTCOLORID)
  THEN UPDATE SET TGT.PRODDATE = SRC.PRODDATE, TGT.METLOGLENGTH = SRC.METLOGLENGTH, TGT.METINVENTSIZEID = SRC.METINVENTSIZEID, TGT.METINVENTCOLORID = SRC.METINVENTCOLORID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, INVENTBATCHID, RECID, PRODDATE, METLOGLENGTH, METINVENTSIZEID, METINVENTCOLORID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.INVENTBATCH_Colata' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'INVENTBATCHID = ' + CAST(COALESCE(inserted.INVENTBATCHID, deleted.INVENTBATCHID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

