
CREATE PROCEDURE AX2009.usp_Create_PRODBOM_OrdiniProduzione_DBA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.PRODBOM_OrdiniProduzione_DBA (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PRODID        NVARCHAR(20) NOT NULL,
    LINENUM        NUMERIC(28, 12) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    PRODLINETYPE        SMALLINT NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    OPRNUM        INT NOT NULL,
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    INVENTREFTYPE        SMALLINT NOT NULL,
    INVENTREFID        NVARCHAR(20) NOT NULL,
    INVENTREFTRANSID        NVARCHAR(20) NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,

    -- Misure
    BOMQTY        NUMERIC(28, 12) NOT NULL,
    REMAINBOMPHYSICAL        NUMERIC(28, 12) NOT NULL,
    QTYBOMSTUP        NUMERIC(28, 12) NOT NULL,
    REMAININVENTPHYSICAL        NUMERIC(28, 12) NOT NULL,
    QTYBOMCALC        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_PRODBOM_OrdiniProduzione_DBA PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PRODID,
        LINENUM,
        RECID
    )
);

END;
GO

