
CREATE PROCEDURE AX2009.usp_Merge_SHIPCARRIERTABLE_Vettore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SHIPCARRIERTABLE_Vettore', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_SHIPCARRIERTABLE_Vettore;
	EXEC AX2009.usp_AddIndexes_SHIPCARRIERTABLE_Vettore;
END;

MERGE INTO AX2009.SHIPCARRIERTABLE_Vettore AS TGT
USING AX2009.SHIPCARRIERTABLE_VettoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CARRIERID = TGT.CARRIERID
WHEN MATCHED AND (TGT.CARRIERNAME <> SRC.CARRIERNAME)
  THEN UPDATE SET TGT.CARRIERNAME = SRC.CARRIERNAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CARRIERID, RECID, CARRIERNAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.SHIPCARRIERTABLE_Vettore' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CARRIERID = ' + CAST(COALESCE(inserted.CARRIERID, deleted.CARRIERID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

