
CREATE PROCEDURE AX2009.usp_AddIndexes_EMPLTABLE_Dipendente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_EMPLTABLE_Dipendente_ ON AX2009.EMPLTABLE_Dipendente () INCLUDE();

END;
GO

