
CREATE PROCEDURE AX2009.usp_Merge_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione;
    EXEC AX2009.usp_AddIndexes_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione;
END;

MERGE INTO AX2009.METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione AS TGT
USING AX2009.METPAINTINGPOWDERWMSLOCATION_FinituraUbicazioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PAINTFINISHINGID = TGT.PAINTFINISHINGID AND SRC.WMSLOCATIONID = TGT.WMSLOCATIONID
--WHEN MATCHED AND ()
--  THEN UPDATE SET 
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PAINTFINISHINGID, WMSLOCATIONID, RECID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PAINTFINISHINGID = ' + CAST(COALESCE(inserted.PAINTFINISHINGID, deleted.PAINTFINISHINGID) AS NVARCHAR) + ' - ' + 'WMSLOCATIONID = ' + CAST(COALESCE(inserted.WMSLOCATIONID, deleted.WMSLOCATIONID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

