
CREATE PROCEDURE AX2009.usp_Create_DATAAREA_Azienda
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.DATAAREA_Azienda (
	-- Chiavi
	ID		NVARCHAR(4) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(40) NOT NULL,
	ISVIRTUAL		BIT NOT NULL,
	TIMEZONE		INT NOT NULL


	-- Constraint
	CONSTRAINT PK_DATAAREA_Azienda PRIMARY KEY CLUSTERED (
		ID
	)
);

END;
GO

