
CREATE PROCEDURE AX2009.usp_Merge_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna;
	EXEC AX2009.usp_AddIndexes_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna;
END;

MERGE INTO AX2009.NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna AS TGT
USING AX2009.NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegnaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.DELIVERYDATE = TGT.DELIVERYDATE AND SRC.INVENTPACKINGSLIPID = TGT.INVENTPACKINGSLIPID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.TRANSFERID <> SRC.TRANSFERID OR TGT.DELIVERYNAME <> SRC.DELIVERYNAME OR TGT.DELIVERYADDRESS <> SRC.DELIVERYADDRESS OR TGT.DLVMODE <> SRC.DLVMODE OR TGT.JOURNEYID <> SRC.JOURNEYID OR TGT.REFDATAAREAID <> SRC.REFDATAAREAID OR TGT.WEIGHT <> SRC.WEIGHT)
  THEN UPDATE SET TGT.TRANSFERID = SRC.TRANSFERID, TGT.DELIVERYNAME = SRC.DELIVERYNAME, TGT.DELIVERYADDRESS = SRC.DELIVERYADDRESS, TGT.DLVMODE = SRC.DLVMODE, TGT.JOURNEYID = SRC.JOURNEYID, TGT.REFDATAAREAID = SRC.REFDATAAREAID, TGT.WEIGHT = SRC.WEIGHT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, DELIVERYDATE, INVENTPACKINGSLIPID, RECID, TRANSFERID, DELIVERYNAME, DELIVERYADDRESS, DLVMODE, JOURNEYID, REFDATAAREAID, WEIGHT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'DELIVERYDATE = ' + CAST(COALESCE(inserted.DELIVERYDATE, deleted.DELIVERYDATE) AS NVARCHAR) + ' - ' + 'INVENTPACKINGSLIPID = ' + CAST(COALESCE(inserted.INVENTPACKINGSLIPID, deleted.INVENTPACKINGSLIPID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

