
CREATE PROCEDURE AX2009.usp_AddIndexes_PRICEDISCTABLE_AccordiPrezzi
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_PRICEDISCTABLE_AccordiPrezzi_RELATION_AMOUNT_INCLUDE ON [AX2009].[PRICEDISCTABLE_AccordiPrezzi] ([RELATION],[AMOUNT]) INCLUDE ([DATAAREAID],[ITEMCODE],[FROMDATE],[TODATE],[PRICEUNIT]);

END;
GO

