
CREATE PROCEDURE AX2009.usp_Merge_VENDTRANS_TransazioniFornitore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.VENDTRANS_TransazioniFornitore', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_VENDTRANS_TransazioniFornitore;
	EXEC AX2009.usp_AddIndexes_VENDTRANS_TransazioniFornitore;
END;

MERGE INTO AX2009.VENDTRANS_TransazioniFornitore AS TGT
USING AX2009.VENDTRANS_TransazioniFornitoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.VOUCHER = TGT.VOUCHER AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM AND SRC.INVOICE = TGT.INVOICE AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.DUEDATE <> SRC.DUEDATE OR TGT.CLOSED <> SRC.CLOSED OR TGT.TRANSTYPE <> SRC.TRANSTYPE OR TGT.DOCUMENTDATE <> SRC.DOCUMENTDATE OR TGT.PAYMMODE <> SRC.PAYMMODE OR TGT.MODIFIEDTRANSACTIONID <> SRC.MODIFIEDTRANSACTIONID OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.AMOUNTCUR <> SRC.AMOUNTCUR OR TGT.AMOUNTMST <> SRC.AMOUNTMST)
  THEN UPDATE SET TGT.DUEDATE = SRC.DUEDATE, TGT.CLOSED = SRC.CLOSED, TGT.TRANSTYPE = SRC.TRANSTYPE, TGT.DOCUMENTDATE = SRC.DOCUMENTDATE, TGT.PAYMMODE = SRC.PAYMMODE, TGT.MODIFIEDTRANSACTIONID = SRC.MODIFIEDTRANSACTIONID, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.AMOUNTCUR = SRC.AMOUNTCUR, TGT.AMOUNTMST = SRC.AMOUNTMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSDATE, VOUCHER, ACCOUNTNUM, INVOICE, RECID, DUEDATE, CLOSED, TRANSTYPE, DOCUMENTDATE, PAYMMODE, MODIFIEDTRANSACTIONID, CURRENCYCODE, AMOUNTCUR, AMOUNTMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.VENDTRANS_TransazioniFornitore' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'VOUCHER = ' + CAST(COALESCE(inserted.VOUCHER, deleted.VOUCHER) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) + ' - ' + 'INVOICE = ' + CAST(COALESCE(inserted.INVOICE, deleted.INVOICE) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

