
CREATE PROCEDURE AX2009.usp_AddIndexes_ROUTEVERSION_Ciclo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ROUTEVERSION_Ciclo_ ON AX2009.ROUTEVERSION_Ciclo () INCLUDE();

END;
GO

