
CREATE PROCEDURE AX2009.usp_Merge_BOMCALCGROUP_GruppoCalcoloDBA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.BOMCALCGROUP_GruppoCalcoloDBA', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_BOMCALCGROUP_GruppoCalcoloDBA;
	EXEC AX2009.usp_AddIndexes_BOMCALCGROUP_GruppoCalcoloDBA;
END;

MERGE INTO AX2009.BOMCALCGROUP_GruppoCalcoloDBA AS TGT
USING AX2009.BOMCALCGROUP_GruppoCalcoloDBAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CALCGROUPID = TGT.CALCGROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.STOPEXPLODEPRICE <> SRC.STOPEXPLODEPRICE)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.STOPEXPLODEPRICE = SRC.STOPEXPLODEPRICE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CALCGROUPID, RECID, NAME, STOPEXPLODEPRICE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.BOMCALCGROUP_GruppoCalcoloDBA' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CALCGROUPID = ' + CAST(COALESCE(inserted.CALCGROUPID, deleted.CALCGROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

