
CREATE PROCEDURE AX2009.usp_Create_SHIPCARRIERTABLE_Vettore
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SHIPCARRIERTABLE_Vettore (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CARRIERID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	CARRIERNAME		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_SHIPCARRIERTABLE_Vettore PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CARRIERID
	)
);

END;
GO

