
CREATE PROCEDURE AX2009.usp_Create_NPOBICOLORWEBSETUP_FinituraBicolore
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOBICOLORWEBSETUP_FinituraBicolore (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	BICOLORCODE		NVARCHAR(5) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	INTERNALFINISHINGID		NVARCHAR(10) NOT NULL,
	EXTERNALFINISHINGID		NVARCHAR(10) NOT NULL,
	NAME		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOBICOLORWEBSETUP_FinituraBicolore PRIMARY KEY CLUSTERED (
		DATAAREAID,
		BICOLORCODE
	)
);

END;
GO

