
CREATE PROCEDURE AX2009.usp_Merge_NPOBOXPALLETRELATION_RelazioneCestaPallet
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOBOXPALLETRELATION_RelazioneCestaPallet', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOBOXPALLETRELATION_RelazioneCestaPallet;
    EXEC AX2009.usp_AddIndexes_NPOBOXPALLETRELATION_RelazioneCestaPallet;
END;

MERGE INTO AX2009.NPOBOXPALLETRELATION_RelazioneCestaPallet AS TGT
USING AX2009.NPOBOXPALLETRELATION_RelazioneCestaPalletView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.NPOBOXID = TGT.NPOBOXID AND SRC.NPOPACKINGID = TGT.NPOPACKINGID AND SRC.PRODID = TGT.PRODID AND SRC.OPRNUM = TGT.OPRNUM AND SRC.INBOX = TGT.INBOX
WHEN MATCHED AND (TGT.OPRID <> SRC.OPRID OR TGT.QTY <> SRC.QTY OR TGT.NPOSECONDUNITQTY <> SRC.NPOSECONDUNITQTY)
  THEN UPDATE SET TGT.OPRID = SRC.OPRID, TGT.QTY = SRC.QTY, TGT.NPOSECONDUNITQTY = SRC.NPOSECONDUNITQTY
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, NPOBOXID, NPOPACKINGID, PRODID, OPRNUM, INBOX, RECID, OPRID, QTY, NPOSECONDUNITQTY)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOBOXPALLETRELATION_RelazioneCestaPallet' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'NPOBOXID = ' + CAST(COALESCE(inserted.NPOBOXID, deleted.NPOBOXID) AS NVARCHAR) + ' - ' + 'NPOPACKINGID = ' + CAST(COALESCE(inserted.NPOPACKINGID, deleted.NPOPACKINGID) AS NVARCHAR) + ' - ' + 'PRODID = ' + CAST(COALESCE(inserted.PRODID, deleted.PRODID) AS NVARCHAR) + ' - ' + 'OPRNUM = ' + CAST(COALESCE(inserted.OPRNUM, deleted.OPRNUM) AS NVARCHAR) + ' - ' + 'INBOX = ' + CAST(COALESCE(inserted.INBOX, deleted.INBOX) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

