
CREATE PROCEDURE AX2009.usp_Create_ROUTEVERSION_Ciclo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ROUTEVERSION_Ciclo (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ROUTEID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	FROMDATE		DATE NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	TODATE		DATE NOT NULL


	-- Constraint
	CONSTRAINT PK_ROUTEVERSION_Ciclo PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ROUTEID,
		RECID
	)
);

END;
GO

