
CREATE PROCEDURE AX2009.usp_Create_NPOPBAFINISHING_Finitura
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPBAFINISHING_Finitura (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    FINISHINGID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    NAME        NVARCHAR(60) NOT NULL,
    LEADTIME        INT NOT NULL,
    ASALIASID        NVARCHAR(3) NOT NULL,
    DEL_FINISHINGTYPE        NVARCHAR(100) NOT NULL,
    FINISHINGGROUPID        NVARCHAR(10) NOT NULL,
    ASALIASIDACCESSORI        NVARCHAR(3) NOT NULL,
    NCEGROUPPRICEMNG        BIT NOT NULL,
    FINISHINGSUBLIMATED        SMALLINT NOT NULL,
    FINISHINGDOUBLELAYER        SMALLINT NOT NULL,
    FINISHINGPOWDERCLASS        SMALLINT NOT NULL,
    FINISHINGMETALLIC        SMALLINT NOT NULL,
    FINISHINGROUGHNESS        SMALLINT NOT NULL,
    FINISHINGSURFACE        SMALLINT NOT NULL,
    FINISHINGFAMILY        SMALLINT NOT NULL,
    FINISHINGTYPE        SMALLINT NOT NULL,
    OPERATIONTYPE        SMALLINT NOT NULL,
    ITEMPRICEGROUPID        NVARCHAR(10) NOT NULL,
    FINISHINGMNG        SMALLINT NOT NULL,
    APPLYCOLORCHANGEMARKUP        BIT NOT NULL,
    FINISHINGDURABILITYCLASS        SMALLINT NOT NULL


    -- Constraint
    CONSTRAINT PK_NPOPBAFINISHING_Finitura PRIMARY KEY CLUSTERED (
        DATAAREAID,
        FINISHINGID
    )
);

END;
GO

