
CREATE PROCEDURE AX2009.usp_Merge_DIRORGANIZATIONDETAIL_DettagliRubrica
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.DIRORGANIZATIONDETAIL_DettagliRubrica', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_DIRORGANIZATIONDETAIL_DettagliRubrica;
    EXEC AX2009.usp_AddIndexes_DIRORGANIZATIONDETAIL_DettagliRubrica;
END;

MERGE INTO AX2009.DIRORGANIZATIONDETAIL_DettagliRubrica AS TGT
USING AX2009.DIRORGANIZATIONDETAIL_DettagliRubricaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PARTYID = TGT.PARTYID
WHEN MATCHED AND (TGT.ABC <> SRC.ABC)
  THEN UPDATE SET TGT.ABC = SRC.ABC
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PARTYID, RECID, ABC)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.DIRORGANIZATIONDETAIL_DettagliRubrica' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PARTYID = ' + CAST(COALESCE(inserted.PARTYID, deleted.PARTYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

