
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTPACKINGSLIPTRANS_DDTCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTPACKINGSLIPTRANS_DDTCliente_Riga_ ON AX2009.CUSTPACKINGSLIPTRANS_DDTCliente_Riga () INCLUDE();

END;
GO

