
CREATE PROCEDURE AX2009.usp_Create_CUSTTRANS_TransazioniCliente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTTRANS_TransazioniCliente (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ACCOUNTNUM		NVARCHAR(20) NOT NULL,
	DUEDATE		DATE NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TRANSDATE		DATE NOT NULL,
	PAYMMODE		NVARCHAR(10) NOT NULL,
	BILLOFEXCHANGEID		NVARCHAR(20) NOT NULL,
	BILLOFEXCHANGESTATUS		SMALLINT NOT NULL,
	BILLOFEXCHANGESEQNUM		INT NOT NULL,
	BANKREMITTANCEFILEID		NVARCHAR(10) NOT NULL,

	-- Misure
	CURRENCYCODE		NVARCHAR(3) NOT NULL,
	AMOUNTCUR		NUMERIC(28, 12) NOT NULL,
	AMOUNTMST		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_CUSTTRANS_TransazioniCliente PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ACCOUNTNUM,
		DUEDATE,
		RECID
	)
);

END;
GO

