
CREATE PROCEDURE AX2009.usp_Create_NPOSCRAPCAUSE_CausaleScarto
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOSCRAPCAUSE_CausaleScarto (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	SCRAPCAUSEID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DESCRIPTION		NVARCHAR(60) NOT NULL,
	SCRAPCAUSEGROUPID		NVARCHAR(3) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOSCRAPCAUSE_CausaleScarto PRIMARY KEY CLUSTERED (
		DATAAREAID,
		SCRAPCAUSEID
	)
);

END;
GO

