
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTPAYMMODETABLE_MetodoPagamentoCliente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTPAYMMODETABLE_MetodoPagamentoCliente_ ON AX2009.CUSTPAYMMODETABLE_MetodoPagamentoCliente () INCLUDE();

END;
GO

