
CREATE PROCEDURE AX2009.usp_Merge_RETURNDISPOSITIONCODE_CodiceSmaltimento
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.RETURNDISPOSITIONCODE_CodiceSmaltimento', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_RETURNDISPOSITIONCODE_CodiceSmaltimento;
	EXEC AX2009.usp_AddIndexes_RETURNDISPOSITIONCODE_CodiceSmaltimento;
END;

MERGE INTO AX2009.RETURNDISPOSITIONCODE_CodiceSmaltimento AS TGT
USING AX2009.RETURNDISPOSITIONCODE_CodiceSmaltimentoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.DISPOSITIONCODEID = TGT.DISPOSITIONCODEID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION OR TGT.DISPOSITIONACTION <> SRC.DISPOSITIONACTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION, TGT.DISPOSITIONACTION = SRC.DISPOSITIONACTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, DISPOSITIONCODEID, RECID, DESCRIPTION, DISPOSITIONACTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.RETURNDISPOSITIONCODE_CodiceSmaltimento' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'DISPOSITIONCODEID = ' + CAST(COALESCE(inserted.DISPOSITIONCODEID, deleted.DISPOSITIONCODEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

