
CREATE PROCEDURE AX2009.usp_Merge_ROUTE_Ciclo_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ROUTE_Ciclo_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_ROUTE_Ciclo_Riga;
	EXEC AX2009.usp_AddIndexes_ROUTE_Ciclo_Riga;
END;

MERGE INTO AX2009.ROUTE_Ciclo_Riga AS TGT
USING AX2009.ROUTE_Ciclo_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ROUTEID = TGT.ROUTEID AND SRC.OPRNUM = TGT.OPRNUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.OPRID <> SRC.OPRID)
  THEN UPDATE SET TGT.OPRID = SRC.OPRID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ROUTEID, OPRNUM, RECID, OPRID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.ROUTE_Ciclo_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ROUTEID = ' + CAST(COALESCE(inserted.ROUTEID, deleted.ROUTEID) AS NVARCHAR) + ' - ' + 'OPRNUM = ' + CAST(COALESCE(inserted.OPRNUM, deleted.OPRNUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

