
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura_ ON AX2009.NPOPBAFINISHINGLEADTIME_LeadTimeFinitura () INCLUDE();

END;
GO

