
CREATE PROCEDURE AX2009.usp_AddIndexes_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi_ ON AX2009.DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi () INCLUDE();

END;
GO

