CREATE PROCEDURE AX2009.usp_Merge_METVENDPROJECT_CommessaFornitore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.METVENDPROJECT_CommessaFornitore', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METVENDPROJECT_CommessaFornitore;
    EXEC AX2009.usp_AddIndexes_METVENDPROJECT_CommessaFornitore;
END;

MERGE INTO AX2009.METVENDPROJECT_CommessaFornitore AS TGT
USING AX2009.METVENDPROJECT_CommessaFornitoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.VENDACCOUNT = TGT.VENDACCOUNT AND SRC.VENDPROJECTID = TGT.VENDPROJECTID
WHEN MATCHED AND (TGT.ENABLECUSTPROJECT <> SRC.ENABLECUSTPROJECT OR TGT.DOCUMENTDESCRIPTION <> SRC.DOCUMENTDESCRIPTION OR TGT.REQUESTDATE <> SRC.REQUESTDATE OR TGT.CUSTACCOUNT <> SRC.CUSTACCOUNT OR TGT.DATEEND <> SRC.DATEEND OR TGT.DATESTART <> SRC.DATESTART OR TGT.SUPPLYTYPE <> SRC.SUPPLYTYPE OR TGT.UNITID <> SRC.UNITID OR TGT.TOTALQTY <> SRC.TOTALQTY OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.METALCOVERPRICE <> SRC.METALCOVERPRICE OR TGT.PRICEUNIT <> SRC.PRICEUNIT OR TGT.METCOVERAGETYPE <> SRC.METCOVERAGETYPE)
  THEN UPDATE SET TGT.ENABLECUSTPROJECT = SRC.ENABLECUSTPROJECT, TGT.DOCUMENTDESCRIPTION = SRC.DOCUMENTDESCRIPTION, TGT.REQUESTDATE = SRC.REQUESTDATE, TGT.CUSTACCOUNT = SRC.CUSTACCOUNT, TGT.DATEEND = SRC.DATEEND, TGT.DATESTART = SRC.DATESTART, TGT.SUPPLYTYPE = SRC.SUPPLYTYPE, TGT.UNITID = SRC.UNITID, TGT.TOTALQTY = SRC.TOTALQTY, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.METALCOVERPRICE = SRC.METALCOVERPRICE, TGT.PRICEUNIT = SRC.PRICEUNIT, TGT.METCOVERAGETYPE = SRC.METCOVERAGETYPE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, VENDACCOUNT, VENDPROJECTID, RECID, ENABLECUSTPROJECT, DOCUMENTDESCRIPTION, REQUESTDATE, CUSTACCOUNT, DATEEND, DATESTART, SUPPLYTYPE, UNITID, TOTALQTY, CURRENCYCODE, METALCOVERPRICE, PRICEUNIT, METCOVERAGETYPE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METVENDPROJECT_CommessaFornitore' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'VENDACCOUNT = ' + CAST(COALESCE(inserted.VENDACCOUNT, deleted.VENDACCOUNT) AS NVARCHAR) + ' - ' + 'VENDPROJECTID = ' + CAST(COALESCE(inserted.VENDPROJECTID, deleted.VENDPROJECTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

