
CREATE PROCEDURE AX2009.usp_AddIndexes_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint_ ON AX2009.AIFENDPOINTCONSTRAINT_AIFEndPointConstraint () INCLUDE();

END;
GO

