
CREATE PROCEDURE AX2009.usp_Create_CUSTINVOICELINE_FattureClienteTestoLibero_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTINVOICELINE_FattureClienteTestoLibero_Riga (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PARENTRECID        BIGINT NOT NULL,
    LINENUM        NUMERIC(28, 12) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    LEDGERACCOUNT        NVARCHAR(20) NOT NULL,
    DIMENSION        NVARCHAR(10) NOT NULL,
    DIMENSION2_        NVARCHAR(10) NOT NULL,
    DIMENSION3_        NVARCHAR(10) NOT NULL,
    DIMENSION4_        NVARCHAR(10) NOT NULL,
    DIMENSION5_        NVARCHAR(10) NOT NULL,
    DIMENSION6_        NVARCHAR(10) NOT NULL


    -- Constraint
    CONSTRAINT PK_CUSTINVOICELINE_FattureClienteTestoLibero_Riga PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PARENTRECID,
        LINENUM,
        RECID
    )
);

END;
GO

