
CREATE PROCEDURE AX2009.usp_Merge_WMSSHIPMENT_Spedizioni
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WMSSHIPMENT_Spedizioni', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_WMSSHIPMENT_Spedizioni;
    EXEC AX2009.usp_AddIndexes_WMSSHIPMENT_Spedizioni;
END;

MERGE INTO AX2009.WMSSHIPMENT_Spedizioni AS TGT
USING AX2009.WMSSHIPMENT_SpedizioniView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SHIPMENTID = TGT.SHIPMENTID
WHEN MATCHED AND (TGT.NPOWMSSHIPMENTSTAGING <> SRC.NPOWMSSHIPMENTSTAGING)
  THEN UPDATE SET TGT.NPOWMSSHIPMENTSTAGING = SRC.NPOWMSSHIPMENTSTAGING
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SHIPMENTID, RECID, NPOWMSSHIPMENTSTAGING)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.WMSSHIPMENT_Spedizioni' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SHIPMENTID = ' + CAST(COALESCE(inserted.SHIPMENTID, deleted.SHIPMENTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

