
CREATE PROCEDURE AX2009.usp_Merge_NPOSCRAPCAUSE_CausaleScarto
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOSCRAPCAUSE_CausaleScarto', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOSCRAPCAUSE_CausaleScarto;
	EXEC AX2009.usp_AddIndexes_NPOSCRAPCAUSE_CausaleScarto;
END;

MERGE INTO AX2009.NPOSCRAPCAUSE_CausaleScarto AS TGT
USING AX2009.NPOSCRAPCAUSE_CausaleScartoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SCRAPCAUSEID = TGT.SCRAPCAUSEID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION OR TGT.SCRAPCAUSEGROUPID <> SRC.SCRAPCAUSEGROUPID)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION, TGT.SCRAPCAUSEGROUPID = SRC.SCRAPCAUSEGROUPID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SCRAPCAUSEID, RECID, DESCRIPTION, SCRAPCAUSEGROUPID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOSCRAPCAUSE_CausaleScarto' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SCRAPCAUSEID = ' + CAST(COALESCE(inserted.SCRAPCAUSEID, deleted.SCRAPCAUSEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

