
CREATE PROCEDURE AX2009.usp_Merge_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione;
	EXEC AX2009.usp_AddIndexes_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione;
END;

MERGE INTO AX2009.NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione AS TGT
USING AX2009.NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.MASTERWRKCTRID = TGT.MASTERWRKCTRID AND SRC.WRKCTRID = TGT.WRKCTRID AND SRC.BARLENGTH = TGT.BARLENGTH
WHEN MATCHED AND (TGT.ESTRBACKLENGTH <> SRC.ESTRBACKLENGTH OR TGT.ISGROUP <> SRC.ISGROUP OR TGT.FIRSTBILLLENGTH <> SRC.FIRSTBILLLENGTH)
  THEN UPDATE SET TGT.ESTRBACKLENGTH = SRC.ESTRBACKLENGTH, TGT.ISGROUP = SRC.ISGROUP, TGT.FIRSTBILLLENGTH = SRC.FIRSTBILLLENGTH
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, MASTERWRKCTRID, WRKCTRID, BARLENGTH, RECID, ESTRBACKLENGTH, ISGROUP, FIRSTBILLLENGTH)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'MASTERWRKCTRID = ' + CAST(COALESCE(inserted.MASTERWRKCTRID, deleted.MASTERWRKCTRID) AS NVARCHAR) + ' - ' + 'WRKCTRID = ' + CAST(COALESCE(inserted.WRKCTRID, deleted.WRKCTRID) AS NVARCHAR) + ' - ' + 'BARLENGTH = ' + CAST(COALESCE(inserted.BARLENGTH, deleted.BARLENGTH) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

