
CREATE PROCEDURE AX2009.usp_AddIndexes_WMSPALLET_Pallet
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WMSPALLET_Pallet_ ON AX2009.WMSPALLET_Pallet () INCLUDE();

END;
GO

