
CREATE PROCEDURE AX2009.usp_Create_PRICEDISCTABLE_AccordiPrezzi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.PRICEDISCTABLE_AccordiPrezzi (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    RELATION        INT NOT NULL,
    ITEMCODE        SMALLINT NOT NULL,
    ACCOUNTCODE        SMALLINT NOT NULL,
    ITEMRELATION        NVARCHAR(20) NOT NULL,
    ACCOUNTRELATION        NVARCHAR(20) NOT NULL,
    QUANTITYAMOUNT        NUMERIC(28, 12) NOT NULL,
    FROMDATE        DATE NOT NULL,
    TODATE        DATE NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    UNITID        NVARCHAR(10) NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,

    -- Misure
    PERCENT1        NUMERIC(28, 12) NOT NULL,
    PERCENT2        NUMERIC(28, 12) NOT NULL,
    CURRENCY        NVARCHAR(3) NOT NULL,
    AMOUNT        NUMERIC(28, 12) NOT NULL,
    PRICEUNIT        NUMERIC(28, 12) NOT NULL,
    MARKUP        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_PRICEDISCTABLE_AccordiPrezzi PRIMARY KEY CLUSTERED (
        DATAAREAID,
        RELATION,
        ITEMCODE,
        ACCOUNTCODE,
        ITEMRELATION,
        ACCOUNTRELATION,
        QUANTITYAMOUNT,
        FROMDATE,
        TODATE,
        RECID
    )
);

END;
GO

