
CREATE PROCEDURE AX2009.usp_AddIndexes_BOMCALCTRANS_CalcoloDBA_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_DATAAREAID_KEY1 ON [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga] ([DATAAREAID],[KEY1]) INCLUDE ([RECID],[OPRNUM]);

CREATE UNIQUE NONCLUSTERED INDEX IX_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_RECID ON [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga] ([RECID]) INCLUDE ([DATAAREAID],[KEY1]);

END;
GO

