
CREATE PROCEDURE AX2009.usp_Merge_WORKCALENDARDATE_DataLavorativa
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WORKCALENDARDATE_DataLavorativa', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_WORKCALENDARDATE_DataLavorativa;
	EXEC AX2009.usp_AddIndexes_WORKCALENDARDATE_DataLavorativa;
END;

MERGE INTO AX2009.WORKCALENDARDATE_DataLavorativa AS TGT
USING AX2009.WORKCALENDARDATE_DataLavorativaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.CALENDARID = TGT.CALENDARID
WHEN MATCHED AND (TGT.WORKTIMECONTROL <> SRC.WORKTIMECONTROL)
  THEN UPDATE SET TGT.WORKTIMECONTROL = SRC.WORKTIMECONTROL
WHEN NOT MATCHED
  THEN INSERT (DATAAREAID, TRANSDATE, CALENDARID, RECID, WORKTIMECONTROL) VALUES (DATAAREAID, TRANSDATE, CALENDARID, RECID, WORKTIMECONTROL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.WORKCALENDARDATE_DataLavorativa' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'CALENDARID = ' + CAST(COALESCE(inserted.CALENDARID, deleted.CALENDARID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

