
CREATE PROCEDURE AX2009.usp_Create_NPOBOETOTALTABLEMONTH_Insoluti_Mese
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOBOETOTALTABLEMONTH_Insoluti_Mese (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	YR		SMALLINT NOT NULL,
	MONTH		TINYINT NOT NULL,
	CUSTACCOUNT		NVARCHAR(20) NOT NULL,
	MACROAREA		NVARCHAR(10) NOT NULL,
	EMPLID		NVARCHAR(20) NOT NULL,
	TRANSTYPE		SMALLINT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Misure
	NUMBERDRAWN		INT NOT NULL,
	NUMBERPROTESTED		INT NOT NULL,
	AMOUNTDRAWN		NUMERIC(28, 12) NOT NULL,
	AMOUNTPROTESTED		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_NPOBOETOTALTABLEMONTH_Insoluti_Mese PRIMARY KEY CLUSTERED (
		DATAAREAID,
		MONTH,
		YR,
		CUSTACCOUNT,
		MACROAREA,
		EMPLID,
		TRANSTYPE
	)
);

END;
GO

