
CREATE PROCEDURE AX2009.usp_AddIndexes_CASHDISC_ScontoCassa
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CASHDISC_ScontoCassa_ ON AX2009.CASHDISC_ScontoCassa () INCLUDE();

END;
GO

