
CREATE PROCEDURE AX2009.usp_AddIndexes_PRICEDISCGROUP_GruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_PRICEDISCGROUP_GruppoPrezzi_ ON AX2009.PRICEDISCGROUP_GruppoPrezzi () INCLUDE();

END;
GO

