
CREATE PROCEDURE AX2009.usp_Merge_INVENTDIM_DimensioneInventariale
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTDIM_DimensioneInventariale', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTDIM_DimensioneInventariale;
	EXEC AX2009.usp_AddIndexes_INVENTDIM_DimensioneInventariale;
END;

MERGE INTO AX2009.INVENTDIM_DimensioneInventariale AS TGT
USING AX2009.INVENTDIM_DimensioneInventarialeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVENTDIMID = TGT.INVENTDIMID
WHEN MATCHED AND (TGT.WMSLOCATIONID <> SRC.WMSLOCATIONID OR TGT.WMSPALLETID <> SRC.WMSPALLETID OR TGT.INVENTLOCATIONID <> SRC.INVENTLOCATIONID OR TGT.INVENTSIZEID <> SRC.INVENTSIZEID OR TGT.INVENTCOLORID <> SRC.INVENTCOLORID OR TGT.INVENTSITEID <> SRC.INVENTSITEID)
  THEN UPDATE SET TGT.WMSLOCATIONID = SRC.WMSLOCATIONID, TGT.WMSPALLETID = SRC.WMSPALLETID, TGT.INVENTLOCATIONID = SRC.INVENTLOCATIONID, TGT.INVENTSIZEID = SRC.INVENTSIZEID, TGT.INVENTCOLORID = SRC.INVENTCOLORID, TGT.INVENTSITEID = SRC.INVENTSITEID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVENTDIMID, RECID, WMSLOCATIONID, WMSPALLETID, INVENTLOCATIONID, INVENTSIZEID, INVENTCOLORID, INVENTSITEID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTDIM_DimensioneInventariale' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVENTDIMID = ' + CAST(COALESCE(inserted.INVENTDIMID, deleted.INVENTDIMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

