
CREATE PROCEDURE AX2009.usp_Merge_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica;
	EXEC AX2009.usp_AddIndexes_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica;
END;

MERGE INTO AX2009.DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica AS TGT
USING AX2009.DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubricaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PARTYID = TGT.PARTYID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ISPRIMARY <> SRC.ISPRIMARY OR TGT.STATUS <> SRC.STATUS OR TGT.VALIDTODATETIME <> SRC.VALIDTODATETIME OR TGT.VALIDFROMDATETIME <> SRC.VALIDFROMDATETIME OR TGT.SHARED <> SRC.SHARED)
  THEN UPDATE SET TGT.ISPRIMARY = SRC.ISPRIMARY, TGT.STATUS = SRC.STATUS, TGT.VALIDTODATETIME = SRC.VALIDTODATETIME, TGT.VALIDFROMDATETIME = SRC.VALIDFROMDATETIME, TGT.SHARED = SRC.SHARED
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PARTYID, RECID, ISPRIMARY, STATUS, VALIDTODATETIME, VALIDFROMDATETIME, SHARED)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PARTYID = ' + CAST(COALESCE(inserted.PARTYID, deleted.PARTYID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

