
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto_ ON AX2009.NPOSCRAPCAUSEGROUP_GruppoCausaleScarto () INCLUDE();

END;
GO

