
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi_ ON AX2009.CUSTBILLOFEXCHANGEJOUR_EffettiAttivi () INCLUDE();

END;
GO

