
CREATE PROCEDURE AX2009.usp_Create_REQITEMTABLE_CoperturaArticoli
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.REQITEMTABLE_CoperturaArticoli (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	MININVENTONHAND		NUMERIC(28, 12) NOT NULL,
	LEADTIMEPURCHASE		INT NOT NULL,
	REQGROUPID		NVARCHAR(10) NOT NULL,
	INVENTLOCATIONIDREQMAIN		NVARCHAR(10) NOT NULL,
	LEADTIMEPURCHASEACTIVE		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_REQITEMTABLE_CoperturaArticoli PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		RECID
	)
);

END;
GO

