
CREATE PROCEDURE AX2009.usp_Create_NPOJOURNEYTABLE_Viaggi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOJOURNEYTABLE_Viaggi (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    JOURNEYID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DELIVERYDATE        DATETIME NOT NULL,
    DLVMODE        NVARCHAR(10) NOT NULL,
    DELIVERYNUM        INT NOT NULL,
    FUELSURCHARGE        NUMERIC(28,12) NOT NULL,

    -- Misure
    JOURNEYKM        INT NOT NULL,
    JOURNEYCOST        NUMERIC(28, 12) NOT NULL,
    REFCHANNEL        SMALLINT NOT NULL

    -- Constraint
    CONSTRAINT PK_NPOJOURNEYTABLE_Viaggi PRIMARY KEY CLUSTERED (
        DATAAREAID,
        JOURNEYID
    )
);

END;
GO

