
CREATE PROCEDURE AX2009.usp_Merge_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOITEMPRICEGROUP_ArticoloGruppoPrezzi', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi;
	EXEC AX2009.usp_AddIndexes_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi;
END;

MERGE INTO AX2009.NPOITEMPRICEGROUP_ArticoloGruppoPrezzi AS TGT
USING AX2009.NPOITEMPRICEGROUP_ArticoloGruppoPrezziView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ITEMPRICEGROUPID <> SRC.ITEMPRICEGROUPID OR TGT.REVITEMID <> SRC.REVITEMID)
  THEN UPDATE SET TGT.ITEMPRICEGROUPID = SRC.ITEMPRICEGROUPID, TGT.REVITEMID = SRC.REVITEMID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, RECID, ITEMPRICEGROUPID, REVITEMID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOITEMPRICEGROUP_ArticoloGruppoPrezzi' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

