
CREATE PROCEDURE AX2009.usp_AddIndexes_TAXTRANS_TransazioniIVA
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_TAXTRANS_TransazioniIVA_ ON AX2009.TAXTRANS_TransazioniIVA () INCLUDE();

END;
GO

