
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOITEMFAMILIES_FamigliaArticolo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOITEMFAMILIES_FamigliaArticolo_ ON AX2009.NPOITEMFAMILIES_FamigliaArticolo () INCLUDE();

END;
GO

