
CREATE PROCEDURE AX2009.usp_Create_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	BILLOFEXCHANGEID		NVARCHAR(20) NOT NULL,
	SEQNUM		INT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	STATUS		INT NOT NULL,
	TRANSDATE		DATE NOT NULL,
	DUEDATE		DATE NOT NULL,

	-- Misure
	CURRENCYCODE		NVARCHAR(3) NOT NULL,
	AMOUNTCUR		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		BILLOFEXCHANGEID,
		SEQNUM,
		RECID
	)
);

END;
GO

