
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia_ ON AX2009.NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia () INCLUDE();

END;
GO

