
CREATE PROCEDURE AX2009.usp_Create_CUSTGROUP_ClienteGruppo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTGROUP_ClienteGruppo (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CUSTGROUP		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_CUSTGROUP_ClienteGruppo PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CUSTGROUP
	)
);

END;
GO

