
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTPOSTING_RegistrazioneMagazzino
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTPOSTING_RegistrazioneMagazzino_ ON AX2009.INVENTPOSTING_RegistrazioneMagazzino () INCLUDE();

END;
GO

