
CREATE PROCEDURE AX2009.usp_AddIndexes_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria_ ON AX2009.FDY_DOCF_FINANCIALVOICE_VoceFinanziaria () INCLUDE();

END;
GO

