
CREATE PROCEDURE AX2009.usp_Merge_PRODROUTE_CicloLavorazioneProduzione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PRODROUTE_CicloLavorazioneProduzione', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_PRODROUTE_CicloLavorazioneProduzione;
    EXEC AX2009.usp_AddIndexes_PRODROUTE_CicloLavorazioneProduzione;
END;

MERGE INTO AX2009.PRODROUTE_CicloLavorazioneProduzione AS TGT
USING AX2009.PRODROUTE_CicloLavorazioneProduzioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PRODID = TGT.PRODID AND SRC.OPRNUM = TGT.OPRNUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.OPRID <> SRC.OPRID OR TGT.WRKCTRID <> SRC.WRKCTRID OR TGT.PROCESSTIME <> SRC.PROCESSTIME OR TGT.PROCESSPERQTY <> SRC.PROCESSPERQTY OR TGT.TOHOURS <> SRC.TOHOURS)
  THEN UPDATE SET TGT.OPRID = SRC.OPRID, TGT.WRKCTRID = SRC.WRKCTRID, TGT.PROCESSTIME = SRC.PROCESSTIME, TGT.PROCESSPERQTY = SRC.PROCESSPERQTY, TGT.TOHOURS = SRC.TOHOURS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PRODID, OPRNUM, RECID, OPRID, WRKCTRID, PROCESSTIME, PROCESSPERQTY, TOHOURS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.PRODROUTE_CicloLavorazioneProduzione' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PRODID = ' + CAST(COALESCE(inserted.PRODID, deleted.PRODID) AS NVARCHAR) + ' - ' + 'OPRNUM = ' + CAST(COALESCE(inserted.OPRNUM, deleted.OPRNUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

