
CREATE PROCEDURE AX2009.usp_Merge_DLVTERM_TerminiConsegna
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DLVTERM_TerminiConsegna', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_DLVTERM_TerminiConsegna;
	EXEC AX2009.usp_AddIndexes_DLVTERM_TerminiConsegna;
END;

MERGE INTO AX2009.DLVTERM_TerminiConsegna AS TGT
USING AX2009.DLVTERM_TerminiConsegnaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CODE = TGT.CODE
WHEN MATCHED AND (TGT.TXT <> SRC.TXT)
  THEN UPDATE SET TGT.TXT = SRC.TXT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CODE, RECID, TXT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.DLVTERM_TerminiConsegna' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CODE = ' + CAST(COALESCE(inserted.CODE, deleted.CODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

