
CREATE PROCEDURE AX2009.usp_Merge_INVENTTRANSFERTABLE_OrdiniTrasferimento
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTTRANSFERTABLE_OrdiniTrasferimento', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTTRANSFERTABLE_OrdiniTrasferimento;
	EXEC AX2009.usp_AddIndexes_INVENTTRANSFERTABLE_OrdiniTrasferimento;
END;

MERGE INTO AX2009.INVENTTRANSFERTABLE_OrdiniTrasferimento AS TGT
USING AX2009.INVENTTRANSFERTABLE_OrdiniTrasferimentoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSFERID = TGT.TRANSFERID
WHEN MATCHED AND (TGT.INVENTLOCATIONIDFROM <> SRC.INVENTLOCATIONIDFROM OR TGT.INVENTLOCATIONIDTO <> SRC.INVENTLOCATIONIDTO OR TGT.TRANSFERSTATUS <> SRC.TRANSFERSTATUS OR TGT.SHIPDATE <> SRC.SHIPDATE OR TGT.RECEIVEDATE <> SRC.RECEIVEDATE)
  THEN UPDATE SET TGT.INVENTLOCATIONIDFROM = SRC.INVENTLOCATIONIDFROM, TGT.INVENTLOCATIONIDTO = SRC.INVENTLOCATIONIDTO, TGT.TRANSFERSTATUS = SRC.TRANSFERSTATUS, TGT.SHIPDATE = SRC.SHIPDATE, TGT.RECEIVEDATE = SRC.RECEIVEDATE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSFERID, RECID, INVENTLOCATIONIDFROM, INVENTLOCATIONIDTO, TRANSFERSTATUS, SHIPDATE, RECEIVEDATE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTTRANSFERTABLE_OrdiniTrasferimento' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSFERID = ' + CAST(COALESCE(inserted.TRANSFERID, deleted.TRANSFERID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

