
CREATE PROCEDURE AX2009.usp_Merge_CUSTPAYMMODETABLE_MetodoPagamentoCliente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTPAYMMODETABLE_MetodoPagamentoCliente', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTPAYMMODETABLE_MetodoPagamentoCliente;
	EXEC AX2009.usp_AddIndexes_CUSTPAYMMODETABLE_MetodoPagamentoCliente;
END;

MERGE INTO AX2009.CUSTPAYMMODETABLE_MetodoPagamentoCliente AS TGT
USING AX2009.CUSTPAYMMODETABLE_MetodoPagamentoClienteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PAYMMODE = TGT.PAYMMODE
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.NPOPAYMTYPE <> SRC.NPOPAYMTYPE)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.NPOPAYMTYPE = SRC.NPOPAYMTYPE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PAYMMODE, RECID, NAME, NPOPAYMTYPE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTPAYMMODETABLE_MetodoPagamentoCliente' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PAYMMODE = ' + CAST(COALESCE(inserted.PAYMMODE, deleted.PAYMMODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

