
CREATE PROCEDURE AX2009.usp_AddIndexes_DLVMODE_ModalitaConsegna
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DLVMODE_ModalitaConsegna_ ON AX2009.DLVMODE_ModalitaConsegna () INCLUDE();

END;
GO

