
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPACKINGSLIPPALLETINFO_DDTPallet
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPACKINGSLIPPALLETINFO_DDTPallet_ ON AX2009.NPOPACKINGSLIPPALLETINFO_DDTPallet () INCLUDE();

END;
GO

