
CREATE PROCEDURE AX2009.usp_Create_NPOCRSTABLE_RiepilogoCRS
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOCRSTABLE_RiepilogoCRS (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CRSNUM		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	EXPEDITIONSTATUS		SMALLINT NOT NULL,
	CREATEDDATETIME		DATETIME NOT NULL,
	COVERINGBASIS		SMALLINT NOT NULL,
	STATIONID		NVARCHAR(10) NOT NULL,
	AREAID		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOCRSTABLE_RiepilogoCRS PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CRSNUM
	)
);

END;
GO

