
CREATE PROCEDURE AX2009.usp_Merge_NPOITEMTYPE_ArticoloGruppoTipoArticolo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOITEMTYPE_ArticoloGruppoTipoArticolo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOITEMTYPE_ArticoloGruppoTipoArticolo;
	EXEC AX2009.usp_AddIndexes_NPOITEMTYPE_ArticoloGruppoTipoArticolo;
END;

MERGE INTO AX2009.NPOITEMTYPE_ArticoloGruppoTipoArticolo AS TGT
USING AX2009.NPOITEMTYPE_ArticoloGruppoTipoArticoloView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMTYPE = TGT.ITEMTYPE
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.STRUCTUALGROUP <> SRC.STRUCTUALGROUP OR TGT.ACCESSORYITEM <> SRC.ACCESSORYITEM)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.STRUCTUALGROUP = SRC.STRUCTUALGROUP, TGT.ACCESSORYITEM = SRC.ACCESSORYITEM
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMTYPE, RECID, NAME, STRUCTUALGROUP, ACCESSORYITEM)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOITEMTYPE_ArticoloGruppoTipoArticolo' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMTYPE = ' + CAST(COALESCE(inserted.ITEMTYPE, deleted.ITEMTYPE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

