
CREATE PROCEDURE AX2009.usp_Merge_WMSORDER_OrdiniMagazzino
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WMSORDER_OrdiniMagazzino', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_WMSORDER_OrdiniMagazzino;
    EXEC AX2009.usp_AddIndexes_WMSORDER_OrdiniMagazzino;
END;

MERGE INTO AX2009.WMSORDER_OrdiniMagazzino AS TGT
USING AX2009.WMSORDER_OrdiniMagazzinoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ORDERID = TGT.ORDERID
WHEN MATCHED AND (TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.ITEMID <> SRC.ITEMID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.STATUS <> SRC.STATUS OR TGT.QTY <> SRC.QTY)
  THEN UPDATE SET TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.ITEMID = SRC.ITEMID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.STATUS = SRC.STATUS, TGT.QTY = SRC.QTY
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ORDERID, RECID, INVENTTRANSID, ITEMID, INVENTDIMID, STATUS, QTY)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.WMSORDER_OrdiniMagazzino' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ORDERID = ' + CAST(COALESCE(inserted.ORDERID, deleted.ORDERID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

