
CREATE PROCEDURE AX2009.usp_Create_ADDRESSCOUNTY_Provincia
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ADDRESSCOUNTY_Provincia (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	COUNTRYREGIONID		NVARCHAR(10) NOT NULL,
	STATEID		NVARCHAR(10) NOT NULL,
	COUNTYID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_ADDRESSCOUNTY_Provincia PRIMARY KEY CLUSTERED (
		DATAAREAID,
		COUNTRYREGIONID,
		STATEID,
		COUNTYID
	)
);

END;
GO

