
CREATE PROCEDURE AX2009.usp_Merge_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione;
	EXEC AX2009.usp_AddIndexes_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione;
END;

MERGE INTO AX2009.METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione AS TGT
USING AX2009.METPBATABLEINSTANCE_ArticoloDettaglioConfigurazioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.INVENTTRANSID = TGT.INVENTTRANSID AND SRC.VARIABLENUM = TGT.VARIABLENUM AND SRC.VARIABLENAME = TGT.VARIABLENAME
WHEN MATCHED AND (TGT.VALUESTR <> SRC.VALUESTR OR TGT.VALUEINT <> SRC.VALUEINT OR TGT.VALUEINT64 <> SRC.VALUEINT64 OR TGT.VALUEREAL <> SRC.VALUEREAL OR TGT.BASETYPENAME <> SRC.BASETYPENAME)
  THEN UPDATE SET TGT.VALUESTR = SRC.VALUESTR, TGT.VALUEINT = SRC.VALUEINT, TGT.VALUEINT64 = SRC.VALUEINT64, TGT.VALUEREAL = SRC.VALUEREAL, TGT.BASETYPENAME = SRC.BASETYPENAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, INVENTTRANSID, VARIABLENUM, VARIABLENAME, RECID, VALUESTR, VALUEINT, VALUEINT64, VALUEREAL, BASETYPENAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'INVENTTRANSID = ' + CAST(COALESCE(inserted.INVENTTRANSID, deleted.INVENTTRANSID) AS NVARCHAR) + ' - ' + 'VARIABLENUM = ' + CAST(COALESCE(inserted.VARIABLENUM, deleted.VARIABLENUM) AS NVARCHAR) + ' - ' + 'VARIABLENAME = ' + CAST(COALESCE(inserted.VARIABLENAME, deleted.VARIABLENAME) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

