
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOJOURNEYTABLE_Viaggi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOJOURNEYTABLE_Viaggi_ ON AX2009.NPOJOURNEYTABLE_Viaggi () INCLUDE();

END;
GO

