
CREATE PROCEDURE AX2009.usp_Merge_NPOREVENUEGROUP_GruppoRicavi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOREVENUEGROUP_GruppoRicavi', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOREVENUEGROUP_GruppoRicavi;
	EXEC AX2009.usp_AddIndexes_NPOREVENUEGROUP_GruppoRicavi;
END;

MERGE INTO AX2009.NPOREVENUEGROUP_GruppoRicavi AS TGT
USING AX2009.NPOREVENUEGROUP_GruppoRicaviView (nolock) AS SRC
ON SRC.REVENUEGROUPID = TGT.REVENUEGROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (REVENUEGROUPID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOREVENUEGROUP_GruppoRicavi' AS full_olap_table_name,
	'REVENUEGROUPID = ' + CAST(COALESCE(inserted.REVENUEGROUPID, deleted.REVENUEGROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

