
CREATE PROCEDURE AX2009.usp_Merge_LEDGERTABLE_ContoCoGe
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.LEDGERTABLE_ContoCoGe', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_LEDGERTABLE_ContoCoGe;
	EXEC AX2009.usp_AddIndexes_LEDGERTABLE_ContoCoGe;
END;

MERGE INTO AX2009.LEDGERTABLE_ContoCoGe AS TGT
USING AX2009.LEDGERTABLE_ContoCoGeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM
WHEN MATCHED AND (TGT.ACCOUNTNAME <> SRC.ACCOUNTNAME)
  THEN UPDATE SET TGT.ACCOUNTNAME = SRC.ACCOUNTNAME, TGT.ACCOUNTCATEGORY = SRC.ACCOUNTCATEGORY
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ACCOUNTNUM, RECID, ACCOUNTNAME, ACCOUNTCATEGORY)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.LEDGERTABLE_ContoCoGe' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

