
CREATE PROCEDURE AX2009.usp_Create_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	SECTORTYPE		SMALLINT NOT NULL,
	MNGTYPE		SMALLINT NOT NULL,
	INVENTITEMTYPE		NVARCHAR(20) NOT NULL,
	FROMDATE		DATE NOT NULL,
	FILTERCODE		SMALLINT NOT NULL,
	CUSTACCOUNT		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	COSTCALCULATIONTYPE		INT NOT NULL,
	PERCENT_		NUMERIC(28, 12) NOT NULL


	-- Constraint
	CONSTRAINT PK_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti PRIMARY KEY CLUSTERED (
		DATAAREAID,
		SECTORTYPE,
		MNGTYPE,
		INVENTITEMTYPE,
		FROMDATE,
		FILTERCODE,
		CUSTACCOUNT
	)
);

END;
GO

