
CREATE PROCEDURE AX2009.usp_Merge_REQPARAMETERS_ParametriPianificazioneGenerale
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.REQPARAMETERS_ParametriPianificazioneGenerale', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_REQPARAMETERS_ParametriPianificazioneGenerale;
    EXEC AX2009.usp_AddIndexes_REQPARAMETERS_ParametriPianificazioneGenerale;
END;

MERGE INTO AX2009.REQPARAMETERS_ParametriPianificazioneGenerale AS TGT
USING AX2009.REQPARAMETERS_ParametriPianificazioneGeneraleView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID
WHEN MATCHED AND (TGT.TODAYSDATECALENDARID <> SRC.TODAYSDATECALENDARID)
  THEN UPDATE SET TGT.TODAYSDATECALENDARID = SRC.TODAYSDATECALENDARID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, RECID, TODAYSDATECALENDARID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.REQPARAMETERS_ParametriPianificazioneGenerale' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

