
CREATE PROCEDURE AX2009.usp_Create_RETURNREASONCODEGROUP_GruppoMotivoReso
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.RETURNREASONCODEGROUP_GruppoMotivoReso (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    REASONCODEGROUPID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DESCRIPTION        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_RETURNREASONCODEGROUP_GruppoMotivoReso PRIMARY KEY CLUSTERED (
        DATAAREAID,
        REASONCODEGROUPID
    )
);

END;
GO

