
CREATE PROCEDURE AX2009.usp_Create_WMSTRANSPORT_TrasportiPallet
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.WMSTRANSPORT_TrasportiPallet (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSPORTID		NVARCHAR(10) NOT NULL,
	WMSPALLETID		NVARCHAR(18) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	FROMLOCATION		NVARCHAR(10) NOT NULL,
	TOLOCATION		NVARCHAR(10) NOT NULL,
	OPERATOR		NVARCHAR(20) NOT NULL,
	EXPEDITIONSTATUS		SMALLINT NOT NULL,
	SHIPMENTID		NVARCHAR(10) NOT NULL,
	FROMINVENTLOCATIONID		NVARCHAR(10) NOT NULL,
	TOINVENTLOCATIONID		NVARCHAR(10) NOT NULL,

	-- Misure
	TOTALQTY		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_WMSTRANSPORT_TrasportiPallet PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSPORTID,
		WMSPALLETID
	)
);

END;
GO

