
CREATE PROCEDURE AX2009.usp_AddIndexes_PAYMTERM_TerminiPagamento
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_PAYMTERM_TerminiPagamento_ ON AX2009.PAYMTERM_TerminiPagamento () INCLUDE();

END;
GO

