
CREATE PROCEDURE AX2009.usp_Merge_NPOPACKING_Pacchi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPACKING_Pacchi', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOPACKING_Pacchi;
    EXEC AX2009.usp_AddIndexes_NPOPACKING_Pacchi;
END;

MERGE INTO AX2009.NPOPACKING_Pacchi AS TGT
USING AX2009.NPOPACKING_PacchiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PACKINGID = TGT.PACKINGID
WHEN MATCHED AND (TGT.WORKSTATIONID <> SRC.WORKSTATIONID OR TGT.EMPLID <> SRC.EMPLID OR TGT.INVENTLOCATIONID <> SRC.INVENTLOCATIONID OR TGT.WMSLOCATIONID <> SRC.WMSLOCATIONID OR TGT.SHIFTID <> SRC.SHIFTID OR TGT.CUSTACCOUNT <> SRC.CUSTACCOUNT OR TGT.CLOSED <> SRC.CLOSED OR TGT.DESTROYED <> SRC.DESTROYED OR TGT.PALLETID <> SRC.PALLETID OR TGT.SCRAPPACKAGE <> SRC.SCRAPPACKAGE OR TGT.WORKSTATIONAREAID <> SRC.WORKSTATIONAREAID OR TGT.WMSLOCATIONIDTO <> SRC.WMSLOCATIONIDTO OR TGT.INTERCOMPANYCUSTACCOUNT <> SRC.INTERCOMPANYCUSTACCOUNT OR TGT.INTERCOMPANYCUSTNAME <> SRC.INTERCOMPANYCUSTNAME OR TGT.INVENTSITEID <> SRC.INVENTSITEID OR TGT.SCRAPCAUSEID <> SRC.SCRAPCAUSEID OR TGT.SAVED <> SRC.SAVED OR TGT.SCALEWORKSTATIONID <> SRC.SCALEWORKSTATIONID OR TGT.SCALEEMPLID <> SRC.SCALEEMPLID OR TGT.SCALEWORKSTATIONAREAID <> SRC.SCALEWORKSTATIONAREAID OR TGT.SCALEDATETIME <> SRC.SCALEDATETIME OR TGT.REASON <> SRC.REASON OR TGT.LOTID <> SRC.LOTID OR TGT.ISPROD <> SRC.ISPROD OR TGT.SCRAPPACKAGETYPE <> SRC.SCRAPPACKAGETYPE OR TGT.SUSPENDED <> SRC.SUSPENDED OR TGT.INTERCOMPANY <> SRC.INTERCOMPANY OR TGT.INTERCOMPANYCOMPANYID <> SRC.INTERCOMPANYCOMPANYID OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.REINSTATEMENTMATERIAL <> SRC.REINSTATEMENTMATERIAL OR TGT.MARKERID <> SRC.MARKERID OR TGT.QTYGOOD <> SRC.QTYGOOD OR TGT.QTYERROR <> SRC.QTYERROR OR TGT.QTYTOT <> SRC.QTYTOT OR TGT.GROSSKG <> SRC.GROSSKG OR TGT.NETKG <> SRC.NETKG OR TGT.TAREKG <> SRC.TAREKG OR TGT.EXPECTEDNETKG <> SRC.EXPECTEDNETKG OR TGT.MEASUREDNETKG <> SRC.MEASUREDNETKG)
  THEN UPDATE SET TGT.WORKSTATIONID = SRC.WORKSTATIONID, TGT.EMPLID = SRC.EMPLID, TGT.INVENTLOCATIONID = SRC.INVENTLOCATIONID, TGT.WMSLOCATIONID = SRC.WMSLOCATIONID, TGT.SHIFTID = SRC.SHIFTID, TGT.CUSTACCOUNT = SRC.CUSTACCOUNT, TGT.CLOSED = SRC.CLOSED, TGT.DESTROYED = SRC.DESTROYED, TGT.PALLETID = SRC.PALLETID, TGT.SCRAPPACKAGE = SRC.SCRAPPACKAGE, TGT.WORKSTATIONAREAID = SRC.WORKSTATIONAREAID, TGT.WMSLOCATIONIDTO = SRC.WMSLOCATIONIDTO, TGT.INTERCOMPANYCUSTACCOUNT = SRC.INTERCOMPANYCUSTACCOUNT, TGT.INTERCOMPANYCUSTNAME = SRC.INTERCOMPANYCUSTNAME, TGT.INVENTSITEID = SRC.INVENTSITEID, TGT.SCRAPCAUSEID = SRC.SCRAPCAUSEID, TGT.SAVED = SRC.SAVED, TGT.SCALEWORKSTATIONID = SRC.SCALEWORKSTATIONID, TGT.SCALEEMPLID = SRC.SCALEEMPLID, TGT.SCALEWORKSTATIONAREAID = SRC.SCALEWORKSTATIONAREAID, TGT.SCALEDATETIME = SRC.SCALEDATETIME, TGT.REASON = SRC.REASON, TGT.LOTID = SRC.LOTID, TGT.ISPROD = SRC.ISPROD, TGT.SCRAPPACKAGETYPE = SRC.SCRAPPACKAGETYPE, TGT.SUSPENDED = SRC.SUSPENDED, TGT.INTERCOMPANY = SRC.INTERCOMPANY, TGT.INTERCOMPANYCOMPANYID = SRC.INTERCOMPANYCOMPANYID, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.REINSTATEMENTMATERIAL = SRC.REINSTATEMENTMATERIAL, TGT.MARKERID = SRC.MARKERID, TGT.QTYGOOD = SRC.QTYGOOD, TGT.QTYERROR = SRC.QTYERROR, TGT.QTYTOT = SRC.QTYTOT, TGT.GROSSKG = SRC.GROSSKG, TGT.NETKG = SRC.NETKG, TGT.TAREKG = SRC.TAREKG, TGT.EXPECTEDNETKG = SRC.EXPECTEDNETKG, TGT.MEASUREDNETKG = SRC.MEASUREDNETKG
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PACKINGID, RECID, WORKSTATIONID, EMPLID, INVENTLOCATIONID, WMSLOCATIONID, SHIFTID, CUSTACCOUNT, CLOSED, DESTROYED, PALLETID, SCRAPPACKAGE, WORKSTATIONAREAID, WMSLOCATIONIDTO, INTERCOMPANYCUSTACCOUNT, INTERCOMPANYCUSTNAME, INVENTSITEID, SCRAPCAUSEID, SAVED, SCALEWORKSTATIONID, SCALEEMPLID, SCALEWORKSTATIONAREAID, SCALEDATETIME, REASON, LOTID, ISPROD, SCRAPPACKAGETYPE, SUSPENDED, INTERCOMPANY, INTERCOMPANYCOMPANYID, CREATEDDATETIME, REINSTATEMENTMATERIAL, MARKERID, QTYGOOD, QTYERROR, QTYTOT, GROSSKG, NETKG, TAREKG, EXPECTEDNETKG, MEASUREDNETKG)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOPACKING_Pacchi' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PACKINGID = ' + CAST(COALESCE(inserted.PACKINGID, deleted.PACKINGID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

