
CREATE PROCEDURE AX2009.usp_Create_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    EMPLID        NVARCHAR(20) NOT NULL,
    RESPONSIBILITYID        NVARCHAR(20) NOT NULL,
    REFTABLEID        INT NOT NULL,
    REFRECID        BIGINT NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni


    -- Constraint
    CONSTRAINT PK_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente PRIMARY KEY CLUSTERED (
        DATAAREAID,
        EMPLID,
        RESPONSIBILITYID,
        REFTABLEID,
        REFRECID
    )
);

END;
GO

