
CREATE PROCEDURE AX2009.usp_AddIndexes_WRKCTRTABLE_CentroDiLavoro
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WRKCTRTABLE_CentroDiLavoro_ ON AX2009.WRKCTRTABLE_CentroDiLavoro () INCLUDE();

END;
GO

