
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOBOXPALLETRELATION_RelazioneCestaPallet
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOBOXPALLETRELATION_RelazioneCestaPallet_ ON AX2009.NPOBOXPALLETRELATION_RelazioneCestaPallet () INCLUDE();

END;
GO

