
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili_ ON AX2009.NPOSTRUCTURALITEMIDSETUPTABLE_ArticoloImpostazioniProfili () INCLUDE();

END;
GO

