
CREATE PROCEDURE AX2009.usp_AddIndexes_ASSETTABLE_Cespite
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ASSETTABLE_Cespite_ ON AX2009.ASSETTABLE_Cespite () INCLUDE();

END;
GO

