
CREATE PROCEDURE AX2009.usp_Create_CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione (
	-- Chiavi
	DATAAREAID  CHAR(4) NOT NULL,
	CODE  NVARCHAR(10) NOT NULL,
	RECID  BIGINT NOT NULL,

	-- Dimensioni
	TXT  NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CODE
	)
);

END;
GO

