
CREATE PROCEDURE AX2009.usp_Merge_ROUTEVERSION_Ciclo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ROUTEVERSION_Ciclo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_ROUTEVERSION_Ciclo;
	EXEC AX2009.usp_AddIndexes_ROUTEVERSION_Ciclo;
END;

MERGE INTO AX2009.ROUTEVERSION_Ciclo AS TGT
USING AX2009.ROUTEVERSION_CicloView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ROUTEID = TGT.ROUTEID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.FROMDATE <> SRC.FROMDATE OR TGT.ITEMID <> SRC.ITEMID OR TGT.TODATE <> SRC.TODATE)
  THEN UPDATE SET TGT.FROMDATE = SRC.FROMDATE, TGT.ITEMID = SRC.ITEMID, TGT.TODATE = SRC.TODATE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ROUTEID, RECID, FROMDATE, ITEMID, TODATE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.ROUTEVERSION_Ciclo' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ROUTEID = ' + CAST(COALESCE(inserted.ROUTEID, deleted.ROUTEID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

