
CREATE PROCEDURE AX2009.usp_AddIndexes_SMMBUSRELSEGMENTGROUP_Segmento
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SMMBUSRELSEGMENTGROUP_Segmento_ ON AX2009.SMMBUSRELSEGMENTGROUP_Segmento () INCLUDE();

END;
GO

