
CREATE PROCEDURE AX2009.usp_Merge_SMMBUSRELSEGMENTGROUP_Segmento
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SMMBUSRELSEGMENTGROUP_Segmento', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_SMMBUSRELSEGMENTGROUP_Segmento;
    EXEC AX2009.usp_AddIndexes_SMMBUSRELSEGMENTGROUP_Segmento;
END;

MERGE INTO AX2009.SMMBUSRELSEGMENTGROUP_Segmento AS TGT
USING AX2009.SMMBUSRELSEGMENTGROUP_SegmentoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SEGMENTID = TGT.SEGMENTID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION OR TGT.BUSINESSSECTORID <> SRC.BUSINESSSECTORID)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION, TGT.BUSINESSSECTORID = SRC.BUSINESSSECTORID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SEGMENTID, RECID, DESCRIPTION, BUSINESSSECTORID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.SMMBUSRELSEGMENTGROUP_Segmento' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SEGMENTID = ' + CAST(COALESCE(inserted.SEGMENTID, deleted.SEGMENTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

