
CREATE PROCEDURE AX2009.usp_Create_NPOREVENUEGROUP_GruppoRicavi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOREVENUEGROUP_GruppoRicavi (
	-- Chiavi
	REVENUEGROUPID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOREVENUEGROUP_GruppoRicavi PRIMARY KEY CLUSTERED (
		REVENUEGROUPID
	)
);

END;
GO

