
CREATE PROCEDURE AX2009.usp_Merge_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPACKINGSLIPEXTERNAL_DDTTerzeParti', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti;
	EXEC AX2009.usp_AddIndexes_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti;
END;

MERGE INTO AX2009.NPOPACKINGSLIPEXTERNAL_DDTTerzeParti AS TGT
USING AX2009.NPOPACKINGSLIPEXTERNAL_DDTTerzePartiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.DELIVERYDATE = TGT.DELIVERYDATE AND SRC.PACKINGCODE = TGT.PACKINGCODE AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.REFDATAAREAID <> SRC.REFDATAAREAID OR TGT.DELIVERYNAME <> SRC.DELIVERYNAME OR TGT.DELIVERYADDRESS <> SRC.DELIVERYADDRESS OR TGT.JOURNEYID <> SRC.JOURNEYID OR TGT.DLVMODEID <> SRC.DLVMODEID OR TGT.DELIVERYCOUNTY <> SRC.DELIVERYCOUNTY OR TGT.DELIVERYCOUNTRYREGIONID <> SRC.DELIVERYCOUNTRYREGIONID OR TGT.DELIVERYSTATEID <> SRC.DELIVERYSTATEID OR TGT.WEIGHT <> SRC.WEIGHT)
  THEN UPDATE SET TGT.REFDATAAREAID = SRC.REFDATAAREAID, TGT.DELIVERYNAME = SRC.DELIVERYNAME, TGT.DELIVERYADDRESS = SRC.DELIVERYADDRESS, TGT.JOURNEYID = SRC.JOURNEYID, TGT.DLVMODEID = SRC.DLVMODEID, TGT.DELIVERYCOUNTY = SRC.DELIVERYCOUNTY, TGT.DELIVERYCOUNTRYREGIONID = SRC.DELIVERYCOUNTRYREGIONID, TGT.DELIVERYSTATEID = SRC.DELIVERYSTATEID, TGT.WEIGHT = SRC.WEIGHT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, DELIVERYDATE, PACKINGCODE, RECID, REFDATAAREAID, DELIVERYNAME, DELIVERYADDRESS, JOURNEYID, DLVMODEID, DELIVERYCOUNTY, DELIVERYCOUNTRYREGIONID, DELIVERYSTATEID, WEIGHT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOPACKINGSLIPEXTERNAL_DDTTerzeParti' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'DELIVERYDATE = ' + CAST(COALESCE(inserted.DELIVERYDATE, deleted.DELIVERYDATE) AS NVARCHAR) + ' - ' + 'PACKINGCODE = ' + CAST(COALESCE(inserted.PACKINGCODE, deleted.PACKINGCODE) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

