
CREATE PROCEDURE AX2009.usp_Create_UNITCONVERT_ConversioneUnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.UNITCONVERT_ConversioneUnitaDiMisura (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	FROMUNIT		NVARCHAR(10) NOT NULL,
	TOUNIT		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	FACTOR		NUMERIC(28, 12) NOT NULL,
	MARKUP		NUMERIC(28, 12) NOT NULL,
	ROUNDOFF		SMALLINT NOT NULL


	-- Constraint
	CONSTRAINT PK_UNITCONVERT_ConversioneUnitaDiMisura PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		FROMUNIT,
		TOUNIT
	)
);

END;
GO

