
CREATE PROCEDURE AX2009.usp_AddIndexes_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento_ ON AX2009.SMMBUSRELSUBSEGMENTGROUP_Sottosegmento () INCLUDE();

END;
GO

