
CREATE PROCEDURE AX2009.usp_Merge_INVENTTRANSFERLINE_OrdiniTrasferimento_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTTRANSFERLINE_OrdiniTrasferimento_Riga', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_INVENTTRANSFERLINE_OrdiniTrasferimento_Riga;
    EXEC AX2009.usp_AddIndexes_INVENTTRANSFERLINE_OrdiniTrasferimento_Riga;
END;

MERGE INTO AX2009.INVENTTRANSFERLINE_OrdiniTrasferimento_Riga AS TGT
USING AX2009.INVENTTRANSFERLINE_OrdiniTrasferimento_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSFERID = TGT.TRANSFERID AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ITEMID <> SRC.ITEMID OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.INVENTTRANSIDRECEIVE <> SRC.INVENTTRANSIDRECEIVE OR TGT.SHIPDATE <> SRC.SHIPDATE OR TGT.RECEIVEDATE <> SRC.RECEIVEDATE OR TGT.NPOINVENTTRANSIDPRODBOM <> SRC.NPOINVENTTRANSIDPRODBOM OR TGT.UNITID <> SRC.UNITID OR TGT.QTYTRANSFER <> SRC.QTYTRANSFER OR TGT.QTYREMAINSHIP <> SRC.QTYREMAINSHIP OR TGT.QTYSHIPPED <> SRC.QTYSHIPPED)
  THEN UPDATE SET TGT.ITEMID = SRC.ITEMID, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.INVENTTRANSIDRECEIVE = SRC.INVENTTRANSIDRECEIVE, TGT.SHIPDATE = SRC.SHIPDATE, TGT.RECEIVEDATE = SRC.RECEIVEDATE, TGT.NPOINVENTTRANSIDPRODBOM = SRC.NPOINVENTTRANSIDPRODBOM, TGT.UNITID = SRC.UNITID, TGT.QTYTRANSFER = SRC.QTYTRANSFER, TGT.QTYREMAINSHIP = SRC.QTYREMAINSHIP, TGT.QTYSHIPPED = SRC.QTYSHIPPED
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSFERID, LINENUM, RECID, ITEMID, INVENTTRANSID, INVENTTRANSIDRECEIVE, SHIPDATE, RECEIVEDATE, NPOINVENTTRANSIDPRODBOM, UNITID, QTYTRANSFER, QTYREMAINSHIP, QTYSHIPPED)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.INVENTTRANSFERLINE_OrdiniTrasferimento_Riga' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSFERID = ' + CAST(COALESCE(inserted.TRANSFERID, deleted.TRANSFERID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

