
CREATE PROCEDURE AX2009.usp_AddIndexes_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita_ ON AX2009.SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita () INCLUDE();

END;
GO

