
CREATE PROCEDURE AX2009.usp_Merge_ASSETGROUP_GruppoCespiti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.ASSETGROUP_GruppoCespiti', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_ASSETGROUP_GruppoCespiti;
    EXEC AX2009.usp_AddIndexes_ASSETGROUP_GruppoCespiti;
END;

MERGE INTO AX2009.ASSETGROUP_GruppoCespiti AS TGT
USING AX2009.ASSETGROUP_GruppoCespitiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.GROUPID = TGT.GROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, GROUPID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.ASSETGROUP_GruppoCespiti' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'GROUPID = ' + CAST(COALESCE(inserted.GROUPID, deleted.GROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

