
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale_ ON AX2009.INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale () INCLUDE();

END;
GO

