
CREATE PROCEDURE AX2009.usp_Create_INVENTITEMPRICE_PrezzoArticoli
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTITEMPRICE_PrezzoArticoli (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    VERSIONID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    PRICETYPE        INT NOT NULL,
    PRICEUNIT        NUMERIC(28, 12) NOT NULL,
    PRICECALCID        NVARCHAR(20) NOT NULL,
    UNITID        NVARCHAR(10) NOT NULL,
    ACTIVATIONDATE        DATETIME NOT NULL,
    CREATEDDATETIME        DATETIME NOT NULL,

    -- Misure
    PRICE        NUMERIC(28, 12) NOT NULL,
    PRICEQTY        NUMERIC(28, 12) NOT NULL,
    MARKUP        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_INVENTITEMPRICE_PrezzoArticoli PRIMARY KEY CLUSTERED (
        DATAAREAID,
        ITEMID,
        VERSIONID,
        RECID
    )
);

END;
GO

