
CREATE PROCEDURE AX2009.usp_Merge_ROUTEOPRTABLE_Operazione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ROUTEOPRTABLE_Operazione', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_ROUTEOPRTABLE_Operazione;
	EXEC AX2009.usp_AddIndexes_ROUTEOPRTABLE_Operazione;
END;

MERGE INTO AX2009.ROUTEOPRTABLE_Operazione AS TGT
USING AX2009.ROUTEOPRTABLE_OperazioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.OPRID = TGT.OPRID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.NPOREVENUEGROUP <> SRC.NPOREVENUEGROUP)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.NPOREVENUEGROUP = SRC.NPOREVENUEGROUP
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, OPRID, RECID, NAME, NPOREVENUEGROUP)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.ROUTEOPRTABLE_Operazione' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'OPRID = ' + CAST(COALESCE(inserted.OPRID, deleted.OPRID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

