
CREATE PROCEDURE AX2009.usp_Create_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTITEMSALESSETUP_ArticoloImpostazioniVendita (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	INVENTDIMID		NVARCHAR(20) NOT NULL,
	INVENTDIMIDDEFAULT		NVARCHAR(20) NOT NULL,
	OVERRIDE		BIT NOT NULL,
	NPOSALESMTSQTYMAX		NUMERIC(28, 12) NOT NULL,

	-- Misure
	LEADTIME		INT NOT NULL

	-- Constraint
	CONSTRAINT PK_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		RECID
	)
);

END;
GO

