
CREATE PROCEDURE AX2009.usp_Merge_USERINFO_Utente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.USERINFO_Utente', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_USERINFO_Utente;
	EXEC AX2009.usp_AddIndexes_USERINFO_Utente;
END;

MERGE INTO AX2009.USERINFO_Utente AS TGT
USING AX2009.USERINFO_UtenteView (nolock) AS SRC
ON SRC.ID = TGT.ID AND SRC.NAME = TGT.NAME
WHEN MATCHED AND (TGT.NETWORKALIAS <> SRC.NETWORKALIAS)
  THEN UPDATE SET TGT.NETWORKALIAS = SRC.NETWORKALIAS
WHEN NOT MATCHED
  THEN INSERT VALUES (ID, NAME, RECID, NETWORKALIAS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.USERINFO_Utente' AS full_olap_table_name,
	'ID = ' + CAST(COALESCE(inserted.ID, deleted.ID) AS NVARCHAR) + ' - ' + 'NAME = ' + CAST(COALESCE(inserted.NAME, deleted.NAME) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

