
CREATE PROCEDURE AX2009.usp_AddIndexes_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite_ ON AX2009.METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite () INCLUDE();

END;
GO

