
CREATE PROCEDURE AX2009.usp_Merge_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione;
	EXEC AX2009.usp_AddIndexes_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione;
END;

MERGE INTO AX2009.NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione AS TGT
USING AX2009.NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.LOTID = TGT.LOTID AND SRC.PRODID = TGT.PRODID
WHEN MATCHED AND (TGT.SALESID <> SRC.SALESID OR TGT.LOTLENGTH <> SRC.LOTLENGTH OR TGT.SALESNPOLINENUM <> SRC.SALESNPOLINENUM OR TGT.ASSIGNEDQTY <> SRC.ASSIGNEDQTY)
  THEN UPDATE SET TGT.SALESID = SRC.SALESID, TGT.LOTLENGTH = SRC.LOTLENGTH, TGT.SALESNPOLINENUM = SRC.SALESNPOLINENUM, TGT.ASSIGNEDQTY = SRC.ASSIGNEDQTY
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, LOTID, PRODID, RECID, SALESID, LOTLENGTH, SALESNPOLINENUM, ASSIGNEDQTY)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'LOTID = ' + CAST(COALESCE(inserted.LOTID, deleted.LOTID) AS NVARCHAR) + ' - ' + 'PRODID = ' + CAST(COALESCE(inserted.PRODID, deleted.PRODID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

