
CREATE PROCEDURE AX2009.usp_Merge_TIMEZONESLIST_FusoOrario
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.TIMEZONESLIST_FusoOrario', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_TIMEZONESLIST_FusoOrario;
	EXEC AX2009.usp_AddIndexes_TIMEZONESLIST_FusoOrario;
END;

MERGE INTO AX2009.TIMEZONESLIST_FusoOrario AS TGT
USING AX2009.TIMEZONESLIST_FusoOrarioView (nolock) AS SRC
ON SRC.TZENUM = TGT.TZENUM
WHEN MATCHED AND (TGT.TIMEZONEKEYNAME <> SRC.TIMEZONEKEYNAME OR TGT.ENUMNAME <> SRC.ENUMNAME)
  THEN UPDATE SET TGT.TIMEZONEKEYNAME = SRC.TIMEZONEKEYNAME, TGT.ENUMNAME = SRC.ENUMNAME
WHEN NOT MATCHED
  THEN INSERT VALUES (TZENUM, RECID, TIMEZONEKEYNAME, ENUMNAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.TIMEZONESLIST_FusoOrario' AS full_olap_table_name,
	'TZENUM = ' + CAST(COALESCE(inserted.TZENUM, deleted.TZENUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

