
CREATE PROCEDURE AX2009.usp_Create_VENDTRANS_TransazioniFornitore
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.VENDTRANS_TransazioniFornitore (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSDATE		DATE NOT NULL,
	VOUCHER		NVARCHAR(20) NOT NULL,
	ACCOUNTNUM		NVARCHAR(20) NOT NULL,
	INVOICE		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DUEDATE		DATE NOT NULL,
	CLOSED		DATE NOT NULL,
	TRANSTYPE		SMALLINT NOT NULL,
	DOCUMENTDATE		DATE NOT NULL,
	PAYMMODE		NVARCHAR(10) NOT NULL,
	MODIFIEDTRANSACTIONID		BIGINT NOT NULL,

	-- Misure
	CURRENCYCODE		NVARCHAR(3) NOT NULL,
	AMOUNTCUR		NUMERIC(28, 12) NOT NULL,
	AMOUNTMST		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_VENDTRANS_TransazioniFornitore PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSDATE,
		VOUCHER,
		ACCOUNTNUM,
		INVOICE,
		RECID
	)
);

END;
GO

