
CREATE PROCEDURE AX2009.usp_Create_PURCHPOOL_PoolAcquisti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.PURCHPOOL_PoolAcquisti (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PURCHPOOLID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_PURCHPOOL_PoolAcquisti PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PURCHPOOLID
	)
);

END;
GO

