
CREATE PROCEDURE AX2009.usp_Merge_NPOPACKINGTAG_Pacchi_Etichetta
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPACKINGTAG_Pacchi_Etichetta', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOPACKINGTAG_Pacchi_Etichetta;
    EXEC AX2009.usp_AddIndexes_NPOPACKINGTAG_Pacchi_Etichetta;
END;

MERGE INTO AX2009.NPOPACKINGTAG_Pacchi_Etichetta AS TGT
USING AX2009.NPOPACKINGTAG_Pacchi_EtichettaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PACKINGID = TGT.PACKINGID
WHEN MATCHED AND (TGT.CUSTNAME <> SRC.CUSTNAME OR TGT.CUSTACCOUNT <> SRC.CUSTACCOUNT OR TGT.REASON <> SRC.REASON OR TGT.CUSTADDRESS <> SRC.CUSTADDRESS OR TGT.FINISHING <> SRC.FINISHING OR TGT.FINISHING2 <> SRC.FINISHING2 OR TGT.IsDaLavorareMetraColor <> SRC.IsDaLavorareMetraColor)
  THEN UPDATE SET TGT.CUSTNAME = SRC.CUSTNAME, TGT.CUSTACCOUNT = SRC.CUSTACCOUNT, TGT.REASON = SRC.REASON, TGT.CUSTADDRESS = SRC.CUSTADDRESS, TGT.FINISHING = SRC.FINISHING, TGT.FINISHING2 = SRC.FINISHING2, TGT.IsDaLavorareMetraColor = SRC.IsDaLavorareMetraColor
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PACKINGID, RECID, CUSTNAME, CUSTACCOUNT, REASON, CUSTADDRESS, FINISHING, FINISHING2, IsDaLavorareMetraColor)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOPACKINGTAG_Pacchi_Etichetta' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PACKINGID = ' + CAST(COALESCE(inserted.PACKINGID, deleted.PACKINGID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

