
CREATE PROCEDURE AX2009.usp_Create_NPOITEMFAMILIES_FamigliaArticolo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOITEMFAMILIES_FamigliaArticolo (
	-- Chiavi
	FAMILYID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOITEMFAMILIES_FamigliaArticolo PRIMARY KEY CLUSTERED (
		FAMILYID
	)
);

END;
GO

