
CREATE PROCEDURE AX2009.usp_AddIndexes_PURCHTABLE_OrdiniFornitore
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_PURCHTABLE_OrdiniFornitore_ ON AX2009.PURCHTABLE_OrdiniFornitore () INCLUDE();

END;
GO

