
CREATE PROCEDURE AX2009.usp_Merge_CUSTINVOICEJOUR_FattureCliente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.CUSTINVOICEJOUR_FattureCliente', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTINVOICEJOUR_FattureCliente;
    EXEC AX2009.usp_AddIndexes_CUSTINVOICEJOUR_FattureCliente;
END;

MERGE INTO AX2009.CUSTINVOICEJOUR_FattureCliente AS TGT
USING AX2009.CUSTINVOICEJOUR_FattureClienteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVOICEDATE = TGT.INVOICEDATE AND SRC.INVOICEID = TGT.INVOICEID AND SRC.SALESID = TGT.SALESID AND SRC.NUMBERSEQUENCEGROUP = TGT.NUMBERSEQUENCEGROUP AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ORDERACCOUNT <> SRC.ORDERACCOUNT OR TGT.INVOICEACCOUNT <> SRC.INVOICEACCOUNT OR TGT.LEDGERVOUCHER <> SRC.LEDGERVOUCHER OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.DLVTERM <> SRC.DLVTERM OR TGT.DLVCOUNTRYREGIONID <> SRC.DLVCOUNTRYREGIONID OR TGT.RETURNREASONCODEID <> SRC.RETURNREASONCODEID OR TGT.INVOICETYPE <> SRC.INVOICETYPE OR TGT.NPOPROJECTCODE <> SRC.NPOPROJECTCODE OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_ OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.EXCHRATE <> SRC.EXCHRATE OR TGT.INVOICEAMOUNT <> SRC.INVOICEAMOUNT OR TGT.INVOICEAMOUNTMST <> SRC.INVOICEAMOUNTMST OR TGT.SALESBALANCE <> SRC.SALESBALANCE OR TGT.SALESBALANCEMST <> SRC.SALESBALANCEMST OR TGT.SUMMARKUP <> SRC.SUMMARKUP OR TGT.SUMMARKUPMST <> SRC.SUMMARKUPMST OR TGT.SUMTAX <> SRC.SUMTAX OR TGT.SUMTAXMST <> SRC.SUMTAXMST)
  THEN UPDATE SET TGT.ORDERACCOUNT = SRC.ORDERACCOUNT, TGT.INVOICEACCOUNT = SRC.INVOICEACCOUNT, TGT.LEDGERVOUCHER = SRC.LEDGERVOUCHER, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.DLVTERM = SRC.DLVTERM, TGT.DLVCOUNTRYREGIONID = SRC.DLVCOUNTRYREGIONID, TGT.RETURNREASONCODEID = SRC.RETURNREASONCODEID, TGT.INVOICETYPE = SRC.INVOICETYPE, TGT.NPOPROJECTCODE = SRC.NPOPROJECTCODE, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.EXCHRATE = SRC.EXCHRATE, TGT.INVOICEAMOUNT = SRC.INVOICEAMOUNT, TGT.INVOICEAMOUNTMST = SRC.INVOICEAMOUNTMST, TGT.SALESBALANCE = SRC.SALESBALANCE, TGT.SALESBALANCEMST = SRC.SALESBALANCEMST, TGT.SUMMARKUP = SRC.SUMMARKUP, TGT.SUMMARKUPMST = SRC.SUMMARKUPMST, TGT.SUMTAX = SRC.SUMTAX, TGT.SUMTAXMST = SRC.SUMTAXMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVOICEDATE, INVOICEID, SALESID, NUMBERSEQUENCEGROUP, RECID, ORDERACCOUNT, INVOICEACCOUNT, LEDGERVOUCHER, DIMENSION, DIMENSION2_, DIMENSION3_, DLVTERM, DLVCOUNTRYREGIONID, RETURNREASONCODEID, INVOICETYPE, NPOPROJECTCODE, DIMENSION4_, DIMENSION5_, DIMENSION6_, CURRENCYCODE, EXCHRATE, INVOICEAMOUNT, INVOICEAMOUNTMST, SALESBALANCE, SALESBALANCEMST, SUMMARKUP, SUMMARKUPMST, SUMTAX, SUMTAXMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTINVOICEJOUR_FattureCliente' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVOICEDATE = ' + CAST(COALESCE(inserted.INVOICEDATE, deleted.INVOICEDATE) AS NVARCHAR) + ' - ' + 'INVOICEID = ' + CAST(COALESCE(inserted.INVOICEID, deleted.INVOICEID) AS NVARCHAR) + ' - ' + 'SALESID = ' + CAST(COALESCE(inserted.SALESID, deleted.SALESID) AS NVARCHAR) + ' - ' + 'NUMBERSEQUENCEGROUP = ' + CAST(COALESCE(inserted.NUMBERSEQUENCEGROUP, deleted.NUMBERSEQUENCEGROUP) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

