
CREATE PROCEDURE AX2009.usp_AddIndexes_WMSTRANSPORT_TrasportiPallet
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WMSTRANSPORT_TrasportiPallet_ ON AX2009.WMSTRANSPORT_TrasportiPallet () INCLUDE();

END;
GO

