
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro
AS
BEGIN
SET NOCOUNT ON;

CREATE UNIQUE NONCLUSTERED INDEX IX_AX2009_NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro_DATAAREAID_PRODID_FILTERED ON AX2009.NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro (DATAAREAID, PRODID) WHERE PRODID <> N'';

END;
GO

