
CREATE PROCEDURE AX2009.usp_AddIndexes_WORKCALENDARDATE_DataLavorativa
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WORKCALENDARDATE_DataLavorativa_ ON AX2009.WORKCALENDARDATE_DataLavorativa () INCLUDE();

END;
GO

