
CREATE PROCEDURE AX2009.usp_AddIndexes_SMMBUSSECTORGROUP_SettoreCommerciale
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SMMBUSSECTORGROUP_SettoreCommerciale_ ON AX2009.SMMBUSSECTORGROUP_SettoreCommerciale () INCLUDE();

END;
GO

