
CREATE PROCEDURE AX2009.usp_Merge_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPBAFINISHINGLEADTIME_LeadTimeFinitura', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura;
    EXEC AX2009.usp_AddIndexes_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura;
END;

MERGE INTO AX2009.NPOPBAFINISHINGLEADTIME_LeadTimeFinitura AS TGT
USING AX2009.NPOPBAFINISHINGLEADTIME_LeadTimeFinituraView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.FINISHINGID = TGT.FINISHINGID AND SRC.SECTORTYPE = TGT.SECTORTYPE AND SRC.VENDACCOUNT = TGT.VENDACCOUNT
WHEN MATCHED AND (TGT.LEADTIME <> SRC.LEADTIME OR TGT.STOCKMANAGEDITEM <> SRC.STOCKMANAGEDITEM)
  THEN UPDATE SET TGT.LEADTIME = SRC.LEADTIME, TGT.STOCKMANAGEDITEM = SRC.STOCKMANAGEDITEM
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, FINISHINGID, SECTORTYPE, VENDACCOUNT, RECID, LEADTIME, STOCKMANAGEDITEM)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOPBAFINISHINGLEADTIME_LeadTimeFinitura' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'FINISHINGID = ' + CAST(COALESCE(inserted.FINISHINGID, deleted.FINISHINGID) AS NVARCHAR) + ' - ' + 'SECTORTYPE = ' + CAST(COALESCE(inserted.SECTORTYPE, deleted.SECTORTYPE) AS NVARCHAR) + ' - ' + 'VENDACCOUNT = ' + CAST(COALESCE(inserted.VENDACCOUNT, deleted.VENDACCOUNT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

