
CREATE PROCEDURE AX2009.usp_Merge_DLVMODE_ModalitaConsegna
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DLVMODE_ModalitaConsegna', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_DLVMODE_ModalitaConsegna;
    EXEC AX2009.usp_AddIndexes_DLVMODE_ModalitaConsegna;
END;

MERGE INTO AX2009.DLVMODE_ModalitaConsegna AS TGT
USING AX2009.DLVMODE_ModalitaConsegnaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CODE = TGT.CODE
WHEN MATCHED AND (TGT.TXT <> SRC.TXT OR TGT.SHIPCARRIERID <> SRC.SHIPCARRIERID OR TGT.INTRASTATTRANSPORTID <> SRC.INTRASTATTRANSPORTID OR TGT.NPOJOURNEYEXTRAITEMID <> SRC.NPOJOURNEYEXTRAITEMID OR TGT.NPOJOURNEYITEMID <> SRC.NPOJOURNEYITEMID OR TGT.NPOJOURNEYPRICEGROUP <> SRC.NPOJOURNEYPRICEGROUP)
  THEN UPDATE SET TGT.TXT = SRC.TXT, TGT.SHIPCARRIERID = SRC.SHIPCARRIERID, TGT.INTRASTATTRANSPORTID = SRC.INTRASTATTRANSPORTID, TGT.NPOJOURNEYEXTRAITEMID = SRC.NPOJOURNEYEXTRAITEMID, TGT.NPOJOURNEYITEMID = SRC.NPOJOURNEYITEMID, TGT.NPOJOURNEYPRICEGROUP = SRC.NPOJOURNEYPRICEGROUP
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CODE, RECID, TXT, SHIPCARRIERID, INTRASTATTRANSPORTID, NPOJOURNEYEXTRAITEMID, NPOJOURNEYITEMID, NPOJOURNEYPRICEGROUP)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.DLVMODE_ModalitaConsegna' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CODE = ' + CAST(COALESCE(inserted.CODE, deleted.CODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

