
CREATE PROCEDURE AX2009.usp_Create_SMMBUSSECTORGROUP_SettoreCommerciale
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SMMBUSSECTORGROUP_SettoreCommerciale (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    BUSINESSSECTORID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DESCRIPTION        NVARCHAR(255) NOT NULL


    -- Constraint
    CONSTRAINT PK_SMMBUSSECTORGROUP_SettoreCommerciale PRIMARY KEY CLUSTERED (
        DATAAREAID,
        BUSINESSSECTORID
    )
);

END;
GO

