
CREATE PROCEDURE AX2009.usp_Merge_CUSTGROUP_ClienteGruppo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTGROUP_ClienteGruppo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTGROUP_ClienteGruppo;
	EXEC AX2009.usp_AddIndexes_CUSTGROUP_ClienteGruppo;
END;

MERGE INTO AX2009.CUSTGROUP_ClienteGruppo AS TGT
USING AX2009.CUSTGROUP_ClienteGruppoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CUSTGROUP = TGT.CUSTGROUP
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CUSTGROUP, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTGROUP_ClienteGruppo' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CUSTGROUP = ' + CAST(COALESCE(inserted.CUSTGROUP, deleted.CUSTGROUP) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

