
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPBAFINISHING_Finitura
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPBAFINISHING_Finitura_ ON AX2009.NPOPBAFINISHING_Finitura () INCLUDE();

END;
GO

