
CREATE PROCEDURE AX2009.usp_Create_NPOPBAFINISHINGRELATION_FinituraAttributo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPBAFINISHINGRELATION_FinituraAttributo (
	-- Chiavi
	FINISHINGID		NVARCHAR(10) NOT NULL,
	IDDETAIL		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DETAILDESCRIPTION		NVARCHAR(60) NOT NULL,
	DETAILLEVEL		INT NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOPBAFINISHINGRELATION_FinituraAttributo PRIMARY KEY CLUSTERED (
		FINISHINGID,
		IDDETAIL,
		RECID
	)
);

END;
GO

