
CREATE PROCEDURE AX2009.usp_AddIndexes_RETURNREASONCODE_MotivoReso
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_RETURNREASONCODE_MotivoReso_ ON AX2009.RETURNREASONCODE_MotivoReso () INCLUDE();

END;
GO

