
CREATE PROCEDURE AX2009.usp_AddIndexes_WMSSHIPMENT_Spedizioni
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WMSSHIPMENT_Spedizioni_ ON AX2009.WMSSHIPMENT_Spedizioni () INCLUDE();

END;
GO

