
CREATE PROCEDURE AX2009.usp_Create_VENDINVOICEJOUR_FattureFornitore
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.VENDINVOICEJOUR_FattureFornitore (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PURCHID		NVARCHAR(20) NOT NULL,
	INVOICEID		NVARCHAR(20) NOT NULL,
	INVOICEDATE		DATE NOT NULL,
	NUMBERSEQUENCEGROUP		NVARCHAR(10) NOT NULL,
	INTERNALINVOICEID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ORDERACCOUNT		NVARCHAR(20) NOT NULL,
	INVOICEACCOUNT		NVARCHAR(20) NOT NULL,
	LEDGERVOUCHER		NVARCHAR(20) NOT NULL,

	-- Misure
	CURRENCYCODE		NVARCHAR(3) NOT NULL,
	EXCHRATE		NUMERIC(28, 12) NOT NULL,
	INVOICEAMOUNT		NUMERIC(28, 12) NOT NULL,
	INVOICEAMOUNTMST		NUMERIC(28, 12) NOT NULL,
	SALESBALANCE		NUMERIC(28, 12) NOT NULL,
	SUMMARKUP		NUMERIC(28, 12) NOT NULL,
	SUMMARKUPMST		NUMERIC(28, 12) NOT NULL,
	SUMTAX		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_VENDINVOICEJOUR_FattureFornitore PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PURCHID,
		INVOICEID,
		INVOICEDATE,
		NUMBERSEQUENCEGROUP,
		INTERNALINVOICEID
	)
);

END;
GO

