
CREATE PROCEDURE AX2009.usp_Create_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PBAFINISHINGID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ITEMPRICEGROUPID		NVARCHAR(10) NOT NULL,
	REVITEMID		NVARCHAR(20) NOT NULL,
	ITEMTYPE		NVARCHAR(20) NOT NULL,
	NCEREFERENCEITEMID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PBAFINISHINGID,
		RECID
	)
);

END;
GO

