
CREATE PROCEDURE AX2009.usp_Merge_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard;
	EXEC AX2009.usp_AddIndexes_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard;
END;

MERGE INTO AX2009.METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard AS TGT
USING AX2009.METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandardView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID
WHEN MATCHED AND (TGT.ANODIZINGCLASS <> SRC.ANODIZINGCLASS)
  THEN UPDATE SET TGT.ANODIZINGCLASS = SRC.ANODIZINGCLASS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, RECID, ANODIZINGCLASS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

