
CREATE PROCEDURE AX2009.usp_Merge_PAYMTERM_TerminiPagamento
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PAYMTERM_TerminiPagamento', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_PAYMTERM_TerminiPagamento;
	EXEC AX2009.usp_AddIndexes_PAYMTERM_TerminiPagamento;
END;

MERGE INTO AX2009.PAYMTERM_TerminiPagamento AS TGT
USING AX2009.PAYMTERM_TerminiPagamentoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PAYMTERMID = TGT.PAYMTERMID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION OR TGT.NUMOFMONTHS <> SRC.NUMOFMONTHS)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION, TGT.NUMOFMONTHS = SRC.NUMOFMONTHS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PAYMTERMID, RECID, DESCRIPTION, NUMOFMONTHS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.PAYMTERM_TerminiPagamento' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PAYMTERMID = ' + CAST(COALESCE(inserted.PAYMTERMID, deleted.PAYMTERMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

