
CREATE PROCEDURE AX2009.usp_Create_PRICEDISCGROUP_GruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.PRICEDISCGROUP_GruppoPrezzi (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	MODULE		INT NOT NULL,
	GROUPID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_PRICEDISCGROUP_GruppoPrezzi PRIMARY KEY CLUSTERED (
		DATAAREAID,
		MODULE,
		GROUPID
	)
);

END;
GO

