
CREATE PROCEDURE AX2009.usp_Merge_REQITEMTABLE_CoperturaArticoli
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.REQITEMTABLE_CoperturaArticoli', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_REQITEMTABLE_CoperturaArticoli;
	EXEC AX2009.usp_AddIndexes_REQITEMTABLE_CoperturaArticoli;
END;

MERGE INTO AX2009.REQITEMTABLE_CoperturaArticoli AS TGT
USING AX2009.REQITEMTABLE_CoperturaArticoliView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.MININVENTONHAND <> SRC.MININVENTONHAND OR TGT.LEADTIMEPURCHASE <> SRC.LEADTIMEPURCHASE OR TGT.REQGROUPID <> SRC.REQGROUPID OR TGT.INVENTLOCATIONIDREQMAIN <> SRC.INVENTLOCATIONIDREQMAIN OR TGT.LEADTIMEPURCHASEACTIVE <> SRC.LEADTIMEPURCHASEACTIVE)
  THEN UPDATE SET TGT.MININVENTONHAND = SRC.MININVENTONHAND, TGT.LEADTIMEPURCHASE = SRC.LEADTIMEPURCHASE, TGT.REQGROUPID = SRC.REQGROUPID, TGT.INVENTLOCATIONIDREQMAIN = SRC.INVENTLOCATIONIDREQMAIN, TGT.LEADTIMEPURCHASEACTIVE = SRC.LEADTIMEPURCHASEACTIVE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, RECID, MININVENTONHAND, LEADTIMEPURCHASE, REQGROUPID, INVENTLOCATIONIDREQMAIN, LEADTIMEPURCHASEACTIVE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.REQITEMTABLE_CoperturaArticoli' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

