CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTCONFIRMJOUR_ConfermaOrdineCliente
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_CUSTCONFIRMJOUR_ConfermaOrdineCliente_DATAAREAID_SALESID ON AX2009.CUSTCONFIRMJOUR_ConfermaOrdineCliente (DATAAREAID, SALESID) INCLUDE(CONFIRMDATE);

END;
GO

