
CREATE PROCEDURE AX2009.usp_Merge_COMMISSIONSALESREP_Agente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.COMMISSIONSALESREP_Agente', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_COMMISSIONSALESREP_Agente;
	EXEC AX2009.usp_AddIndexes_COMMISSIONSALESREP_Agente;
END;

MERGE INTO AX2009.COMMISSIONSALESREP_Agente AS TGT
USING AX2009.COMMISSIONSALESREP_AgenteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.GROUPID = TGT.GROUPID AND SRC.EMPLID = TGT.EMPLID
--WHEN MATCHED AND ()
--  THEN UPDATE SET 
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, GROUPID, EMPLID, RECID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.COMMISSIONSALESREP_Agente' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'GROUPID = ' + CAST(COALESCE(inserted.GROUPID, deleted.GROUPID) AS NVARCHAR) + ' - ' + 'EMPLID = ' + CAST(COALESCE(inserted.EMPLID, deleted.EMPLID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

