
CREATE PROCEDURE AX2009.usp_Create_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PAINTFINISHINGID        NVARCHAR(10) NOT NULL,
    WMSLOCATIONID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL

    -- Dimensioni


    -- Constraint
    CONSTRAINT PK_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PAINTFINISHINGID,
        WMSLOCATIONID
    )
);

END;
GO

