
CREATE PROCEDURE [AX2009].[usp_Create_NPOWORKCALENDARDATELINE_DataLavorativa_Turno]
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOWORKCALENDARDATELINE_DataLavorativa_Turno (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSDATE		DATE NOT NULL,
	CALENDARID		NVARCHAR(10) NOT NULL,
	SHIFTID		NVARCHAR(2) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DURATION		INT NOT NULL,
	FROMTIME		INT NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOWORKCALENDARDATELINE_DataLavorativa_Turno PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSDATE,
		CALENDARID,
		SHIFTID
	)
);

END;
GO

