
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice_ ON AX2009.NPOWRKCTRSETUPTABLE_CentroDiLavoroDatiMatrice () INCLUDE();

END;
GO

