
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione_ ON AX2009.CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione () INCLUDE();

END;
GO

