
CREATE PROCEDURE AX2009.usp_AddIndexes_PURCHPOOL_PoolAcquisti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_PURCHPOOL_PoolAcquisti_ ON AX2009.PURCHPOOL_PoolAcquisti () INCLUDE();

END;
GO

