
CREATE PROCEDURE [AX2009].[usp_Create_WORKCALENDARDATE_DataLavorativa]
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.WORKCALENDARDATE_DataLavorativa (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSDATE		DATE NOT NULL,
	CALENDARID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	WORKTIMECONTROL		SMALLINT NOT NULL


	-- Constraint
	CONSTRAINT PK_WORKCALENDARDATE_DataLavorativa PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CALENDARID,
		TRANSDATE
	)
);

END;
GO

