
CREATE PROCEDURE AX2009.usp_Create_NPOWORKSTATION_PostazioneDiLavoro
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOWORKSTATION_PostazioneDiLavoro (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    WORKSTATIONID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    WMSLOCATIONID        NVARCHAR(10) NOT NULL,
    EMPLID        NVARCHAR(20) NOT NULL,
    INVENTLOCATIONID        NVARCHAR(10) NOT NULL,
    WRKCTRID        NVARCHAR(10) NOT NULL,
    GROUPWRKCTRID        NVARCHAR(10) NOT NULL,
    AREAID        NVARCHAR(25) NOT NULL,
    INVENTSITEID        NVARCHAR(10) NOT NULL,
    WORKSTATIONNAME        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_NPOWORKSTATION_PostazioneDiLavoro PRIMARY KEY CLUSTERED (
        DATAAREAID,
        WORKSTATIONID,
        RECID
    )
);

END;
GO

