
CREATE PROCEDURE AX2009.usp_Create_TIMEZONESLIST_FusoOrario
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.TIMEZONESLIST_FusoOrario (
	-- Chiavi
	TZENUM		INT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TIMEZONEKEYNAME		NVARCHAR(64) NOT NULL,
	ENUMNAME		NVARCHAR(64) NOT NULL


	-- Constraint
	CONSTRAINT PK_TIMEZONESLIST_FusoOrario PRIMARY KEY CLUSTERED (
		TZENUM
	)
);

END;
GO

