
CREATE PROCEDURE AX2009.usp_Create_INVENTDIM_DimensioneInventariale
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTDIM_DimensioneInventariale (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	INVENTDIMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	WMSLOCATIONID		NVARCHAR(10) NOT NULL,
	WMSPALLETID		NVARCHAR(18) NOT NULL,
	INVENTLOCATIONID		NVARCHAR(10) NOT NULL,
	INVENTSIZEID		NVARCHAR(10) NOT NULL,
	INVENTCOLORID		NVARCHAR(10) NOT NULL,
	INVENTSITEID		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTDIM_DimensioneInventariale PRIMARY KEY CLUSTERED (
		DATAAREAID,
		INVENTDIMID
	)
);

END;
GO

