
CREATE PROCEDURE AX2009.usp_Create_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	INVENTITEMTYPE		NVARCHAR(20) NOT NULL,
	FROMDATE		DATE NOT NULL,
	FILTERCODE		SMALLINT NOT NULL,
	CUSTACCOUNT		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	PRICEPERUNIT		NUMERIC(28, 12) NOT NULL,
	PRICEPERSECONDUNIT		NUMERIC(28, 12) NOT NULL


	-- Constraint
	CONSTRAINT PK_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking PRIMARY KEY CLUSTERED (
		DATAAREAID,
		INVENTITEMTYPE,
		FROMDATE,
		FILTERCODE,
		CUSTACCOUNT
	)
);

END;
GO

