
CREATE PROCEDURE AX2009.usp_AddIndexes_METSALESCREDITREASONTABLE_CausaleFido
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METSALESCREDITREASONTABLE_CausaleFido_ ON AX2009.METSALESCREDITREASONTABLE_CausaleFido () INCLUDE();

END;
GO

