
CREATE PROCEDURE AX2009.usp_Create_INVENTTRANSFERTABLE_OrdiniTrasferimento
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTTRANSFERTABLE_OrdiniTrasferimento (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSFERID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	INVENTLOCATIONIDFROM		NVARCHAR(10) NOT NULL,
	INVENTLOCATIONIDTO		NVARCHAR(10) NOT NULL,
	TRANSFERSTATUS		SMALLINT NOT NULL,
	SHIPDATE		DATE NOT NULL,
	RECEIVEDATE		DATE NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTTRANSFERTABLE_OrdiniTrasferimento PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSFERID
	)
);

END;
GO

