
CREATE PROCEDURE AX2009.usp_Merge_INVENTTRANSFERJOUR_OrdiniTrasferimento
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTTRANSFERJOUR_OrdiniTrasferimento', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTTRANSFERJOUR_OrdiniTrasferimento;
	EXEC AX2009.usp_AddIndexes_INVENTTRANSFERJOUR_OrdiniTrasferimento;
END;

MERGE INTO AX2009.INVENTTRANSFERJOUR_OrdiniTrasferimento AS TGT
USING AX2009.INVENTTRANSFERJOUR_OrdiniTrasferimentoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSFERID = TGT.TRANSFERID AND SRC.VOUCHERID = TGT.VOUCHERID
WHEN MATCHED AND (TGT.TRANSDATE <> SRC.TRANSDATE OR TGT.TOADDRESSCOUNTY <> SRC.TOADDRESSCOUNTY OR TGT.TOADDRESSSTATE <> SRC.TOADDRESSSTATE OR TGT.TOADDRESSCOUNTRYREGIONID <> SRC.TOADDRESSCOUNTRYREGIONID OR TGT.UPDATETYPE <> SRC.UPDATETYPE OR TGT.NPOINVENTPACKINGSLIPID <> SRC.NPOINVENTPACKINGSLIPID)
  THEN UPDATE SET TGT.TRANSDATE = SRC.TRANSDATE, TGT.TOADDRESSCOUNTY = SRC.TOADDRESSCOUNTY, TGT.TOADDRESSSTATE = SRC.TOADDRESSSTATE, TGT.TOADDRESSCOUNTRYREGIONID = SRC.TOADDRESSCOUNTRYREGIONID, TGT.UPDATETYPE = SRC.UPDATETYPE, TGT.NPOINVENTPACKINGSLIPID = SRC.NPOINVENTPACKINGSLIPID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSFERID, VOUCHERID, RECID, TRANSDATE, TOADDRESSCOUNTY, TOADDRESSSTATE, TOADDRESSCOUNTRYREGIONID, UPDATETYPE, NPOINVENTPACKINGSLIPID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTTRANSFERJOUR_OrdiniTrasferimento' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSFERID = ' + CAST(COALESCE(inserted.TRANSFERID, deleted.TRANSFERID) AS NVARCHAR) + ' - ' + 'VOUCHERID = ' + CAST(COALESCE(inserted.VOUCHERID, deleted.VOUCHERID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

