
CREATE PROCEDURE AX2009.usp_Merge_EXCHRATES_TassiDiCambio
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.EXCHRATES_TassiDiCambio', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_EXCHRATES_TassiDiCambio;
	EXEC AX2009.usp_AddIndexes_EXCHRATES_TassiDiCambio;
END;

--MERGE INTO AX2009.EXCHRATES_TassiDiCambio AS TGT
--USING AX2009.EXCHRATES_TassiDiCambioView (nolock) AS SRC
--ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CURRENCYCODE = TGT.CURRENCYCODE AND SRC.FROMDATE = TGT.FROMDATE
--WHEN MATCHED AND (TGT.TODATE <> SRC.TODATE OR TGT.EXCHRATE <> SRC.EXCHRATE)
--  THEN UPDATE SET TGT.TODATE = SRC.TODATE, TGT.EXCHRATE = SRC.EXCHRATE
--WHEN NOT MATCHED
--  THEN INSERT VALUES (DATAAREAID, CURRENCYCODE, FROMDATE, RECID, TODATE, EXCHRATE)
--WHEN NOT MATCHED BY SOURCE
--  THEN DELETE
--OUTPUT
--	CURRENT_TIMESTAMP AS merge_datetime,
--	$action AS merge_action,
--	'AX2009.EXCHRATES_TassiDiCambio' AS full_olap_table_name,
--	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CURRENCYCODE = ' + CAST(COALESCE(inserted.CURRENCYCODE, deleted.CURRENCYCODE) AS NVARCHAR) + ' - ' + 'FROMDATE = ' + CAST(COALESCE(inserted.FROMDATE, deleted.FROMDATE) AS NVARCHAR) AS primary_key_description
--INTO audit.merge_log_details;

WITH EXCHRATES_TassiDiCambio_filtered
AS (
	SELECT *
	FROM AX2009.EXCHRATES_TassiDiCambio
	WHERE FROMDATE >= '20120712'
)
MERGE INTO EXCHRATES_TassiDiCambio_filtered AS TGT
USING (
	SELECT *
	FROM AX2009.EXCHRATES_TassiDiCambioView (nolock)
	WHERE FROMDATE >= '20120712'
) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CURRENCYCODE = TGT.CURRENCYCODE AND SRC.FROMDATE = TGT.FROMDATE
WHEN MATCHED AND (TGT.TODATE <> SRC.TODATE OR TGT.EXCHRATE <> SRC.EXCHRATE)
  THEN UPDATE SET TGT.TODATE = SRC.TODATE, TGT.EXCHRATE = SRC.EXCHRATE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CURRENCYCODE, FROMDATE, RECID, TODATE, EXCHRATE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.EXCHRATES_TassiDiCambio' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CURRENCYCODE = ' + CAST(COALESCE(inserted.CURRENCYCODE, deleted.CURRENCYCODE) AS NVARCHAR) + ' - ' + 'FROMDATE = ' + CAST(COALESCE(inserted.FROMDATE, deleted.FROMDATE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

