
CREATE PROCEDURE AX2009.usp_AddIndexes_DIMENSIONS_DimensioneContabile
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DIMENSIONS_DimensioneContabile_ ON AX2009.DIMENSIONS_DimensioneContabile () INCLUDE();

END;
GO

