
CREATE PROCEDURE AX2009.usp_Create_CUSTINVOICEJOUR_FattureCliente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTINVOICEJOUR_FattureCliente (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    INVOICEDATE        DATE NOT NULL,
    INVOICEID        NVARCHAR(20) NOT NULL,
    SALESID        NVARCHAR(20) NOT NULL,
    NUMBERSEQUENCEGROUP        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    ORDERACCOUNT        NVARCHAR(20) NOT NULL,
    INVOICEACCOUNT        NVARCHAR(20) NOT NULL,
    LEDGERVOUCHER        NVARCHAR(20) NOT NULL,
    DIMENSION        NVARCHAR(10) NOT NULL,
    DIMENSION2_        NVARCHAR(10) NOT NULL,
    DIMENSION3_        NVARCHAR(10) NOT NULL,
    DLVTERM        NVARCHAR(10) NOT NULL,
    DLVCOUNTRYREGIONID        NVARCHAR(10) NOT NULL,
    RETURNREASONCODEID        NVARCHAR(10) NOT NULL,
    INVOICETYPE        SMALLINT NOT NULL,
    NPOPROJECTCODE        NVARCHAR(40) NOT NULL,
    DIMENSION4_        NVARCHAR(10) NOT NULL,
    DIMENSION5_        NVARCHAR(10) NOT NULL,
    DIMENSION6_        NVARCHAR(10) NOT NULL,

    -- Misure
    CURRENCYCODE        NVARCHAR(3) NOT NULL,
    EXCHRATE        NUMERIC(28, 12) NOT NULL,
    INVOICEAMOUNT        NUMERIC(28, 12) NOT NULL,
    INVOICEAMOUNTMST        NUMERIC(28, 12) NOT NULL,
    SALESBALANCE        NUMERIC(28, 12) NOT NULL,
    SALESBALANCEMST        NUMERIC(28, 12) NOT NULL,
    SUMMARKUP        NUMERIC(28, 12) NOT NULL,
    SUMMARKUPMST        NUMERIC(28, 12) NOT NULL,
    SUMTAX        NUMERIC(28, 12) NOT NULL,
    SUMTAXMST        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_CUSTINVOICEJOUR_FattureCliente PRIMARY KEY CLUSTERED (
        DATAAREAID,
        INVOICEDATE,
        INVOICEID,
        SALESID,
        NUMBERSEQUENCEGROUP,
        RECID
    )
);

END;
GO

