
CREATE PROCEDURE AX2009.usp_Merge_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite;
	EXEC AX2009.usp_AddIndexes_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite;
END;

MERGE INTO AX2009.METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite AS TGT
USING AX2009.METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVenditeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.GROUPIDAS = TGT.GROUPIDAS
WHEN MATCHED AND (TGT.GROUPID <> SRC.GROUPID OR TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.GROUPID = SRC.GROUPID, TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, GROUPIDAS, RECID, GROUPID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'GROUPIDAS = ' + CAST(COALESCE(inserted.GROUPIDAS, deleted.GROUPIDAS) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

