
CREATE PROCEDURE AX2009.usp_Merge_ADDRESSCOUNTY_Provincia
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ADDRESSCOUNTY_Provincia', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_ADDRESSCOUNTY_Provincia;
	EXEC AX2009.usp_AddIndexes_ADDRESSCOUNTY_Provincia;
END;

MERGE INTO AX2009.ADDRESSCOUNTY_Provincia AS TGT
USING AX2009.ADDRESSCOUNTY_ProvinciaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.COUNTRYREGIONID = TGT.COUNTRYREGIONID AND SRC.STATEID = TGT.STATEID AND SRC.COUNTYID = TGT.COUNTYID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, COUNTRYREGIONID, STATEID, COUNTYID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.ADDRESSCOUNTY_Provincia' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'COUNTRYREGIONID = ' + CAST(COALESCE(inserted.COUNTRYREGIONID, deleted.COUNTRYREGIONID) AS NVARCHAR) + ' - ' + 'STATEID = ' + CAST(COALESCE(inserted.STATEID, deleted.STATEID) AS NVARCHAR) + ' - ' + 'COUNTYID = ' + CAST(COALESCE(inserted.COUNTYID, deleted.COUNTYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

