
CREATE PROCEDURE AX2009.usp_Create_EXCHRATES_TassiDiCambio
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.EXCHRATES_TassiDiCambio (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CURRENCYCODE		NVARCHAR(3) NOT NULL,
	FROMDATE		DATE NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TODATE		DATE NOT NULL,

	-- Misure
	EXCHRATE		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_EXCHRATES_TassiDiCambio PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CURRENCYCODE,
		FROMDATE
	)
);

END;
GO

