
CREATE PROCEDURE AX2009.usp_Merge_INVENTPOSTING_RegistrazioneMagazzino
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.INVENTPOSTING_RegistrazioneMagazzino', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_INVENTPOSTING_RegistrazioneMagazzino;
    EXEC AX2009.usp_AddIndexes_INVENTPOSTING_RegistrazioneMagazzino;
END;

MERGE INTO AX2009.INVENTPOSTING_RegistrazioneMagazzino AS TGT
USING AX2009.INVENTPOSTING_RegistrazioneMagazzinoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVENTACCOUNTTYPE = TGT.INVENTACCOUNTTYPE AND SRC.ITEMCODE = TGT.ITEMCODE AND SRC.ITEMRELATION = TGT.ITEMRELATION AND SRC.CUSTVENDCODE = TGT.CUSTVENDCODE AND SRC.CUSTVENDRELATION = TGT.CUSTVENDRELATION
WHEN MATCHED AND (TGT.TAXGROUPID <> SRC.TAXGROUPID OR TGT.LEDGERACCOUNTID <> SRC.LEDGERACCOUNTID OR TGT.COSTCODE <> SRC.COSTCODE OR TGT.COSTRELATION <> SRC.COSTRELATION)
  THEN UPDATE SET TGT.TAXGROUPID = SRC.TAXGROUPID, TGT.LEDGERACCOUNTID = SRC.LEDGERACCOUNTID, TGT.COSTCODE = SRC.COSTCODE, TGT.COSTRELATION = SRC.COSTRELATION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVENTACCOUNTTYPE, ITEMCODE, ITEMRELATION, CUSTVENDCODE, CUSTVENDRELATION, RECID, TAXGROUPID, LEDGERACCOUNTID, COSTCODE, COSTRELATION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.INVENTPOSTING_RegistrazioneMagazzino' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVENTACCOUNTTYPE = ' + CAST(COALESCE(inserted.INVENTACCOUNTTYPE, deleted.INVENTACCOUNTTYPE) AS NVARCHAR) + ' - ' + 'ITEMCODE = ' + CAST(COALESCE(inserted.ITEMCODE, deleted.ITEMCODE) AS NVARCHAR) + ' - ' + 'ITEMRELATION = ' + CAST(COALESCE(inserted.ITEMRELATION, deleted.ITEMRELATION) AS NVARCHAR) + ' - ' + 'CUSTVENDCODE = ' + CAST(COALESCE(inserted.CUSTVENDCODE, deleted.CUSTVENDCODE) AS NVARCHAR) + ' - ' + 'CUSTVENDRELATION = ' + CAST(COALESCE(inserted.CUSTVENDRELATION, deleted.CUSTVENDRELATION) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

