
CREATE PROCEDURE AX2009.usp_Merge_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.AIFENDPOINTCONSTRAINT_AIFEndPointConstraint', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint;
    EXEC AX2009.usp_AddIndexes_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint;
END;

MERGE INTO AX2009.AIFENDPOINTCONSTRAINT_AIFEndPointConstraint AS TGT
USING AX2009.AIFENDPOINTCONSTRAINT_AIFEndPointConstraintView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ENDPOINTID = TGT.ENDPOINTID AND SRC.CONSTRAINTID = TGT.CONSTRAINTID
WHEN MATCHED AND (TGT.CONSTRAINTTYPE <> SRC.CONSTRAINTTYPE)
  THEN UPDATE SET TGT.CONSTRAINTTYPE = SRC.CONSTRAINTTYPE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ENDPOINTID, CONSTRAINTID, RECID, CONSTRAINTTYPE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.AIFENDPOINTCONSTRAINT_AIFEndPointConstraint' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ENDPOINTID = ' + CAST(COALESCE(inserted.ENDPOINTID, deleted.ENDPOINTID) AS NVARCHAR) + ' - ' + 'CONSTRAINTID = ' + CAST(COALESCE(inserted.CONSTRAINTID, deleted.CONSTRAINTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

