

CREATE PROCEDURE AX2009.usp_Create_METVENDPROJECT_CommessaFornitore
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METVENDPROJECT_CommessaFornitore (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    VENDACCOUNT        NVARCHAR(20) NOT NULL,
    VENDPROJECTID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    ENABLECUSTPROJECT        BIT NOT NULL,
    DOCUMENTDESCRIPTION        NVARCHAR(70) NOT NULL,
    REQUESTDATE        DATE NOT NULL,
    CUSTACCOUNT        NVARCHAR(20) NOT NULL,
    DATEEND        DATE NOT NULL,
    DATESTART        DATE NOT NULL,
    SUPPLYTYPE        SMALLINT NOT NULL,

    -- Misure
    UNITID        NVARCHAR(10) NOT NULL,
    TOTALQTY        NUMERIC(28, 12) NOT NULL,
    CURRENCYCODE        NVARCHAR(3) NOT NULL,
    METALCOVERPRICE        NUMERIC(28, 12) NOT NULL,
    PRICEUNIT        NUMERIC(28, 12) NOT NULL,
    METCOVERAGETYPE        SMALLINT NOT NULL

    -- Constraint
    CONSTRAINT PK_METVENDPROJECT_CommessaFornitore PRIMARY KEY CLUSTERED (
        DATAAREAID,
        VENDACCOUNT,
        VENDPROJECTID
    )
);

END;
GO

