
CREATE PROCEDURE AX2009.usp_Merge_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOSCRAPCAUSEGROUP_GruppoCausaleScarto', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto;
	EXEC AX2009.usp_AddIndexes_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto;
END;

MERGE INTO AX2009.NPOSCRAPCAUSEGROUP_GruppoCausaleScarto AS TGT
USING AX2009.NPOSCRAPCAUSEGROUP_GruppoCausaleScartoView (nolock) AS SRC
ON SRC.SCRAPCAUSEGROUPID = TGT.SCRAPCAUSEGROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (SCRAPCAUSEGROUPID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOSCRAPCAUSEGROUP_GruppoCausaleScarto' AS full_olap_table_name,
	'SCRAPCAUSEGROUPID = ' + CAST(COALESCE(inserted.SCRAPCAUSEGROUPID, deleted.SCRAPCAUSEGROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

