
CREATE PROCEDURE AX2009.usp_Merge_WMSPICKINGROUTE_CicloPrelievo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WMSPICKINGROUTE_CicloPrelievo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_WMSPICKINGROUTE_CicloPrelievo;
	EXEC AX2009.usp_AddIndexes_WMSPICKINGROUTE_CicloPrelievo;
END;

MERGE INTO AX2009.WMSPICKINGROUTE_CicloPrelievo AS TGT
USING AX2009.WMSPICKINGROUTE_CicloPrelievoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PICKINGROUTEID = TGT.PICKINGROUTEID
WHEN MATCHED AND (TGT.EXPEDITIONSTATUS <> SRC.EXPEDITIONSTATUS OR TGT.CURRENTPICKPALLETID <> SRC.CURRENTPICKPALLETID OR TGT.NPOWORKSPACE <> SRC.NPOWORKSPACE OR TGT.NPODLVSTATIONID <> SRC.NPODLVSTATIONID OR TGT.NPOCRSNUMID <> SRC.NPOCRSNUMID)
  THEN UPDATE SET TGT.EXPEDITIONSTATUS = SRC.EXPEDITIONSTATUS, TGT.CURRENTPICKPALLETID = SRC.CURRENTPICKPALLETID, TGT.NPOWORKSPACE = SRC.NPOWORKSPACE, TGT.NPODLVSTATIONID = SRC.NPODLVSTATIONID, TGT.NPOCRSNUMID = SRC.NPOCRSNUMID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PICKINGROUTEID, RECID, EXPEDITIONSTATUS, CURRENTPICKPALLETID, NPOWORKSPACE, NPODLVSTATIONID, NPOCRSNUMID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.WMSPICKINGROUTE_CicloPrelievo' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PICKINGROUTEID = ' + CAST(COALESCE(inserted.PICKINGROUTEID, deleted.PICKINGROUTEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

