
CREATE PROCEDURE AX2009.usp_Merge_ADDRESS_Indirizzo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ADDRESS_Indirizzo', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_ADDRESS_Indirizzo;
	EXEC AX2009.usp_AddIndexes_ADDRESS_Indirizzo;
END;

MERGE INTO AX2009.ADDRESS_Indirizzo AS TGT
USING AX2009.ADDRESS_IndirizzoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ADDRTABLEID <> SRC.ADDRTABLEID OR TGT.ADDRRECID <> SRC.ADDRRECID OR TGT.TYPE <> SRC.TYPE OR TGT.NAME <> SRC.NAME OR TGT.ADDRESS <> SRC.ADDRESS OR TGT.COUNTRYREGIONID <> SRC.COUNTRYREGIONID OR TGT.ZIPCODE <> SRC.ZIPCODE OR TGT.STATE <> SRC.STATE OR TGT.COUNTY <> SRC.COUNTY OR TGT.CITY <> SRC.CITY OR TGT.STREET <> SRC.STREET)
  THEN UPDATE SET TGT.ADDRTABLEID = SRC.ADDRTABLEID, TGT.ADDRRECID = SRC.ADDRRECID, TGT.TYPE = SRC.TYPE, TGT.NAME = SRC.NAME, TGT.ADDRESS = SRC.ADDRESS, TGT.COUNTRYREGIONID = SRC.COUNTRYREGIONID, TGT.ZIPCODE = SRC.ZIPCODE, TGT.STATE = SRC.STATE, TGT.COUNTY = SRC.COUNTY, TGT.CITY = SRC.CITY, TGT.STREET = SRC.STREET
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, RECID, ADDRTABLEID, ADDRRECID, TYPE, NAME, ADDRESS, COUNTRYREGIONID, ZIPCODE, STATE, COUNTY, CITY, STREET)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.ADDRESS_Indirizzo' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

