
CREATE PROCEDURE AX2009.usp_Merge_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTBILLOFEXCHANGEJOUR_EffettiAttivi', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi;
	EXEC AX2009.usp_AddIndexes_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi;
END;

MERGE INTO AX2009.CUSTBILLOFEXCHANGEJOUR_EffettiAttivi AS TGT
USING AX2009.CUSTBILLOFEXCHANGEJOUR_EffettiAttiviView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BILLOFEXCHANGEID = TGT.BILLOFEXCHANGEID
WHEN MATCHED AND (TGT.CUSTACCOUNT <> SRC.CUSTACCOUNT OR TGT.BILLOFEXCHANGESEQNUM <> SRC.BILLOFEXCHANGESEQNUM OR TGT.STATUS <> SRC.STATUS)
  THEN UPDATE SET TGT.CUSTACCOUNT = SRC.CUSTACCOUNT, TGT.BILLOFEXCHANGESEQNUM = SRC.BILLOFEXCHANGESEQNUM, TGT.STATUS = SRC.STATUS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BILLOFEXCHANGEID, RECID, CUSTACCOUNT, BILLOFEXCHANGESEQNUM, STATUS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTBILLOFEXCHANGEJOUR_EffettiAttivi' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BILLOFEXCHANGEID = ' + CAST(COALESCE(inserted.BILLOFEXCHANGEID, deleted.BILLOFEXCHANGEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

