
CREATE PROCEDURE AX2009.usp_AddIndexes_PURCHLINE_OrdiniFornitore_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_PURCHLINE_OrdiniFornitore_Riga_ ON AX2009.PURCHLINE_OrdiniFornitore_Riga () INCLUDE();

END;
GO

