
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDGROUP_FornitoreGruppo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_VENDGROUP_FornitoreGruppo_ ON AX2009.VENDGROUP_FornitoreGruppo () INCLUDE();

END;
GO

