
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOREVENUEGROUP_GruppoRicavi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOREVENUEGROUP_GruppoRicavi_ ON AX2009.NPOREVENUEGROUP_GruppoRicavi () INCLUDE();

END;
GO

