
CREATE PROCEDURE AX2009.usp_Merge_PURCHLINE_OrdiniFornitore_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.PURCHLINE_OrdiniFornitore_Riga', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_PURCHLINE_OrdiniFornitore_Riga;
    EXEC AX2009.usp_AddIndexes_PURCHLINE_OrdiniFornitore_Riga;
END;

MERGE INTO AX2009.PURCHLINE_OrdiniFornitore_Riga AS TGT
USING AX2009.PURCHLINE_OrdiniFornitore_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PURCHID = TGT.PURCHID AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ITEMID <> SRC.ITEMID OR TGT.PURCHSTATUS <> SRC.PURCHSTATUS OR TGT.LEDGERACCOUNT <> SRC.LEDGERACCOUNT OR TGT.DELIVERYDATE <> SRC.DELIVERYDATE OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.CONFIRMEDDLV <> SRC.CONFIRMEDDLV OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.INVENTREFID <> SRC.INVENTREFID OR TGT.INVENTREFTRANSID <> SRC.INVENTREFTRANSID OR TGT.ITEMREFTYPE <> SRC.ITEMREFTYPE OR TGT.INTERCOMPANYORIGIN <> SRC.INTERCOMPANYORIGIN OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.ASSETID <> SRC.ASSETID OR TGT.INTERCOMPANYINVENTTRANSID <> SRC.INTERCOMPANYINVENTTRANSID OR TGT.NPOWRKCTRGROUPID <> SRC.NPOWRKCTRGROUPID OR TGT.NPOPURCHPRICEEXTRA <> SRC.NPOPURCHPRICEEXTRA OR TGT.NPOLISTPRICE <> SRC.NPOLISTPRICE OR TGT.NPOINTERCOMPANYORIGINALIN30008 <> SRC.NPOINTERCOMPANYORIGINALIN30008 OR TGT.NPOINTERCOMPANYORIGINALCU30009 <> SRC.NPOINTERCOMPANYORIGINALCU30009 OR TGT.NPOINTERCOMPANYORIGINALSALESID <> SRC.NPOINTERCOMPANYORIGINALSALESID OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_ OR TGT.NCEMATRIXPURCHTYPE <> SRC.NCEMATRIXPURCHTYPE OR TGT.NPOORIGINALCONFIRMEDDLV <> SRC.NPOORIGINALCONFIRMEDDLV OR TGT.PURCHUNIT <> SRC.PURCHUNIT OR TGT.PURCHQTY <> SRC.PURCHQTY OR TGT.REMAINPURCHPHYSICAL <> SRC.REMAINPURCHPHYSICAL OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.LINEAMOUNT <> SRC.LINEAMOUNT OR TGT.PURCHPRICE <> SRC.PURCHPRICE OR TGT.PRICEUNIT <> SRC.PRICEUNIT OR TGT.LINEPERCENT <> SRC.LINEPERCENT OR TGT.LINEDISC <> SRC.LINEDISC)
  THEN UPDATE SET TGT.ITEMID = SRC.ITEMID, TGT.PURCHSTATUS = SRC.PURCHSTATUS, TGT.LEDGERACCOUNT = SRC.LEDGERACCOUNT, TGT.DELIVERYDATE = SRC.DELIVERYDATE, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.CONFIRMEDDLV = SRC.CONFIRMEDDLV, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.INVENTREFID = SRC.INVENTREFID, TGT.INVENTREFTRANSID = SRC.INVENTREFTRANSID, TGT.ITEMREFTYPE = SRC.ITEMREFTYPE, TGT.INTERCOMPANYORIGIN = SRC.INTERCOMPANYORIGIN, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.ASSETID = SRC.ASSETID, TGT.INTERCOMPANYINVENTTRANSID = SRC.INTERCOMPANYINVENTTRANSID, TGT.NPOWRKCTRGROUPID = SRC.NPOWRKCTRGROUPID, TGT.NPOPURCHPRICEEXTRA = SRC.NPOPURCHPRICEEXTRA, TGT.NPOLISTPRICE = SRC.NPOLISTPRICE, TGT.NPOINTERCOMPANYORIGINALIN30008 = SRC.NPOINTERCOMPANYORIGINALIN30008, TGT.NPOINTERCOMPANYORIGINALCU30009 = SRC.NPOINTERCOMPANYORIGINALCU30009, TGT.NPOINTERCOMPANYORIGINALSALESID = SRC.NPOINTERCOMPANYORIGINALSALESID, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_, TGT.NCEMATRIXPURCHTYPE = SRC.NCEMATRIXPURCHTYPE, TGT.NPOORIGINALCONFIRMEDDLV = SRC.NPOORIGINALCONFIRMEDDLV, TGT.PURCHUNIT = SRC.PURCHUNIT, TGT.PURCHQTY = SRC.PURCHQTY, TGT.REMAINPURCHPHYSICAL = SRC.REMAINPURCHPHYSICAL, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.LINEAMOUNT = SRC.LINEAMOUNT, TGT.PURCHPRICE = SRC.PURCHPRICE, TGT.PRICEUNIT = SRC.PRICEUNIT, TGT.LINEPERCENT = SRC.LINEPERCENT, TGT.LINEDISC = SRC.LINEDISC
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PURCHID, LINENUM, RECID, ITEMID, PURCHSTATUS, LEDGERACCOUNT, DELIVERYDATE, DIMENSION, DIMENSION2_, DIMENSION3_, CONFIRMEDDLV, INVENTTRANSID, INVENTREFID, INVENTREFTRANSID, ITEMREFTYPE, INTERCOMPANYORIGIN, INVENTDIMID, ASSETID, INTERCOMPANYINVENTTRANSID, NPOWRKCTRGROUPID, NPOPURCHPRICEEXTRA, NPOLISTPRICE, NPOINTERCOMPANYORIGINALIN30008, NPOINTERCOMPANYORIGINALCU30009, NPOINTERCOMPANYORIGINALSALESID, DIMENSION4_, DIMENSION5_, DIMENSION6_, NCEMATRIXPURCHTYPE, NPOORIGINALCONFIRMEDDLV, PURCHUNIT, PURCHQTY, REMAINPURCHPHYSICAL, CURRENCYCODE, LINEAMOUNT, PURCHPRICE, PRICEUNIT, LINEPERCENT, LINEDISC)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.PURCHLINE_OrdiniFornitore_Riga' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PURCHID = ' + CAST(COALESCE(inserted.PURCHID, deleted.PURCHID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

