
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTRANS_Transazioni
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTRANS_Transazioni_TRANSTYPE_TRANSREFID_DATEFINANCIAL_INVOICEID_INCLUDE ON [AX2009].[INVENTTRANS_Transazioni] ([TRANSTYPE],[TRANSREFID],[DATEFINANCIAL],[INVOICEID]) INCLUDE ([QTY],[NPOINVENTQTYPHYSICALONHAND2UM]);

END;
GO

