
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTXT_ArticoloTraduzione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTXT_ArticoloTraduzione_ ON AX2009.INVENTTXT_ArticoloTraduzione () INCLUDE();

END;
GO

