
CREATE PROCEDURE AX2009.usp_AddIndexes_LEDGERTRANS_TransazioniContabili
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_LEDGERTRANS_TransazioniContabili_ ON AX2009.LEDGERTRANS_TransazioniContabili () INCLUDE();

END;
GO

