
CREATE PROCEDURE AX2009.usp_Create_CUSTTABLE_Cliente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTTABLE_Cliente (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    ACCOUNTNUM        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    NAME        NVARCHAR(60) NOT NULL,
    CUSTGROUP        NVARCHAR(10) NOT NULL,
    LINEDISC        NVARCHAR(10) NOT NULL,
    PAYMTERMID        NVARCHAR(10) NOT NULL,
    CASHDISC        NVARCHAR(10) NOT NULL,
    SALESGROUP        NVARCHAR(10) NOT NULL,
    BLOCKED        SMALLINT NOT NULL,
    VATNUM        NVARCHAR(20) NOT NULL,
    COUNTRYREGIONID        NVARCHAR(10) NOT NULL,
    STATE        NVARCHAR(10) NOT NULL,
    COUNTY        NVARCHAR(10) NOT NULL,
    STATISTICSGROUP        NVARCHAR(10) NOT NULL,
    PAYMMODE        NVARCHAR(10) NOT NULL,
    SALESPOOLID        NVARCHAR(10) NOT NULL,
    CITY        NVARCHAR(60) NOT NULL,
    FISCALCODE        NVARCHAR(16) NOT NULL,
    CUSTCLASSIFICATIONID        NVARCHAR(10) NOT NULL,
    PARTYTYPE        INT NOT NULL,
    PARTYID        NVARCHAR(20) NOT NULL,
    SALESDISTRICTID        NVARCHAR(20) NOT NULL,
    SEGMENTID        NVARCHAR(20) NOT NULL,
    SUBSEGMENTID        NVARCHAR(20) NOT NULL,
    MAINCONTACTID        NVARCHAR(20) NOT NULL,
    NPOCUSTGROUPID        NVARCHAR(10) NOT NULL,

    -- Misure
    CreatedDate        DATE NOT NULL

    -- Constraint
    CONSTRAINT PK_CUSTTABLE_Cliente PRIMARY KEY CLUSTERED (
        DATAAREAID,
        ACCOUNTNUM
    )
);

END;
GO

