
CREATE PROCEDURE AX2009.usp_AddIndexes_ROUTEOPR_RelazioneOperativa
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_ROUTEOPR_RelazioneOperativa_DATAAREAID_ITEMRELATION_ROUTECODE_ROUTERELATION ON [AX2009].[ROUTEOPR_RelazioneOperativa] ([DATAAREAID],[ITEMRELATION],[ROUTECODE],[ROUTERELATION]) INCLUDE ([OPRID],[WRKCTRID]);

END;
GO

