
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOBICOLORWEBSETUP_FinituraBicolore
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOBICOLORWEBSETUP_FinituraBicolore_ ON AX2009.NPOBICOLORWEBSETUP_FinituraBicolore () INCLUDE();

END;
GO

