
CREATE PROCEDURE AX2009.usp_Create_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.FDY_DOCF_FINANCIALVOICE_VoceFinanziaria (
    -- Chiavi
    FDY_DOCF_VOCEFINANZIARIA        NVARCHAR(6) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    DESCRIPTION        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria PRIMARY KEY CLUSTERED (
        FDY_DOCF_VOCEFINANZIARIA
    )
);

END;
GO

