
CREATE PROCEDURE AX2009.usp_Create_INVENTTABLEMODULE_ArticoloUnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTTABLEMODULE_ArticoloUnitaDiMisura (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	MODULETYPE		SMALLINT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	UNITID		NVARCHAR(10) NOT NULL,
	PRICE		NUMERIC(28, 12) NOT NULL,
	PRICEUNIT		NUMERIC(28, 12) NOT NULL,
	MARKUP		NUMERIC(28, 12) NOT NULL,
	PRICEQTY		NUMERIC(28, 12) NOT NULL,
	NPOSECONDINVENTUNITID		NVARCHAR(10) NOT NULL,
	NPOSECONDUNITACTIVE		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTTABLEMODULE_ArticoloUnitaDiMisura PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		MODULETYPE
	)
);

END;
GO

