
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTITEMPURCHSETUP_ArticoloImpostazioniAcquisto
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTITEMPURCHSETUP_ArticoloImpostazioniAcquisto_ ON AX2009.INVENTITEMPURCHSETUP_ArticoloImpostazioniAcquisto () INCLUDE();

END;
GO

