
CREATE PROCEDURE AX2009.usp_AddIndexes_ADDRESSSTATE_Regione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ADDRESSSTATE_Regione_ ON AX2009.ADDRESSSTATE_Regione () INCLUDE();

END;
GO

