
CREATE PROCEDURE AX2009.usp_AddIndexes_DLVTERM_TerminiConsegna
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DLVTERM_TerminiConsegna_ ON AX2009.DLVTERM_TerminiConsegna () INCLUDE();

END;
GO

