
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOITEMSUBFAMILIES_SottofamigliaArticolo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOITEMSUBFAMILIES_SottofamigliaArticolo_ ON AX2009.NPOITEMSUBFAMILIES_SottofamigliaArticolo () INCLUDE();

END;
GO

