
CREATE PROCEDURE AX2009.usp_AddIndexes_DATAAREA_Azienda
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DATAAREA_Azienda_ ON AX2009.DATAAREA_Azienda () INCLUDE();

END;
GO

