
CREATE PROCEDURE AX2009.usp_AddIndexes_WORKCALENDARDATELINE_DataLavorativa_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_WORKCALENDARDATELINE_DataLavorativa_Riga_ ON AX2009.WORKCALENDARDATELINE_DataLavorativa_Riga () INCLUDE();

END;
GO

