
CREATE PROCEDURE AX2009.usp_Create_MARKUPTABLE_CodiceSpeseVarie
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.MARKUPTABLE_CodiceSpeseVarie (
	-- Chiavi
	DATAAREAID  CHAR(4) NOT NULL,
	MODULETYPE  TINYINT NOT NULL,
	MARKUPCODE  NVARCHAR(10) NOT NULL,
	RECID  BIGINT NOT NULL,

	-- Dimensioni
	TXT  NVARCHAR(60) NOT NULL,
	CUSTPOSTING  TINYINT NOT NULL,
	CUSTACCOUNT  NVARCHAR(20) NOT NULL,
	VENDPOSTING  TINYINT NOT NULL,
	VENDACCOUNT  NVARCHAR(20) NOT NULL,
	CUSTTYPE  TINYINT NOT NULL,
	VENDTYPE  TINYINT NOT NULL


	-- Constraint
	CONSTRAINT PK_MARKUPTABLE_CodiceSpeseVarie PRIMARY KEY CLUSTERED (
		DATAAREAID,
		MODULETYPE,
		MARKUPCODE
	)
);

END;
GO

