
CREATE PROCEDURE AX2009.usp_Create_BOMCALCGROUP_GruppoCalcoloDBA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.BOMCALCGROUP_GruppoCalcoloDBA (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CALCGROUPID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	STOPEXPLODEPRICE		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_BOMCALCGROUP_GruppoCalcoloDBA PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CALCGROUPID
	)
);

END;
GO

