
CREATE PROCEDURE AX2009.usp_Merge_NPOBOETOTALTABLE_Insoluti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOBOETOTALTABLE_Insoluti', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOBOETOTALTABLE_Insoluti;
	EXEC AX2009.usp_AddIndexes_NPOBOETOTALTABLE_Insoluti;
END;

MERGE INTO AX2009.NPOBOETOTALTABLE_Insoluti AS TGT
USING AX2009.NPOBOETOTALTABLE_InsolutiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CUSTACCOUNT = TGT.CUSTACCOUNT AND SRC.MACROAREA = TGT.MACROAREA AND SRC.EMPLID = TGT.EMPLID AND SRC.TRANSTYPE = TGT.TRANSTYPE
WHEN MATCHED AND (TGT.STARTYRMTHDATE <> SRC.STARTYRMTHDATE OR TGT.NUMBERDRAWN <> SRC.NUMBERDRAWN OR TGT.NUMBERPROTESTED <> SRC.NUMBERPROTESTED OR TGT.AMOUNTDRAWN <> SRC.AMOUNTDRAWN OR TGT.AMOUNTPROTESTED <> SRC.AMOUNTPROTESTED)
  THEN UPDATE SET TGT.STARTYRMTHDATE = SRC.STARTYRMTHDATE, TGT.NUMBERDRAWN = SRC.NUMBERDRAWN, TGT.NUMBERPROTESTED = SRC.NUMBERPROTESTED, TGT.AMOUNTDRAWN = SRC.AMOUNTDRAWN, TGT.AMOUNTPROTESTED = SRC.AMOUNTPROTESTED
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CUSTACCOUNT, MACROAREA, EMPLID, TRANSTYPE, RECID, STARTYRMTHDATE, NUMBERDRAWN, NUMBERPROTESTED, AMOUNTDRAWN, AMOUNTPROTESTED)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOBOETOTALTABLE_Insoluti' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CUSTACCOUNT = ' + CAST(COALESCE(inserted.CUSTACCOUNT, deleted.CUSTACCOUNT) AS NVARCHAR) + ' - ' + 'MACROAREA = ' + CAST(COALESCE(inserted.MACROAREA, deleted.MACROAREA) AS NVARCHAR) + ' - ' + 'EMPLID = ' + CAST(COALESCE(inserted.EMPLID, deleted.EMPLID) AS NVARCHAR) + ' - ' + 'TRANSTYPE = ' + CAST(COALESCE(inserted.TRANSTYPE, deleted.TRANSTYPE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

