
CREATE PROCEDURE AX2009.usp_Create_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOSCRAPCAUSEGROUP_GruppoCausaleScarto (
	-- Chiavi
	SCRAPCAUSEGROUPID		NVARCHAR(3) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto PRIMARY KEY CLUSTERED (
		SCRAPCAUSEGROUPID
	)
);

END;
GO

