
CREATE PROCEDURE AX2009.usp_Merge_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA;
	EXEC AX2009.usp_AddIndexes_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA;
END;

MERGE INTO AX2009.NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA AS TGT
USING AX2009.NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.NPOPBAFINISHINGID = TGT.NPOPBAFINISHINGID AND SRC.ITEMIDDEFAULT = TGT.ITEMIDDEFAULT
WHEN MATCHED AND (TGT.DEFAULT_ <> SRC.DEFAULT_)
  THEN UPDATE SET TGT.DEFAULT_ = SRC.DEFAULT_
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, NPOPBAFINISHINGID, ITEMIDDEFAULT, RECID, DEFAULT_)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'NPOPBAFINISHINGID = ' + CAST(COALESCE(inserted.NPOPBAFINISHINGID, deleted.NPOPBAFINISHINGID) AS NVARCHAR) + ' - ' + 'ITEMIDDEFAULT = ' + CAST(COALESCE(inserted.ITEMIDDEFAULT, deleted.ITEMIDDEFAULT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

