
CREATE PROCEDURE AX2009.usp_AddIndexes_DLVREASON_CausaleConsegna
AS
BEGIN
SET NOCOUNT ON;

	--CREATE NONCLUSTERED INDEX IX_AX2009_DLVREASON_CausaleConsegna_ ON AX2009.DLVREASON_CausaleConsegna () INCLUDE();

END;
GO

