
CREATE PROCEDURE AX2009.usp_AddIndexes_LEDGERTABLE_ContoCoGe
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_LEDGERTABLE_ContoCoGe_ ON AX2009.LEDGERTABLE_ContoCoGe () INCLUDE();

END;
GO

