
CREATE PROCEDURE AX2009.usp_Merge_CUSTSETTLEMENT_LiquidazioniCliente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTSETTLEMENT_LiquidazioniCliente', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTSETTLEMENT_LiquidazioniCliente;
	EXEC AX2009.usp_AddIndexes_CUSTSETTLEMENT_LiquidazioniCliente;
END;

MERGE INTO AX2009.CUSTSETTLEMENT_LiquidazioniCliente AS TGT
USING AX2009.CUSTSETTLEMENT_LiquidazioniClienteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSRECID = TGT.TRANSRECID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.OFFSETTRANSVOUCHER <> SRC.OFFSETTRANSVOUCHER OR TGT.DUEDATE <> SRC.DUEDATE OR TGT.OFFSETCOMPANY <> SRC.OFFSETCOMPANY OR TGT.OFFSETACCOUNTNUM <> SRC.OFFSETACCOUNTNUM OR TGT.SETTLEAMOUNTCUR <> SRC.SETTLEAMOUNTCUR OR TGT.SETTLEAMOUNTMST <> SRC.SETTLEAMOUNTMST OR TGT.EXCHADJUSTMENT <> SRC.EXCHADJUSTMENT)
  THEN UPDATE SET TGT.OFFSETTRANSVOUCHER = SRC.OFFSETTRANSVOUCHER, TGT.DUEDATE = SRC.DUEDATE, TGT.OFFSETCOMPANY = SRC.OFFSETCOMPANY, TGT.OFFSETACCOUNTNUM = SRC.OFFSETACCOUNTNUM, TGT.SETTLEAMOUNTCUR = SRC.SETTLEAMOUNTCUR, TGT.SETTLEAMOUNTMST = SRC.SETTLEAMOUNTMST, TGT.EXCHADJUSTMENT = SRC.EXCHADJUSTMENT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSRECID, TRANSDATE, RECID, OFFSETTRANSVOUCHER, DUEDATE, OFFSETCOMPANY, OFFSETACCOUNTNUM, SETTLEAMOUNTCUR, SETTLEAMOUNTMST, EXCHADJUSTMENT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTSETTLEMENT_LiquidazioniCliente' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSRECID = ' + CAST(COALESCE(inserted.TRANSRECID, deleted.TRANSRECID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

