
CREATE PROCEDURE AX2009.usp_Merge_NPOSCRAP_DichiarazioniScarto
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOSCRAP_DichiarazioniScarto', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOSCRAP_DichiarazioniScarto;
    EXEC AX2009.usp_AddIndexes_NPOSCRAP_DichiarazioniScarto;
END;

MERGE INTO AX2009.NPOSCRAP_DichiarazioniScarto AS TGT
USING AX2009.NPOSCRAP_DichiarazioniScartoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.LOTID = TGT.LOTID AND SRC.PACKINGID = TGT.PACKINGID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.WMSLOCATIONID <> SRC.WMSLOCATIONID OR TGT.INVENTLOCATIONID <> SRC.INVENTLOCATIONID OR TGT.SCRAPCAUSEID <> SRC.SCRAPCAUSEID OR TGT.ITEMID <> SRC.ITEMID OR TGT.BASKETNO <> SRC.BASKETNO OR TGT.WORKSTATIONID <> SRC.WORKSTATIONID OR TGT.SCRAPTYPE <> SRC.SCRAPTYPE OR TGT.INVENTREFID <> SRC.INVENTREFID OR TGT.INVENTREFTYPE <> SRC.INVENTREFTYPE OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.ITEMLENGTH <> SRC.ITEMLENGTH OR TGT.QTY <> SRC.QTY)
  THEN UPDATE SET TGT.WMSLOCATIONID = SRC.WMSLOCATIONID, TGT.INVENTLOCATIONID = SRC.INVENTLOCATIONID, TGT.SCRAPCAUSEID = SRC.SCRAPCAUSEID, TGT.ITEMID = SRC.ITEMID, TGT.BASKETNO = SRC.BASKETNO, TGT.WORKSTATIONID = SRC.WORKSTATIONID, TGT.SCRAPTYPE = SRC.SCRAPTYPE, TGT.INVENTREFID = SRC.INVENTREFID, TGT.INVENTREFTYPE = SRC.INVENTREFTYPE, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.ITEMLENGTH = SRC.ITEMLENGTH, TGT.QTY = SRC.QTY
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, LOTID, PACKINGID, RECID, WMSLOCATIONID, INVENTLOCATIONID, SCRAPCAUSEID, ITEMID, BASKETNO, WORKSTATIONID, SCRAPTYPE, INVENTREFID, INVENTREFTYPE, CREATEDDATETIME, ITEMLENGTH, QTY)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOSCRAP_DichiarazioniScarto' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'LOTID = ' + CAST(COALESCE(inserted.LOTID, deleted.LOTID) AS NVARCHAR) + ' - ' + 'PACKINGID = ' + CAST(COALESCE(inserted.PACKINGID, deleted.PACKINGID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

