
CREATE PROCEDURE AX2009.usp_AddIndexes_DIRPARTYTABLE_Rubrica
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DIRPARTYTABLE_Rubrica_ ON AX2009.DIRPARTYTABLE_Rubrica () INCLUDE();

END;
GO

