
CREATE PROCEDURE AX2009.usp_Merge_BANKACCOUNTTABLE_ContoBancario
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.BANKACCOUNTTABLE_ContoBancario', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_BANKACCOUNTTABLE_ContoBancario;
    EXEC AX2009.usp_AddIndexes_BANKACCOUNTTABLE_ContoBancario;
END;

MERGE INTO AX2009.BANKACCOUNTTABLE_ContoBancario AS TGT
USING AX2009.BANKACCOUNTTABLE_ContoBancarioView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ACCOUNTID = TGT.ACCOUNTID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ACCOUNTID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.BANKACCOUNTTABLE_ContoBancario' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ACCOUNTID = ' + CAST(COALESCE(inserted.ACCOUNTID, deleted.ACCOUNTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

