
CREATE PROCEDURE AX2009.usp_Merge_ADDRESSSTATE_Regione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ADDRESSSTATE_Regione', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_ADDRESSSTATE_Regione;
	EXEC AX2009.usp_AddIndexes_ADDRESSSTATE_Regione;
END;

MERGE INTO AX2009.ADDRESSSTATE_Regione AS TGT
USING AX2009.ADDRESSSTATE_RegioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.COUNTRYREGIONID = TGT.COUNTRYREGIONID AND SRC.STATEID = TGT.STATEID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, COUNTRYREGIONID, STATEID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.ADDRESSSTATE_Regione' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'COUNTRYREGIONID = ' + CAST(COALESCE(inserted.COUNTRYREGIONID, deleted.COUNTRYREGIONID) AS NVARCHAR) + ' - ' + 'STATEID = ' + CAST(COALESCE(inserted.STATEID, deleted.STATEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

