
CREATE PROCEDURE AX2009.usp_Merge_PRODBOM_OrdiniProduzione_DBA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PRODBOM_OrdiniProduzione_DBA', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_PRODBOM_OrdiniProduzione_DBA;
    EXEC AX2009.usp_AddIndexes_PRODBOM_OrdiniProduzione_DBA;
END;

MERGE INTO AX2009.PRODBOM_OrdiniProduzione_DBA AS TGT
USING AX2009.PRODBOM_OrdiniProduzione_DBAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PRODID = TGT.PRODID AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.PRODLINETYPE <> SRC.PRODLINETYPE OR TGT.ITEMID <> SRC.ITEMID OR TGT.OPRNUM <> SRC.OPRNUM OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.INVENTREFTYPE <> SRC.INVENTREFTYPE OR TGT.INVENTREFID <> SRC.INVENTREFID OR TGT.INVENTREFTRANSID <> SRC.INVENTREFTRANSID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.BOMQTY <> SRC.BOMQTY OR TGT.REMAINBOMPHYSICAL <> SRC.REMAINBOMPHYSICAL OR TGT.QTYBOMSTUP <> SRC.QTYBOMSTUP OR TGT.REMAININVENTPHYSICAL <> SRC.REMAININVENTPHYSICAL OR TGT.QTYBOMCALC <> SRC.QTYBOMCALC)
  THEN UPDATE SET TGT.PRODLINETYPE = SRC.PRODLINETYPE, TGT.ITEMID = SRC.ITEMID, TGT.OPRNUM = SRC.OPRNUM, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.INVENTREFTYPE = SRC.INVENTREFTYPE, TGT.INVENTREFID = SRC.INVENTREFID, TGT.INVENTREFTRANSID = SRC.INVENTREFTRANSID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.BOMQTY = SRC.BOMQTY, TGT.REMAINBOMPHYSICAL = SRC.REMAINBOMPHYSICAL, TGT.QTYBOMSTUP = SRC.QTYBOMSTUP, TGT.REMAININVENTPHYSICAL = SRC.REMAININVENTPHYSICAL, TGT.QTYBOMCALC = SRC.QTYBOMCALC
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PRODID, LINENUM, RECID, PRODLINETYPE, ITEMID, OPRNUM, INVENTTRANSID, INVENTREFTYPE, INVENTREFID, INVENTREFTRANSID, INVENTDIMID, BOMQTY, REMAINBOMPHYSICAL, QTYBOMSTUP, REMAININVENTPHYSICAL, QTYBOMCALC)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.PRODBOM_OrdiniProduzione_DBA' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PRODID = ' + CAST(COALESCE(inserted.PRODID, deleted.PRODID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

