
CREATE PROCEDURE AX2009.usp_AddIndexes_UNITCONVERT_ConversioneUnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_UNITCONVERT_ConversioneUnitaDiMisura_ ON AX2009.UNITCONVERT_ConversioneUnitaDiMisura () INCLUDE();

END;
GO

