
CREATE PROCEDURE AX2009.usp_Merge_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia;
	EXEC AX2009.usp_AddIndexes_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia;
END;

MERGE INTO AX2009.NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia AS TGT
USING AX2009.NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamigliaView (nolock) AS SRC
ON SRC.ITEMID = TGT.ITEMID AND SRC.SUBFAMILYID = TGT.SUBFAMILYID
WHEN MATCHED AND (TGT.FAMILYID <> SRC.FAMILYID)
  THEN UPDATE SET TGT.FAMILYID = SRC.FAMILYID
WHEN NOT MATCHED
  THEN INSERT VALUES (ITEMID, SUBFAMILYID, RECID, FAMILYID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia' AS full_olap_table_name,
	'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'SUBFAMILYID = ' + CAST(COALESCE(inserted.SUBFAMILYID, deleted.SUBFAMILYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

