
CREATE PROCEDURE AX2009.usp_Merge_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METPAINTINGSETUPTABLE_ParametriLineaVerniciatura', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura;
    EXEC AX2009.usp_AddIndexes_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura;
END;

MERGE INTO AX2009.METPAINTINGSETUPTABLE_ParametriLineaVerniciatura AS TGT
USING AX2009.METPAINTINGSETUPTABLE_ParametriLineaVerniciaturaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PAINTINGLINEID = TGT.PAINTINGLINEID
WHEN MATCHED AND (TGT.PROCESSTIMECALCTYPE <> SRC.PROCESSTIMECALCTYPE OR TGT.CHAINSPEED <> SRC.CHAINSPEED OR TGT.HOOKSPERMETER <> SRC.HOOKSPERMETER)
  THEN UPDATE SET TGT.PROCESSTIMECALCTYPE = SRC.PROCESSTIMECALCTYPE, TGT.CHAINSPEED = SRC.CHAINSPEED, TGT.HOOKSPERMETER = SRC.HOOKSPERMETER
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PAINTINGLINEID, RECID, PROCESSTIMECALCTYPE, CHAINSPEED, HOOKSPERMETER)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METPAINTINGSETUPTABLE_ParametriLineaVerniciatura' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PAINTINGLINEID = ' + CAST(COALESCE(inserted.PAINTINGLINEID, deleted.PAINTINGLINEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

