
CREATE PROCEDURE AX2009.usp_Merge_INVENTITEMPRICE_PrezzoArticoli
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTITEMPRICE_PrezzoArticoli', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_INVENTITEMPRICE_PrezzoArticoli;
    EXEC AX2009.usp_AddIndexes_INVENTITEMPRICE_PrezzoArticoli;
END;

MERGE INTO AX2009.INVENTITEMPRICE_PrezzoArticoli AS TGT
USING AX2009.INVENTITEMPRICE_PrezzoArticoliView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.VERSIONID = TGT.VERSIONID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.PRICETYPE <> SRC.PRICETYPE OR TGT.PRICEUNIT <> SRC.PRICEUNIT OR TGT.PRICECALCID <> SRC.PRICECALCID OR TGT.UNITID <> SRC.UNITID OR TGT.ACTIVATIONDATE <> SRC.ACTIVATIONDATE OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.PRICE <> SRC.PRICE OR TGT.PRICEQTY <> SRC.PRICEQTY OR TGT.MARKUP <> SRC.MARKUP)
  THEN UPDATE SET TGT.PRICETYPE = SRC.PRICETYPE, TGT.PRICEUNIT = SRC.PRICEUNIT, TGT.PRICECALCID = SRC.PRICECALCID, TGT.UNITID = SRC.UNITID, TGT.ACTIVATIONDATE = SRC.ACTIVATIONDATE, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.PRICE = SRC.PRICE, TGT.PRICEQTY = SRC.PRICEQTY, TGT.MARKUP = SRC.MARKUP
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, VERSIONID, RECID, PRICETYPE, PRICEUNIT, PRICECALCID, UNITID, ACTIVATIONDATE, CREATEDDATETIME, PRICE, PRICEQTY, MARKUP)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.INVENTITEMPRICE_PrezzoArticoli' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'VERSIONID = ' + CAST(COALESCE(inserted.VERSIONID, deleted.VERSIONID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

