
CREATE PROCEDURE AX2009.usp_Create_INVENTITEMLOCATION_ArticoloDimensioneInventariale
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTITEMLOCATION_ArticoloDimensioneInventariale (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	INVENTDIMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NPODLVAREAID		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTITEMLOCATION_ArticoloDimensioneInventariale PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		INVENTDIMID
	)
);

END;
GO

