
CREATE PROCEDURE AX2009.usp_Create_DLVMODE_ModalitaConsegna
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.DLVMODE_ModalitaConsegna (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    CODE        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    TXT        NVARCHAR(60) NOT NULL,
    SHIPCARRIERID        NVARCHAR(10) NOT NULL,
    INTRASTATTRANSPORTID        NVARCHAR(10) NOT NULL,
    NPOJOURNEYEXTRAITEMID        NVARCHAR(20) NOT NULL,
    NPOJOURNEYITEMID        NVARCHAR(20) NOT NULL,
    NPOJOURNEYPRICEGROUP        NVARCHAR(10) NOT NULL


    -- Constraint
    CONSTRAINT PK_DLVMODE_ModalitaConsegna PRIMARY KEY CLUSTERED (
        DATAAREAID,
        CODE
    )
);

END;
GO

