
CREATE PROCEDURE AX2009.usp_Merge_METWMSORDERTRANSPLANNED_PianificazionePrelievi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.METWMSORDERTRANSPLANNED_PianificazionePrelievi', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METWMSORDERTRANSPLANNED_PianificazionePrelievi;
    EXEC AX2009.usp_AddIndexes_METWMSORDERTRANSPLANNED_PianificazionePrelievi;
END;

MERGE INTO AX2009.METWMSORDERTRANSPLANNED_PianificazionePrelievi AS TGT
USING AX2009.METWMSORDERTRANSPLANNED_PianificazionePrelieviView (nolock) AS SRC
ON SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.REQPOID <> SRC.REQPOID OR TGT.CRSNUM <> SRC.CRSNUM OR TGT.CRSEXPEDITIONSTATUS <> SRC.CRSEXPEDITIONSTATUS OR TGT.COVERINGBASIS <> SRC.COVERINGBASIS OR TGT.ANALYSISTYPE <> SRC.ANALYSISTYPE OR TGT.INCLUDEINBOUNDDOCK <> SRC.INCLUDEINBOUNDDOCK OR TGT.SHIPMENTTYPE <> SRC.SHIPMENTTYPE OR TGT.PROCESSNUM <> SRC.PROCESSNUM OR TGT.PICKINGSTATUS <> SRC.PICKINGSTATUS OR TGT.REMAINONHANDQTY <> SRC.REMAINONHANDQTY OR TGT.REMAINPHYSICAL <> SRC.REMAINPHYSICAL OR TGT.REMAINSALESPHYSICAL <> SRC.REMAINSALESPHYSICAL OR TGT.PICKINGROUTEID <> SRC.PICKINGROUTEID OR TGT.SHIPMENTID <> SRC.SHIPMENTID OR TGT.PICKINGROUTEEXPEDITIONSTATUS <> SRC.PICKINGROUTEEXPEDITIONSTATUS OR TGT.INVENTLOCATIONID <> SRC.INVENTLOCATIONID OR TGT.WORKSPACE <> SRC.WORKSPACE OR TGT.DLVSTATIONID <> SRC.DLVSTATIONID OR TGT.DLVAREAID <> SRC.DLVAREAID OR TGT.QTY <> SRC.QTY OR TGT.ORDERTYPE <> SRC.ORDERTYPE OR TGT.WMSORDERTRANSEXPEDITIONSTATUS <> SRC.WMSORDERTRANSEXPEDITIONSTATUS OR TGT.ITEMID <> SRC.ITEMID OR TGT.ORDERID <> SRC.ORDERID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.DLVDATE <> SRC.DLVDATE OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.INVENTTRANSTYPE <> SRC.INVENTTRANSTYPE OR TGT.INVENTTRANSREFID <> SRC.INVENTTRANSREFID OR TGT.CUSTOMER <> SRC.CUSTOMER OR TGT.DELIVERYADDRESS <> SRC.DELIVERYADDRESS OR TGT.KASTOID <> SRC.KASTOID OR TGT.SALESIDSPLIT <> SRC.SALESIDSPLIT OR TGT.DATAAREAID <> SRC.DATAAREAID OR TGT.PICKAVAILABLE <> SRC.PICKAVAILABLE OR TGT.INVENTITEMTYPE <> SRC.INVENTITEMTYPE OR TGT.ITEMFINISHINGIDFINAL <> SRC.ITEMFINISHINGIDFINAL OR TGT.ITEMFINISHINGID <> SRC.ITEMFINISHINGID OR TGT.INVENTLOCATIONIDTO <> SRC.INVENTLOCATIONIDTO OR TGT.LINENUM <> SRC.LINENUM OR TGT.SALESID <> SRC.SALESID OR TGT.INVENTDIMIDONHAND <> SRC.INVENTDIMIDONHAND OR TGT.SHIPMENTTABLEINIT <> SRC.SHIPMENTTABLEINIT)
  THEN UPDATE SET TGT.REQPOID = SRC.REQPOID, TGT.CRSNUM = SRC.CRSNUM, TGT.CRSEXPEDITIONSTATUS = SRC.CRSEXPEDITIONSTATUS, TGT.COVERINGBASIS = SRC.COVERINGBASIS, TGT.ANALYSISTYPE = SRC.ANALYSISTYPE, TGT.INCLUDEINBOUNDDOCK = SRC.INCLUDEINBOUNDDOCK, TGT.SHIPMENTTYPE = SRC.SHIPMENTTYPE, TGT.PROCESSNUM = SRC.PROCESSNUM, TGT.PICKINGSTATUS = SRC.PICKINGSTATUS, TGT.REMAINONHANDQTY = SRC.REMAINONHANDQTY, TGT.REMAINPHYSICAL = SRC.REMAINPHYSICAL, TGT.REMAINSALESPHYSICAL = SRC.REMAINSALESPHYSICAL, TGT.PICKINGROUTEID = SRC.PICKINGROUTEID, TGT.SHIPMENTID = SRC.SHIPMENTID, TGT.PICKINGROUTEEXPEDITIONSTATUS = SRC.PICKINGROUTEEXPEDITIONSTATUS, TGT.INVENTLOCATIONID = SRC.INVENTLOCATIONID, TGT.WORKSPACE = SRC.WORKSPACE, TGT.DLVSTATIONID = SRC.DLVSTATIONID, TGT.DLVAREAID = SRC.DLVAREAID, TGT.QTY = SRC.QTY, TGT.ORDERTYPE = SRC.ORDERTYPE, TGT.WMSORDERTRANSEXPEDITIONSTATUS = SRC.WMSORDERTRANSEXPEDITIONSTATUS, TGT.ITEMID = SRC.ITEMID, TGT.ORDERID = SRC.ORDERID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.DLVDATE = SRC.DLVDATE, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.INVENTTRANSTYPE = SRC.INVENTTRANSTYPE, TGT.INVENTTRANSREFID = SRC.INVENTTRANSREFID, TGT.CUSTOMER = SRC.CUSTOMER, TGT.DELIVERYADDRESS = SRC.DELIVERYADDRESS, TGT.KASTOID = SRC.KASTOID, TGT.SALESIDSPLIT = SRC.SALESIDSPLIT, TGT.DATAAREAID = SRC.DATAAREAID, TGT.PICKAVAILABLE = SRC.PICKAVAILABLE, TGT.INVENTITEMTYPE = SRC.INVENTITEMTYPE, TGT.ITEMFINISHINGIDFINAL = SRC.ITEMFINISHINGIDFINAL, TGT.ITEMFINISHINGID = SRC.ITEMFINISHINGID, TGT.INVENTLOCATIONIDTO = SRC.INVENTLOCATIONIDTO, TGT.LINENUM = SRC.LINENUM, TGT.SALESID = SRC.SALESID, TGT.INVENTDIMIDONHAND = SRC.INVENTDIMIDONHAND, TGT.SHIPMENTTABLEINIT = SRC.SHIPMENTTABLEINIT
WHEN NOT MATCHED
  THEN INSERT VALUES (RECID, REQPOID, CRSNUM, CRSEXPEDITIONSTATUS, COVERINGBASIS, ANALYSISTYPE, INCLUDEINBOUNDDOCK, SHIPMENTTYPE, PROCESSNUM, PICKINGSTATUS, REMAINONHANDQTY, REMAINPHYSICAL, REMAINSALESPHYSICAL, PICKINGROUTEID, SHIPMENTID, PICKINGROUTEEXPEDITIONSTATUS, INVENTLOCATIONID, WORKSPACE, DLVSTATIONID, DLVAREAID, QTY, ORDERTYPE, WMSORDERTRANSEXPEDITIONSTATUS, ITEMID, ORDERID, INVENTDIMID, DLVDATE, INVENTTRANSID, INVENTTRANSTYPE, INVENTTRANSREFID, CUSTOMER, DELIVERYADDRESS, KASTOID, SALESIDSPLIT, DATAAREAID, PICKAVAILABLE, INVENTITEMTYPE, ITEMFINISHINGIDFINAL, ITEMFINISHINGID, INVENTLOCATIONIDTO, LINENUM, SALESID, INVENTDIMIDONHAND, SHIPMENTTABLEINIT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METWMSORDERTRANSPLANNED_PianificazionePrelievi' AS full_olap_table_name,
    'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

