
CREATE PROCEDURE AX2009.usp_Create_PRODTABLE_OrdiniProduzione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.PRODTABLE_OrdiniProduzione (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PRODID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    ITEMID        NVARCHAR(20) NOT NULL,
    PRODSTATUS        SMALLINT NOT NULL,
    SCHEDSTATUS        SMALLINT NOT NULL,
    DLVDATE        DATE NOT NULL,
    STUPDATE        DATE NOT NULL,
    FINISHEDDATE        DATE NOT NULL,
    SCHEDSTART        DATE NOT NULL,
    SCHEDEND        DATE NOT NULL,
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    INVENTREFTYPE        SMALLINT NOT NULL,
    INVENTREFID        NVARCHAR(20) NOT NULL,
    INVENTREFTRANSID        NVARCHAR(20) NOT NULL,
    COLLECTREFLEVEL        TINYINT NOT NULL,
    COLLECTREFPRODID        NVARCHAR(20) NOT NULL,
    BACKORDERSTATUS        SMALLINT NOT NULL,
    REQPLANIDSCHED        NVARCHAR(10) NOT NULL,
    LATESTSCHEDDATE        DATE NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,
    SCHEDTOTIME        INT NOT NULL,
    SCHEDFROMTIME        INT NOT NULL,
    CREATEDDATETIME        DATETIME NOT NULL,
    NPOSEQUENCENUMBER        INT NOT NULL,
    NPOBOMPALLETID        NVARCHAR(18) NOT NULL,
    NPOSTUPTIME        INT NOT NULL,
    NPOFINISHINGID        NVARCHAR(512) NOT NULL,
    NPOLENGTH        NVARCHAR(512) NOT NULL,
    METLOCKPACKING        BIT NOT NULL,

    -- Misure
    QTYSCHED        NUMERIC(28, 12) NOT NULL,
    NPOPRODQTYMORE        NUMERIC(28, 12) NOT NULL,
    REMAININVENTPHYSICAL        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_PRODTABLE_OrdiniProduzione PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PRODID
    )
);

END;
GO

