
CREATE PROCEDURE AX2009.usp_Create_NPOPRODUCTIONLOT_Lotti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPRODUCTIONLOT_Lotti (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	LOTID		NVARCHAR(15) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	MASTERWRKCTRID		NVARCHAR(10) NOT NULL,
	LINEARKG		NUMERIC(28, 12) NOT NULL,
	LOTDATE		DATE NOT NULL,
	LOTDATETIME		DATETIME NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOPRODUCTIONLOT_Lotti PRIMARY KEY CLUSTERED (
		DATAAREAID,
		LOTID
	)
);

END;
GO

