
CREATE PROCEDURE AX2009.usp_Merge_PBAREUSEBOMROUTE_StringaDiRicerca
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PBAREUSEBOMROUTE_StringaDiRicerca', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_PBAREUSEBOMROUTE_StringaDiRicerca;
    EXEC AX2009.usp_AddIndexes_PBAREUSEBOMROUTE_StringaDiRicerca;
END;

MERGE INTO AX2009.PBAREUSEBOMROUTE_StringaDiRicerca AS TGT
USING AX2009.PBAREUSEBOMROUTE_StringaDiRicercaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BOMID = TGT.BOMID AND SRC.ROUTEID = TGT.ROUTEID
WHEN MATCHED AND (TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.ITEMID <> SRC.ITEMID OR TGT.SEARCHSTRING <> SRC.SEARCHSTRING)
  THEN UPDATE SET TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.ITEMID = SRC.ITEMID, TGT.SEARCHSTRING = SRC.SEARCHSTRING
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BOMID, ROUTEID, RECID, INVENTTRANSID, ITEMID, SEARCHSTRING)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.PBAREUSEBOMROUTE_StringaDiRicerca' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BOMID = ' + CAST(COALESCE(inserted.BOMID, deleted.BOMID) AS NVARCHAR) + ' - ' + 'ROUTEID = ' + CAST(COALESCE(inserted.ROUTEID, deleted.ROUTEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

