
CREATE PROCEDURE AX2009.usp_Create_INVENTTRANSFERLINE_OrdiniTrasferimento_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTTRANSFERLINE_OrdiniTrasferimento_Riga (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    TRANSFERID        NVARCHAR(20) NOT NULL,
    LINENUM        NUMERIC(28, 12) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    ITEMID        NVARCHAR(20) NOT NULL,
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    INVENTTRANSIDRECEIVE        NVARCHAR(20) NOT NULL,
    SHIPDATE        DATE NOT NULL,
    RECEIVEDATE        DATE NOT NULL,
    NPOINVENTTRANSIDPRODBOM        NVARCHAR(20) NOT NULL,

    -- Misure
    UNITID        NVARCHAR(10) NOT NULL,
    QTYTRANSFER        NUMERIC(28, 12) NOT NULL,
    QTYREMAINSHIP        NUMERIC(28, 12) NOT NULL,
    QTYSHIPPED        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_INVENTTRANSFERLINE_OrdiniTrasferimento_Riga PRIMARY KEY CLUSTERED (
        DATAAREAID,
        TRANSFERID,
        LINENUM,
        RECID
    )
);

END;
GO

