
CREATE PROCEDURE AX2009.usp_Create_TAXTABLE_CodiceIVA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.TAXTABLE_CodiceIVA (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TAXCODE		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TAXNAME		NVARCHAR(30) NOT NULL


	-- Constraint
	CONSTRAINT PK_TAXTABLE_CodiceIVA PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TAXCODE
	)
);

END;
GO

