
CREATE PROCEDURE AX2009.usp_Merge_NPOPACKINGITEMS_Pacchi_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPACKINGITEMS_Pacchi_Riga', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOPACKINGITEMS_Pacchi_Riga;
    EXEC AX2009.usp_AddIndexes_NPOPACKINGITEMS_Pacchi_Riga;
END;

MERGE INTO AX2009.NPOPACKINGITEMS_Pacchi_Riga AS TGT
USING AX2009.NPOPACKINGITEMS_Pacchi_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PACKINGID = TGT.PACKINGID AND SRC.SALESLINENUM = TGT.SALESLINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.SALESID <> SRC.SALESID OR TGT.BARLENGTH <> SRC.BARLENGTH OR TGT.ITEMID <> SRC.ITEMID OR TGT.WMSORDERTRANSRECID <> SRC.WMSORDERTRANSRECID OR TGT.INVENTREFID <> SRC.INVENTREFID OR TGT.INVENTREFTYPE <> SRC.INVENTREFTYPE OR TGT.SALESLINERECID <> SRC.SALESLINERECID OR TGT.PURCHLINERECID <> SRC.PURCHLINERECID OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.BOMITEMID <> SRC.BOMITEMID OR TGT.PAINTINGTHICKNESS <> SRC.PAINTINGTHICKNESS OR TGT.SALESUNIT <> SRC.SALESUNIT OR TGT.QTYGOOD <> SRC.QTYGOOD OR TGT.QTYERROR <> SRC.QTYERROR OR TGT.BALANCEDKG <> SRC.BALANCEDKG OR TGT.INVENTTRANSKG <> SRC.INVENTTRANSKG OR TGT.PAINTINGHOOKS <> SRC.PAINTINGHOOKS)
  THEN UPDATE SET TGT.SALESID = SRC.SALESID, TGT.BARLENGTH = SRC.BARLENGTH, TGT.ITEMID = SRC.ITEMID, TGT.WMSORDERTRANSRECID = SRC.WMSORDERTRANSRECID, TGT.INVENTREFID = SRC.INVENTREFID, TGT.INVENTREFTYPE = SRC.INVENTREFTYPE, TGT.SALESLINERECID = SRC.SALESLINERECID, TGT.PURCHLINERECID = SRC.PURCHLINERECID, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.BOMITEMID = SRC.BOMITEMID, TGT.PAINTINGTHICKNESS = SRC.PAINTINGTHICKNESS, TGT.SALESUNIT = SRC.SALESUNIT, TGT.QTYGOOD = SRC.QTYGOOD, TGT.QTYERROR = SRC.QTYERROR, TGT.BALANCEDKG = SRC.BALANCEDKG, TGT.INVENTTRANSKG = SRC.INVENTTRANSKG, TGT.PAINTINGHOOKS = SRC.PAINTINGHOOKS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PACKINGID, SALESLINENUM, RECID, SALESID, BARLENGTH, ITEMID, WMSORDERTRANSRECID, INVENTREFID, INVENTREFTYPE, SALESLINERECID, PURCHLINERECID, INVENTTRANSID, BOMITEMID, PAINTINGTHICKNESS, SALESUNIT, QTYGOOD, QTYERROR, BALANCEDKG, INVENTTRANSKG, PAINTINGHOOKS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOPACKINGITEMS_Pacchi_Riga' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PACKINGID = ' + CAST(COALESCE(inserted.PACKINGID, deleted.PACKINGID) AS NVARCHAR) + ' - ' + 'SALESLINENUM = ' + CAST(COALESCE(inserted.SALESLINENUM, deleted.SALESLINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

