
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTTRANS_TransazioniCliente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTTRANS_TransazioniCliente_ ON AX2009.CUSTTRANS_TransazioniCliente () INCLUDE();

END;
GO

