
CREATE PROCEDURE AX2009.usp_Merge_NPOPBAFINISHING_Finitura
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOPBAFINISHING_Finitura', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOPBAFINISHING_Finitura;
    EXEC AX2009.usp_AddIndexes_NPOPBAFINISHING_Finitura;
END;

MERGE INTO AX2009.NPOPBAFINISHING_Finitura AS TGT
USING AX2009.NPOPBAFINISHING_FinituraView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.FINISHINGID = TGT.FINISHINGID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.LEADTIME <> SRC.LEADTIME OR TGT.ASALIASID <> SRC.ASALIASID OR TGT.DEL_FINISHINGTYPE <> SRC.DEL_FINISHINGTYPE OR TGT.FINISHINGGROUPID <> SRC.FINISHINGGROUPID OR TGT.ASALIASIDACCESSORI <> SRC.ASALIASIDACCESSORI OR TGT.NCEGROUPPRICEMNG <> SRC.NCEGROUPPRICEMNG OR TGT.FINISHINGSUBLIMATED <> SRC.FINISHINGSUBLIMATED OR TGT.FINISHINGDOUBLELAYER <> SRC.FINISHINGDOUBLELAYER OR TGT.FINISHINGPOWDERCLASS <> SRC.FINISHINGPOWDERCLASS OR TGT.FINISHINGMETALLIC <> SRC.FINISHINGMETALLIC OR TGT.FINISHINGROUGHNESS <> SRC.FINISHINGROUGHNESS OR TGT.FINISHINGSURFACE <> SRC.FINISHINGSURFACE OR TGT.FINISHINGFAMILY <> SRC.FINISHINGFAMILY OR TGT.FINISHINGTYPE <> SRC.FINISHINGTYPE OR TGT.OPERATIONTYPE <> SRC.OPERATIONTYPE OR TGT.ITEMPRICEGROUPID <> SRC.ITEMPRICEGROUPID OR TGT.FINISHINGMNG <> SRC.FINISHINGMNG OR TGT.APPLYCOLORCHANGEMARKUP <> SRC.APPLYCOLORCHANGEMARKUP OR TGT.FINISHINGDURABILITYCLASS <> SRC.FINISHINGDURABILITYCLASS)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.LEADTIME = SRC.LEADTIME, TGT.ASALIASID = SRC.ASALIASID, TGT.DEL_FINISHINGTYPE = SRC.DEL_FINISHINGTYPE, TGT.FINISHINGGROUPID = SRC.FINISHINGGROUPID, TGT.ASALIASIDACCESSORI = SRC.ASALIASIDACCESSORI, TGT.NCEGROUPPRICEMNG = SRC.NCEGROUPPRICEMNG, TGT.FINISHINGSUBLIMATED = SRC.FINISHINGSUBLIMATED, TGT.FINISHINGDOUBLELAYER = SRC.FINISHINGDOUBLELAYER, TGT.FINISHINGPOWDERCLASS = SRC.FINISHINGPOWDERCLASS, TGT.FINISHINGMETALLIC = SRC.FINISHINGMETALLIC, TGT.FINISHINGROUGHNESS = SRC.FINISHINGROUGHNESS, TGT.FINISHINGSURFACE = SRC.FINISHINGSURFACE, TGT.FINISHINGFAMILY = SRC.FINISHINGFAMILY, TGT.FINISHINGTYPE = SRC.FINISHINGTYPE, TGT.OPERATIONTYPE = SRC.OPERATIONTYPE, TGT.ITEMPRICEGROUPID = SRC.ITEMPRICEGROUPID, TGT.FINISHINGMNG = SRC.FINISHINGMNG, TGT.APPLYCOLORCHANGEMARKUP = SRC.APPLYCOLORCHANGEMARKUP, TGT.FINISHINGDURABILITYCLASS = SRC.FINISHINGDURABILITYCLASS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, FINISHINGID, RECID, NAME, LEADTIME, ASALIASID, DEL_FINISHINGTYPE, FINISHINGGROUPID, ASALIASIDACCESSORI, NCEGROUPPRICEMNG, FINISHINGSUBLIMATED, FINISHINGDOUBLELAYER, FINISHINGPOWDERCLASS, FINISHINGMETALLIC, FINISHINGROUGHNESS, FINISHINGSURFACE, FINISHINGFAMILY, FINISHINGTYPE, OPERATIONTYPE, ITEMPRICEGROUPID, FINISHINGMNG, APPLYCOLORCHANGEMARKUP, FINISHINGDURABILITYCLASS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOPBAFINISHING_Finitura' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'FINISHINGID = ' + CAST(COALESCE(inserted.FINISHINGID, deleted.FINISHINGID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

