
CREATE PROCEDURE AX2009.usp_Merge_PRODTABLE_OrdiniProduzione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PRODTABLE_OrdiniProduzione', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_PRODTABLE_OrdiniProduzione;
    EXEC AX2009.usp_AddIndexes_PRODTABLE_OrdiniProduzione;
END;

MERGE INTO AX2009.PRODTABLE_OrdiniProduzione AS TGT
USING AX2009.PRODTABLE_OrdiniProduzioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PRODID = TGT.PRODID
WHEN MATCHED AND (TGT.ITEMID <> SRC.ITEMID OR TGT.PRODSTATUS <> SRC.PRODSTATUS OR TGT.SCHEDSTATUS <> SRC.SCHEDSTATUS OR TGT.DLVDATE <> SRC.DLVDATE OR TGT.STUPDATE <> SRC.STUPDATE OR TGT.FINISHEDDATE <> SRC.FINISHEDDATE OR TGT.SCHEDSTART <> SRC.SCHEDSTART OR TGT.SCHEDEND <> SRC.SCHEDEND OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.INVENTREFTYPE <> SRC.INVENTREFTYPE OR TGT.INVENTREFID <> SRC.INVENTREFID OR TGT.INVENTREFTRANSID <> SRC.INVENTREFTRANSID OR TGT.COLLECTREFLEVEL <> SRC.COLLECTREFLEVEL OR TGT.COLLECTREFPRODID <> SRC.COLLECTREFPRODID OR TGT.BACKORDERSTATUS <> SRC.BACKORDERSTATUS OR TGT.REQPLANIDSCHED <> SRC.REQPLANIDSCHED OR TGT.LATESTSCHEDDATE <> SRC.LATESTSCHEDDATE OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.SCHEDTOTIME <> SRC.SCHEDTOTIME OR TGT.SCHEDFROMTIME <> SRC.SCHEDFROMTIME OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.NPOSEQUENCENUMBER <> SRC.NPOSEQUENCENUMBER OR TGT.NPOBOMPALLETID <> SRC.NPOBOMPALLETID OR TGT.NPOSTUPTIME <> SRC.NPOSTUPTIME OR TGT.NPOFINISHINGID <> SRC.NPOFINISHINGID OR TGT.NPOLENGTH <> SRC.NPOLENGTH OR TGT.METLOCKPACKING <> SRC.METLOCKPACKING OR TGT.QTYSCHED <> SRC.QTYSCHED OR TGT.NPOPRODQTYMORE <> SRC.NPOPRODQTYMORE OR TGT.REMAININVENTPHYSICAL <> SRC.REMAININVENTPHYSICAL)
  THEN UPDATE SET TGT.ITEMID = SRC.ITEMID, TGT.PRODSTATUS = SRC.PRODSTATUS, TGT.SCHEDSTATUS = SRC.SCHEDSTATUS, TGT.DLVDATE = SRC.DLVDATE, TGT.STUPDATE = SRC.STUPDATE, TGT.FINISHEDDATE = SRC.FINISHEDDATE, TGT.SCHEDSTART = SRC.SCHEDSTART, TGT.SCHEDEND = SRC.SCHEDEND, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.INVENTREFTYPE = SRC.INVENTREFTYPE, TGT.INVENTREFID = SRC.INVENTREFID, TGT.INVENTREFTRANSID = SRC.INVENTREFTRANSID, TGT.COLLECTREFLEVEL = SRC.COLLECTREFLEVEL, TGT.COLLECTREFPRODID = SRC.COLLECTREFPRODID, TGT.BACKORDERSTATUS = SRC.BACKORDERSTATUS, TGT.REQPLANIDSCHED = SRC.REQPLANIDSCHED, TGT.LATESTSCHEDDATE = SRC.LATESTSCHEDDATE, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.SCHEDTOTIME = SRC.SCHEDTOTIME, TGT.SCHEDFROMTIME = SRC.SCHEDFROMTIME, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.NPOSEQUENCENUMBER = SRC.NPOSEQUENCENUMBER, TGT.NPOBOMPALLETID = SRC.NPOBOMPALLETID, TGT.NPOSTUPTIME = SRC.NPOSTUPTIME, TGT.NPOFINISHINGID = SRC.NPOFINISHINGID, TGT.NPOLENGTH = SRC.NPOLENGTH, TGT.METLOCKPACKING = SRC.METLOCKPACKING, TGT.QTYSCHED = SRC.QTYSCHED, TGT.NPOPRODQTYMORE = SRC.NPOPRODQTYMORE, TGT.REMAININVENTPHYSICAL = SRC.REMAININVENTPHYSICAL
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PRODID, RECID, ITEMID, PRODSTATUS, SCHEDSTATUS, DLVDATE, STUPDATE, FINISHEDDATE, SCHEDSTART, SCHEDEND, INVENTTRANSID, INVENTREFTYPE, INVENTREFID, INVENTREFTRANSID, COLLECTREFLEVEL, COLLECTREFPRODID, BACKORDERSTATUS, REQPLANIDSCHED, LATESTSCHEDDATE, INVENTDIMID, SCHEDTOTIME, SCHEDFROMTIME, CREATEDDATETIME, NPOSEQUENCENUMBER, NPOBOMPALLETID, NPOSTUPTIME, NPOFINISHINGID, NPOLENGTH, METLOCKPACKING, QTYSCHED, NPOPRODQTYMORE, REMAININVENTPHYSICAL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.PRODTABLE_OrdiniProduzione' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PRODID = ' + CAST(COALESCE(inserted.PRODID, deleted.PRODID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

