
CREATE PROCEDURE AX2009.usp_AddIndexes_SHIPCARRIERCOMPANY_SocietaSpedizioni
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SHIPCARRIERCOMPANY_SocietaSpedizioni_ ON AX2009.SHIPCARRIERCOMPANY_SocietaSpedizioni () INCLUDE();

END;
GO

