
CREATE PROCEDURE AX2009.usp_AddIndexes_METWMSORDERTRANSPLANNED_PianificazionePrelievi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METWMSORDERTRANSPLANNED_PianificazionePrelievi_ ON AX2009.METWMSORDERTRANSPLANNED_PianificazionePrelievi () INCLUDE();

END;
GO

