
CREATE PROCEDURE AX2009.usp_Merge_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga;
	EXEC AX2009.usp_AddIndexes_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga;
END;

MERGE INTO AX2009.LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga AS TGT
USING AX2009.LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.JOURNALNUM = TGT.JOURNALNUM AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.VENDTRANSID <> SRC.VENDTRANSID OR TGT.PAYMENT <> SRC.PAYMENT)
  THEN UPDATE SET TGT.VENDTRANSID = SRC.VENDTRANSID, TGT.PAYMENT = SRC.PAYMENT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, JOURNALNUM, LINENUM, RECID, VENDTRANSID, PAYMENT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'JOURNALNUM = ' + CAST(COALESCE(inserted.JOURNALNUM, deleted.JOURNALNUM) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

