
CREATE PROCEDURE AX2009.usp_AddIndexes_COMMISSIONSALESREP_Agente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_COMMISSIONSALESREP_Agente_ ON AX2009.COMMISSIONSALESREP_Agente () INCLUDE();

END;
GO

