
CREATE PROCEDURE AX2009.usp_Merge_INVENTTXT_ArticoloTraduzione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTTXT_ArticoloTraduzione', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTTXT_ArticoloTraduzione;
	EXEC AX2009.usp_AddIndexes_INVENTTXT_ArticoloTraduzione;
END;

MERGE INTO AX2009.INVENTTXT_ArticoloTraduzione AS TGT
USING AX2009.INVENTTXT_ArticoloTraduzioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.LANGUAGEID = TGT.LANGUAGEID
WHEN MATCHED AND (TGT.TXT <> SRC.TXT)
  THEN UPDATE SET TGT.TXT = SRC.TXT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, LANGUAGEID, RECID, TXT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTTXT_ArticoloTraduzione' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'LANGUAGEID = ' + CAST(COALESCE(inserted.LANGUAGEID, deleted.LANGUAGEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

