
CREATE PROCEDURE AX2009.usp_Merge_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale;
	EXEC AX2009.usp_AddIndexes_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale;
END;

MERGE INTO AX2009.INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale AS TGT
USING AX2009.INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscaleView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.JOURNALID = TGT.JOURNALID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, JOURNALID, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'JOURNALID = ' + CAST(COALESCE(inserted.JOURNALID, deleted.JOURNALID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

