CREATE PROCEDURE AX2009.usp_Merge_CUSTPACKINGSLIPJOUR_DDTCliente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.CUSTPACKINGSLIPJOUR_DDTCliente', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTPACKINGSLIPJOUR_DDTCliente;
    EXEC AX2009.usp_AddIndexes_CUSTPACKINGSLIPJOUR_DDTCliente;
END;

MERGE INTO AX2009.CUSTPACKINGSLIPJOUR_DDTCliente AS TGT
USING AX2009.CUSTPACKINGSLIPJOUR_DDTClienteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.DELIVERYDATE = TGT.DELIVERYDATE AND SRC.PACKINGSLIPID = TGT.PACKINGSLIPID AND SRC.SALESID = TGT.SALESID
WHEN MATCHED AND (TGT.ORDERACCOUNT <> SRC.ORDERACCOUNT OR TGT.INVOICEACCOUNT <> SRC.INVOICEACCOUNT OR TGT.DELIVERYNAME <> SRC.DELIVERYNAME OR TGT.DELIVERYADDRESS <> SRC.DELIVERYADDRESS OR TGT.INVOICECOUNTRYREGIONID <> SRC.INVOICECOUNTRYREGIONID OR TGT.DLVTERM <> SRC.DLVTERM OR TGT.DLVMODE <> SRC.DLVMODE OR TGT.LEDGERVOUCHER <> SRC.LEDGERVOUCHER OR TGT.DLVZIPCODE <> SRC.DLVZIPCODE OR TGT.DLVCOUNTY <> SRC.DLVCOUNTY OR TGT.DLVCOUNTRYREGIONID <> SRC.DLVCOUNTRYREGIONID OR TGT.DLVSTATE <> SRC.DLVSTATE OR TGT.DELIVERYCITY <> SRC.DELIVERYCITY OR TGT.DELIVERYSTREET <> SRC.DELIVERYSTREET OR TGT.SHIPCARRIERID <> SRC.SHIPCARRIERID OR TGT.NPOTRANSPORTSTART <> SRC.NPOTRANSPORTSTART OR TGT.NPOPACKINGSLIPFROMWMS <> SRC.NPOPACKINGSLIPFROMWMS OR TGT.NPOJOURNEYID <> SRC.NPOJOURNEYID OR TGT.NPOREFDATAAREAID <> SRC.NPOREFDATAAREAID OR TGT.NPOFREECARIERADDRESS <> SRC.NPOFREECARIERADDRESS OR TGT.NPOPALLETNUM <> SRC.NPOPALLETNUM OR TGT.QTY <> SRC.QTY OR TGT.WEIGHT <> SRC.WEIGHT)
  THEN UPDATE SET TGT.ORDERACCOUNT = SRC.ORDERACCOUNT, TGT.INVOICEACCOUNT = SRC.INVOICEACCOUNT, TGT.DELIVERYNAME = SRC.DELIVERYNAME, TGT.DELIVERYADDRESS = SRC.DELIVERYADDRESS, TGT.INVOICECOUNTRYREGIONID = SRC.INVOICECOUNTRYREGIONID, TGT.DLVTERM = SRC.DLVTERM, TGT.DLVMODE = SRC.DLVMODE, TGT.LEDGERVOUCHER = SRC.LEDGERVOUCHER, TGT.DLVZIPCODE = SRC.DLVZIPCODE, TGT.DLVCOUNTY = SRC.DLVCOUNTY, TGT.DLVCOUNTRYREGIONID = SRC.DLVCOUNTRYREGIONID, TGT.DLVSTATE = SRC.DLVSTATE, TGT.DELIVERYCITY = SRC.DELIVERYCITY, TGT.DELIVERYSTREET = SRC.DELIVERYSTREET, TGT.SHIPCARRIERID = SRC.SHIPCARRIERID, TGT.NPOTRANSPORTSTART = SRC.NPOTRANSPORTSTART, TGT.NPOPACKINGSLIPFROMWMS = SRC.NPOPACKINGSLIPFROMWMS, TGT.NPOJOURNEYID = SRC.NPOJOURNEYID, TGT.NPOREFDATAAREAID = SRC.NPOREFDATAAREAID, TGT.NPOFREECARIERADDRESS = SRC.NPOFREECARIERADDRESS, TGT.NPOPALLETNUM = SRC.NPOPALLETNUM, TGT.QTY = SRC.QTY, TGT.WEIGHT = SRC.WEIGHT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, DELIVERYDATE, PACKINGSLIPID, SALESID, RECID, ORDERACCOUNT, INVOICEACCOUNT, DELIVERYNAME, DELIVERYADDRESS, INVOICECOUNTRYREGIONID, DLVTERM, DLVMODE, LEDGERVOUCHER, DLVZIPCODE, DLVCOUNTY, DLVCOUNTRYREGIONID, DLVSTATE, DELIVERYCITY, DELIVERYSTREET, SHIPCARRIERID, NPOTRANSPORTSTART, NPOPACKINGSLIPFROMWMS, NPOJOURNEYID, NPOREFDATAAREAID, NPOFREECARIERADDRESS, NPOPALLETNUM, QTY, WEIGHT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTPACKINGSLIPJOUR_DDTCliente' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'DELIVERYDATE = ' + CAST(COALESCE(inserted.DELIVERYDATE, deleted.DELIVERYDATE) AS NVARCHAR) + ' - ' + 'PACKINGSLIPID = ' + CAST(COALESCE(inserted.PACKINGSLIPID, deleted.PACKINGSLIPID) AS NVARCHAR) + ' - ' + 'SALESID = ' + CAST(COALESCE(inserted.SALESID, deleted.SALESID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

