
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOWORKSTATION_PostazioneDiLavoro
AS
BEGIN
SET NOCOUNT ON;

CREATE UNIQUE NONCLUSTERED INDEX IX_AX2009_NPOWORKSTATION_PostazioneDiLavoro_DATAREAID_WORKSTATIONID ON AX2009.NPOWORKSTATION_PostazioneDiLavoro (DATAAREAID, WORKSTATIONID);

END;
GO

