
CREATE PROCEDURE AX2009.usp_AddIndexes_METVENDPROJECT_CommessaFornitore
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METVENDPROJECT_CommessaFornitore_ ON AX2009.METVENDPROJECT_CommessaFornitore () INCLUDE();

END;
GO

