
CREATE PROCEDURE AX2009.usp_Create_VENDINVOICETRANS_FattureFornitore_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.VENDINVOICETRANS_FattureFornitore_Riga (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PURCHID        NVARCHAR(20) NOT NULL,
    INVOICEID        NVARCHAR(20) NOT NULL,
    INVOICEDATE        DATETIME NOT NULL,
    NUMBERSEQUENCEGROUP        NVARCHAR(10) NOT NULL,
    INTERNALINVOICEID        NVARCHAR(20) NOT NULL,
    LINENUM        NUMERIC(28, 12) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    DIMENSION        NVARCHAR(10) NOT NULL,
    DIMENSION2_        NVARCHAR(10) NOT NULL,
    DIMENSION3_        NVARCHAR(10) NOT NULL,
    ORIGPURCHID        NVARCHAR(20) NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,
    DIMENSION4_        NVARCHAR(10) NOT NULL,
    DIMENSION5_        NVARCHAR(10) NOT NULL,
    DIMENSION6_        NVARCHAR(10) NOT NULL,

    -- Misure
    PURCHUNIT        NVARCHAR(10) NOT NULL,
    QTY        NUMERIC(28, 12) NOT NULL,
    INVENTQTY        NUMERIC(28, 12) NOT NULL,
    CURRENCYCODE        NVARCHAR(3) NOT NULL,
    LINEAMOUNT        NUMERIC(28, 12) NOT NULL,
    LINEAMOUNTMST        NUMERIC(28, 12) NOT NULL,
    PURCHPRICE        NUMERIC(28, 12) NOT NULL,
    PRICEUNIT        NUMERIC(28, 12) NOT NULL,
    DISCPERCENT        NUMERIC(28, 12) NOT NULL,
    DISCAMOUNT        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_VENDINVOICETRANS_FattureFornitore_Riga PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PURCHID,
        INVOICEID,
        INVOICEDATE,
        NUMBERSEQUENCEGROUP,
        INTERNALINVOICEID,
        LINENUM
    )
);

END;
GO

