
CREATE PROCEDURE AX2009.usp_AddIndexes_TAXDATA_DettaglioIVA
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_TAXDATA_DettaglioIVA_ ON AX2009.TAXDATA_DettaglioIVA () INCLUDE();

END;
GO

