
CREATE PROCEDURE AX2009.usp_Create_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METPAINTINGSETUPTABLE_ParametriLineaVerniciatura (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PAINTINGLINEID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni

    -- Misure
    PROCESSTIMECALCTYPE        SMALLINT NOT NULL,
    CHAINSPEED        NUMERIC(28, 12) NOT NULL,
    HOOKSPERMETER        NUMERIC(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PAINTINGLINEID
    )
);

END;
GO

