
CREATE PROCEDURE AX2009.usp_Create_EMPLTABLE_Dipendente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.EMPLTABLE_Dipendente (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	EMPLID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	PARTYID		NVARCHAR(20) NOT NULL,
	PBAUSERPROFILE		NVARCHAR(10) NOT NULL,
	DIMENSION6_		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_EMPLTABLE_Dipendente PRIMARY KEY CLUSTERED (
		DATAAREAID,
		EMPLID
	)
);

END;
GO

