
CREATE PROCEDURE AX2009.usp_Create_UNIT_UnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.UNIT_UnitaDiMisura (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	UNITID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TXT		NVARCHAR(60) NOT NULL,
	UNITDECIMALS		TINYINT NOT NULL,
	NPOTYPEUNITPCS		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_UNIT_UnitaDiMisura PRIMARY KEY CLUSTERED (
		DATAAREAID,
		UNITID
	)
);

END;
GO

