
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTDIM_DimensioneInventariale
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTDIM_DimensioneInventariale_ ON AX2009.INVENTDIM_DimensioneInventariale () INCLUDE();
CREATE NONCLUSTERED INDEX IX_AX2009_INVENTDIM_DimensioneInventariale_INVENTDIMID_INVENTLOCATIONID ON AX2009.INVENTDIM_DimensioneInventariale (INVENTDIMID,INVENTLOCATIONID);

END;
GO

