
CREATE PROCEDURE AX2009.usp_Merge_CUSTTRANS_TransazioniCliente
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTTRANS_TransazioniCliente', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_CUSTTRANS_TransazioniCliente;
	EXEC AX2009.usp_AddIndexes_CUSTTRANS_TransazioniCliente;
END;

MERGE INTO AX2009.CUSTTRANS_TransazioniCliente AS TGT
USING AX2009.CUSTTRANS_TransazioniClienteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM AND SRC.DUEDATE = TGT.DUEDATE AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.TRANSDATE <> SRC.TRANSDATE OR TGT.PAYMMODE <> SRC.PAYMMODE OR TGT.BILLOFEXCHANGEID <> SRC.BILLOFEXCHANGEID OR TGT.BILLOFEXCHANGESTATUS <> SRC.BILLOFEXCHANGESTATUS OR TGT.BILLOFEXCHANGESEQNUM <> SRC.BILLOFEXCHANGESEQNUM OR TGT.BANKREMITTANCEFILEID <> SRC.BANKREMITTANCEFILEID OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.AMOUNTCUR <> SRC.AMOUNTCUR OR TGT.AMOUNTMST <> SRC.AMOUNTMST)
  THEN UPDATE SET TGT.TRANSDATE = SRC.TRANSDATE, TGT.PAYMMODE = SRC.PAYMMODE, TGT.BILLOFEXCHANGEID = SRC.BILLOFEXCHANGEID, TGT.BILLOFEXCHANGESTATUS = SRC.BILLOFEXCHANGESTATUS, TGT.BILLOFEXCHANGESEQNUM = SRC.BILLOFEXCHANGESEQNUM, TGT.BANKREMITTANCEFILEID = SRC.BANKREMITTANCEFILEID, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.AMOUNTCUR = SRC.AMOUNTCUR, TGT.AMOUNTMST = SRC.AMOUNTMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ACCOUNTNUM, DUEDATE, RECID, TRANSDATE, PAYMMODE, BILLOFEXCHANGEID, BILLOFEXCHANGESTATUS, BILLOFEXCHANGESEQNUM, BANKREMITTANCEFILEID, CURRENCYCODE, AMOUNTCUR, AMOUNTMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.CUSTTRANS_TransazioniCliente' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) + ' - ' + 'DUEDATE = ' + CAST(COALESCE(inserted.DUEDATE, deleted.DUEDATE) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

