
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPRODUCTIONTAG_CartellinoProduzione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPRODUCTIONTAG_CartellinoProduzione_MASTERWRKCTRID_INCLUDE ON [AX2009].[NPOPRODUCTIONTAG_CartellinoProduzione] ([MASTERWRKCTRID]) INCLUDE ([DATAAREAID],[PRODID],[PRODLENGTH],[PRESETESTRBACKLENGTH],[PRESETESTRCROP],[PRESETBARSINBILLET])
CREATE NONCLUSTERED INDEX IX_AX2009_NPOPRODUCTIONTAG_CartellinoProduzione_MASTERWRKCTRID_INCLUDE ON [AX2009].[NPOPRODUCTIONTAG_CartellinoProduzione] ([MASTERWRKCTRID]) INCLUDE ([PRODLENGTH],[PRESETESTRBACKLENGTH],[PRESETESTRCROP],[PRESETBARSINBILLET])

END;
GO

