
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTRANSFERTABLE_OrdiniTrasferimento
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTRANSFERTABLE_OrdiniTrasferimento_ ON AX2009.INVENTTRANSFERTABLE_OrdiniTrasferimento () INCLUDE();

END;
GO

