
CREATE PROCEDURE AX2009.usp_Merge_NPOWORKCALENDARDATELINE_DataLavorativa_Turno
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOWORKCALENDARDATELINE_DataLavorativa_Turno', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOWORKCALENDARDATELINE_DataLavorativa_Turno;
	EXEC AX2009.usp_AddIndexes_NPOWORKCALENDARDATELINE_DataLavorativa_Turno;
END;

MERGE INTO AX2009.NPOWORKCALENDARDATELINE_DataLavorativa_Turno AS TGT
USING AX2009.NPOWORKCALENDARDATELINE_DataLavorativa_TurnoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.CALENDARID = TGT.CALENDARID AND SRC.SHIFTID = TGT.SHIFTID
WHEN MATCHED AND (TGT.DURATION <> SRC.DURATION OR TGT.FROMTIME <> SRC.FROMTIME)
  THEN UPDATE SET TGT.DURATION = SRC.DURATION, TGT.FROMTIME = SRC.FROMTIME
WHEN NOT MATCHED
  THEN INSERT (DATAAREAID, TRANSDATE, CALENDARID, SHIFTID, RECID, DURATION, FROMTIME) VALUES (DATAAREAID, TRANSDATE, CALENDARID, SHIFTID, RECID, DURATION, FROMTIME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOWORKCALENDARDATELINE_DataLavorativa_Turno' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'CALENDARID = ' + CAST(COALESCE(inserted.CALENDARID, deleted.CALENDARID) AS NVARCHAR) + ' - ' + 'SHIFTID = ' + CAST(COALESCE(inserted.SHIFTID, deleted.SHIFTID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

