
CREATE PROCEDURE AX2009.usp_Merge_BANKREMITTANCEFILESCUST_FileRimesseClienti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.BANKREMITTANCEFILESCUST_FileRimesseClienti', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_BANKREMITTANCEFILESCUST_FileRimesseClienti;
	EXEC AX2009.usp_AddIndexes_BANKREMITTANCEFILESCUST_FileRimesseClienti;
END;

MERGE INTO AX2009.BANKREMITTANCEFILESCUST_FileRimesseClienti AS TGT
USING AX2009.BANKREMITTANCEFILESCUST_FileRimesseClientiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.FILEID = TGT.FILEID
WHEN MATCHED AND (TGT.BANKACCOUNTID <> SRC.BANKACCOUNTID OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.AMOUNTMST <> SRC.AMOUNTMST)
  THEN UPDATE SET TGT.BANKACCOUNTID = SRC.BANKACCOUNTID, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.AMOUNTMST = SRC.AMOUNTMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, FILEID, RECID, BANKACCOUNTID, CREATEDDATETIME, AMOUNTMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.BANKREMITTANCEFILESCUST_FileRimesseClienti' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'FILEID = ' + CAST(COALESCE(inserted.FILEID, deleted.FILEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

