
CREATE PROCEDURE AX2009.usp_Create_METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    BATCHID        DATETIME NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    ORDERTYPE        BIT NOT NULL,
    WMSORDERTRANSEXPEDITIONSTATUS        SMALLINT NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    ORDERID        NVARCHAR(20) NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,
    DLVDATE        DATE NOT NULL,
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    INVENTTRANSTYPE        SMALLINT NOT NULL,
    INVENTTRANSREFID        NVARCHAR(20) NOT NULL,
    SALESID        NVARCHAR(20) NOT NULL,
    LINENUM        INT NOT NULL,
    INVENTLOCATIONIDTO        NVARCHAR(10) NOT NULL,
    ITEMFINISHINGID        NVARCHAR(512) NOT NULL,
    ITEMFINISHINGIDFINAL        NVARCHAR(512) NOT NULL,
    INVENTITEMTYPE        NVARCHAR(20) NOT NULL,
    PICKAVAILABLE        BIT NOT NULL,

    -- Misure
    REMAINONHANDQTY        DECIMAL(28, 12) NOT NULL,
    QTY        DECIMAL(28, 12) NOT NULL,
    REMAINSALESPHYSICAL        DECIMAL(28, 12) NOT NULL

    -- Constraint
    CONSTRAINT PK_METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi PRIMARY KEY CLUSTERED (
        DATAAREAID,
        BATCHID,
        RECID
    )
);

END;
GO

