
CREATE PROCEDURE AX2009.usp_AddIndexes_SALESLINE_OrdiniCliente_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SALESLINE_OrdiniCliente_Riga_ ON AX2009.SALESLINE_OrdiniCliente_Riga () INCLUDE();
CREATE UNIQUE NONCLUSTERED INDEX IX_AX2009_SALESLINE_OrdiniCliente_Riga_DATAAREAID_SALESID_INVENTTRANSID_filtered ON AX2009.SALESLINE_OrdiniCliente_Riga (DATAAREAID, SALESID, INVENTTRANSID) WHERE NPOREVENUESALESLINE = 1;
CREATE NONCLUSTERED INDEX IX_AX2009_SALESLINE_OrdiniCliente_Riga_DATAAREAID_SALESID_INVENTTRANSID_INCLUDE ON [AX2009].[SALESLINE_OrdiniCliente_Riga] ([DATAAREAID],[SALESID],[INVENTTRANSID]) INCLUDE ([RECID],[NPOFINISHINGID]);
CREATE NONCLUSTERED INDEX IX_AX2009_SALESLINE_OrdiniCliente_Riga_DATAAREAID_INVENTREFTYPE_NPOOTHERINFO_INCLUDE ON [AX2009].[SALESLINE_OrdiniCliente_Riga] ([DATAAREAID],[INVENTREFTYPE],[NPOOTHERINFO]) INCLUDE ([SALESID],[RECID],[INVENTREFID])
CREATE NONCLUSTERED INDEX IX_AX2009_SALESLINE_OrdiniCliente_Riga_DATAAREAID_NPOOTHERINFO_INCLUDE ON [AX2009].[SALESLINE_OrdiniCliente_Riga] ([DATAAREAID],[NPOOTHERINFO]) INCLUDE ([SALESID],[RECID],[ITEMID],[INVENTTRANSID],[NPOSALESUNIT])
CREATE NONCLUSTERED INDEX IX_AX2009_SALESLINE_OrdiniCliente_Riga_INVENTTRANSID ON [AX2009].[SALESLINE_OrdiniCliente_Riga] ([INVENTTRANSID]);

END;
GO

