
CREATE PROCEDURE AX2009.usp_Merge_INTRASTATTRANSPORTMODE_Trasporto
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INTRASTATTRANSPORTMODE_Trasporto', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_INTRASTATTRANSPORTMODE_Trasporto;
    EXEC AX2009.usp_AddIndexes_INTRASTATTRANSPORTMODE_Trasporto;
END;

MERGE INTO AX2009.INTRASTATTRANSPORTMODE_Trasporto AS TGT
USING AX2009.INTRASTATTRANSPORTMODE_TrasportoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSPORTCODE = TGT.TRANSPORTCODE
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, TRANSPORTCODE, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.INTRASTATTRANSPORTMODE_Trasporto' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSPORTCODE = ' + CAST(COALESCE(inserted.TRANSPORTCODE, deleted.TRANSPORTCODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

