
CREATE PROCEDURE AX2009.usp_Create_ROUTE_Ciclo_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ROUTE_Ciclo_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ROUTEID		NVARCHAR(20) NOT NULL,
	OPRNUM		INT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	OPRID		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_ROUTE_Ciclo_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ROUTEID,
		OPRNUM,
		RECID
	)
);

END;
GO

