
CREATE PROCEDURE AX2009.usp_Create_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SMMBUSRELSUBSEGMENTGROUP_Sottosegmento (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    SEGMENTID        NVARCHAR(20) NOT NULL,
    SUBSEGMENTID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    SUBSEGMENTDESCRIPTION        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento PRIMARY KEY CLUSTERED (
        DATAAREAID,
        SEGMENTID,
        SUBSEGMENTID
    )
);

END;
GO

