
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating_ ON AX2009.NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating () INCLUDE();

END;
GO

