
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTLOCATION_Magazzino
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTLOCATION_Magazzino_ ON AX2009.INVENTLOCATION_Magazzino () INCLUDE();

END;
GO

