
CREATE PROCEDURE AX2009.usp_Create_COSTINGVERSION_VersioneDeterminazioneCosti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.COSTINGVERSION_VersioneDeterminazioneCosti (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	VERSIONID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	LASTUPDATE		DATE NOT NULL,
	LASTACTIVATION		DATE NOT NULL


	-- Constraint
	CONSTRAINT PK_COSTINGVERSION_VersioneDeterminazioneCosti PRIMARY KEY CLUSTERED (
		DATAAREAID,
		VERSIONID
	)
);

END;
GO

