CREATE PROCEDURE AX2009.usp_Merge_ASSETTABLE_Cespite
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.ASSETTABLE_Cespite', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_ASSETTABLE_Cespite;
    EXEC AX2009.usp_AddIndexes_ASSETTABLE_Cespite;
END;

MERGE INTO AX2009.ASSETTABLE_Cespite AS TGT
USING AX2009.ASSETTABLE_CespiteView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ASSETID = TGT.ASSETID
WHEN MATCHED AND (TGT.ASSETGROUP <> SRC.ASSETGROUP OR TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.ASSETGROUP = SRC.ASSETGROUP, TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ASSETID, RECID, ASSETGROUP, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.ASSETTABLE_Cespite' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ASSETID = ' + CAST(COALESCE(inserted.ASSETID, deleted.ASSETID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

