
CREATE PROCEDURE AX2009.usp_Merge_NPOBICOLORWEBSETUP_FinituraBicolore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOBICOLORWEBSETUP_FinituraBicolore', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOBICOLORWEBSETUP_FinituraBicolore;
	EXEC AX2009.usp_AddIndexes_NPOBICOLORWEBSETUP_FinituraBicolore;
END;

MERGE INTO AX2009.NPOBICOLORWEBSETUP_FinituraBicolore AS TGT
USING AX2009.NPOBICOLORWEBSETUP_FinituraBicoloreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BICOLORCODE = TGT.BICOLORCODE
WHEN MATCHED AND (TGT.INTERNALFINISHINGID <> SRC.INTERNALFINISHINGID OR TGT.EXTERNALFINISHINGID <> SRC.EXTERNALFINISHINGID OR TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.INTERNALFINISHINGID = SRC.INTERNALFINISHINGID, TGT.EXTERNALFINISHINGID = SRC.EXTERNALFINISHINGID, TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BICOLORCODE, RECID, INTERNALFINISHINGID, EXTERNALFINISHINGID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOBICOLORWEBSETUP_FinituraBicolore' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BICOLORCODE = ' + CAST(COALESCE(inserted.BICOLORCODE, deleted.BICOLORCODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

