
CREATE PROCEDURE AX2009.usp_Merge_VENDINVOICEJOUR_FattureFornitore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.VENDINVOICEJOUR_FattureFornitore', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_VENDINVOICEJOUR_FattureFornitore;
	EXEC AX2009.usp_AddIndexes_VENDINVOICEJOUR_FattureFornitore;
END;

MERGE INTO AX2009.VENDINVOICEJOUR_FattureFornitore AS TGT
USING AX2009.VENDINVOICEJOUR_FattureFornitoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PURCHID = TGT.PURCHID AND SRC.INVOICEID = TGT.INVOICEID AND SRC.INVOICEDATE = TGT.INVOICEDATE AND SRC.NUMBERSEQUENCEGROUP = TGT.NUMBERSEQUENCEGROUP AND SRC.INTERNALINVOICEID = TGT.INTERNALINVOICEID
WHEN MATCHED AND (TGT.ORDERACCOUNT <> SRC.ORDERACCOUNT OR TGT.INVOICEACCOUNT <> SRC.INVOICEACCOUNT OR TGT.LEDGERVOUCHER <> SRC.LEDGERVOUCHER OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.EXCHRATE <> SRC.EXCHRATE OR TGT.INVOICEAMOUNT <> SRC.INVOICEAMOUNT OR TGT.INVOICEAMOUNTMST <> SRC.INVOICEAMOUNTMST OR TGT.SALESBALANCE <> SRC.SALESBALANCE OR TGT.SUMMARKUP <> SRC.SUMMARKUP OR TGT.SUMMARKUPMST <> SRC.SUMMARKUPMST OR TGT.SUMTAX <> SRC.SUMTAX)
  THEN UPDATE SET TGT.ORDERACCOUNT = SRC.ORDERACCOUNT, TGT.INVOICEACCOUNT = SRC.INVOICEACCOUNT, TGT.LEDGERVOUCHER = SRC.LEDGERVOUCHER, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.EXCHRATE = SRC.EXCHRATE, TGT.INVOICEAMOUNT = SRC.INVOICEAMOUNT, TGT.INVOICEAMOUNTMST = SRC.INVOICEAMOUNTMST, TGT.SALESBALANCE = SRC.SALESBALANCE, TGT.SUMMARKUP = SRC.SUMMARKUP, TGT.SUMMARKUPMST = SRC.SUMMARKUPMST, TGT.SUMTAX = SRC.SUMTAX
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PURCHID, INVOICEID, INVOICEDATE, NUMBERSEQUENCEGROUP, INTERNALINVOICEID, RECID, ORDERACCOUNT, INVOICEACCOUNT, LEDGERVOUCHER, CURRENCYCODE, EXCHRATE, INVOICEAMOUNT, INVOICEAMOUNTMST, SALESBALANCE, SUMMARKUP, SUMMARKUPMST, SUMTAX)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.VENDINVOICEJOUR_FattureFornitore' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PURCHID = ' + CAST(COALESCE(inserted.PURCHID, deleted.PURCHID) AS NVARCHAR) + ' - ' + 'INVOICEID = ' + CAST(COALESCE(inserted.INVOICEID, deleted.INVOICEID) AS NVARCHAR) + ' - ' + 'INVOICEDATE = ' + CAST(COALESCE(inserted.INVOICEDATE, deleted.INVOICEDATE) AS NVARCHAR) + ' - ' + 'NUMBERSEQUENCEGROUP = ' + CAST(COALESCE(inserted.NUMBERSEQUENCEGROUP, deleted.NUMBERSEQUENCEGROUP) AS NVARCHAR) + ' - ' + 'INTERNALINVOICEID = ' + CAST(COALESCE(inserted.INTERNALINVOICEID, deleted.INTERNALINVOICEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

