
CREATE PROCEDURE AX2009.usp_AddIndexes_SYSCOMPANYUSERINFO_RelazioneUtente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SYSCOMPANYUSERINFO_RelazioneUtente_ ON AX2009.SYSCOMPANYUSERINFO_RelazioneUtente () INCLUDE();

END;
GO

