
CREATE PROCEDURE AX2009.usp_Create_METWMSORDERTRANSPLANNED_PianificazionePrelievi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METWMSORDERTRANSPLANNED_PianificazionePrelievi (
    -- Chiavi
    RECID        BIGINT NOT NULL,

    -- Dimensioni

    -- Misure
    REQPOID        NVARCHAR(20) NOT NULL,
    CRSNUM        NVARCHAR(20) NOT NULL,
    CRSEXPEDITIONSTATUS        SMALLINT NOT NULL,
    COVERINGBASIS        SMALLINT NOT NULL,
    ANALYSISTYPE        SMALLINT NOT NULL,
    INCLUDEINBOUNDDOCK        BIT NOT NULL,
    SHIPMENTTYPE        SMALLINT NOT NULL,
    PROCESSNUM        NVARCHAR(10) NOT NULL,
    PICKINGSTATUS        SMALLINT NOT NULL,
    REMAINONHANDQTY        DECIMAL(28, 12) NOT NULL,
    REMAINPHYSICAL        DECIMAL(28, 12) NOT NULL,
    REMAINSALESPHYSICAL        DECIMAL(28, 12) NOT NULL,
    PICKINGROUTEID        NVARCHAR(10) NOT NULL,
    SHIPMENTID        NVARCHAR(10) NOT NULL,
    PICKINGROUTEEXPEDITIONSTATUS        SMALLINT NOT NULL,
    INVENTLOCATIONID        NVARCHAR(10) NOT NULL,
    WORKSPACE        INT NOT NULL,
    DLVSTATIONID        NVARCHAR(10) NOT NULL,
    DLVAREAID        NVARCHAR(10) NOT NULL,
    QTY        DECIMAL(28, 12) NOT NULL,
    ORDERTYPE        SMALLINT NOT NULL,
    WMSORDERTRANSEXPEDITIONSTATUS        SMALLINT NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    ORDERID        NVARCHAR(20) NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,
    DLVDATE        DATE NOT NULL,
    INVENTTRANSID        NVARCHAR(20) NOT NULL,
    INVENTTRANSTYPE        SMALLINT NOT NULL,
    INVENTTRANSREFID        NVARCHAR(20) NOT NULL,
    CUSTOMER        NVARCHAR(20) NOT NULL,
    DELIVERYADDRESS        NVARCHAR(250) NOT NULL,
    KASTOID        NVARCHAR(20) NOT NULL,
    SALESIDSPLIT        NVARCHAR(20) NOT NULL,
    DATAAREAID        CHAR(4) NOT NULL,
    PICKAVAILABLE        SMALLINT NOT NULL,
    INVENTITEMTYPE        NVARCHAR(20) NOT NULL,
    ITEMFINISHINGIDFINAL        NVARCHAR(512) NOT NULL,
    ITEMFINISHINGID        NVARCHAR(512) NOT NULL,
    INVENTLOCATIONIDTO        NVARCHAR(10) NOT NULL,
    LINENUM        INT NOT NULL,
    SALESID        NVARCHAR(20) NOT NULL,
    INVENTDIMIDONHAND        NVARCHAR(20) NOT NULL,
    SHIPMENTTABLEINIT        BIT NOT NULL

    -- Constraint
    CONSTRAINT PK_METWMSORDERTRANSPLANNED_PianificazionePrelievi PRIMARY KEY CLUSTERED (
        RECID
    )
);

END;
GO

