
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTINVOICETABLE_FattureClienteTestoLibero
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTINVOICETABLE_FattureClienteTestoLibero_ ON AX2009.CUSTINVOICETABLE_FattureClienteTestoLibero () INCLUDE();

END;
GO

