
CREATE PROCEDURE AX2009.usp_Merge_SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale;
    EXEC AX2009.usp_AddIndexes_SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale;
END;

MERGE INTO AX2009.SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale AS TGT
USING AX2009.SMMBUSRELSECTORTABLE_RubricaSettoreCommercialeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PARTYID = TGT.PARTYID AND SRC.BUSINESSSECTORID = TGT.BUSINESSSECTORID
--WHEN MATCHED AND ()
--  THEN UPDATE SET 
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PARTYID, BUSINESSSECTORID, RECID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PARTYID = ' + CAST(COALESCE(inserted.PARTYID, deleted.PARTYID) AS NVARCHAR) + ' - ' + 'BUSINESSSECTORID = ' + CAST(COALESCE(inserted.BUSINESSSECTORID, deleted.BUSINESSSECTORID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

