
CREATE PROCEDURE AX2009.usp_AddIndexes_AIFENDPOINT_AIFEndPoint
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_AIFENDPOINT_AIFEndPoint_ ON AX2009.AIFENDPOINT_AIFEndPoint () INCLUDE();

END;
GO

