
CREATE PROCEDURE AX2009.usp_Create_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	JOURNALID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DESCRIPTION		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale PRIMARY KEY CLUSTERED (
		DATAAREAID,
		JOURNALID
	)
);

END;
GO

