
CREATE PROCEDURE AX2009.usp_Create_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	DELIVERYDATE		DATE NOT NULL,
	INVENTPACKINGSLIPID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TRANSFERID		NVARCHAR(20) NOT NULL,
	DELIVERYNAME		NVARCHAR(60) NOT NULL,
	DELIVERYADDRESS		NVARCHAR(250) NOT NULL,
	DLVMODE		NVARCHAR(10) NOT NULL,
	JOURNEYID		NVARCHAR(20) NOT NULL,
	REFDATAAREAID		NVARCHAR(4) NOT NULL,

	-- Misure
	WEIGHT		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna PRIMARY KEY CLUSTERED (
		DATAAREAID,
		DELIVERYDATE,
		INVENTPACKINGSLIPID,
		RECID
	)
);

END;
GO

