
CREATE PROCEDURE AX2009.usp_Create_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA (
	-- Chiavi
	DATAAREAID  CHAR(4) NOT NULL,
	NPOPBAFINISHINGID  NVARCHAR(10) NOT NULL,
	ITEMIDDEFAULT  NVARCHAR(20) NOT NULL,
	RECID  BIGINT NOT NULL,

	-- Dimensioni
	DEFAULT_  BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA PRIMARY KEY CLUSTERED (
		DATAAREAID,
		NPOPBAFINISHINGID,
		ITEMIDDEFAULT
	)
);

END;
GO

