
CREATE PROCEDURE AX2009.usp_Merge_INVENTITEMLOCATION_ArticoloDimensioneInventariale
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTITEMLOCATION_ArticoloDimensioneInventariale', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTITEMLOCATION_ArticoloDimensioneInventariale;
	EXEC AX2009.usp_AddIndexes_INVENTITEMLOCATION_ArticoloDimensioneInventariale;
END;

MERGE INTO AX2009.INVENTITEMLOCATION_ArticoloDimensioneInventariale AS TGT
USING AX2009.INVENTITEMLOCATION_ArticoloDimensioneInventarialeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMID = TGT.ITEMID AND SRC.INVENTDIMID = TGT.INVENTDIMID
WHEN MATCHED AND (TGT.NPODLVAREAID <> SRC.NPODLVAREAID)
  THEN UPDATE SET TGT.NPODLVAREAID = SRC.NPODLVAREAID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMID, INVENTDIMID, RECID, NPODLVAREAID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTITEMLOCATION_ArticoloDimensioneInventariale' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'INVENTDIMID = ' + CAST(COALESCE(inserted.INVENTDIMID, deleted.INVENTDIMID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

