
CREATE PROCEDURE AX2009.usp_Merge_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti;
	EXEC AX2009.usp_AddIndexes_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti;
END;

MERGE INTO AX2009.METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti AS TGT
USING AX2009.METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndirettiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SECTORTYPE = TGT.SECTORTYPE AND SRC.MNGTYPE = TGT.MNGTYPE AND SRC.INVENTITEMTYPE = TGT.INVENTITEMTYPE AND SRC.FROMDATE = TGT.FROMDATE AND SRC.FILTERCODE = TGT.FILTERCODE AND SRC.CUSTACCOUNT = TGT.CUSTACCOUNT
WHEN MATCHED AND (TGT.COSTCALCULATIONTYPE <> SRC.COSTCALCULATIONTYPE OR TGT.PERCENT_ <> SRC.PERCENT_)
  THEN UPDATE SET TGT.COSTCALCULATIONTYPE = SRC.COSTCALCULATIONTYPE, TGT.PERCENT_ = SRC.PERCENT_
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SECTORTYPE, MNGTYPE, INVENTITEMTYPE, FROMDATE, FILTERCODE, CUSTACCOUNT, RECID, COSTCALCULATIONTYPE, PERCENT_)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SECTORTYPE = ' + CAST(COALESCE(inserted.SECTORTYPE, deleted.SECTORTYPE) AS NVARCHAR) + ' - ' + 'MNGTYPE = ' + CAST(COALESCE(inserted.MNGTYPE, deleted.MNGTYPE) AS NVARCHAR) + ' - ' + 'INVENTITEMTYPE = ' + CAST(COALESCE(inserted.INVENTITEMTYPE, deleted.INVENTITEMTYPE) AS NVARCHAR) + ' - ' + 'FROMDATE = ' + CAST(COALESCE(inserted.FROMDATE, deleted.FROMDATE) AS NVARCHAR) + ' - ' + 'FILTERCODE = ' + CAST(COALESCE(inserted.FILTERCODE, deleted.FILTERCODE) AS NVARCHAR) + ' - ' + 'CUSTACCOUNT = ' + CAST(COALESCE(inserted.CUSTACCOUNT, deleted.CUSTACCOUNT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

