
CREATE PROCEDURE AX2009.usp_Merge_SRSANALYSISENUMS_Etichetta
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.SRSANALYSISENUMS_Etichetta', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_SRSANALYSISENUMS_Etichetta;
	EXEC AX2009.usp_AddIndexes_SRSANALYSISENUMS_Etichetta;
END;

MERGE INTO AX2009.SRSANALYSISENUMS_Etichetta AS TGT
USING AX2009.SRSANALYSISENUMS_EtichettaView (nolock) AS SRC
ON SRC.ENUMNAME = TGT.ENUMNAME AND SRC.ENUMITEMVALUE = TGT.ENUMITEMVALUE AND SRC.LANGUAGEID = TGT.LANGUAGEID
WHEN MATCHED AND (TGT.ENUMITEMLABEL <> SRC.ENUMITEMLABEL)
  THEN UPDATE SET TGT.ENUMITEMLABEL = SRC.ENUMITEMLABEL
WHEN NOT MATCHED
  THEN INSERT VALUES (ENUMNAME, ENUMITEMVALUE, LANGUAGEID, RECID, ENUMITEMLABEL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.SRSANALYSISENUMS_Etichetta' AS full_olap_table_name,
	'ENUMNAME = ' + CAST(COALESCE(inserted.ENUMNAME, deleted.ENUMNAME) AS NVARCHAR) + ' - ' + 'ENUMITEMVALUE = ' + CAST(COALESCE(inserted.ENUMITEMVALUE, deleted.ENUMITEMVALUE) AS NVARCHAR) + ' - ' + 'LANGUAGEID = ' + CAST(COALESCE(inserted.LANGUAGEID, deleted.LANGUAGEID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

