
CREATE PROCEDURE AX2009.usp_Create_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	LOTID		NVARCHAR(15) NOT NULL,
	PRODID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	SALESID		NVARCHAR(20) NOT NULL,
	LOTLENGTH		NUMERIC(28, 12) NOT NULL,
	SALESNPOLINENUM		INT NOT NULL,

	-- Misure
	ASSIGNEDQTY		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione PRIMARY KEY CLUSTERED (
		DATAAREAID,
		LOTID,
		PRODID
	)
);

END;
GO

