
CREATE PROCEDURE AX2009.usp_Merge_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio;
	EXEC AX2009.usp_AddIndexes_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio;
END;

MERGE INTO AX2009.METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio AS TGT
USING AX2009.METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggioView (NOLOCK) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.MNGTYPE = TGT.MNGTYPE AND SRC.FROMDATE = TGT.FROMDATE
WHEN MATCHED AND (TGT.AMOUNT <> SRC.AMOUNT)
  THEN UPDATE SET TGT.AMOUNT = SRC.AMOUNT
WHEN NOT MATCHED
  THEN INSERT VALUES (SRC.DATAAREAID, SRC.MNGTYPE, SRC.FROMDATE, SRC.RECID, SRC.AMOUNT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'MNGTYPE = ' + CAST(COALESCE(inserted.MNGTYPE, deleted.MNGTYPE) AS NVARCHAR) + ' - ' + 'FROMDATE = ' + CAST(COALESCE(inserted.FROMDATE, deleted.FROMDATE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

