
CREATE PROCEDURE AX2009.usp_Create_INVENTBATCH_Colata
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTBATCH_Colata (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    INVENTBATCHID        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    PRODDATE        DATE NOT NULL,
    METLOGLENGTH        INT NOT NULL,
    METINVENTSIZEID        NVARCHAR(10) NOT NULL,
    METINVENTCOLORID        NVARCHAR(10) NOT NULL


    -- Constraint
    CONSTRAINT PK_INVENTBATCH_Colata PRIMARY KEY CLUSTERED (
        DATAAREAID,
        ITEMID,
        INVENTBATCHID
    )
);

END;
GO

