CREATE PROCEDURE AX2009.usp_Merge_BOMCALCTABLE_CalcoloDBA
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.BOMCALCTABLE_CalcoloDBA', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_BOMCALCTABLE_CalcoloDBA;
	EXEC AX2009.usp_AddIndexes_BOMCALCTABLE_CalcoloDBA;
END;

WITH TGT
AS (
    SELECT *
    FROM AX2009.BOMCALCTABLE_CalcoloDBA
    WHERE TRANSDATE >= CAST('20230101' AS DATE)
)
MERGE INTO TGT
USING AX2009.BOMCALCTABLE_CalcoloDBAView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PRICECALCID = TGT.PRICECALCID
WHEN MATCHED AND (TGT.ITEMID <> SRC.ITEMID OR TGT.TRANSDATE <> SRC.TRANSDATE)
  THEN UPDATE SET TGT.ITEMID = SRC.ITEMID, TGT.TRANSDATE = SRC.TRANSDATE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PRICECALCID, RECID, ITEMID, TRANSDATE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.BOMCALCTABLE_CalcoloDBA' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PRICECALCID = ' + CAST(COALESCE(inserted.PRICECALCID, deleted.PRICECALCID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

