
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo_ ON AX2009.NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo () INCLUDE();

END;
GO

