
CREATE PROCEDURE AX2009.usp_Merge_ASSETTRANS_AmmortamentoCespiti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.ASSETTRANS_AmmortamentoCespiti', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_ASSETTRANS_AmmortamentoCespiti;
    EXEC AX2009.usp_AddIndexes_ASSETTRANS_AmmortamentoCespiti;
END;

MERGE INTO AX2009.ASSETTRANS_AmmortamentoCespiti AS TGT
USING AX2009.ASSETTRANS_AmmortamentoCespitiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ASSETID = TGT.ASSETID AND SRC.VOUCHER = TGT.VOUCHER AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.TXT <> SRC.TXT OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.TRANSTYPE <> SRC.TRANSTYPE OR TGT.ASSETGROUP <> SRC.ASSETGROUP OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_ OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.AMOUNTCUR <> SRC.AMOUNTCUR OR TGT.AMOUNTMST <> SRC.AMOUNTMST)
  THEN UPDATE SET TGT.TXT = SRC.TXT, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.TRANSTYPE = SRC.TRANSTYPE, TGT.ASSETGROUP = SRC.ASSETGROUP, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.AMOUNTCUR = SRC.AMOUNTCUR, TGT.AMOUNTMST = SRC.AMOUNTMST
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ASSETID, VOUCHER, TRANSDATE, RECID, TXT, DIMENSION, DIMENSION2_, DIMENSION3_, TRANSTYPE, ASSETGROUP, DIMENSION4_, DIMENSION5_, DIMENSION6_, CURRENCYCODE, AMOUNTCUR, AMOUNTMST)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.ASSETTRANS_AmmortamentoCespiti' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ASSETID = ' + CAST(COALESCE(inserted.ASSETID, deleted.ASSETID) AS NVARCHAR) + ' - ' + 'VOUCHER = ' + CAST(COALESCE(inserted.VOUCHER, deleted.VOUCHER) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

