
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga_ ON AX2009.INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga () INCLUDE();

END;
GO

