
CREATE PROCEDURE AX2009.usp_Create_VENDGROUP_FornitoreGruppo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.VENDGROUP_FornitoreGruppo (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	VENDGROUP		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_VENDGROUP_FornitoreGruppo PRIMARY KEY CLUSTERED (
		DATAAREAID,
		VENDGROUP
	)
);

END;
GO

