
CREATE PROCEDURE AX2009.usp_Merge_INVENTTRANS_Transazioni
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTTRANS_Transazioni', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_INVENTTRANS_Transazioni;
    EXEC AX2009.usp_AddIndexes_INVENTTRANS_Transazioni;
END;

MERGE INTO AX2009.INVENTTRANS_Transazioni AS TGT
USING AX2009.INVENTTRANS_TransazioniView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.INVENTTRANSID = TGT.INVENTTRANSID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ITEMID <> SRC.ITEMID OR TGT.STATUSISSUE <> SRC.STATUSISSUE OR TGT.DATEPHYSICAL <> SRC.DATEPHYSICAL OR TGT.TRANSTYPE <> SRC.TRANSTYPE OR TGT.TRANSREFID <> SRC.TRANSREFID OR TGT.INVOICEID <> SRC.INVOICEID OR TGT.VOUCHER <> SRC.VOUCHER OR TGT.INVENTTRANSIDTRANSFER <> SRC.INVENTTRANSIDTRANSFER OR TGT.DATEFINANCIAL <> SRC.DATEFINANCIAL OR TGT.STATUSRECEIPT <> SRC.STATUSRECEIPT OR TGT.PACKINGSLIPID <> SRC.PACKINGSLIPID OR TGT.VOUCHERPHYSICAL <> SRC.VOUCHERPHYSICAL OR TGT.SHIPPINGDATEREQUESTED <> SRC.SHIPPINGDATEREQUESTED OR TGT.SHIPPINGDATECONFIRMED <> SRC.SHIPPINGDATECONFIRMED OR TGT.DIRECTION <> SRC.DIRECTION OR TGT.PICKINGROUTEID <> SRC.PICKINGROUTEID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.DATEINVENT <> SRC.DATEINVENT OR TGT.CUSTVENDAC <> SRC.CUSTVENDAC OR TGT.TRANSCHILDREFID <> SRC.TRANSCHILDREFID OR TGT.TRANSCHILDTYPE <> SRC.TRANSCHILDTYPE OR TGT.INVENTREFTRANSID <> SRC.INVENTREFTRANSID OR TGT.NPOVALUEBACKGROUND <> SRC.NPOVALUEBACKGROUND OR TGT.NCEREVENUEREFTRANSID <> SRC.NCEREVENUEREFTRANSID OR TGT.QTY <> SRC.QTY OR TGT.NPOINVENTQTYPHYSICALONHAND2UM <> SRC.NPOINVENTQTYPHYSICALONHAND2UM OR TGT.NPOPACKINGSLIPWEIGHT <> SRC.NPOPACKINGSLIPWEIGHT OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE OR TGT.COSTAMOUNTPOSTED <> SRC.COSTAMOUNTPOSTED OR TGT.COSTAMOUNTADJUSTMENT <> SRC.COSTAMOUNTADJUSTMENT OR TGT.COSTAMOUNTPHYSICAL <> SRC.COSTAMOUNTPHYSICAL OR TGT.REVENUEAMOUNTPHYSICAL <> SRC.REVENUEAMOUNTPHYSICAL)
  THEN UPDATE SET TGT.ITEMID = SRC.ITEMID, TGT.STATUSISSUE = SRC.STATUSISSUE, TGT.DATEPHYSICAL = SRC.DATEPHYSICAL, TGT.TRANSTYPE = SRC.TRANSTYPE, TGT.TRANSREFID = SRC.TRANSREFID, TGT.INVOICEID = SRC.INVOICEID, TGT.VOUCHER = SRC.VOUCHER, TGT.INVENTTRANSIDTRANSFER = SRC.INVENTTRANSIDTRANSFER, TGT.DATEFINANCIAL = SRC.DATEFINANCIAL, TGT.STATUSRECEIPT = SRC.STATUSRECEIPT, TGT.PACKINGSLIPID = SRC.PACKINGSLIPID, TGT.VOUCHERPHYSICAL = SRC.VOUCHERPHYSICAL, TGT.SHIPPINGDATEREQUESTED = SRC.SHIPPINGDATEREQUESTED, TGT.SHIPPINGDATECONFIRMED = SRC.SHIPPINGDATECONFIRMED, TGT.DIRECTION = SRC.DIRECTION, TGT.PICKINGROUTEID = SRC.PICKINGROUTEID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.DATEINVENT = SRC.DATEINVENT, TGT.CUSTVENDAC = SRC.CUSTVENDAC, TGT.TRANSCHILDREFID = SRC.TRANSCHILDREFID, TGT.TRANSCHILDTYPE = SRC.TRANSCHILDTYPE, TGT.INVENTREFTRANSID = SRC.INVENTREFTRANSID, TGT.NPOVALUEBACKGROUND = SRC.NPOVALUEBACKGROUND, TGT.NCEREVENUEREFTRANSID = SRC.NCEREVENUEREFTRANSID, TGT.DataTransazione = SRC.DataTransazione, TGT.QTY = SRC.QTY, TGT.NPOINVENTQTYPHYSICALONHAND2UM = SRC.NPOINVENTQTYPHYSICALONHAND2UM, TGT.NPOPACKINGSLIPWEIGHT = SRC.NPOPACKINGSLIPWEIGHT, TGT.CURRENCYCODE = SRC.CURRENCYCODE, TGT.COSTAMOUNTPOSTED = SRC.COSTAMOUNTPOSTED, TGT.COSTAMOUNTADJUSTMENT = SRC.COSTAMOUNTADJUSTMENT, TGT.COSTAMOUNTPHYSICAL = SRC.COSTAMOUNTPHYSICAL, TGT.REVENUEAMOUNTPHYSICAL = SRC.REVENUEAMOUNTPHYSICAL
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, INVENTTRANSID, RECID, ITEMID, STATUSISSUE, DATEPHYSICAL, TRANSTYPE, TRANSREFID, INVOICEID, VOUCHER, INVENTTRANSIDTRANSFER, DATEFINANCIAL, STATUSRECEIPT, PACKINGSLIPID, VOUCHERPHYSICAL, SHIPPINGDATEREQUESTED, SHIPPINGDATECONFIRMED, DIRECTION, PICKINGROUTEID, INVENTDIMID, DATEINVENT, CUSTVENDAC, TRANSCHILDREFID, TRANSCHILDTYPE, INVENTREFTRANSID, NPOVALUEBACKGROUND, NCEREVENUEREFTRANSID, DataTransazione, QTY, NPOINVENTQTYPHYSICALONHAND2UM, NPOPACKINGSLIPWEIGHT, CURRENCYCODE, COSTAMOUNTPOSTED, COSTAMOUNTADJUSTMENT, COSTAMOUNTPHYSICAL, REVENUEAMOUNTPHYSICAL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.INVENTTRANS_Transazioni' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'INVENTTRANSID = ' + CAST(COALESCE(inserted.INVENTTRANSID, deleted.INVENTTRANSID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

