
CREATE PROCEDURE AX2009.usp_AddIndexes_ASSETTRANS_AmmortamentoCespiti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ASSETTRANS_AmmortamentoCespiti_ ON AX2009.ASSETTRANS_AmmortamentoCespiti () INCLUDE();

END;
GO

