
CREATE PROCEDURE AX2009.usp_Create_BOM_VersioneDBA_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.BOM_VersioneDBA_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	BOMID		NVARCHAR(20) NOT NULL,
	LINENUM		NUMERIC(28, 12) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ITEMID		NVARCHAR(20) NOT NULL,
	BOMQTY		NUMERIC(28, 12) NOT NULL,
	FROMDATE		DATE NOT NULL,
	TODATE		DATE NOT NULL,
	INVENTDIMID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_BOM_VersioneDBA_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		BOMID,
		LINENUM,
		RECID
	)
);

END;
GO

