
CREATE PROCEDURE AX2009.usp_Create_TAXDATA_DettaglioIVA
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.TAXDATA_DettaglioIVA (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TAXCODE		NVARCHAR(10) NOT NULL,
	TAXFROMDATE		DATE NOT NULL,
	TAXTODATE		DATE NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	VATEXEMPTPCT		NUMERIC(28, 12) NOT NULL


	-- Constraint
	CONSTRAINT PK_TAXDATA_DettaglioIVA PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TAXCODE,
		TAXFROMDATE,
		TAXTODATE
	)
);

END;
GO

