
CREATE PROCEDURE AX2009.usp_Create_USERINFO_Utente
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.USERINFO_Utente (
	-- Chiavi
	ID		NVARCHAR(5) NOT NULL,
	NAME		NVARCHAR(40) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NETWORKALIAS		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_USERINFO_Utente PRIMARY KEY CLUSTERED (
		ID,
		NAME
	)
);

END;
GO

