
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga_ ON AX2009.CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga () INCLUDE();

END;
GO

