
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi_ ON AX2009.NPOITEMPRICEGROUP_ArticoloGruppoPrezzi () INCLUDE();

END;
GO

