
CREATE PROCEDURE AX2009.usp_Create_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PARTYID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ISPRIMARY		BIT NOT NULL,
	STATUS		SMALLINT NOT NULL,
	VALIDTODATETIME		DATE NOT NULL,
	VALIDFROMDATETIME		DATE NOT NULL,
	SHARED		BIT NOT NULL


	-- Constraint
	CONSTRAINT PK_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PARTYID,
		RECID
	)
);

END;
GO

