
CREATE PROCEDURE AX2009.usp_Merge_METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi;
    EXEC AX2009.usp_AddIndexes_METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi;
END;

MERGE INTO AX2009.METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi AS TGT
USING AX2009.METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelieviView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BATCHID = TGT.BATCHID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ORDERTYPE <> SRC.ORDERTYPE OR TGT.WMSORDERTRANSEXPEDITIONSTATUS <> SRC.WMSORDERTRANSEXPEDITIONSTATUS OR TGT.ITEMID <> SRC.ITEMID OR TGT.ORDERID <> SRC.ORDERID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.DLVDATE <> SRC.DLVDATE OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.INVENTTRANSTYPE <> SRC.INVENTTRANSTYPE OR TGT.INVENTTRANSREFID <> SRC.INVENTTRANSREFID OR TGT.SALESID <> SRC.SALESID OR TGT.LINENUM <> SRC.LINENUM OR TGT.INVENTLOCATIONIDTO <> SRC.INVENTLOCATIONIDTO OR TGT.ITEMFINISHINGID <> SRC.ITEMFINISHINGID OR TGT.ITEMFINISHINGIDFINAL <> SRC.ITEMFINISHINGIDFINAL OR TGT.INVENTITEMTYPE <> SRC.INVENTITEMTYPE OR TGT.PICKAVAILABLE <> SRC.PICKAVAILABLE OR TGT.REMAINONHANDQTY <> SRC.REMAINONHANDQTY OR TGT.QTY <> SRC.QTY OR TGT.REMAINSALESPHYSICAL <> SRC.REMAINSALESPHYSICAL)
  THEN UPDATE SET TGT.ORDERTYPE = SRC.ORDERTYPE, TGT.WMSORDERTRANSEXPEDITIONSTATUS = SRC.WMSORDERTRANSEXPEDITIONSTATUS, TGT.ITEMID = SRC.ITEMID, TGT.ORDERID = SRC.ORDERID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.DLVDATE = SRC.DLVDATE, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.INVENTTRANSTYPE = SRC.INVENTTRANSTYPE, TGT.INVENTTRANSREFID = SRC.INVENTTRANSREFID, TGT.SALESID = SRC.SALESID, TGT.LINENUM = SRC.LINENUM, TGT.INVENTLOCATIONIDTO = SRC.INVENTLOCATIONIDTO, TGT.ITEMFINISHINGID = SRC.ITEMFINISHINGID, TGT.ITEMFINISHINGIDFINAL = SRC.ITEMFINISHINGIDFINAL, TGT.INVENTITEMTYPE = SRC.INVENTITEMTYPE, TGT.PICKAVAILABLE = SRC.PICKAVAILABLE, TGT.REMAINONHANDQTY = SRC.REMAINONHANDQTY, TGT.QTY = SRC.QTY, TGT.REMAINSALESPHYSICAL = SRC.REMAINSALESPHYSICAL
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BATCHID, RECID, ORDERTYPE, WMSORDERTRANSEXPEDITIONSTATUS, ITEMID, ORDERID, INVENTDIMID, DLVDATE, INVENTTRANSID, INVENTTRANSTYPE, INVENTTRANSREFID, SALESID, LINENUM, INVENTLOCATIONIDTO, ITEMFINISHINGID, ITEMFINISHINGIDFINAL, INVENTITEMTYPE, PICKAVAILABLE, REMAINONHANDQTY, QTY, REMAINSALESPHYSICAL)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METWMSORDERTRANSPLANNEDHISTORY_StoricoPianificazionePrelievi' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BATCHID = ' + CAST(COALESCE(inserted.BATCHID, deleted.BATCHID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

