
CREATE PROCEDURE AX2009.usp_Create_SALESPOOL_PoolVendite
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SALESPOOL_PoolVendite (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	SALESPOOLID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_SALESPOOL_PoolVendite PRIMARY KEY CLUSTERED (
		DATAAREAID,
		SALESPOOLID
	)
);

END;
GO

