
CREATE PROCEDURE AX2009.usp_Merge_NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro;
    EXEC AX2009.usp_AddIndexes_NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro;
END;

MERGE INTO AX2009.NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro AS TGT
USING AX2009.NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoroView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.WRKCTRID = TGT.WRKCTRID AND SRC.YR = TGT.YR AND SRC.WEEK = TGT.WEEK AND SRC.ITEMID = TGT.ITEMID AND SRC.CUSTACCOUNT = TGT.CUSTACCOUNT
WHEN MATCHED AND (TGT.PRODID <> SRC.PRODID OR TGT.KG <> SRC.KG)
  THEN UPDATE SET TGT.PRODID = SRC.PRODID, TGT.KG = SRC.KG
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, WRKCTRID, YR, WEEK, ITEMID, CUSTACCOUNT, RECID, PRODID, KG)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'WRKCTRID = ' + CAST(COALESCE(inserted.WRKCTRID, deleted.WRKCTRID) AS NVARCHAR) + ' - ' + 'YR = ' + CAST(COALESCE(inserted.YR, deleted.YR) AS NVARCHAR) + ' - ' + 'WEEK = ' + CAST(COALESCE(inserted.WEEK, deleted.WEEK) AS NVARCHAR) + ' - ' + 'ITEMID = ' + CAST(COALESCE(inserted.ITEMID, deleted.ITEMID) AS NVARCHAR) + ' - ' + 'CUSTACCOUNT = ' + CAST(COALESCE(inserted.CUSTACCOUNT, deleted.CUSTACCOUNT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

