
CREATE PROCEDURE AX2009.usp_Create_RETURNDISPOSITIONCODE_CodiceSmaltimento
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.RETURNDISPOSITIONCODE_CodiceSmaltimento (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	DISPOSITIONCODEID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DESCRIPTION		NVARCHAR(60) NOT NULL,
	DISPOSITIONACTION		SMALLINT NOT NULL


	-- Constraint
	CONSTRAINT PK_RETURNDISPOSITIONCODE_CodiceSmaltimento PRIMARY KEY CLUSTERED (
		DATAAREAID,
		DISPOSITIONCODEID
	)
);

END;
GO

