
CREATE PROCEDURE AX2009.usp_AddIndexes_EXCHRATES_TassiDiCambio
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_EXCHRATES_TassiDiCambio_ ON AX2009.EXCHRATES_TassiDiCambio () INCLUDE();

END;
GO

