
CREATE PROCEDURE AX2009.usp_Create_ROUTEOPR_RelazioneOperativa
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ROUTEOPR_RelazioneOperativa (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	ITEMCODE		INT NOT NULL,
	ITEMRELATION		NVARCHAR(20) NOT NULL,
	ROUTECODE		INT NOT NULL,
	ROUTERELATION		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	OPRID		NVARCHAR(10) NOT NULL,
	WRKCTRID		NVARCHAR(10) NOT NULL


	-- Constraint
	CONSTRAINT PK_ROUTEOPR_RelazioneOperativa PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMCODE,
		ITEMRELATION,
		ROUTECODE,
		ROUTERELATION,
		RECID
	)
);

END;
GO

