
CREATE PROCEDURE AX2009.usp_AddIndexes_RETURNREASONCODEGROUP_GruppoMotivoReso
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_RETURNREASONCODEGROUP_GruppoMotivoReso_ ON AX2009.RETURNREASONCODEGROUP_GruppoMotivoReso () INCLUDE();

END;
GO

