
CREATE PROCEDURE AX2009.usp_Create_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	JOURNALNUM		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL


	-- Constraint
	CONSTRAINT PK_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile PRIMARY KEY CLUSTERED (
		DATAAREAID,
		JOURNALNUM
	)
);

END;
GO

