
CREATE PROCEDURE AX2009.usp_Create_AIFENDPOINT_AIFEndPoint
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.AIFENDPOINT_AIFEndPoint (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    ENDPOINTID        NVARCHAR(30) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    INTERCOMPANYCOMPANYID        CHAR(4) NOT NULL,
    NAME        NVARCHAR(60) NOT NULL


    -- Constraint
    CONSTRAINT PK_AIFENDPOINT_AIFEndPoint PRIMARY KEY CLUSTERED (
        DATAAREAID,
        ENDPOINTID
    )
);

END;
GO

