
CREATE PROCEDURE AX2009.usp_AddIndexes_ROUTEOPRTABLE_Operazione
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ROUTEOPRTABLE_Operazione_ ON AX2009.ROUTEOPRTABLE_Operazione () INCLUDE();

END;
GO

