
CREATE PROCEDURE AX2009.usp_Create_INVENTTRANSFERJOUR_OrdiniTrasferimento
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTTRANSFERJOUR_OrdiniTrasferimento (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSFERID		NVARCHAR(20) NOT NULL,
	VOUCHERID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TRANSDATE		DATE NOT NULL,
	TOADDRESSCOUNTY		NVARCHAR(10) NOT NULL,
	TOADDRESSSTATE		NVARCHAR(10) NOT NULL,
	TOADDRESSCOUNTRYREGIONID		NVARCHAR(10) NOT NULL,
	UPDATETYPE		SMALLINT NOT NULL,
	NPOINVENTPACKINGSLIPID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_INVENTTRANSFERJOUR_OrdiniTrasferimento PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSFERID,
		VOUCHERID
	)
);

END;
GO

