
CREATE PROCEDURE AX2009.usp_Create_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    ITEMID        NVARCHAR(20) NOT NULL,
    INVENTDIMID        NVARCHAR(20) NOT NULL,
    MODULETYPE        SMALLINT NOT NULL,
    CUSTVENDRELATION        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    EXTERNALITEMTXT        NVARCHAR(1000) NOT NULL,
    EXTERNALITEMID        NVARCHAR(30) NOT NULL


    -- Constraint
    CONSTRAINT PK_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo PRIMARY KEY CLUSTERED (
        DATAAREAID,
        ITEMID,
        INVENTDIMID,
        MODULETYPE,
        CUSTVENDRELATION
    )
);

END;
GO

