
CREATE PROCEDURE AX2009.usp_Create_ADDRESS_Indirizzo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.ADDRESS_Indirizzo (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	ADDRTABLEID		INT NOT NULL,
	ADDRRECID		BIGINT NOT NULL,
	TYPE		SMALLINT NOT NULL,
	NAME		NVARCHAR(60) NOT NULL,
	ADDRESS		NVARCHAR(250) NOT NULL,
	COUNTRYREGIONID		NVARCHAR(10) NOT NULL,
	ZIPCODE		NVARCHAR(10) NOT NULL,
	STATE		NVARCHAR(10) NOT NULL,
	COUNTY		NVARCHAR(10) NOT NULL,
	CITY		NVARCHAR(60) NOT NULL,
	STREET		NVARCHAR(250) NOT NULL


	-- Constraint
	CONSTRAINT PK_ADDRESS_Indirizzo PRIMARY KEY CLUSTERED (
		DATAAREAID,
		RECID
	)
);

END;
GO

