
CREATE PROCEDURE AX2009.usp_Create_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.CUSTBILLOFEXCHANGEJOUR_EffettiAttivi (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	BILLOFEXCHANGEID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	CUSTACCOUNT		NVARCHAR(20) NOT NULL,
	BILLOFEXCHANGESEQNUM		INT NOT NULL,
	STATUS		INT NOT NULL


	-- Constraint
	CONSTRAINT PK_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi PRIMARY KEY CLUSTERED (
		DATAAREAID,
		BILLOFEXCHANGEID
	)
);

END;
GO

