
CREATE PROCEDURE AX2009.usp_Merge_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi;
	EXEC AX2009.usp_AddIndexes_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi;
END;

MERGE INTO AX2009.DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi AS TGT
USING AX2009.DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizziView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PARTYADDRESSRELATIONSHIPRECID = TGT.PARTYADDRESSRELATIONSHIPRECID AND SRC.ADDRESSRECID = TGT.ADDRESSRECID AND SRC.REFCOMPANYID = TGT.REFCOMPANYID
--WHEN MATCHED AND ()
--  THEN UPDATE SET 
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PARTYADDRESSRELATIONSHIPRECID, ADDRESSRECID, REFCOMPANYID, RECID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PARTYADDRESSRELATIONSHIPRECID = ' + CAST(COALESCE(inserted.PARTYADDRESSRELATIONSHIPRECID, deleted.PARTYADDRESSRELATIONSHIPRECID) AS NVARCHAR) + ' - ' + 'ADDRESSRECID = ' + CAST(COALESCE(inserted.ADDRESSRECID, deleted.ADDRESSRECID) AS NVARCHAR) + ' - ' + 'REFCOMPANYID = ' + CAST(COALESCE(inserted.REFCOMPANYID, deleted.REFCOMPANYID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

