
CREATE PROCEDURE AX2009.usp_AddIndexes_REQGROUP_GruppoCopertura
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_REQGROUP_GruppoCopertura_ ON AX2009.REQGROUP_GruppoCopertura () INCLUDE();

END;
GO

