
CREATE PROCEDURE AX2009.usp_Merge_UNIT_UnitaDiMisura
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.UNIT_UnitaDiMisura', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_UNIT_UnitaDiMisura;
	EXEC AX2009.usp_AddIndexes_UNIT_UnitaDiMisura;
END;

MERGE INTO AX2009.UNIT_UnitaDiMisura AS TGT
USING AX2009.UNIT_UnitaDiMisuraView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.UNITID = TGT.UNITID
WHEN MATCHED AND (TGT.TXT <> SRC.TXT OR TGT.UNITDECIMALS <> SRC.UNITDECIMALS OR TGT.NPOTYPEUNITPCS <> SRC.NPOTYPEUNITPCS)
  THEN UPDATE SET TGT.TXT = SRC.TXT, TGT.UNITDECIMALS = SRC.UNITDECIMALS, TGT.NPOTYPEUNITPCS = SRC.NPOTYPEUNITPCS
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, UNITID, RECID, TXT, UNITDECIMALS, NPOTYPEUNITPCS)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.UNIT_UnitaDiMisura' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'UNITID = ' + CAST(COALESCE(inserted.UNITID, deleted.UNITID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

