
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo_ ON AX2009.CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo () INCLUDE();

END;
GO

