
CREATE PROCEDURE AX2009.usp_Merge_COMPANYINFO_InformazioniAzienda
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.COMPANYINFO_InformazioniAzienda', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_COMPANYINFO_InformazioniAzienda;
    EXEC AX2009.usp_AddIndexes_COMPANYINFO_InformazioniAzienda;
END;

MERGE INTO AX2009.COMPANYINFO_InformazioniAzienda AS TGT
USING AX2009.COMPANYINFO_InformazioniAziendaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.CURRENCYCODE = SRC.CURRENCYCODE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, RECID, NAME, CURRENCYCODE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.COMPANYINFO_InformazioniAzienda' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

