
CREATE PROCEDURE [AX2009].[usp_Create_WORKCALENDARDATELINE_DataLavorativa_Riga]
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.WORKCALENDARDATELINE_DataLavorativa_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSDATE		DATETIME NOT NULL,
	CALENDARID		NVARCHAR(10) NOT NULL,
	FROMTIME		INT NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	TOTIME		INT NOT NULL,
	NPOWORKCALENDARDATELINEID		BIGINT NOT NULL


	-- Constraint
	CONSTRAINT PK_WORKCALENDARDATELINE_DataLavorativa_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSDATE,
		CALENDARID,
		FROMTIME
	)
);

END;
GO

