
CREATE PROCEDURE AX2009.usp_AddIndexes_INVENTTABLE_ArticoloConfigurato
AS
BEGIN
SET NOCOUNT ON;

CREATE NONCLUSTERED INDEX IX_AX2009_INVENTTABLE_ArticoloConfigurato_DATAAREAID_NPOINVENTITEMTYPE_INCLUDE ON AX2009.INVENTTABLE_ArticoloConfigurato (DATAAREAID,NPOINVENTITEMTYPE) INCLUDE (ITEMID);

END;
GO

