
CREATE PROCEDURE AX2009.usp_Merge_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.FDY_DOCF_FINANCIALVOICE_VoceFinanziaria', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria;
    EXEC AX2009.usp_AddIndexes_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria;
END;

MERGE INTO AX2009.FDY_DOCF_FINANCIALVOICE_VoceFinanziaria AS TGT
USING AX2009.FDY_DOCF_FINANCIALVOICE_VoceFinanziariaView (nolock) AS SRC
ON SRC.FDY_DOCF_VOCEFINANZIARIA = TGT.FDY_DOCF_VOCEFINANZIARIA
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (FDY_DOCF_VOCEFINANZIARIA, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.FDY_DOCF_FINANCIALVOICE_VoceFinanziaria' AS full_olap_table_name,
    'FDY_DOCF_VOCEFINANZIARIA = ' + CAST(COALESCE(inserted.FDY_DOCF_VOCEFINANZIARIA, deleted.FDY_DOCF_VOCEFINANZIARIA) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

