
CREATE PROCEDURE AX2009.usp_Merge_WORKCALENDARDATELINE_DataLavorativa_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WORKCALENDARDATELINE_DataLavorativa_Riga', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_WORKCALENDARDATELINE_DataLavorativa_Riga;
	EXEC AX2009.usp_AddIndexes_WORKCALENDARDATELINE_DataLavorativa_Riga;
END;

MERGE INTO AX2009.WORKCALENDARDATELINE_DataLavorativa_Riga AS TGT
USING AX2009.WORKCALENDARDATELINE_DataLavorativa_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.TRANSDATE = TGT.TRANSDATE AND SRC.CALENDARID = TGT.CALENDARID AND SRC.FROMTIME = TGT.FROMTIME
WHEN MATCHED AND (TGT.TOTIME <> SRC.TOTIME OR TGT.NPOWORKCALENDARDATELINEID <> SRC.NPOWORKCALENDARDATELINEID)
  THEN UPDATE SET TGT.TOTIME = SRC.TOTIME, TGT.NPOWORKCALENDARDATELINEID = SRC.NPOWORKCALENDARDATELINEID
WHEN NOT MATCHED
  THEN INSERT (DATAAREAID, TRANSDATE, CALENDARID, FROMTIME, RECID, TOTIME, NPOWORKCALENDARDATELINEID) VALUES (DATAAREAID, TRANSDATE, CALENDARID, FROMTIME, RECID, TOTIME, NPOWORKCALENDARDATELINEID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.WORKCALENDARDATELINE_DataLavorativa_Riga' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'TRANSDATE = ' + CAST(COALESCE(inserted.TRANSDATE, deleted.TRANSDATE) AS NVARCHAR) + ' - ' + 'CALENDARID = ' + CAST(COALESCE(inserted.CALENDARID, deleted.CALENDARID) AS NVARCHAR) + ' - ' + 'FROMTIME = ' + CAST(COALESCE(inserted.FROMTIME, deleted.FROMTIME) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

