
CREATE PROCEDURE AX2009.usp_Create_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	TRANSFERID		NVARCHAR(20) NOT NULL,
	VOUCHERID		NVARCHAR(20) NOT NULL,
	LINENUM		NUMERIC(28, 12) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	INVENTTRANSID		NVARCHAR(20) NOT NULL,
	ITEMID		NVARCHAR(20) NOT NULL,
	INVENTDIMID		NVARCHAR(20) NOT NULL,
	TRANSDATE		DATE NOT NULL,
	NPOINVENTPACKINGSLIPID		NVARCHAR(20) NOT NULL,

	-- Misure
	UNITID		NVARCHAR(10) NOT NULL,
	QTYRECEIVED		NUMERIC(28, 12) NOT NULL,
	QTYSHIPPED		NUMERIC(28, 12) NOT NULL,
	QTYSCRAPPED		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga PRIMARY KEY CLUSTERED (
		DATAAREAID,
		TRANSFERID,
		VOUCHERID,
		LINENUM,
		RECID
	)
);

END;
GO

