
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTTRANSOPEN_TransazioniClienteAperte
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTTRANSOPEN_TransazioniClienteAperte_ ON AX2009.CUSTTRANSOPEN_TransazioniClienteAperte () INCLUDE();

END;
GO

