
CREATE PROCEDURE AX2009.usp_Merge_DLVREASON_CausaleConsegna
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DLVREASON_CausaleConsegna', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_DLVREASON_CausaleConsegna;
	EXEC AX2009.usp_AddIndexes_DLVREASON_CausaleConsegna;
END;

MERGE INTO AX2009.DLVREASON_CausaleConsegna AS TGT
USING AX2009.DLVREASON_CausaleConsegnaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.CODE = TGT.CODE
WHEN MATCHED AND (TGT.TXT <> SRC.TXT OR TGT.FREE <> SRC.FREE OR TGT.NPODLVLINETYPE <> SRC.NPODLVLINETYPE OR TGT.NPOCONTRACTWORK <> SRC.NPOCONTRACTWORK)
  THEN UPDATE SET TGT.TXT = SRC.TXT, TGT.FREE = SRC.FREE, TGT.NPODLVLINETYPE = SRC.NPODLVLINETYPE, TGT.NPOCONTRACTWORK = SRC.NPOCONTRACTWORK
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, CODE, RECID, TXT, FREE, NPODLVLINETYPE, NPOCONTRACTWORK)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.DLVREASON_CausaleConsegna' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'CODE = ' + CAST(COALESCE(inserted.CODE, deleted.CODE) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

