
CREATE PROCEDURE AX2009.usp_AddIndexes_VENDPAYMMODETABLE_MetodoPagamentoFornitore
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_VENDPAYMMODETABLE_MetodoPagamentoFornitore_ ON AX2009.VENDPAYMMODETABLE_MetodoPagamentoFornitore () INCLUDE();

END;
GO

