
CREATE PROCEDURE AX2009.usp_AddIndexes_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti_ ON AX2009.METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti () INCLUDE();

END;
GO

