
CREATE PROCEDURE AX2009.usp_Merge_PURCHTABLE_OrdiniFornitore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.PURCHTABLE_OrdiniFornitore', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_PURCHTABLE_OrdiniFornitore;
    EXEC AX2009.usp_AddIndexes_PURCHTABLE_OrdiniFornitore;
END;

MERGE INTO AX2009.PURCHTABLE_OrdiniFornitore AS TGT
USING AX2009.PURCHTABLE_OrdiniFornitoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PURCHID = TGT.PURCHID
WHEN MATCHED AND (TGT.ORDERACCOUNT <> SRC.ORDERACCOUNT OR TGT.DELIVERYDATE <> SRC.DELIVERYDATE OR TGT.INTERCOMPANYORIGINALSALESID <> SRC.INTERCOMPANYORIGINALSALESID OR TGT.INTERCOMPANYORIGINALCUSTACCO12 <> SRC.INTERCOMPANYORIGINALCUSTACCO12 OR TGT.INTERCOMPANYDIRECTDELIVERY <> SRC.INTERCOMPANYDIRECTDELIVERY OR TGT.PURCHSTATUS <> SRC.PURCHSTATUS OR TGT.PURCHASETYPE <> SRC.PURCHASETYPE OR TGT.INTERCOMPANYORIGIN <> SRC.INTERCOMPANYORIGIN OR TGT.DOCUMENTSTATUS <> SRC.DOCUMENTSTATUS OR TGT.PURCHPOOLID <> SRC.PURCHPOOLID OR TGT.VENDORREF <> SRC.VENDORREF OR TGT.INTERCOMPANYCOMPANYID <> SRC.INTERCOMPANYCOMPANYID OR TGT.INTERCOMPANYSALESID <> SRC.INTERCOMPANYSALESID OR TGT.INTERCOMPANYORDER <> SRC.INTERCOMPANYORDER OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.CURRENCYCODE <> SRC.CURRENCYCODE)
  THEN UPDATE SET TGT.ORDERACCOUNT = SRC.ORDERACCOUNT, TGT.DELIVERYDATE = SRC.DELIVERYDATE, TGT.INTERCOMPANYORIGINALSALESID = SRC.INTERCOMPANYORIGINALSALESID, TGT.INTERCOMPANYORIGINALCUSTACCO12 = SRC.INTERCOMPANYORIGINALCUSTACCO12, TGT.INTERCOMPANYDIRECTDELIVERY = SRC.INTERCOMPANYDIRECTDELIVERY, TGT.PURCHSTATUS = SRC.PURCHSTATUS, TGT.PURCHASETYPE = SRC.PURCHASETYPE, TGT.INTERCOMPANYORIGIN = SRC.INTERCOMPANYORIGIN, TGT.DOCUMENTSTATUS = SRC.DOCUMENTSTATUS, TGT.PURCHPOOLID = SRC.PURCHPOOLID, TGT.VENDORREF = SRC.VENDORREF, TGT.INTERCOMPANYCOMPANYID = SRC.INTERCOMPANYCOMPANYID, TGT.INTERCOMPANYSALESID = SRC.INTERCOMPANYSALESID, TGT.INTERCOMPANYORDER = SRC.INTERCOMPANYORDER, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.CURRENCYCODE = SRC.CURRENCYCODE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PURCHID, RECID, ORDERACCOUNT, DELIVERYDATE, INTERCOMPANYORIGINALSALESID, INTERCOMPANYORIGINALCUSTACCO12, INTERCOMPANYDIRECTDELIVERY, PURCHSTATUS, PURCHASETYPE, INTERCOMPANYORIGIN, DOCUMENTSTATUS, PURCHPOOLID, VENDORREF, INTERCOMPANYCOMPANYID, INTERCOMPANYSALESID, INTERCOMPANYORDER, CREATEDDATETIME, CURRENCYCODE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.PURCHTABLE_OrdiniFornitore' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PURCHID = ' + CAST(COALESCE(inserted.PURCHID, deleted.PURCHID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

