
CREATE PROCEDURE AX2009.usp_Merge_RETURNREASONCODEGROUP_GruppoMotivoReso
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.RETURNREASONCODEGROUP_GruppoMotivoReso', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_RETURNREASONCODEGROUP_GruppoMotivoReso;
    EXEC AX2009.usp_AddIndexes_RETURNREASONCODEGROUP_GruppoMotivoReso;
END;

MERGE INTO AX2009.RETURNREASONCODEGROUP_GruppoMotivoReso AS TGT
USING AX2009.RETURNREASONCODEGROUP_GruppoMotivoResoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.REASONCODEGROUPID = TGT.REASONCODEGROUPID
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, REASONCODEGROUPID, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.RETURNREASONCODEGROUP_GruppoMotivoReso' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'REASONCODEGROUPID = ' + CAST(COALESCE(inserted.REASONCODEGROUPID, deleted.REASONCODEGROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

