
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTSETTLEMENT_LiquidazioniCliente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTSETTLEMENT_LiquidazioniCliente_ ON AX2009.CUSTSETTLEMENT_LiquidazioniCliente () INCLUDE();

END;
GO

