
CREATE PROCEDURE AX2009.usp_AddIndexes_PBAREUSEBOMROUTE_StringaDiRicerca
AS
BEGIN
SET NOCOUNT ON;

CREATE UNIQUE NONCLUSTERED INDEX IX_AX2009_PBAREUSEBOMROUTE_StringaDiRicerca_DATAAREAID_ITEMID ON AX2009.PBAREUSEBOMROUTE_StringaDiRicerca (DATAAREAID, ITEMID);

END;
GO

