
CREATE PROCEDURE AX2009.usp_Merge_VENDTABLE_Fornitore
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.VENDTABLE_Fornitore', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_VENDTABLE_Fornitore;
    EXEC AX2009.usp_AddIndexes_VENDTABLE_Fornitore;
END;

MERGE INTO AX2009.VENDTABLE_Fornitore AS TGT
USING AX2009.VENDTABLE_FornitoreView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ACCOUNTNUM = TGT.ACCOUNTNUM
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.VENDGROUP <> SRC.VENDGROUP OR TGT.PAYMTERMID <> SRC.PAYMTERMID OR TGT.CUSTACCOUNT <> SRC.CUSTACCOUNT OR TGT.VATNUM <> SRC.VATNUM OR TGT.PAYMMODE <> SRC.PAYMMODE OR TGT.PURCHPOOLID <> SRC.PURCHPOOLID OR TGT.FISCALCODE <> SRC.FISCALCODE OR TGT.PARTYID <> SRC.PARTYID OR TGT.PARTYTYPE <> SRC.PARTYTYPE OR TGT.FDY_DOCF_VOCEFINANZIARIA <> SRC.FDY_DOCF_VOCEFINANZIARIA)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.VENDGROUP = SRC.VENDGROUP, TGT.PAYMTERMID = SRC.PAYMTERMID, TGT.CUSTACCOUNT = SRC.CUSTACCOUNT, TGT.VATNUM = SRC.VATNUM, TGT.PAYMMODE = SRC.PAYMMODE, TGT.PURCHPOOLID = SRC.PURCHPOOLID, TGT.FISCALCODE = SRC.FISCALCODE, TGT.PARTYID = SRC.PARTYID, TGT.PARTYTYPE = SRC.PARTYTYPE, TGT.FDY_DOCF_VOCEFINANZIARIA = SRC.FDY_DOCF_VOCEFINANZIARIA
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ACCOUNTNUM, RECID, NAME, VENDGROUP, PAYMTERMID, CUSTACCOUNT, VATNUM, PAYMMODE, PURCHPOOLID, FISCALCODE, PARTYID, PARTYTYPE, FDY_DOCF_VOCEFINANZIARIA)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.VENDTABLE_Fornitore' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ACCOUNTNUM = ' + CAST(COALESCE(inserted.ACCOUNTNUM, deleted.ACCOUNTNUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

