
CREATE PROCEDURE AX2009.usp_Create_SHIPCARRIERCOMPANY_SocietaSpedizioni
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.SHIPCARRIERCOMPANY_SocietaSpedizioni (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	CARRIERNAME		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	VENDACCOUNT		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_SHIPCARRIERCOMPANY_SocietaSpedizioni PRIMARY KEY CLUSTERED (
		DATAAREAID,
		CARRIERNAME
	)
);

END;
GO

