
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOSCRAP_DichiarazioniScarto
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOSCRAP_DichiarazioniScarto_ ON AX2009.NPOSCRAP_DichiarazioniScarto () INCLUDE();

END;
GO

