
CREATE PROCEDURE AX2009.usp_Merge_DIMENSIONS_DimensioneContabile
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.DIMENSIONS_DimensioneContabile', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_DIMENSIONS_DimensioneContabile;
	EXEC AX2009.usp_AddIndexes_DIMENSIONS_DimensioneContabile;
END;

MERGE INTO AX2009.DIMENSIONS_DimensioneContabile AS TGT
USING AX2009.DIMENSIONS_DimensioneContabileView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.DIMENSIONCODE = TGT.DIMENSIONCODE AND SRC.NUM = TGT.NUM
WHEN MATCHED AND (TGT.DESCRIPTION <> SRC.DESCRIPTION)
  THEN UPDATE SET TGT.DESCRIPTION = SRC.DESCRIPTION
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, DIMENSIONCODE, NUM, RECID, DESCRIPTION)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.DIMENSIONS_DimensioneContabile' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'DIMENSIONCODE = ' + CAST(COALESCE(inserted.DIMENSIONCODE, deleted.DIMENSIONCODE) AS NVARCHAR) + ' - ' + 'NUM = ' + CAST(COALESCE(inserted.NUM, deleted.NUM) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

