
CREATE PROCEDURE AX2009.usp_Merge_NPOSALESCREDITGROUP_ClienteFidoDiGruppo
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.NPOSALESCREDITGROUP_ClienteFidoDiGruppo', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_NPOSALESCREDITGROUP_ClienteFidoDiGruppo;
    EXEC AX2009.usp_AddIndexes_NPOSALESCREDITGROUP_ClienteFidoDiGruppo;
END;

MERGE INTO AX2009.NPOSALESCREDITGROUP_ClienteFidoDiGruppo AS TGT
USING AX2009.NPOSALESCREDITGROUP_ClienteFidoDiGruppoView (nolock) AS SRC
ON SRC.CUSTOMERCODE = TGT.CUSTOMERCODE AND SRC.CUSTOMERRELATION = TGT.CUSTOMERRELATION AND SRC.DATEFROM = TGT.DATEFROM AND SRC.DATETO = TGT.DATETO AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.REASONID <> SRC.REASONID OR TGT.AMOUNT <> SRC.AMOUNT OR TGT.INSURANCEAMOUNT <> SRC.INSURANCEAMOUNT)
  THEN UPDATE SET TGT.REASONID = SRC.REASONID, TGT.AMOUNT = SRC.AMOUNT, TGT.INSURANCEAMOUNT = SRC.INSURANCEAMOUNT
WHEN NOT MATCHED
  THEN INSERT VALUES (CUSTOMERCODE, CUSTOMERRELATION, DATEFROM, DATETO, RECID, REASONID, AMOUNT, INSURANCEAMOUNT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.NPOSALESCREDITGROUP_ClienteFidoDiGruppo' AS full_olap_table_name,
    'CUSTOMERCODE = ' + CAST(COALESCE(inserted.CUSTOMERCODE, deleted.CUSTOMERCODE) AS NVARCHAR) + ' - ' + 'CUSTOMERRELATION = ' + CAST(COALESCE(inserted.CUSTOMERRELATION, deleted.CUSTOMERRELATION) AS NVARCHAR) + ' - ' + 'DATEFROM = ' + CAST(COALESCE(inserted.DATEFROM, deleted.DATEFROM) AS NVARCHAR) + ' - ' + 'DATETO = ' + CAST(COALESCE(inserted.DATETO, deleted.DATETO) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

