
CREATE PROCEDURE AX2009.usp_AddIndexes_DIRORGANIZATIONDETAIL_DettagliRubrica
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_DIRORGANIZATIONDETAIL_DettagliRubrica_ ON AX2009.DIRORGANIZATIONDETAIL_DettagliRubrica () INCLUDE();

END;
GO

