
CREATE PROCEDURE AX2009.usp_Merge_CUSTINVOICELINE_FattureClienteTestoLibero_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.CUSTINVOICELINE_FattureClienteTestoLibero_Riga', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_CUSTINVOICELINE_FattureClienteTestoLibero_Riga;
    EXEC AX2009.usp_AddIndexes_CUSTINVOICELINE_FattureClienteTestoLibero_Riga;
END;

MERGE INTO AX2009.CUSTINVOICELINE_FattureClienteTestoLibero_Riga AS TGT
USING AX2009.CUSTINVOICELINE_FattureClienteTestoLibero_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PARENTRECID = TGT.PARENTRECID AND SRC.LINENUM = TGT.LINENUM AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.LEDGERACCOUNT <> SRC.LEDGERACCOUNT OR TGT.DIMENSION <> SRC.DIMENSION OR TGT.DIMENSION2_ <> SRC.DIMENSION2_ OR TGT.DIMENSION3_ <> SRC.DIMENSION3_ OR TGT.DIMENSION4_ <> SRC.DIMENSION4_ OR TGT.DIMENSION5_ <> SRC.DIMENSION5_ OR TGT.DIMENSION6_ <> SRC.DIMENSION6_)
  THEN UPDATE SET TGT.LEDGERACCOUNT = SRC.LEDGERACCOUNT, TGT.DIMENSION = SRC.DIMENSION, TGT.DIMENSION2_ = SRC.DIMENSION2_, TGT.DIMENSION3_ = SRC.DIMENSION3_, TGT.DIMENSION4_ = SRC.DIMENSION4_, TGT.DIMENSION5_ = SRC.DIMENSION5_, TGT.DIMENSION6_ = SRC.DIMENSION6_
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PARENTRECID, LINENUM, RECID, LEDGERACCOUNT, DIMENSION, DIMENSION2_, DIMENSION3_, DIMENSION4_, DIMENSION5_, DIMENSION6_)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.CUSTINVOICELINE_FattureClienteTestoLibero_Riga' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PARENTRECID = ' + CAST(COALESCE(inserted.PARENTRECID, deleted.PARENTRECID) AS NVARCHAR) + ' - ' + 'LINENUM = ' + CAST(COALESCE(inserted.LINENUM, deleted.LINENUM) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

