
CREATE PROCEDURE AX2009.usp_Merge_ADDRESSCOUNTRYREGION_Nazione
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.ADDRESSCOUNTRYREGION_Nazione', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_ADDRESSCOUNTRYREGION_Nazione;
    EXEC AX2009.usp_AddIndexes_ADDRESSCOUNTRYREGION_Nazione;
END;

MERGE INTO AX2009.ADDRESSCOUNTRYREGION_Nazione AS TGT
USING AX2009.ADDRESSCOUNTRYREGION_NazioneView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.COUNTRYREGIONID = TGT.COUNTRYREGIONID
WHEN MATCHED AND (TGT.TYPE <> SRC.TYPE OR TGT.ISOCODE <> SRC.ISOCODE OR TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.TYPE = SRC.TYPE, TGT.ISOCODE = SRC.ISOCODE, TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, COUNTRYREGIONID, RECID, TYPE, ISOCODE, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.ADDRESSCOUNTRYREGION_Nazione' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'COUNTRYREGIONID = ' + CAST(COALESCE(inserted.COUNTRYREGIONID, deleted.COUNTRYREGIONID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

