
CREATE PROCEDURE AX2009.usp_AddIndexes_REQITEMTABLE_CoperturaArticoli
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_REQITEMTABLE_CoperturaArticoli_ ON AX2009.REQITEMTABLE_CoperturaArticoli () INCLUDE();

END;
GO

