
CREATE PROCEDURE AX2009.usp_Create_NPOITEMSYSTEM_Sistema
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOITEMSYSTEM_Sistema (
	-- Chiavi
	SYSTEMID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	SECTORTYPE		SMALLINT NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOITEMSYSTEM_Sistema PRIMARY KEY CLUSTERED (
		SYSTEMID
	)
);

END;
GO

