
CREATE PROCEDURE AX2009.usp_AddIndexes_ADDRESSCOUNTY_Provincia
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_ADDRESSCOUNTY_Provincia_ ON AX2009.ADDRESSCOUNTY_Provincia () INCLUDE();

END;
GO

