
CREATE PROCEDURE AX2009.usp_Merge_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido;
	EXEC AX2009.usp_AddIndexes_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido;
END;

MERGE INTO AX2009.NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido AS TGT
USING AX2009.NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFidoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.SALESID = TGT.SALESID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.CONFIRMBLOCKED <> SRC.CONFIRMBLOCKED OR TGT.UNLOCKCAUSAL <> SRC.UNLOCKCAUSAL OR TGT.PACKINGBLOCKED <> SRC.PACKINGBLOCKED OR TGT.PICKINGBLOCKED <> SRC.PICKINGBLOCKED OR TGT.INVOICEBLOCKED <> SRC.INVOICEBLOCKED OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME)
  THEN UPDATE SET TGT.CONFIRMBLOCKED = SRC.CONFIRMBLOCKED, TGT.UNLOCKCAUSAL = SRC.UNLOCKCAUSAL, TGT.PACKINGBLOCKED = SRC.PACKINGBLOCKED, TGT.PICKINGBLOCKED = SRC.PICKINGBLOCKED, TGT.INVOICEBLOCKED = SRC.INVOICEBLOCKED, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, SALESID, RECID, CONFIRMBLOCKED, UNLOCKCAUSAL, PACKINGBLOCKED, PICKINGBLOCKED, INVOICEBLOCKED, CREATEDDATETIME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'SALESID = ' + CAST(COALESCE(inserted.SALESID, deleted.SALESID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

