
CREATE PROCEDURE AX2009.usp_Merge_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi;
	EXEC AX2009.usp_AddIndexes_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi;
END;

MERGE INTO AX2009.NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi AS TGT
USING AX2009.NPOFINISHINGPRICEGROUP_FinituraGruppoPrezziView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PBAFINISHINGID = TGT.PBAFINISHINGID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ITEMPRICEGROUPID <> SRC.ITEMPRICEGROUPID OR TGT.REVITEMID <> SRC.REVITEMID OR TGT.ITEMTYPE <> SRC.ITEMTYPE OR TGT.NCEREFERENCEITEMID <> SRC.NCEREFERENCEITEMID)
  THEN UPDATE SET TGT.ITEMPRICEGROUPID = SRC.ITEMPRICEGROUPID, TGT.REVITEMID = SRC.REVITEMID, TGT.ITEMTYPE = SRC.ITEMTYPE, TGT.NCEREFERENCEITEMID = SRC.NCEREFERENCEITEMID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PBAFINISHINGID, RECID, ITEMPRICEGROUPID, REVITEMID, ITEMTYPE, NCEREFERENCEITEMID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PBAFINISHINGID = ' + CAST(COALESCE(inserted.PBAFINISHINGID, deleted.PBAFINISHINGID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

