
CREATE PROCEDURE AX2009.usp_Create_WRKCTRTABLE_CentroDiLavoro
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.WRKCTRTABLE_CentroDiLavoro (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    WRKCTRID        NVARCHAR(10) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    WRKCTRGROUPID        NVARCHAR(10) NOT NULL,
    NAME        NVARCHAR(60) NOT NULL,
    WRKCTRTYPE        INT NOT NULL,
    ISGROUP        INT NOT NULL,
    CALENDARID        NVARCHAR(10) NOT NULL,
    NPOERRORPCT        NUMERIC(28, 12) NOT NULL,
    NPOWRKCTRTYPE        INT NOT NULL,
    NPOALLOYDIAMETER        NVARCHAR(10) NOT NULL,

    -- Misure
    METITEMID        NVARCHAR(20) NOT NULL

    -- Constraint
    CONSTRAINT PK_WRKCTRTABLE_CentroDiLavoro PRIMARY KEY CLUSTERED (
        DATAAREAID,
        WRKCTRID
    )
);

END;
GO

