
CREATE PROCEDURE AX2009.usp_Merge_WRKCTRTABLE_CentroDiLavoro
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WRKCTRTABLE_CentroDiLavoro', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_WRKCTRTABLE_CentroDiLavoro;
    EXEC AX2009.usp_AddIndexes_WRKCTRTABLE_CentroDiLavoro;
END;

MERGE INTO AX2009.WRKCTRTABLE_CentroDiLavoro AS TGT
USING AX2009.WRKCTRTABLE_CentroDiLavoroView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.WRKCTRID = TGT.WRKCTRID
WHEN MATCHED AND (TGT.WRKCTRGROUPID <> SRC.WRKCTRGROUPID OR TGT.NAME <> SRC.NAME OR TGT.WRKCTRTYPE <> SRC.WRKCTRTYPE OR TGT.ISGROUP <> SRC.ISGROUP OR TGT.CALENDARID <> SRC.CALENDARID OR TGT.NPOERRORPCT <> SRC.NPOERRORPCT OR TGT.NPOWRKCTRTYPE <> SRC.NPOWRKCTRTYPE OR TGT.NPOALLOYDIAMETER <> SRC.NPOALLOYDIAMETER OR TGT.METITEMID <> SRC.METITEMID)
  THEN UPDATE SET TGT.WRKCTRGROUPID = SRC.WRKCTRGROUPID, TGT.NAME = SRC.NAME, TGT.WRKCTRTYPE = SRC.WRKCTRTYPE, TGT.ISGROUP = SRC.ISGROUP, TGT.CALENDARID = SRC.CALENDARID, TGT.NPOERRORPCT = SRC.NPOERRORPCT, TGT.NPOWRKCTRTYPE = SRC.NPOWRKCTRTYPE, TGT.NPOALLOYDIAMETER = SRC.NPOALLOYDIAMETER, TGT.METITEMID = SRC.METITEMID
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, WRKCTRID, RECID, WRKCTRGROUPID, NAME, WRKCTRTYPE, ISGROUP, CALENDARID, NPOERRORPCT, NPOWRKCTRTYPE, NPOALLOYDIAMETER, METITEMID)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.WRKCTRTABLE_CentroDiLavoro' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'WRKCTRID = ' + CAST(COALESCE(inserted.WRKCTRID, deleted.WRKCTRID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

