
CREATE PROCEDURE AX2009.usp_Merge_INVENTITEMGROUP_GruppoArticoli
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.INVENTITEMGROUP_GruppoArticoli', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_INVENTITEMGROUP_GruppoArticoli;
	EXEC AX2009.usp_AddIndexes_INVENTITEMGROUP_GruppoArticoli;
END;

MERGE INTO AX2009.INVENTITEMGROUP_GruppoArticoli AS TGT
USING AX2009.INVENTITEMGROUP_GruppoArticoliView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ITEMGROUPID = TGT.ITEMGROUPID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ITEMGROUPID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.INVENTITEMGROUP_GruppoArticoli' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ITEMGROUPID = ' + CAST(COALESCE(inserted.ITEMGROUPID, deleted.ITEMGROUPID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

