
CREATE PROCEDURE AX2009.usp_Create_NPOITEMSUBFAMILIES_SottofamigliaArticolo
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOITEMSUBFAMILIES_SottofamigliaArticolo (
	-- Chiavi
	SUBFAMILYID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	NAME		NVARCHAR(60) NOT NULL,
	FAMILYID		NVARCHAR(20) NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOITEMSUBFAMILIES_SottofamigliaArticolo PRIMARY KEY CLUSTERED (
		SUBFAMILYID
	)
);

END;
GO

