
CREATE PROCEDURE AX2009.usp_Create_BANKREMITTANCEFILESCUST_FileRimesseClienti
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.BANKREMITTANCEFILESCUST_FileRimesseClienti (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	FILEID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	BANKACCOUNTID		NVARCHAR(10) NOT NULL,
	CREATEDDATETIME		DATETIME NOT NULL,

	-- Misure
	AMOUNTMST		NUMERIC(28, 12) NOT NULL

	-- Constraint
	CONSTRAINT PK_BANKREMITTANCEFILESCUST_FileRimesseClienti PRIMARY KEY CLUSTERED (
		DATAAREAID,
		FILEID
	)
);

END;
GO

