
CREATE PROCEDURE AX2009.usp_Create_PAYMTERM_TerminiPagamento
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.PAYMTERM_TerminiPagamento (
	-- Chiavi
	DATAAREAID		CHAR(4) NOT NULL,
	PAYMTERMID		NVARCHAR(10) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	DESCRIPTION		NVARCHAR(60) NOT NULL,
	NUMOFMONTHS		TINYINT NOT NULL


	-- Constraint
	CONSTRAINT PK_PAYMTERM_TerminiPagamento PRIMARY KEY CLUSTERED (
		DATAAREAID,
		PAYMTERMID
	)
);

END;
GO

