
CREATE PROCEDURE AX2009.usp_Merge_PURCHPOOL_PoolAcquisti
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.PURCHPOOL_PoolAcquisti', N'U') IS NULL
BEGIN
	EXEC AX2009.usp_Create_PURCHPOOL_PoolAcquisti;
	EXEC AX2009.usp_AddIndexes_PURCHPOOL_PoolAcquisti;
END;

MERGE INTO AX2009.PURCHPOOL_PoolAcquisti AS TGT
USING AX2009.PURCHPOOL_PoolAcquistiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PURCHPOOLID = TGT.PURCHPOOLID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PURCHPOOLID, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
	CURRENT_TIMESTAMP AS merge_datetime,
	$action AS merge_action,
	'AX2009.PURCHPOOL_PoolAcquisti' AS full_olap_table_name,
	'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PURCHPOOLID = ' + CAST(COALESCE(inserted.PURCHPOOLID, deleted.PURCHPOOLID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

