
CREATE PROCEDURE AX2009.usp_Merge_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID('AX2009.METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra;
    EXEC AX2009.usp_AddIndexes_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra;
END;

MERGE INTO AX2009.METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra AS TGT
USING AX2009.METBOMCALCTRANSEXT_CalcoloDBA_Riga_ExtraView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.REFRECID = TGT.REFRECID
WHEN MATCHED AND (TGT.PRIMARYVENDORID <> SRC.PRIMARYVENDORID OR TGT.STOPEXPLODEBOMCALCGROUP <> SRC.STOPEXPLODEBOMCALCGROUP OR TGT.STOPEXPLODEITEM <> SRC.STOPEXPLODEITEM)
  THEN UPDATE SET TGT.PRIMARYVENDORID = SRC.PRIMARYVENDORID, TGT.STOPEXPLODEBOMCALCGROUP = SRC.STOPEXPLODEBOMCALCGROUP, TGT.STOPEXPLODEITEM = SRC.STOPEXPLODEITEM
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, REFRECID, RECID, PRIMARYVENDORID, STOPEXPLODEBOMCALCGROUP, STOPEXPLODEITEM)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'REFRECID = ' + CAST(COALESCE(inserted.REFRECID, deleted.REFRECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

