
CREATE PROCEDURE AX2009.usp_AddIndexes_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking_ ON AX2009.METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking () INCLUDE();

END;
GO

