
CREATE PROCEDURE AX2009.usp_Create_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating (
	-- Chiavi
	PARTYID		NVARCHAR(20) NOT NULL,
	RECID		BIGINT NOT NULL,

	-- Dimensioni
	RATINGREFTYPE		SMALLINT NOT NULL,
	RATINGREFID		NVARCHAR(20) NOT NULL,
	RATINGID		NVARCHAR(20) NOT NULL,
	DATEFROM		DATE NOT NULL,
	DATETO		DATE NOT NULL


	-- Constraint
	CONSTRAINT PK_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating PRIMARY KEY CLUSTERED (
		PARTYID,
		RECID
	)
);

END;
GO

