
CREATE PROCEDURE AX2009.usp_Merge_WMSORDERTRANS_OrdiniMagazzino_Riga
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AX2009.WMSORDERTRANS_OrdiniMagazzino_Riga', N'U') IS NULL
BEGIN
    EXEC AX2009.usp_Create_WMSORDERTRANS_OrdiniMagazzino_Riga;
    EXEC AX2009.usp_AddIndexes_WMSORDERTRANS_OrdiniMagazzino_Riga;
END;

MERGE INTO AX2009.WMSORDERTRANS_OrdiniMagazzino_Riga AS TGT
USING AX2009.WMSORDERTRANS_OrdiniMagazzino_RigaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.ORDERID = TGT.ORDERID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.ROUTEID <> SRC.ROUTEID OR TGT.EXPEDITIONSTATUS <> SRC.EXPEDITIONSTATUS OR TGT.ITEMID <> SRC.ITEMID OR TGT.OPERATOR <> SRC.OPERATOR OR TGT.EXPEDITIONTIME <> SRC.EXPEDITIONTIME OR TGT.ISRESERVED <> SRC.ISRESERVED OR TGT.SHIPMENTIDORIGINAL <> SRC.SHIPMENTIDORIGINAL OR TGT.SHIPMENTID <> SRC.SHIPMENTID OR TGT.INVENTDIMID <> SRC.INVENTDIMID OR TGT.DLVDATE <> SRC.DLVDATE OR TGT.ORDERTYPE <> SRC.ORDERTYPE OR TGT.INVENTTRANSID <> SRC.INVENTTRANSID OR TGT.FULLPALLET <> SRC.FULLPALLET OR TGT.TOINVENTDIMID <> SRC.TOINVENTDIMID OR TGT.PALLETIDPICKED <> SRC.PALLETIDPICKED OR TGT.INVENTTRANSTYPE <> SRC.INVENTTRANSTYPE OR TGT.INVENTTRANSREFID <> SRC.INVENTTRANSREFID OR TGT.NPOKASTOID <> SRC.NPOKASTOID OR TGT.NPOPACKINGSLIPID <> SRC.NPOPACKINGSLIPID OR TGT.NPOPACKINGSLIPTRANSRECID <> SRC.NPOPACKINGSLIPTRANSRECID OR TGT.CREATEDDATETIME <> SRC.CREATEDDATETIME OR TGT.NPOPICKEDDATETIME <> SRC.NPOPICKEDDATETIME OR TGT.QTY <> SRC.QTY OR TGT.NPOPACKINGSLIPWEIGHT <> SRC.NPOPACKINGSLIPWEIGHT)
  THEN UPDATE SET TGT.ROUTEID = SRC.ROUTEID, TGT.EXPEDITIONSTATUS = SRC.EXPEDITIONSTATUS, TGT.ITEMID = SRC.ITEMID, TGT.OPERATOR = SRC.OPERATOR, TGT.EXPEDITIONTIME = SRC.EXPEDITIONTIME, TGT.ISRESERVED = SRC.ISRESERVED, TGT.SHIPMENTIDORIGINAL = SRC.SHIPMENTIDORIGINAL, TGT.SHIPMENTID = SRC.SHIPMENTID, TGT.INVENTDIMID = SRC.INVENTDIMID, TGT.DLVDATE = SRC.DLVDATE, TGT.ORDERTYPE = SRC.ORDERTYPE, TGT.INVENTTRANSID = SRC.INVENTTRANSID, TGT.FULLPALLET = SRC.FULLPALLET, TGT.TOINVENTDIMID = SRC.TOINVENTDIMID, TGT.PALLETIDPICKED = SRC.PALLETIDPICKED, TGT.INVENTTRANSTYPE = SRC.INVENTTRANSTYPE, TGT.INVENTTRANSREFID = SRC.INVENTTRANSREFID, TGT.NPOKASTOID = SRC.NPOKASTOID, TGT.NPOPACKINGSLIPID = SRC.NPOPACKINGSLIPID, TGT.NPOPACKINGSLIPTRANSRECID = SRC.NPOPACKINGSLIPTRANSRECID, TGT.CREATEDDATETIME = SRC.CREATEDDATETIME, TGT.NPOPICKEDDATETIME = SRC.NPOPICKEDDATETIME, TGT.QTY = SRC.QTY, TGT.NPOPACKINGSLIPWEIGHT = SRC.NPOPACKINGSLIPWEIGHT
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, ORDERID, RECID, ROUTEID, EXPEDITIONSTATUS, ITEMID, OPERATOR, EXPEDITIONTIME, ISRESERVED, SHIPMENTIDORIGINAL, SHIPMENTID, INVENTDIMID, DLVDATE, ORDERTYPE, INVENTTRANSID, FULLPALLET, TOINVENTDIMID, PALLETIDPICKED, INVENTTRANSTYPE, INVENTTRANSREFID, NPOKASTOID, NPOPACKINGSLIPID, NPOPACKINGSLIPTRANSRECID, CREATEDDATETIME, NPOPICKEDDATETIME, QTY, NPOPACKINGSLIPWEIGHT)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AX2009.WMSORDERTRANS_OrdiniMagazzino_Riga' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'ORDERID = ' + CAST(COALESCE(inserted.ORDERID, deleted.ORDERID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

