
CREATE PROCEDURE AX2009.usp_Create_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METPRICECALCITEMSETUP_CalcoloPrezzi_Extra (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    REFTABLEID        INT NOT NULL,
    REFRECID        BIGINT NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    PRIMARYVENDORID        NVARCHAR(20) NOT NULL,
    STOPEXPLODEITEM        BIT NOT NULL,
    BOMCALCGROUPID        NVARCHAR(10) NOT NULL,
    STOPEXPLODEBOMCALCGROUP        BIT NOT NULL


    -- Constraint
    CONSTRAINT PK_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra PRIMARY KEY CLUSTERED (
        DATAAREAID,
        REFTABLEID,
        REFRECID
    )
);

END;
GO

