
CREATE PROCEDURE AX2009.usp_AddIndexes_SHIPCARRIERTABLE_Vettore
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_SHIPCARRIERTABLE_Vettore_ ON AX2009.SHIPCARRIERTABLE_Vettore () INCLUDE();

END;
GO

