
CREATE PROCEDURE AX2009.usp_Create_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AX2009.METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione (
	-- Chiavi
	DATAAREAID  CHAR(4) NOT NULL,
	ITEMID  NVARCHAR(20) NOT NULL,
	INVENTTRANSID  NVARCHAR(20) NOT NULL,
	VARIABLENUM  INT NOT NULL,
	VARIABLENAME  NVARCHAR(50) NOT NULL,
	RECID  BIGINT NOT NULL,

	-- Dimensioni
	VALUESTR  NVARCHAR(60) NOT NULL,
	VALUEINT  INT NOT NULL,
	VALUEINT64  BIGINT NOT NULL,
	VALUEREAL  NUMERIC(28, 12) NOT NULL,
	BASETYPENAME  NVARCHAR(50) NOT NULL


	-- Constraint
	CONSTRAINT PK_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione PRIMARY KEY CLUSTERED (
		DATAAREAID,
		ITEMID,
		INVENTTRANSID,
		VARIABLENUM,
		VARIABLENAME
	)
);

END;
GO

