
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOITEMSYSTEM_Sistema
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOITEMSYSTEM_Sistema_ ON AX2009.NPOITEMSYSTEM_Sistema () INCLUDE();

END;
GO

