
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTTABLE_Cliente
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTTABLE_Cliente_ ON AX2009.CUSTTABLE_Cliente () INCLUDE();

END;
GO

