
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOSALESCREDITGROUP_ClienteFidoDiGruppo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOSALESCREDITGROUP_ClienteFidoDiGruppo_ ON AX2009.NPOSALESCREDITGROUP_ClienteFidoDiGruppo () INCLUDE();

END;
GO

