
CREATE PROCEDURE AX2009.usp_AddIndexes_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra_ ON AX2009.METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra () INCLUDE();

END;
GO

