
CREATE PROCEDURE AX2009.usp_AddIndexes_CUSTGROUP_ClienteGruppo
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_CUSTGROUP_ClienteGruppo_ ON AX2009.CUSTGROUP_ClienteGruppo () INCLUDE();

END;
GO

