
CREATE PROCEDURE AX2009.usp_AddIndexes_NPOWORKSTATIONAREA_AreaDiLavoro
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AX2009_NPOWORKSTATIONAREA_AreaDiLavoro_ ON AX2009.NPOWORKSTATIONAREA_AreaDiLavoro () INCLUDE();

END;
GO

