/*
SET NOEXEC OFF;
--*/ SET NOEXEC ON;
GO

USE master;
GO

IF EXISTS(SELECT name FROM sys.databases WHERE name = 'SampleDWH')
BEGIN

    ALTER DATABASE SampleDWH SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

    DROP DATABASE IF EXISTS SampleDWH;

END;
GO

CREATE DATABASE [SampleDWH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleDWH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\SampleDWH.mdf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SampleDWH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\SampleDWH_log.ldf' , SIZE = 65536KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [SampleDWH] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [SampleDWH] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SampleDWH] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SampleDWH] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SampleDWH] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SampleDWH] SET ARITHABORT OFF 
GO
ALTER DATABASE [SampleDWH] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SampleDWH] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SampleDWH] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SampleDWH] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SampleDWH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SampleDWH] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SampleDWH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SampleDWH] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SampleDWH] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SampleDWH] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SampleDWH] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SampleDWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SampleDWH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SampleDWH] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SampleDWH] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SampleDWH] SET  READ_WRITE 
GO
ALTER DATABASE [SampleDWH] SET RECOVERY FULL 
GO
ALTER DATABASE [SampleDWH] SET  MULTI_USER 
GO
ALTER DATABASE [SampleDWH] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SampleDWH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SampleDWH] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SampleDWH]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [SampleDWH]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SampleDWH] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
