
CREATE VIEW AS400.MEDEP_KK_STATS00F_FattureCliente_MetraSistemiView
AS
SELECT
	-- Chiavi
    STDFA ,
    STNFA ,
    STNUO ,
    STRIO ,
    STDBO ,
    STNBO ,
	ROW_NUMBER() OVER (ORDER BY STDFA, STNFA, STDBO, STNBO, STNUO, STRIO) AS PKFattureCliente_MetraSistemi,

	-- Dimensioni
	STNNR ,
	STDEL ,
	STTRK ,
	STFL1 ,
	STFL2 ,
	STFL3 ,
	STFL4 ,
	STFL5 ,
	STTPO ,
	STTIM ,
	STTOM ,
	STRBO ,
	STDUO ,
	STCLI ,
	STCLS ,
	STPAR ,
	STAGE ,
	STZON ,
	STVALD ,
	STIMPD ,
	STIMPE ,
	STCAME ,
	STIMLD ,
	STIMLE ,
	STQTAS ,
	STUMIS ,
	STQTAK ,
	STUMIK ,
	STQTAF ,
	STUMIF ,
	STPRO ,
	TPPRC ,
	STTPR ,
	TITIP ,
	CLMER ,
	PROFI ,
	LAVOR ,
	LUNBA ,
	STEWA ,
	CALAV ,
	MIORJE ,
	STFLG1 ,
	STPRZT ,
	STMACA

--FROM OPENQUERY(ALBERTO, 'SELECT * FROM MEDEP_KK.STATS00F WHERE STDFA BETWEEN 20080101 AND 20111231 ORDER BY STDFA, STNFA');
FROM AS400_BACKUPS.AS400.MEDEP_KK_STATS00F_FattureCliente_MetraSistemi WHERE STDEL = '';
GO

