
CREATE VIEW AS400.SVIBAPALM_STATS00F_FattureCliente_MetraRagusaView
AS
SELECT
	-- Chiavi
    STDFA ,
    STNFA ,
    STNUO ,
    STRIO ,
    STDBO ,
    STNBO ,
	ROW_NUMBER() OVER (ORDER BY STDFA, STNFA, STDBO, STNBO, STNUO, STRIO) AS PKFattureCliente_MetraRagusa,

	-- Dimensioni
	STDEL ,
    STTRK ,
    STCLI ,
    STPAR ,
    STAGE ,
    STZON ,
    STMAG ,
    STNAZ ,
    STVAL ,
    STQTS ,
    STUNI ,
    STPRZ ,
    STIMP ,
    STIMV ,
    STSC1 ,
    STSC2 ,
    STSC3 ,
    STPRO ,
    STPRC ,
    STDIV ,
    STTOM ,
    STTIP ,
    STTIB ,
    STNNR ,
    STFL1 ,
    STFL2 ,
    STFL3 ,
    STPRV ,
    STDAO ,
    STTIF ,
    STCDE ,
    STCSE ,
    STQTK ,
    STQTQ ,
    STIMQ ,
    STLA1 ,
    [ST£A1] ,
    STUA1 ,
    STLA2 ,
    [ST£A2] ,
    STUA2 ,
    STLA3 ,
    [ST£A3] ,
    STUA3 ,
    STLA4 ,
    [ST£A4] ,
    STUA4 ,
    STLEG ,
    PROFI ,
    LAVOR ,
    OLBAR ,
    OMFIS ,
    ORFAC ,
    ORPEL ,
    NREWA ,
    EWAA1 ,
    EWAA2 ,
    EWAA3 ,
    RSPRK ,
    RSPPF

--FROM OPENQUERY(ALBERTO, 'SELECT * FROM SVIBAPALM.STATS00F WHERE STDFA BETWEEN 20080101 AND 20160531 ORDER BY STDFA, STNFA');
FROM AS400_BACKUPS.AS400.SVIBAPALM_STATS00F_FattureCliente_MetraRagusa WHERE STDEL = '';
GO

