
CREATE VIEW AS400.UNICA_ALC_CSFAT00F_Fatture_MetraColorView
AS
SELECT 'mcol' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_ALC.CSFAT00F WHERE FTANNO BETWEEN 2005 AND 2011 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_ALC_CSFAT00F_Fatture_MetraColor WHERE FTANNO BETWEEN 2005 AND 2011;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

