
CREATE VIEW AS400.UNICA_ALM_CSFAT00F_Fatture_MetraRagusaView
AS
SELECT 'mrag' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_ALM.CSFAT00F WHERE (FTANNO BETWEEN 2005 AND 2015) OR (FTANNO = 2016 AND FTMESE BETWEEN 1 AND 5) ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_ALM_CSFAT00F_Fatture_MetraRagusa WHERE (FTANNO BETWEEN 2005 AND 2015) OR (FTANNO = 2016 AND FTMESE BETWEEN 1 AND 5);-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

