
CREATE VIEW AS400.UNICA_MET_CSFAT00F_Fatture_MetraView
AS
SELECT 'mspa' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_MET.CSFAT00F WHERE FTANNO BETWEEN 2005 AND 2011 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_MET_CSFAT00F_Fatture_Metra WHERE FTANNO BETWEEN 2005 AND 2011;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

