
CREATE VIEW AS400.UNICA_FOA_CSFAT00F_Fatture_FoallView
AS
SELECT 'mfoa' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_FOA.CSFAT00F WHERE FTANNO BETWEEN 2005 AND 2011 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_FOA_CSFAT00F_Fatture_Foall WHERE FTANNO BETWEEN 2005 AND 2011;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

