
CREATE VIEW AS400.UNICA_GRU_ABFOR00F_FornitoreView
AS
SELECT
	-- Chiavi
    FOCOFO ,

	-- Dimensioni
	FOSTAT ,
    FODTCR ,
    FOUSCR ,
    FODTAG ,
    FOUSAG ,
    FORAGS ,
    FORAGC ,
    FOINDI ,
    FOINDC ,
    FOLOCA ,
    FONAZN ,
    FOPROV ,
    FOCAPA ,
    FOAIND ,
    FOAINC ,
    FOALOC ,
    FOANAZ ,
    FOAPRV ,
    FOACAP ,
    FOINES ,
    FOPAIV ,
    FOCFIS ,
    FOCAUE ,
    FOINCO ,
    FOSCEE ,
    FOPAIE ,
    FOCDAZ ,
    FOVALU ,
    FOLING ,
    FOBASC ,
    FOBABO ,
    FOBABI ,
    FOBCAB ,
    FOCOBO ,
    FOCOMC ,
    FOCATC ,
    FOCATF ,
    FOCPAG ,
    FODOGA ,
    FOCP01 ,
    FOCP02 ,
    FOCP03 ,
    FOCP04 ,
    FOCP05 ,
    FOBLKV ,
    FOBLKF ,
    FOTELE ,
    FONFAX ,
    FOTELX ,
    FOMAIL ,
    FOPERA ,
    FOFORC ,
    FOTRFO ,
    FOBNAZ ,
    FOBBAN ,
    FOBCIN ,
    FOBDGT ,
    FSTATO ,
    FOPEFI ,
    FOCOGN ,
    FONOME ,
    FODTNA ,
    FOCONA ,
    FOPRNA ,
    FOSTNA ,
    FOLORE ,
    FOINRE ,
    FOIIVA ,
    FOSMVX ,
    FO3000 ,
    FOPX11 ,
    FOPX12 ,
    FOPX21 ,
    FOPX22 ,
    FOPX31 ,
    FOPX32 ,
    FOPX91 ,
    FOPX92

--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_GRU.ABFOR00F');
FROM AS400_BACKUPS.AS400.UNICA_GRU_ABFOR00F_Fornitore;
GO

