
CREATE VIEW AS400.UNICA_IME_CSFAT00F_Fatture_ImetView
AS
SELECT 'imet' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_IME.CSFAT00F WHERE FTANNO BETWEEN 2005 AND 2014 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_IME_CSFAT00F_Fatture_Imet WHERE FTANNO BETWEEN 2005 AND 2014;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

