
CREATE VIEW AS400.UNICA_VER_CSFAT00F_Fatture_VerallView
AS
SELECT 'mver' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_VER.CSFAT00F WHERE FTANNO >= 2005 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_VER_CSFAT00F_Fatture_Verall WHERE FTANNO >= 2005;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

