
CREATE VIEW AS400.UNICA_GRU_ABCLI00F_ClienteView
AS
SELECT
	-- Chiavi
    CLCOCL ,

	-- Dimensioni
	CLSTAT ,
    CLDTCR ,
    CLUSCR ,
    CLDTAG ,
    CLUSAG ,
    CLRAGS ,
    CLRAGC ,
    CLINDI ,
    CLINDC ,
    CLLOCA ,
    CLNAZN ,
    CLPROV ,
    CLCAPA ,
    CLAIND ,
    CLAINC ,
    CLALOC ,
    CLANAZ ,
    CLAPRV ,
    CLACAP ,
    CLINES ,
    CLPAIV ,
    CLCFIS ,
    CLCAUE ,
    CLINCO ,
    CLSCEE ,
    CLPAIE ,
    CLCDAG ,
    CLCDAZ ,
    CLVALU ,
    CLLING ,
    CLBABI ,
    CLBCAB ,
    CLCOBO ,
    CLFIDO ,
    CLCOMC ,
    CLCONT ,
    CLCATF ,
    CLCPAG ,
    CLCP01 ,
    CLCP02 ,
    CLCP03 ,
    CLCP04 ,
    CLCP05 ,
    CLMMP1 ,
    CLMMP2 ,
    CLMMP3 ,
    CLGMP1 ,
    CLGMP2 ,
    CLGMP3 ,
    CLGGP1 ,
    CLGGP2 ,
    CLGGP3 ,
    CLBLKV ,
    CLBLKF ,
    CLTELE ,
    CLNFAX ,
    CLTELX ,
    CLMAIL ,
    CLPERA ,
    CLCLIC ,
    CLTRCL ,
    CLRGEF ,
    CLBAAN ,
    CLDBCD ,
    CLCNAZ ,
    CLCBAN ,
    CLCCIN ,
    CLCDGT ,
    CLCRGS ,
    CLNAZC ,
    CLCVEN ,
    CLTPCL ,
    CSTATO ,
    CLPEFI ,
    CLCOGN ,
    CLNOME ,
    CLDTNA ,
    CLCONA ,
    CLPRNA ,
    CLSTNA ,
    CLLORE ,
    CLINRE ,
    CLIIVA ,
    CLFLGC ,
    CL3000 ,
    CLPX11 ,
    CLPX12 ,
    CLPX21 ,
    CLPX22 ,
    CLPX31 ,
    CLPX32 ,
    CLPX91 ,
    CLPX92

--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_GRU.ABCLI00F');
FROM AS400_BACKUPS.AS400.UNICA_GRU_ABCLI00F_Cliente;
GO

