
CREATE VIEW AS400.UNICA_MYS_CSFAT00F_Fatture_MetraSistemiView
AS
SELECT 'msis' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_MYS.CSFAT00F WHERE FTANNO BETWEEN 2005 AND 2011 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_MYS_CSFAT00F_Fatture_MetraSistemi WHERE FTANNO BETWEEN 2005 AND 2011;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

