
CREATE VIEW AS400.UNICA_PUG_CSFAT00F_Fatture_MetraPugliaView
AS
SELECT 'mpug' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_PUG.CSFAT00F WHERE FTANNO BETWEEN 2005 AND 2014 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_PUG_CSFAT00F_Fatture_MetraPuglia WHERE FTANNO BETWEEN 2005 AND 2014;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

