
CREATE VIEW AS400.UNICA_COM_CSFAT00F_Fatture_MetraComponentiView
AS
SELECT 'mcom' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_COM.CSFAT00F WHERE FTANNO >= 2005 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_COM_CSFAT00F_Fatture_MetraComponenti WHERE FTANNO >= 2005;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

