
CREATE VIEW AS400.UNICA_MES_CSFAT00F_Fatture_MetraServiceView
AS
SELECT 'mser' AS IDAzienda, *
--FROM OPENQUERY(ALBERTO, 'SELECT * FROM UNICA_MES.CSFAT00F WHERE FTANNO BETWEEN 2005 AND 2014 ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT');
FROM AS400_BACKUPS.AS400.UNICA_MES_CSFAT00F_Fatture_MetraService WHERE FTANNO BETWEEN 2005 AND 2014;-- ORDER BY FTCDAZ, FTTCLF, FTANNO, FTMESE, FTCLIF, FTDIVI, FTCDAG, FTVALU, FTCONT;
GO

