CREATE TABLE [Import].[Date]
(
[DateKey] [int] NOT NULL,
[Date] [date] NOT NULL,
[FullDateUK] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FullDateUSA] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayOfMonth] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DaySuffix] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayName] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayOfWeekUSA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayOfWeekUK] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayOfWeekInMonth] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayOfWeekInYear] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayOfQuarter] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DayOfYear] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WeekOfMonth] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WeekOfQuarter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WeekOfYear] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Month] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MonthName] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MonthOfQuarter] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Quarter] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[QuarterName] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Year] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[YearName] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MonthYear] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MMYYYY] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FirstDayOfMonth] [date] NOT NULL,
[LastDayOfMonth] [date] NOT NULL,
[FirstDayOfQuarter] [date] NOT NULL,
[LastDayOfQuarter] [date] NOT NULL,
[FirstDayOfYear] [date] NOT NULL,
[LastDayOfYear] [date] NOT NULL,
[IsHolidayUSA] [bit] NULL,
[IsWeekday] [bit] NULL,
[HolidayUSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsHolidayUK] [bit] NULL,
[HolidayUK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DayNameIT] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MonthNameIT] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsHolidayIT] [bit] NULL,
[HolidayIT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullDateIT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FiscalDayOfYear] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalWeekOfYear] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalMonth] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalQuarter] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalQuarterName] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalYear] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalYearName] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalMonthYear] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalMMYYYY] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FiscalFirstDayOfMonth] [date] NULL,
[FiscalLastDayOfMonth] [date] NULL,
[FiscalFirstDayOfQuarter] [date] NULL,
[FiscalLastDayOfQuarter] [date] NULL,
[FiscalFirstDayOfYear] [date] NULL,
[FiscalLastDayOfYear] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [Import].[Date] ADD CONSTRAINT [PK_Import_Date] PRIMARY KEY CLUSTERED ([DateKey]) ON [PRIMARY]
GO
