CREATE TABLE [AX2009].[ADDRESSCOUNTY_Provincia] (
    [DATAAREAID]      CHAR (4)      NOT NULL,
    [COUNTRYREGIONID] NVARCHAR (10) NOT NULL,
    [STATEID]         NVARCHAR (10) NOT NULL,
    [COUNTYID]        NVARCHAR (10) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [NAME]            NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[ADDRESSCOUNTY_Provincia]
    ADD CONSTRAINT [PK_ADDRESSCOUNTY_Provincia] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [COUNTRYREGIONID] ASC, [STATEID] ASC, [COUNTYID] ASC);
GO

