CREATE TABLE [AX2009].[ADDRESSCOUNTRYREGION_Nazione] (
    [DATAAREAID]      CHAR (4)      NOT NULL,
    [COUNTRYREGIONID] NVARCHAR (10) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [TYPE]            SMALLINT      NOT NULL,
    [ISOCODE]         NVARCHAR (2)  NOT NULL,
    [NAME]            NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[ADDRESSCOUNTRYREGION_Nazione]
    ADD CONSTRAINT [PK_ADDRESSCOUNTRYREGION_Nazione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [COUNTRYREGIONID] ASC);
GO

