CREATE TABLE [AX2009].[ADDRESSSTATE_Regione] (
    [DATAAREAID]      CHAR (4)      NOT NULL,
    [COUNTRYREGIONID] NVARCHAR (10) NOT NULL,
    [STATEID]         NVARCHAR (10) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [NAME]            NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[ADDRESSSTATE_Regione]
    ADD CONSTRAINT [PK_ADDRESSSTATE_Regione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [COUNTRYREGIONID] ASC, [STATEID] ASC);
GO

