CREATE TABLE [AX2009].[AIFENDPOINT_AIFEndPoint] (
    [DATAAREAID]            CHAR (4)      NOT NULL,
    [ENDPOINTID]            NVARCHAR (30) NOT NULL,
    [RECID]                 BIGINT        NOT NULL,
    [INTERCOMPANYCOMPANYID] CHAR (4)      NOT NULL,
    [NAME]                  NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[AIFENDPOINT_AIFEndPoint]
    ADD CONSTRAINT [PK_AIFENDPOINT_AIFEndPoint] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ENDPOINTID] ASC);
GO

