CREATE TABLE [AX2009].[AIFENDPOINTCONSTRAINT_AIFEndPointConstraint] (
    [DATAAREAID]     CHAR (4)      NOT NULL,
    [ENDPOINTID]     NVARCHAR (30) NOT NULL,
    [CONSTRAINTID]   NVARCHAR (20) NOT NULL,
    [RECID]          BIGINT        NOT NULL,
    [CONSTRAINTTYPE] SMALLINT      NOT NULL
);
GO

ALTER TABLE [AX2009].[AIFENDPOINTCONSTRAINT_AIFEndPointConstraint]
    ADD CONSTRAINT [PK_AIFENDPOINTCONSTRAINT_AIFEndPointConstraint] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ENDPOINTID] ASC, [CONSTRAINTID] ASC);
GO

