CREATE TABLE [AX2009].[ASSETTABLE_Cespite] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [ASSETID]    NVARCHAR (20) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [ASSETGROUP] NVARCHAR (10) NOT NULL,
    [NAME]       NVARCHAR (30) NOT NULL
);
GO

ALTER TABLE [AX2009].[ASSETTABLE_Cespite]
    ADD CONSTRAINT [PK_ASSETTABLE_Cespite] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ASSETID] ASC);
GO

