CREATE TABLE [AX2009].[ASSETGROUP_GruppoCespiti] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [GROUPID]    NVARCHAR (10) NOT NULL,
    [NAME]       NVARCHAR (30) NOT NULL
);
GO

ALTER TABLE [AX2009].[ASSETGROUP_GruppoCespiti]
    ADD CONSTRAINT [PK_ASSETGROUP_GruppoCespiti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [GROUPID] ASC);
GO

