CREATE TABLE [AX2009].[ASSETTRANS_AmmortamentoCespiti] (
    [DATAAREAID]   CHAR (4)         NOT NULL,
    [ASSETID]      NVARCHAR (20)    NOT NULL,
    [VOUCHER]      NVARCHAR (20)    NOT NULL,
    [TRANSDATE]    DATE             NOT NULL,
    [RECID]        BIGINT           NOT NULL,
    [TXT]          NVARCHAR (60)    NOT NULL,
    [DIMENSION]    NVARCHAR (10)    NOT NULL,
    [DIMENSION2_]  NVARCHAR (10)    NOT NULL,
    [DIMENSION3_]  NVARCHAR (10)    NOT NULL,
    [TRANSTYPE]    SMALLINT         NOT NULL,
    [ASSETGROUP]   NVARCHAR (10)    NOT NULL,
    [DIMENSION4_]  NVARCHAR (10)    NOT NULL,
    [DIMENSION5_]  NVARCHAR (10)    NOT NULL,
    [DIMENSION6_]  NVARCHAR (10)    NOT NULL,
    [CURRENCYCODE] NVARCHAR (3)     NOT NULL,
    [AMOUNTCUR]    NUMERIC (28, 12) NOT NULL,
    [AMOUNTMST]    NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[ASSETTRANS_AmmortamentoCespiti]
    ADD CONSTRAINT [PK_ASSETTRANS_AmmortamentoCespiti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ASSETID] ASC, [VOUCHER] ASC, [TRANSDATE] ASC, [RECID] ASC);
GO

