CREATE TABLE [AX2009].[BANKREMITTANCEFILESCUST_FileRimesseClienti] (
    [DATAAREAID]      CHAR (4)         NOT NULL,
    [FILEID]          NVARCHAR (10)    NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    [BANKACCOUNTID]   NVARCHAR (10)    NOT NULL,
    [CREATEDDATETIME] DATETIME         NOT NULL,
    [AMOUNTMST]       NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[BANKREMITTANCEFILESCUST_FileRimesseClienti]
    ADD CONSTRAINT [PK_BANKREMITTANCEFILESCUST_FileRimesseClienti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [FILEID] ASC);
GO

