CREATE TABLE [AX2009].[BANKACCOUNTTABLE_ContoBancario] (
    [DATAAREAID] CHAR (4)       NOT NULL,
    [ACCOUNTID]  NVARCHAR (10)  NOT NULL,
    [RECID]      BIGINT         NOT NULL,
    [NAME]       NVARCHAR (100) NOT NULL
);
GO

ALTER TABLE [AX2009].[BANKACCOUNTTABLE_ContoBancario]
    ADD CONSTRAINT [PK_BANKACCOUNTTABLE_ContoBancario] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ACCOUNTID] ASC);
GO

