CREATE TABLE [AX2009].[BOM_VersioneDBA_Riga] (
    [DATAAREAID]  CHAR (4)         NOT NULL,
    [BOMID]       NVARCHAR (20)    NOT NULL,
    [LINENUM]     NUMERIC (28, 12) NOT NULL,
    [RECID]       BIGINT           NOT NULL,
    [ITEMID]      NVARCHAR (20)    NOT NULL,
    [BOMQTY]      NUMERIC (28, 12) NOT NULL,
    [FROMDATE]    DATE             NOT NULL,
    [TODATE]      DATE             NOT NULL,
    [INVENTDIMID] NVARCHAR (20)    NOT NULL
);
GO

ALTER TABLE [AX2009].[BOM_VersioneDBA_Riga]
    ADD CONSTRAINT [PK_BOM_VersioneDBA_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BOMID] ASC, [LINENUM] ASC, [RECID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_BOM_VersioneDBA_Riga_DATAAREAID_ITEMID_INCLUDE]
    ON [AX2009].[BOM_VersioneDBA_Riga]([DATAAREAID] ASC, [ITEMID] ASC)
    INCLUDE([BOMID]);
GO

