CREATE TABLE [AX2009].[BOMCALCGROUP_GruppoCalcoloDBA] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [CALCGROUPID]      NVARCHAR (10) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [NAME]             NVARCHAR (60) NOT NULL,
    [STOPEXPLODEPRICE] BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[BOMCALCGROUP_GruppoCalcoloDBA]
    ADD CONSTRAINT [PK_BOMCALCGROUP_GruppoCalcoloDBA] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CALCGROUPID] ASC);
GO

