CREATE TABLE [AX2009].[BOMCALCTABLE_CalcoloDBA] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [PRICECALCID] NVARCHAR (20) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [ITEMID]      NVARCHAR (20) NOT NULL,
    [TRANSDATE]   DATE          NOT NULL
) ON [ups_BOMCalcTables] ([TRANSDATE]);
GO

CREATE UNIQUE CLUSTERED INDEX [IX_BOMCALCTABLE_CalcoloDBA_TRANSDATE_DATAAREAID_PRICECALCID]
    ON [AX2009].[BOMCALCTABLE_CalcoloDBA]([TRANSDATE] ASC, [DATAAREAID] ASC, [PRICECALCID] ASC)
    ON [ups_BOMCalcTables] ([TRANSDATE]);
GO

ALTER TABLE [AX2009].[BOMCALCTABLE_CalcoloDBA]
    ADD CONSTRAINT [PK_BOMCALCTABLE_CalcoloDBA] PRIMARY KEY NONCLUSTERED ([DATAAREAID] ASC, [PRICECALCID] ASC) ON [PRIMARY];
GO

