CREATE TABLE [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [PRICECALCID]         NVARCHAR (20)    NOT NULL,
    [LINENUM]             NUMERIC (28, 12) NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [COSTGROUPID]         NVARCHAR (10)    NOT NULL,
    [LEVEL_]              INT              NOT NULL,
    [QTY]                 NUMERIC (28, 12) NOT NULL,
    [COSTPRICE]           NUMERIC (28, 12) NOT NULL,
    [TRANSDATE]           DATE             NOT NULL,
    [KEY1]                NVARCHAR (20)    NOT NULL,
    [KEY2]                NVARCHAR (10)    NOT NULL,
    [KEY3]                NVARCHAR (20)    NOT NULL,
    [CONSUMPTIONVARIABLE] NUMERIC (28, 12) NOT NULL,
    [OPRNUM]              INT              NOT NULL,
    [CALCTYPE]            SMALLINT         NOT NULL,
    [COSTPRICEUNIT]       NUMERIC (28, 12) NOT NULL,
    [COSTPRICEQTY]        NUMERIC (28, 12) NOT NULL,
    [COSTMARKUPQTY]       NUMERIC (28, 12) NOT NULL,
    [PARENTRECID]         BIGINT           NOT NULL,
    [IsFoglia]            BIT              NOT NULL,
    [SERVICEITEMRECID]    BIGINT           NOT NULL,
    [CONSUMPTIONCONSTANT] DECIMAL (28, 12) NULL
) ON [ups_BOMCalcTables] ([TRANSDATE]);
GO

ALTER TABLE [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga]
    ADD CONSTRAINT [DFT_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_SERVICEITEMRECID] DEFAULT ((0)) FOR [SERVICEITEMRECID];
GO

ALTER TABLE [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga]
    ADD CONSTRAINT [DFT_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_IsFoglia] DEFAULT ((1)) FOR [IsFoglia];
GO

ALTER TABLE [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga]
    ADD CONSTRAINT [DFT_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_PARENTRECID] DEFAULT ((0)) FOR [PARENTRECID];
GO

ALTER TABLE [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga]
    ADD CONSTRAINT [PK_BOMCALCTRANS_CalcoloDBA_Riga] PRIMARY KEY NONCLUSTERED ([DATAAREAID] ASC, [PRICECALCID] ASC, [LINENUM] ASC) ON [PRIMARY];
GO

CREATE UNIQUE CLUSTERED INDEX [IX_BOMCALCTRANS_CalcoloDBA_Riga_TRANSDATE_DATAAREAID_PRICECALCID_LINENUM]
    ON [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga]([TRANSDATE] ASC, [DATAAREAID] ASC, [PRICECALCID] ASC, [LINENUM] ASC)
    ON [ups_BOMCalcTables] ([TRANSDATE]);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_DATAAREAID_KEY1]
    ON [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga]([DATAAREAID] ASC, [KEY1] ASC)
    INCLUDE([RECID], [OPRNUM]) WITH (FILLFACTOR = 100)
    ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_AX2009_BOMCALCTRANS_CalcoloDBA_Riga_RECID]
    ON [AX2009].[BOMCALCTRANS_CalcoloDBA_Riga]([RECID] ASC)
    INCLUDE([DATAAREAID], [KEY1])
    ON [PRIMARY];
GO

