CREATE TABLE [AX2009].[BOMVERSION_VersioneDBA] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [BOMID]      NVARCHAR (20) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [TODATE]     DATE          NOT NULL,
    [FROMDATE]   DATE          NOT NULL,
    [ITEMID]     NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[BOMVERSION_VersioneDBA]
    ADD CONSTRAINT [PK_BOMVERSION_VersioneDBA] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BOMID] ASC, [RECID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_BOMVERSION_VersioneDBA_DATAAREAID_ITEMID_BOMID]
    ON [AX2009].[BOMVERSION_VersioneDBA]([DATAAREAID] ASC, [ITEMID] ASC, [BOMID] ASC);
GO

