CREATE TABLE [AX2009].[CASHDISC_ScontoCassa] (
    [DATAAREAID]   CHAR (4)      NOT NULL,
    [CASHDISCCODE] NVARCHAR (10) NOT NULL,
    [RECID]        BIGINT        NOT NULL,
    [DESCRIPTION]  NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[CASHDISC_ScontoCassa]
    ADD CONSTRAINT [PK_CASHDISC_ScontoCassa] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CASHDISCCODE] ASC);
GO

