CREATE TABLE [AX2009].[COMMISSIONSALESGROUP_GruppoVendite] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [GROUPID]    NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[COMMISSIONSALESGROUP_GruppoVendite]
    ADD CONSTRAINT [PK_COMMISSIONSALESGROUP_GruppoVendite] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [GROUPID] ASC);
GO

