CREATE TABLE [AX2009].[COMMISSIONSALESREP_Agente] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [GROUPID]    NVARCHAR (10) NOT NULL,
    [EMPLID]     NVARCHAR (20) NOT NULL,
    [RECID]      BIGINT        NOT NULL
);
GO

ALTER TABLE [AX2009].[COMMISSIONSALESREP_Agente]
    ADD CONSTRAINT [PK_COMMISSIONSALESREP_Agente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [GROUPID] ASC, [EMPLID] ASC);
GO

