CREATE TABLE [AX2009].[COMPANYINFO_InformazioniAzienda] (
    [DATAAREAID]   CHAR (4)      NOT NULL,
    [RECID]        BIGINT        NOT NULL,
    [NAME]         NVARCHAR (60) NOT NULL,
    [CURRENCYCODE] NVARCHAR (3)  NOT NULL
);
GO

ALTER TABLE [AX2009].[COMPANYINFO_InformazioniAzienda]
    ADD CONSTRAINT [PK_COMPANYINFO_InformazioniAzienda] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC);
GO

