CREATE TABLE [AX2009].[CUSTINVOICELINE_FattureClienteTestoLibero_Riga] (
    [DATAAREAID]    CHAR (4)         NOT NULL,
    [PARENTRECID]   BIGINT           NOT NULL,
    [LINENUM]       NUMERIC (28, 12) NOT NULL,
    [RECID]         BIGINT           NOT NULL,
    [LEDGERACCOUNT] NVARCHAR (20)    NOT NULL,
    [DIMENSION]     NVARCHAR (10)    NOT NULL,
    [DIMENSION2_]   NVARCHAR (10)    NOT NULL,
    [DIMENSION3_]   NVARCHAR (10)    NOT NULL,
    [DIMENSION4_]   NVARCHAR (10)    NOT NULL,
    [DIMENSION5_]   NVARCHAR (10)    NOT NULL,
    [DIMENSION6_]   NVARCHAR (10)    NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTINVOICELINE_FattureClienteTestoLibero_Riga]
    ADD CONSTRAINT [PK_CUSTINVOICELINE_FattureClienteTestoLibero_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PARENTRECID] ASC, [LINENUM] ASC, [RECID] ASC) WITH (FILLFACTOR = 100);
GO

