CREATE TABLE [AX2009].[CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [CODE]       NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [TXT]        NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione]
    ADD CONSTRAINT [PK_CUSTCLASSIFICATIONGROUP_ClienteGruppoClassificazione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CODE] ASC);
GO

