CREATE TABLE [AX2009].[CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo] (
    [DATAAREAID]       CHAR (4)        NOT NULL,
    [ITEMID]           NVARCHAR (20)   NOT NULL,
    [INVENTDIMID]      NVARCHAR (20)   NOT NULL,
    [MODULETYPE]       SMALLINT        NOT NULL,
    [CUSTVENDRELATION] NVARCHAR (20)   NOT NULL,
    [RECID]            BIGINT          NOT NULL,
    [EXTERNALITEMTXT]  NVARCHAR (1000) NOT NULL,
    [EXTERNALITEMID]   NVARCHAR (30)   NOT NULL
);
GO

CREATE STATISTICS [MODULETYPE]
    ON [AX2009].[CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo]([MODULETYPE]);
GO

CREATE STATISTICS [CUSTVENDRELATION]
    ON [AX2009].[CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo]([CUSTVENDRELATION]);
GO

ALTER TABLE [AX2009].[CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo]
    ADD CONSTRAINT [PK_CUSTVENDEXTERNALITEM_DescrizioneEsternaArticolo] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [INVENTDIMID] ASC, [MODULETYPE] ASC, [CUSTVENDRELATION] ASC);
GO

