CREATE TABLE [AX2009].[CUSTINVOICETRANS_FattureCliente_Riga] (
    [DATAAREAID]           CHAR (4)         NOT NULL,
    [INVOICEDATE]          DATE             NOT NULL,
    [INVOICEID]            NVARCHAR (20)    NOT NULL,
    [SALESID]              NVARCHAR (20)    NOT NULL,
    [NUMBERSEQUENCEGROUP]  NVARCHAR (10)    NOT NULL,
    [LINENUM]              NUMERIC (28, 12) NOT NULL,
    [RECID]                BIGINT           NOT NULL,
    [INVENTTRANSID]        NVARCHAR (20)    NOT NULL,
    [ITEMID]               NVARCHAR (20)    NOT NULL,
    [NAME]                 NVARCHAR (1000)  NOT NULL,
    [SALESGROUP]           NVARCHAR (10)    NOT NULL,
    [LEDGERACCOUNT]        NVARCHAR (20)    NOT NULL,
    [DIMENSION]            NVARCHAR (10)    NOT NULL,
    [DIMENSION2_]          NVARCHAR (10)    NOT NULL,
    [DIMENSION3_]          NVARCHAR (10)    NOT NULL,
    [ORIGSALESID]          NVARCHAR (20)    NOT NULL,
    [INVENTDIMID]          NVARCHAR (20)    NOT NULL,
    [DIMENSION4_]          NVARCHAR (10)    NOT NULL,
    [DIMENSION5_]          NVARCHAR (10)    NOT NULL,
    [DIMENSION6_]          NVARCHAR (10)    NOT NULL,
    [SALESUNIT]            NVARCHAR (10)    NOT NULL,
    [QTY]                  NUMERIC (28, 12) NOT NULL,
    [INVENTQTY]            NUMERIC (28, 12) NOT NULL,
    [NPOQTYSHIPPED]        NUMERIC (28, 12) NOT NULL,
    [CURRENCYCODE]         NVARCHAR (3)     NOT NULL,
    [LINEAMOUNT]           NUMERIC (28, 12) NOT NULL,
    [LINEAMOUNTMST]        NUMERIC (28, 12) NOT NULL,
    [SALESPRICE]           NUMERIC (28, 12) NOT NULL,
    [PRICEUNIT]            NUMERIC (28, 12) NOT NULL,
    [DISCPERCENT]          NUMERIC (28, 12) NOT NULL,
    [DISCAMOUNT]           NUMERIC (28, 12) NOT NULL,
    [METSYSSALESPRICE]     NUMERIC (28, 12) NOT NULL,
    [METSYSLINEDISC]       NUMERIC (28, 12) NOT NULL,
    [METSYSLINEPERCENT]    NUMERIC (28, 12) NOT NULL,
    [METVENDPROJECTID]     NVARCHAR (20)    NOT NULL,
    [METMETALCOVERPRICEKG] NUMERIC (28, 12) NOT NULL,
    [METPROJECTCODE]       NVARCHAR (40)    NOT NULL,
    [SUMLINEDISC]          NUMERIC (28, 12) NOT NULL,
    [SUMLINEDISCMST]       NUMERIC (28, 12) NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_CUSTINVOICETRANS_FattureCliente_Riga_DATAAREAID_INVENTTRANSID_ORIGSALESID_INCLUDE]
    ON [AX2009].[CUSTINVOICETRANS_FattureCliente_Riga]([DATAAREAID] ASC, [INVENTTRANSID] ASC, [ORIGSALESID] ASC)
    INCLUDE([INVOICEDATE], [INVOICEID], [SALESID], [RECID], [QTY], [LINEAMOUNTMST]);
GO

CREATE STATISTICS [LINENUM]
    ON [AX2009].[CUSTINVOICETRANS_FattureCliente_Riga]([LINENUM]);
GO

ALTER TABLE [AX2009].[CUSTINVOICETRANS_FattureCliente_Riga]
    ADD CONSTRAINT [PK_CUSTINVOICETRANS_FattureCliente_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVOICEDATE] ASC, [INVOICEID] ASC, [SALESID] ASC, [NUMBERSEQUENCEGROUP] ASC, [LINENUM] ASC, [RECID] ASC);
GO

