CREATE TABLE [AX2009].[CUSTPAYMMODETABLE_MetodoPagamentoCliente] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [PAYMMODE]    NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [NAME]        NVARCHAR (60) NOT NULL,
    [NPOPAYMTYPE] NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTPAYMMODETABLE_MetodoPagamentoCliente]
    ADD CONSTRAINT [PK_CUSTPAYMMODETABLE_MetodoPagamentoCliente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PAYMMODE] ASC);
GO

