CREATE TABLE [AX2009].[CUSTPACKINGSLIPTRANS_DDTCliente_Riga] (
    [DATAAREAID]             CHAR (4)         NOT NULL,
    [DELIVERYDATE]           DATE             NOT NULL,
    [PACKINGSLIPID]          NVARCHAR (20)    NOT NULL,
    [SALESID]                NVARCHAR (20)    NOT NULL,
    [NPOLINENUM]             INT              NOT NULL,
    [RECID]                  BIGINT           NOT NULL,
    [INVENTTRANSID]          NVARCHAR (20)    NOT NULL,
    [ITEMID]                 NVARCHAR (20)    NOT NULL,
    [ORIGSALESID]            NVARCHAR (20)    NOT NULL,
    [NPOCONTRACTWORKTRANSID] NVARCHAR (20)    NOT NULL,
    [SALESUNIT]              NVARCHAR (10)    NOT NULL,
    [QTY]                    NUMERIC (28, 12) NOT NULL,
    [INVENTQTY]              NUMERIC (28, 12) NOT NULL,
    [ORDERED]                NUMERIC (28, 12) NOT NULL,
    [REMAIN]                 NUMERIC (28, 12) NOT NULL,
    [NPOCONTRACTWORKQTY]     NUMERIC (28, 12) NOT NULL,
    [NPOQTYSHIPPED]          NUMERIC (28, 12) NOT NULL,
    [NPOCONTRACTWORKSECQTY]  NUMERIC (28, 12) NOT NULL,
    [VALUEMST]               NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTPACKINGSLIPTRANS_DDTCliente_Riga]
    ADD CONSTRAINT [PK_CUSTPACKINGSLIPTRANS_DDTCliente_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [DELIVERYDATE] ASC, [PACKINGSLIPID] ASC, [SALESID] ASC, [NPOLINENUM] ASC, [RECID] ASC);
GO

