CREATE TABLE [AX2009].[CUSTSETTLEMENT_LiquidazioniCliente] (
    [DATAAREAID]         CHAR (4)         NOT NULL,
    [TRANSRECID]         BIGINT           NOT NULL,
    [TRANSDATE]          DATE             NOT NULL,
    [RECID]              BIGINT           NOT NULL,
    [OFFSETTRANSVOUCHER] NVARCHAR (20)    NOT NULL,
    [DUEDATE]            DATE             NOT NULL,
    [OFFSETCOMPANY]      NVARCHAR (4)     NOT NULL,
    [OFFSETACCOUNTNUM]   NVARCHAR (20)    NOT NULL,
    [SETTLEAMOUNTCUR]    NUMERIC (28, 12) NOT NULL,
    [SETTLEAMOUNTMST]    NUMERIC (28, 12) NOT NULL,
    [EXCHADJUSTMENT]     NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTSETTLEMENT_LiquidazioniCliente]
    ADD CONSTRAINT [PK_CUSTSETTLEMENT_LiquidazioniCliente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSRECID] ASC, [TRANSDATE] ASC, [RECID] ASC);
GO

