CREATE TABLE [AX2009].[CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga] (
    [DATAAREAID]       CHAR (4)         NOT NULL,
    [BILLOFEXCHANGEID] NVARCHAR (20)    NOT NULL,
    [SEQNUM]           INT              NOT NULL,
    [RECID]            BIGINT           NOT NULL,
    [STATUS]           INT              NOT NULL,
    [TRANSDATE]        DATE             NOT NULL,
    [DUEDATE]          DATE             NOT NULL,
    [CURRENCYCODE]     NVARCHAR (3)     NOT NULL,
    [AMOUNTCUR]        NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga]
    ADD CONSTRAINT [PK_CUSTBILLOFEXCHANGETRANS_EffettiAttivi_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BILLOFEXCHANGEID] ASC, [SEQNUM] ASC, [RECID] ASC);
GO

