CREATE TABLE [AX2009].[CUSTGROUP_ClienteGruppo] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [CUSTGROUP]  NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTGROUP_ClienteGruppo]
    ADD CONSTRAINT [PK_CUSTGROUP_ClienteGruppo] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CUSTGROUP] ASC);
GO

