CREATE TABLE [AX2009].[CUSTBILLOFEXCHANGEJOUR_EffettiAttivi] (
    [DATAAREAID]           CHAR (4)      NOT NULL,
    [BILLOFEXCHANGEID]     NVARCHAR (20) NOT NULL,
    [RECID]                BIGINT        NOT NULL,
    [CUSTACCOUNT]          NVARCHAR (20) NOT NULL,
    [BILLOFEXCHANGESEQNUM] INT           NOT NULL,
    [STATUS]               INT           NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTBILLOFEXCHANGEJOUR_EffettiAttivi]
    ADD CONSTRAINT [PK_CUSTBILLOFEXCHANGEJOUR_EffettiAttivi] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BILLOFEXCHANGEID] ASC);
GO

