CREATE TABLE [AX2009].[CUSTINVOICETABLE_FattureClienteTestoLibero] (
    [DATAAREAID]          CHAR (4)      NOT NULL,
    [INVOICEDATE]         DATE          NOT NULL,
    [INVOICEID]           NVARCHAR (20) NOT NULL,
    [NUMBERSEQUENCEGROUP] NVARCHAR (10) NOT NULL,
    [RECID]               BIGINT        NOT NULL,
    [DLVCOUNTRYREGIONID]  NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTINVOICETABLE_FattureClienteTestoLibero]
    ADD CONSTRAINT [PK_CUSTINVOICETABLE_FattureClienteTestoLibero] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVOICEDATE] ASC, [INVOICEID] ASC, [NUMBERSEQUENCEGROUP] ASC);
GO

