CREATE TABLE [AX2009].[CUSTTRANSOPEN_TransazioniClienteAperte] (
    [DATAAREAID] CHAR (4)         NOT NULL,
    [ACCOUNTNUM] NVARCHAR (20)    NOT NULL,
    [DUEDATE]    DATE             NOT NULL,
    [RECID]      BIGINT           NOT NULL,
    [REFRECID]   BIGINT           NOT NULL,
    [TRANSDATE]  DATE             NOT NULL,
    [AMOUNTCUR]  NUMERIC (28, 12) NOT NULL,
    [AMOUNTMST]  NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTTRANSOPEN_TransazioniClienteAperte]
    ADD CONSTRAINT [PK_CUSTTRANSOPEN_TransazioniClienteAperte] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ACCOUNTNUM] ASC, [DUEDATE] ASC, [RECID] ASC) WITH (FILLFACTOR = 100);
GO

