CREATE TABLE [AX2009].[CUSTCONFIRMJOUR_ConfermaOrdineCliente] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [CONFIRMID]   NVARCHAR (20) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [CONFIRMDATE] DATE          NOT NULL,
    [SALESID]     NVARCHAR (20) NOT NULL
);
GO

CREATE STATISTICS [CONFIRMID]
    ON [AX2009].[CUSTCONFIRMJOUR_ConfermaOrdineCliente]([CONFIRMID]);
GO

ALTER TABLE [AX2009].[CUSTCONFIRMJOUR_ConfermaOrdineCliente]
    ADD CONSTRAINT [PK_CUSTCONFIRMJOUR_ConfermaOrdineCliente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CONFIRMID] ASC);
GO

