CREATE TABLE [AX2009].[CUSTPACKINGSLIPJOUR_DDTCliente] (
    [DATAAREAID]             CHAR (4)         NOT NULL,
    [DELIVERYDATE]           DATE             NOT NULL,
    [PACKINGSLIPID]          NVARCHAR (20)    NOT NULL,
    [SALESID]                NVARCHAR (20)    NOT NULL,
    [RECID]                  BIGINT           NOT NULL,
    [ORDERACCOUNT]           NVARCHAR (20)    NOT NULL,
    [INVOICEACCOUNT]         NVARCHAR (20)    NOT NULL,
    [DELIVERYNAME]           NVARCHAR (60)    NOT NULL,
    [DELIVERYADDRESS]        NVARCHAR (250)   NOT NULL,
    [INVOICECOUNTRYREGIONID] NVARCHAR (10)    NOT NULL,
    [DLVTERM]                NVARCHAR (10)    NOT NULL,
    [DLVMODE]                NVARCHAR (10)    NOT NULL,
    [LEDGERVOUCHER]          NVARCHAR (20)    NOT NULL,
    [DLVZIPCODE]             NVARCHAR (10)    NOT NULL,
    [DLVCOUNTY]              NVARCHAR (10)    NOT NULL,
    [DLVCOUNTRYREGIONID]     NVARCHAR (10)    NOT NULL,
    [DLVSTATE]               NVARCHAR (10)    NOT NULL,
    [DELIVERYCITY]           NVARCHAR (60)    NOT NULL,
    [DELIVERYSTREET]         NVARCHAR (250)   NOT NULL,
    [SHIPCARRIERID]          NVARCHAR (10)    NOT NULL,
    [NPOTRANSPORTSTART]      DATETIME         NOT NULL,
    [NPOPACKINGSLIPFROMWMS]  BIT              NOT NULL,
    [NPOJOURNEYID]           NVARCHAR (20)    NOT NULL,
    [NPOREFDATAAREAID]       NVARCHAR (4)     NOT NULL,
    [NPOFREECARIERADDRESS]   NVARCHAR (250)   NOT NULL,
    [NPOPALLETNUM]           INT              NOT NULL,
    [QTY]                    NUMERIC (28, 12) NOT NULL,
    [WEIGHT]                 NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTPACKINGSLIPJOUR_DDTCliente]
    ADD CONSTRAINT [PK_CUSTPACKINGSLIPJOUR_DDTCliente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [DELIVERYDATE] ASC, [PACKINGSLIPID] ASC, [SALESID] ASC);
GO

