CREATE TABLE [AX2009].[CUSTTRANS_TransazioniCliente] (
    [DATAAREAID]           CHAR (4)         NOT NULL,
    [ACCOUNTNUM]           NVARCHAR (20)    NOT NULL,
    [DUEDATE]              DATE             NOT NULL,
    [RECID]                BIGINT           NOT NULL,
    [TRANSDATE]            DATE             NOT NULL,
    [PAYMMODE]             NVARCHAR (10)    NOT NULL,
    [BILLOFEXCHANGEID]     NVARCHAR (20)    NOT NULL,
    [BILLOFEXCHANGESTATUS] SMALLINT         NOT NULL,
    [BILLOFEXCHANGESEQNUM] INT              NOT NULL,
    [BANKREMITTANCEFILEID] NVARCHAR (10)    NOT NULL,
    [CURRENCYCODE]         NVARCHAR (3)     NOT NULL,
    [AMOUNTCUR]            NUMERIC (28, 12) NOT NULL,
    [AMOUNTMST]            NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[CUSTTRANS_TransazioniCliente]
    ADD CONSTRAINT [PK_CUSTTRANS_TransazioniCliente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ACCOUNTNUM] ASC, [DUEDATE] ASC, [RECID] ASC);
GO

