CREATE TABLE [AX2009].[DATAAREA_Azienda] (
    [ID]        NVARCHAR (4)  NOT NULL,
    [RECID]     BIGINT        NOT NULL,
    [NAME]      NVARCHAR (40) NOT NULL,
    [ISVIRTUAL] BIT           NOT NULL,
    [TIMEZONE]  INT           NOT NULL
);
GO

ALTER TABLE [AX2009].[DATAAREA_Azienda]
    ADD CONSTRAINT [PK_DATAAREA_Azienda] PRIMARY KEY CLUSTERED ([ID] ASC);
GO

