CREATE TABLE [AX2009].[DIMENSIONS_DimensioneContabile] (
    [DATAAREAID]    CHAR (4)      NOT NULL,
    [DIMENSIONCODE] TINYINT       NOT NULL,
    [NUM]           NVARCHAR (10) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    [DESCRIPTION]   NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[DIMENSIONS_DimensioneContabile]
    ADD CONSTRAINT [PK_DIMENSIONS_DimensioneContabile] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [DIMENSIONCODE] ASC, [NUM] ASC) WITH (FILLFACTOR = 100);
GO

