CREATE TABLE [AX2009].[DIRORGANIZATIONDETAIL_DettagliRubrica] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [PARTYID]    NVARCHAR (20) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [ABC]        SMALLINT      NOT NULL
);
GO

ALTER TABLE [AX2009].[DIRORGANIZATIONDETAIL_DettagliRubrica]
    ADD CONSTRAINT [PK_DIRORGANIZATIONDETAIL_DettagliRubrica] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PARTYID] ASC);
GO

