CREATE TABLE [AX2009].[DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica] (
    [DATAAREAID]        CHAR (4)      NOT NULL,
    [PARTYID]           NVARCHAR (20) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [ISPRIMARY]         BIT           NOT NULL,
    [STATUS]            SMALLINT      NOT NULL,
    [VALIDTODATETIME]   DATE          NOT NULL,
    [VALIDFROMDATETIME] DATE          NOT NULL,
    [SHARED]            BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica]
    ADD CONSTRAINT [PK_DIRPARTYADDRESSRELATIONSHIP_IndirizzoRubrica] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PARTYID] ASC, [RECID] ASC) WITH (FILLFACTOR = 100);
GO

