CREATE TABLE [AX2009].[DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi] (
    [DATAAREAID]                    CHAR (4) NOT NULL,
    [PARTYADDRESSRELATIONSHIPRECID] BIGINT   NOT NULL,
    [ADDRESSRECID]                  BIGINT   NOT NULL,
    [REFCOMPANYID]                  CHAR (4) NOT NULL,
    [RECID]                         BIGINT   NOT NULL
);
GO

ALTER TABLE [AX2009].[DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi]
    ADD CONSTRAINT [PK_DIRPARTYADDRESSRELATIONSHI1066_MappingIndirizzi] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PARTYADDRESSRELATIONSHIPRECID] ASC, [ADDRESSRECID] ASC, [REFCOMPANYID] ASC);
GO

