CREATE TABLE [AX2009].[DIRPARTYTABLE_Rubrica] (
    [DATAAREAID]              CHAR (4)      NOT NULL,
    [PARTYID]                 NVARCHAR (20) NOT NULL,
    [RECID]                   BIGINT        NOT NULL,
    [NAME]                    NVARCHAR (60) NOT NULL,
    [NPODIRPARTYTABLEGROUPID] NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[DIRPARTYTABLE_Rubrica]
    ADD CONSTRAINT [PK_DIRPARTYTABLE_Rubrica] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PARTYID] ASC);
GO

