CREATE TABLE [AX2009].[DLVMODE_ModalitaConsegna] (
    [DATAAREAID]            CHAR (4)      NOT NULL,
    [CODE]                  NVARCHAR (10) NOT NULL,
    [RECID]                 BIGINT        NOT NULL,
    [TXT]                   NVARCHAR (60) NOT NULL,
    [SHIPCARRIERID]         NVARCHAR (10) NOT NULL,
    [INTRASTATTRANSPORTID]  NVARCHAR (10) NOT NULL,
    [NPOJOURNEYEXTRAITEMID] NVARCHAR (20) NOT NULL,
    [NPOJOURNEYITEMID]      NVARCHAR (20) NOT NULL,
    [NPOJOURNEYPRICEGROUP]  NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[DLVMODE_ModalitaConsegna]
    ADD CONSTRAINT [PK_DLVMODE_ModalitaConsegna] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CODE] ASC);
GO

