CREATE TABLE [AX2009].[DLVTERM_TerminiConsegna] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [CODE]       NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [TXT]        NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[DLVTERM_TerminiConsegna]
    ADD CONSTRAINT [PK_DLVTERM_TerminiConsegna] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CODE] ASC);
GO

