CREATE TABLE [AX2009].[EMPLTABLE_Dipendente] (
    [DATAAREAID]     CHAR (4)      NOT NULL,
    [EMPLID]         NVARCHAR (20) NOT NULL,
    [RECID]          BIGINT        NOT NULL,
    [PARTYID]        NVARCHAR (20) NOT NULL,
    [PBAUSERPROFILE] NVARCHAR (10) NOT NULL,
    [DIMENSION6_]    NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[EMPLTABLE_Dipendente]
    ADD CONSTRAINT [PK_EMPLTABLE_Dipendente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [EMPLID] ASC) WITH (FILLFACTOR = 100);
GO

