CREATE TABLE [AX2009].[EXCHRATES_TassiDiCambio] (
    [DATAAREAID]   CHAR (4)         NOT NULL,
    [CURRENCYCODE] NVARCHAR (3)     NOT NULL,
    [FROMDATE]     DATE             NOT NULL,
    [RECID]        BIGINT           NOT NULL,
    [TODATE]       DATE             NOT NULL,
    [EXCHRATE]     NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[EXCHRATES_TassiDiCambio]
    ADD CONSTRAINT [PK_EXCHRATES_TassiDiCambio] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CURRENCYCODE] ASC, [FROMDATE] ASC) WITH (FILLFACTOR = 100);
GO

