CREATE TABLE [AX2009].[FDY_DOCF_FINANCIALVOICE_VoceFinanziaria] (
    [FDY_DOCF_VOCEFINANZIARIA] NVARCHAR (6)  NOT NULL,
    [RECID]                    BIGINT        NOT NULL,
    [DESCRIPTION]              NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[FDY_DOCF_FINANCIALVOICE_VoceFinanziaria]
    ADD CONSTRAINT [PK_FDY_DOCF_FINANCIALVOICE_VoceFinanziaria] PRIMARY KEY CLUSTERED ([FDY_DOCF_VOCEFINANZIARIA] ASC);
GO

