CREATE TABLE [AX2009].[INTRASTATTRANSPORTMODE_Trasporto] (
    [DATAAREAID]    CHAR (4)      NOT NULL,
    [TRANSPORTCODE] NVARCHAR (10) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    [DESCRIPTION]   NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[INTRASTATTRANSPORTMODE_Trasporto]
    ADD CONSTRAINT [PK_INTRASTATTRANSPORTMODE_Trasporto] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSPORTCODE] ASC);
GO

