CREATE TABLE [AX2009].[INVENTPOSTING_History] (
    [DATAAREAID]        CHAR (4)       NOT NULL,
    [INVENTACCOUNTTYPE] INT            NOT NULL,
    [ITEMCODE]          INT            NOT NULL,
    [ITEMRELATION]      NVARCHAR (20)  NOT NULL,
    [CUSTVENDCODE]      INT            NOT NULL,
    [CUSTVENDRELATION]  NVARCHAR (20)  NOT NULL,
    [TAXGROUPID]        NVARCHAR (10)  NOT NULL,
    [COSTCODE]          INT            NOT NULL,
    [COSTRELATION]      NVARCHAR (10)  NOT NULL,
    [FROMDATE]          DATE           NOT NULL,
    [TODATE]            DATE           NULL,
    [HistoricalHashKey] VARBINARY (20) NULL,
    [ChangeHashKey]     VARBINARY (20) NULL,
    [LEDGERACCOUNTID]   NVARCHAR (20)  NOT NULL,
    [IsActive]          BIT            NOT NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [PK_AX2009_INVENTPOSTING_History_FILTERED]
    ON [AX2009].[INVENTPOSTING_History]([DATAAREAID] ASC, [INVENTACCOUNTTYPE] ASC, [ITEMCODE] ASC, [ITEMRELATION] ASC, [CUSTVENDCODE] ASC, [CUSTVENDRELATION] ASC, [TAXGROUPID] ASC, [COSTCODE] ASC, [COSTRELATION] ASC) WHERE ([IsActive]=CONVERT([bit],(1)));
GO

ALTER TABLE [AX2009].[INVENTPOSTING_History]
    ADD CONSTRAINT [PK_AX2009_INVENTPOSTING_History] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVENTACCOUNTTYPE] ASC, [ITEMCODE] ASC, [ITEMRELATION] ASC, [CUSTVENDCODE] ASC, [CUSTVENDRELATION] ASC, [TAXGROUPID] ASC, [COSTCODE] ASC, [COSTRELATION] ASC, [FROMDATE] ASC);
GO

