CREATE TABLE [AX2009].[INVENTITEMSALESSETUP_ArticoloImpostazioniVendita] (
    [DATAAREAID]         CHAR (4)         NOT NULL,
    [ITEMID]             NVARCHAR (20)    NOT NULL,
    [RECID]              BIGINT           NOT NULL,
    [INVENTDIMID]        NVARCHAR (20)    NOT NULL,
    [INVENTDIMIDDEFAULT] NVARCHAR (20)    NOT NULL,
    [OVERRIDE]           BIT              NOT NULL,
    [NPOSALESMTSQTYMAX]  NUMERIC (28, 12) NOT NULL,
    [LEADTIME]           INT              NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita_INVENTDIMID_INVENTDIMIDDEFAULT]
    ON [AX2009].[INVENTITEMSALESSETUP_ArticoloImpostazioniVendita]([INVENTDIMID] ASC, [INVENTDIMIDDEFAULT] ASC);
GO

ALTER TABLE [AX2009].[INVENTITEMSALESSETUP_ArticoloImpostazioniVendita]
    ADD CONSTRAINT [PK_INVENTITEMSALESSETUP_ArticoloImpostazioniVendita] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [RECID] ASC);
GO

