CREATE TABLE [AX2009].[INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte] (
    [DATAAREAID]         CHAR (4)      NOT NULL,
    [ITEMID]             NVARCHAR (20) NOT NULL,
    [INVENTDIMID]        NVARCHAR (20) NOT NULL,
    [RECID]              BIGINT        NOT NULL,
    [INVENTDIMIDDEFAULT] NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte]
    ADD CONSTRAINT [PK_INVENTITEMINVENTSETUP_ArticoloImpostazioniScorte] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [INVENTDIMID] ASC);
GO

