CREATE TABLE [AX2009].[INVENTDIM_DimensioneInventariale] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [INVENTDIMID]      NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [WMSLOCATIONID]    NVARCHAR (10) NOT NULL,
    [WMSPALLETID]      NVARCHAR (18) NOT NULL,
    [INVENTLOCATIONID] NVARCHAR (10) NOT NULL,
    [INVENTSIZEID]     NVARCHAR (10) NOT NULL,
    [INVENTCOLORID]    NVARCHAR (10) NOT NULL,
    [INVENTSITEID]     NVARCHAR (10) NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_INVENTDIM_DimensioneInventariale_INVENTDIMID_INVENTLOCATIONID]
    ON [AX2009].[INVENTDIM_DimensioneInventariale]([INVENTDIMID] ASC, [INVENTLOCATIONID] ASC);
GO

ALTER TABLE [AX2009].[INVENTDIM_DimensioneInventariale]
    ADD CONSTRAINT [PK_INVENTDIM_DimensioneInventariale] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVENTDIMID] ASC);
GO

