CREATE TABLE [AX2009].[INVENTITEMPRICE_PrezzoArticoli] (
    [DATAAREAID]      CHAR (4)         NOT NULL,
    [ITEMID]          NVARCHAR (20)    NOT NULL,
    [VERSIONID]       NVARCHAR (10)    NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    [PRICETYPE]       INT              NOT NULL,
    [PRICEUNIT]       NUMERIC (28, 12) NOT NULL,
    [PRICECALCID]     NVARCHAR (20)    NOT NULL,
    [UNITID]          NVARCHAR (10)    NOT NULL,
    [ACTIVATIONDATE]  DATETIME         NOT NULL,
    [CREATEDDATETIME] DATETIME         NOT NULL,
    [PRICE]           NUMERIC (28, 12) NOT NULL,
    [PRICEQTY]        NUMERIC (28, 12) NOT NULL,
    [MARKUP]          NUMERIC (28, 12) NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_INVENTITEMPRICE_PrezzoArticoli_DATAAREAID_ITEMID_INCLUDE]
    ON [AX2009].[INVENTITEMPRICE_PrezzoArticoli]([DATAAREAID] ASC, [ITEMID] ASC)
    INCLUDE([PRICECALCID], [ACTIVATIONDATE]);
GO

ALTER TABLE [AX2009].[INVENTITEMPRICE_PrezzoArticoli]
    ADD CONSTRAINT [PK_INVENTITEMPRICE_PrezzoArticoli] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [VERSIONID] ASC, [RECID] ASC);
GO

