CREATE TABLE [AX2009].[INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [JOURNALID]   NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [DESCRIPTION] NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale]
    ADD CONSTRAINT [PK_INVENTFISCALLIFOJOURNALTABLE_GiornaliLIFOFiscale] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [JOURNALID] ASC);
GO

