CREATE TABLE [AX2009].[INVENTTABLEMODULE_ArticoloUnitaDiMisura] (
    [DATAAREAID]            CHAR (4)         NOT NULL,
    [ITEMID]                NVARCHAR (20)    NOT NULL,
    [MODULETYPE]            SMALLINT         NOT NULL,
    [RECID]                 BIGINT           NOT NULL,
    [UNITID]                NVARCHAR (10)    NOT NULL,
    [PRICE]                 NUMERIC (28, 12) NOT NULL,
    [PRICEUNIT]             NUMERIC (28, 12) NOT NULL,
    [MARKUP]                NUMERIC (28, 12) NOT NULL,
    [PRICEQTY]              NUMERIC (28, 12) NOT NULL,
    [NPOSECONDINVENTUNITID] NVARCHAR (10)    NOT NULL,
    [NPOSECONDUNITACTIVE]   BIT              NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_INVENTTABLEMODULE_ArticoloUnitaDiMisura_MODULETYPE_INCLUDE]
    ON [AX2009].[INVENTTABLEMODULE_ArticoloUnitaDiMisura]([MODULETYPE] ASC)
    INCLUDE([PRICE], [PRICEUNIT]);
GO

ALTER TABLE [AX2009].[INVENTTABLEMODULE_ArticoloUnitaDiMisura]
    ADD CONSTRAINT [PK_INVENTTABLEMODULE_ArticoloUnitaDiMisura] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [MODULETYPE] ASC);
GO

