CREATE TABLE [AX2009].[INVENTBATCH_Colata] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [ITEMID]           NVARCHAR (20) NOT NULL,
    [INVENTBATCHID]    NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [PRODDATE]         DATE          NOT NULL,
    [METLOGLENGTH]     INT           NOT NULL,
    [METINVENTSIZEID]  NVARCHAR (10) NOT NULL,
    [METINVENTCOLORID] NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTBATCH_Colata]
    ADD CONSTRAINT [PK_INVENTBATCH_Colata] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [INVENTBATCHID] ASC);
GO

