CREATE TABLE [AX2009].[INVENTITEMPURCHSETUP_ArticoloImpostazioniAcquisto] (
    [DATAAREAID]         CHAR (4)      NOT NULL,
    [ITEMID]             NVARCHAR (20) NOT NULL,
    [RECID]              BIGINT        NOT NULL,
    [INVENTDIMID]        NVARCHAR (20) NOT NULL,
    [INVENTDIMIDDEFAULT] NVARCHAR (20) NOT NULL,
    [LEADTIME]           INT           NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTITEMPURCHSETUP_ArticoloImpostazioniAcquisto]
    ADD CONSTRAINT [PK_INVENTITEMPURCHSETUP_ArticoloImpostazioniAcquisto] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [RECID] ASC);
GO

