CREATE TABLE [AX2009].[INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga] (
    [DATAAREAID]        CHAR (4)         NOT NULL,
    [JOURNALID]         NVARCHAR (10)    NOT NULL,
    [ITEMGROUP]         INT              NOT NULL,
    [LINENUM]           NUMERIC (28, 12) NOT NULL,
    [RECID]             BIGINT           NOT NULL,
    [ITEMID]            NVARCHAR (20)    NOT NULL,
    [FISCALLIFOGROUPID] NVARCHAR (10)    NOT NULL,
    [YR]                INT              NOT NULL,
    [UNITID]            NVARCHAR (10)    NOT NULL,
    [REMAINQTY]         NUMERIC (28, 12) NOT NULL,
    [UNITVALUE]         NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga]
    ADD CONSTRAINT [PK_INVENTFISCALLIFOJOURNALTRANS_GiornaliLIFOFiscale_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [JOURNALID] ASC, [ITEMGROUP] ASC, [LINENUM] ASC);
GO

