CREATE TABLE [AX2009].[INVENTITEMLOCATION_ArticoloDimensioneInventariale] (
    [DATAAREAID]   CHAR (4)      NOT NULL,
    [ITEMID]       NVARCHAR (20) NOT NULL,
    [INVENTDIMID]  NVARCHAR (20) NOT NULL,
    [RECID]        BIGINT        NOT NULL,
    [NPODLVAREAID] NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTITEMLOCATION_ArticoloDimensioneInventariale]
    ADD CONSTRAINT [PK_INVENTITEMLOCATION_ArticoloDimensioneInventariale] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [INVENTDIMID] ASC) WITH (FILLFACTOR = 100);
GO

