CREATE TABLE [AX2009].[INVENTTXT_ArticoloTraduzione] (
    [DATAAREAID] CHAR (4)        NOT NULL,
    [ITEMID]     NVARCHAR (20)   NOT NULL,
    [LANGUAGEID] NVARCHAR (7)    NOT NULL,
    [RECID]      BIGINT          NOT NULL,
    [TXT]        NVARCHAR (1000) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTTXT_ArticoloTraduzione]
    ADD CONSTRAINT [PK_INVENTTXT_ArticoloTraduzione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [LANGUAGEID] ASC);
GO

