CREATE TABLE [AX2009].[INVENTITEMGROUP_GruppoArticoli] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [ITEMGROUPID] NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [NAME]        NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTITEMGROUP_GruppoArticoli]
    ADD CONSTRAINT [PK_INVENTITEMGROUP_GruppoArticoli] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMGROUPID] ASC) WITH (FILLFACTOR = 100);
GO

