CREATE TABLE [AX2009].[INVENTTRANSFERTABLE_OrdiniTrasferimento] (
    [DATAAREAID]           CHAR (4)      NOT NULL,
    [TRANSFERID]           NVARCHAR (20) NOT NULL,
    [RECID]                BIGINT        NOT NULL,
    [INVENTLOCATIONIDFROM] NVARCHAR (10) NOT NULL,
    [INVENTLOCATIONIDTO]   NVARCHAR (10) NOT NULL,
    [TRANSFERSTATUS]       SMALLINT      NOT NULL,
    [SHIPDATE]             DATE          NOT NULL,
    [RECEIVEDATE]          DATE          NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTTRANSFERTABLE_OrdiniTrasferimento]
    ADD CONSTRAINT [PK_INVENTTRANSFERTABLE_OrdiniTrasferimento] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSFERID] ASC);
GO

