CREATE TABLE [AX2009].[INVENTLOCATION_Magazzino] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [INVENTSITEID]     NVARCHAR (10) NOT NULL,
    [INVENTLOCATIONID] NVARCHAR (10) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [REQCALENDARID]    NVARCHAR (10) NOT NULL,
    [VENDACCOUNT]      NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTLOCATION_Magazzino]
    ADD CONSTRAINT [PK_INVENTLOCATION_Magazzino] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVENTSITEID] ASC, [INVENTLOCATIONID] ASC);
GO

