CREATE TABLE [AX2009].[INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga] (
    [DATAAREAID]             CHAR (4)         NOT NULL,
    [TRANSFERID]             NVARCHAR (20)    NOT NULL,
    [VOUCHERID]              NVARCHAR (20)    NOT NULL,
    [LINENUM]                NUMERIC (28, 12) NOT NULL,
    [RECID]                  BIGINT           NOT NULL,
    [INVENTTRANSID]          NVARCHAR (20)    NOT NULL,
    [ITEMID]                 NVARCHAR (20)    NOT NULL,
    [INVENTDIMID]            NVARCHAR (20)    NOT NULL,
    [TRANSDATE]              DATE             NOT NULL,
    [NPOINVENTPACKINGSLIPID] NVARCHAR (20)    NOT NULL,
    [UNITID]                 NVARCHAR (10)    NOT NULL,
    [QTYRECEIVED]            NUMERIC (28, 12) NOT NULL,
    [QTYSHIPPED]             NUMERIC (28, 12) NOT NULL,
    [QTYSCRAPPED]            NUMERIC (28, 12) NOT NULL
);
GO

CREATE STATISTICS [LINENUM]
    ON [AX2009].[INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga]([LINENUM]);
GO

CREATE STATISTICS [TRANSFERID]
    ON [AX2009].[INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga]([TRANSFERID]);
GO

CREATE STATISTICS [RECID]
    ON [AX2009].[INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga]([RECID]);
GO

CREATE STATISTICS [VOUCHERID]
    ON [AX2009].[INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga]([VOUCHERID]);
GO

ALTER TABLE [AX2009].[INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga]
    ADD CONSTRAINT [PK_INVENTTRANSFERJOURLINE_OrdiniTrasferimento_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSFERID] ASC, [VOUCHERID] ASC, [LINENUM] ASC, [RECID] ASC);
GO

