CREATE TABLE [AX2009].[INVENTPOSTING_RegistrazioneMagazzino] (
    [DATAAREAID]        CHAR (4)      NOT NULL,
    [INVENTACCOUNTTYPE] INT           NOT NULL,
    [ITEMCODE]          INT           NOT NULL,
    [ITEMRELATION]      NVARCHAR (20) NOT NULL,
    [CUSTVENDCODE]      INT           NOT NULL,
    [CUSTVENDRELATION]  NVARCHAR (20) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [TAXGROUPID]        NVARCHAR (10) NOT NULL,
    [LEDGERACCOUNTID]   NVARCHAR (20) NOT NULL,
    [COSTCODE]          INT           NOT NULL,
    [COSTRELATION]      NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTPOSTING_RegistrazioneMagazzino]
    ADD CONSTRAINT [PK_INVENTPOSTING_RegistrazioneMagazzino] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVENTACCOUNTTYPE] ASC, [ITEMCODE] ASC, [ITEMRELATION] ASC, [CUSTVENDCODE] ASC, [CUSTVENDRELATION] ASC);
GO

