CREATE TABLE [AX2009].[INVENTTRANSFERJOUR_OrdiniTrasferimento] (
    [DATAAREAID]               CHAR (4)      NOT NULL,
    [TRANSFERID]               NVARCHAR (20) NOT NULL,
    [VOUCHERID]                NVARCHAR (20) NOT NULL,
    [RECID]                    BIGINT        NOT NULL,
    [TRANSDATE]                DATE          NOT NULL,
    [TOADDRESSCOUNTY]          NVARCHAR (10) NOT NULL,
    [TOADDRESSSTATE]           NVARCHAR (10) NOT NULL,
    [TOADDRESSCOUNTRYREGIONID] NVARCHAR (10) NOT NULL,
    [UPDATETYPE]               SMALLINT      NOT NULL,
    [NPOINVENTPACKINGSLIPID]   NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[INVENTTRANSFERJOUR_OrdiniTrasferimento]
    ADD CONSTRAINT [PK_INVENTTRANSFERJOUR_OrdiniTrasferimento] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSFERID] ASC, [VOUCHERID] ASC);
GO

