CREATE TABLE [AX2009].[LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga] (
    [DATAAREAID]  CHAR (4)         NOT NULL,
    [JOURNALNUM]  NVARCHAR (10)    NOT NULL,
    [LINENUM]     NUMERIC (28, 12) NOT NULL,
    [RECID]       BIGINT           NOT NULL,
    [VENDTRANSID] BIGINT           NOT NULL,
    [PAYMENT]     NVARCHAR (10)    NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga_DATAAREAID_VENDTRANSID_INCLUDE]
    ON [AX2009].[LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga]([DATAAREAID] ASC, [VENDTRANSID] ASC)
    INCLUDE([PAYMENT]);
GO

ALTER TABLE [AX2009].[LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga]
    ADD CONSTRAINT [PK_LEDGERJOURNALTRANS_GiornaliRegistrazioneContabile_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [JOURNALNUM] ASC, [LINENUM] ASC, [RECID] ASC);
GO

