CREATE TABLE [AX2009].[LEDGERTABLE_ContoCoGe] (
    [DATAAREAID]      CHAR (4)      NOT NULL,
    [ACCOUNTNUM]      NVARCHAR (20) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [ACCOUNTNAME]     NVARCHAR (60) NOT NULL,
    [ACCOUNTCATEGORY] NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[LEDGERTABLE_ContoCoGe]
    ADD CONSTRAINT [PK_LEDGERTABLE_ContoCoGe] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ACCOUNTNUM] ASC);
GO

