CREATE TABLE [AX2009].[LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [JOURNALNUM] NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile]
    ADD CONSTRAINT [PK_LEDGERJOURNALTABLE_GiornaliRegistrazioneContabile] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [JOURNALNUM] ASC);
GO

