CREATE TABLE [AX2009].[MARKUPTABLE_CodiceSpeseVarie] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [MODULETYPE]  TINYINT       NOT NULL,
    [MARKUPCODE]  NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [TXT]         NVARCHAR (60) NOT NULL,
    [CUSTPOSTING] TINYINT       NOT NULL,
    [CUSTACCOUNT] NVARCHAR (20) NOT NULL,
    [VENDPOSTING] TINYINT       NOT NULL,
    [VENDACCOUNT] NVARCHAR (20) NOT NULL,
    [CUSTTYPE]    TINYINT       NOT NULL,
    [VENDTYPE]    TINYINT       NOT NULL
);
GO

ALTER TABLE [AX2009].[MARKUPTABLE_CodiceSpeseVarie]
    ADD CONSTRAINT [PK_MARKUPTABLE_CodiceSpeseVarie] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [MODULETYPE] ASC, [MARKUPCODE] ASC) WITH (FILLFACTOR = 100);
GO

CREATE STATISTICS [MARKUPCODE]
    ON [AX2009].[MARKUPTABLE_CodiceSpeseVarie]([MARKUPCODE]);
GO

