CREATE TABLE [AX2009].[METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard] (
    [DATAAREAID]     CHAR (4)      NOT NULL,
    [ITEMID]         NVARCHAR (20) NOT NULL,
    [RECID]          BIGINT        NOT NULL,
    [ANODIZINGCLASS] SMALLINT      NOT NULL
);
GO

ALTER TABLE [AX2009].[METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard]
    ADD CONSTRAINT [PK_METANODIZINGCLASSDEFAULT_ArticoloClasseAnodizzazioneStandard] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC);
GO

