CREATE TABLE [AX2009].[METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra] (
    [DATAAREAID]              CHAR (4)      NOT NULL,
    [REFRECID]                BIGINT        NOT NULL,
    [RECID]                   BIGINT        NOT NULL,
    [PRIMARYVENDORID]         NVARCHAR (40) NOT NULL,
    [STOPEXPLODEBOMCALCGROUP] BIT           NOT NULL,
    [STOPEXPLODEITEM]         BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra]
    ADD CONSTRAINT [PK_METBOMCALCTRANSEXT_CalcoloDBA_Riga_Extra] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [REFRECID] ASC);
GO

