CREATE TABLE [AX2009].[METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [GROUPIDAS]  NVARCHAR (20) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [GROUPID]    NVARCHAR (10) NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite]
    ADD CONSTRAINT [PK_METCOMMISSIONSALESGROUPAS_TrascodificaGruppiVendite] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [GROUPIDAS] ASC);
GO

