CREATE TABLE [AX2009].[METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [SECTORTYPE]          SMALLINT         NOT NULL,
    [MNGTYPE]             SMALLINT         NOT NULL,
    [INVENTITEMTYPE]      NVARCHAR (20)    NOT NULL,
    [FROMDATE]            DATE             NOT NULL,
    [FILTERCODE]          SMALLINT         NOT NULL,
    [CUSTACCOUNT]         NVARCHAR (20)    NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [COSTCALCULATIONTYPE] INT              NOT NULL,
    [PERCENT_]            NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti]
    ADD CONSTRAINT [PK_METINDIRECTCOSTCALCULATIO30448_CriterioCalcoloCostiIndiretti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SECTORTYPE] ASC, [MNGTYPE] ASC, [INVENTITEMTYPE] ASC, [FROMDATE] ASC, [FILTERCODE] ASC, [CUSTACCOUNT] ASC);
GO

