CREATE TABLE [AX2009].[METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione] (
    [DATAAREAID]    CHAR (4)         NOT NULL,
    [ITEMID]        NVARCHAR (20)    NOT NULL,
    [INVENTTRANSID] NVARCHAR (20)    NOT NULL,
    [VARIABLENUM]   INT              NOT NULL,
    [VARIABLENAME]  NVARCHAR (50)    NOT NULL,
    [RECID]         BIGINT           NOT NULL,
    [VALUESTR]      NVARCHAR (60)    NOT NULL,
    [VALUEINT]      INT              NOT NULL,
    [VALUEINT64]    BIGINT           NOT NULL,
    [VALUEREAL]     NUMERIC (28, 12) NOT NULL,
    [BASETYPENAME]  NVARCHAR (50)    NOT NULL
);
GO

CREATE STATISTICS [VARIABLENUM]
    ON [AX2009].[METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione]([VARIABLENUM]);
GO

ALTER TABLE [AX2009].[METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione]
    ADD CONSTRAINT [PK_METPBATABLEINSTANCE_ArticoloDettaglioConfigurazione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [INVENTTRANSID] ASC, [VARIABLENUM] ASC, [VARIABLENAME] ASC);
GO

