CREATE TABLE [AX2009].[METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [PAINTFINISHINGID] NVARCHAR (10) NOT NULL,
    [WMSLOCATIONID]    NVARCHAR (10) NOT NULL,
    [RECID]            BIGINT        NOT NULL
);
GO

ALTER TABLE [AX2009].[METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione]
    ADD CONSTRAINT [PK_METPAINTINGPOWDERWMSLOCATION_FinituraUbicazione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PAINTFINISHINGID] ASC, [WMSLOCATIONID] ASC) WITH (FILLFACTOR = 100);
GO

