CREATE TABLE [AX2009].[METPAINTINGSETUPTABLE_ParametriLineaVerniciatura] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [PAINTINGLINEID]      NVARCHAR (10)    NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [PROCESSTIMECALCTYPE] SMALLINT         NOT NULL,
    [CHAINSPEED]          NUMERIC (28, 12) NOT NULL,
    [HOOKSPERMETER]       NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[METPAINTINGSETUPTABLE_ParametriLineaVerniciatura]
    ADD CONSTRAINT [PK_METPAINTINGSETUPTABLE_ParametriLineaVerniciatura] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PAINTINGLINEID] ASC);
GO

