CREATE TABLE [AX2009].[METPRICECALCITEMSETUP_CalcoloPrezzi_Extra] (
    [DATAAREAID]              CHAR (4)      NOT NULL,
    [REFTABLEID]              INT           NOT NULL,
    [REFRECID]                BIGINT        NOT NULL,
    [RECID]                   BIGINT        NOT NULL,
    [PRIMARYVENDORID]         NVARCHAR (20) NOT NULL,
    [STOPEXPLODEITEM]         BIT           NOT NULL,
    [BOMCALCGROUPID]          NVARCHAR (10) NOT NULL,
    [STOPEXPLODEBOMCALCGROUP] BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[METPRICECALCITEMSETUP_CalcoloPrezzi_Extra]
    ADD CONSTRAINT [PK_METPRICECALCITEMSETUP_CalcoloPrezzi_Extra] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [REFTABLEID] ASC, [REFRECID] ASC);
GO

