CREATE TABLE [AX2009].[METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking] (
    [DATAAREAID]         CHAR (4)         NOT NULL,
    [INVENTITEMTYPE]     NVARCHAR (20)    NOT NULL,
    [FROMDATE]           DATE             NOT NULL,
    [FILTERCODE]         SMALLINT         NOT NULL,
    [CUSTACCOUNT]        NVARCHAR (20)    NOT NULL,
    [RECID]              BIGINT           NOT NULL,
    [PRICEPERUNIT]       NUMERIC (28, 12) NOT NULL,
    [PRICEPERSECONDUNIT] NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking]
    ADD CONSTRAINT [PK_METPICKINGCOSTCALCULATION30449_CriterioCalcoloCostiPicking] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVENTITEMTYPE] ASC, [FROMDATE] ASC, [FILTERCODE] ASC, [CUSTACCOUNT] ASC);
GO

