CREATE TABLE [AX2009].[METSALESCREDITREASONTABLE_CausaleFido] (
    [DATAAREAID]  NVARCHAR (8)   NOT NULL,
    [REASONID]    NVARCHAR (20)  NOT NULL,
    [RECID]       BIGINT         NOT NULL,
    [DESCRIPTION] NVARCHAR (120) NOT NULL
);
GO

ALTER TABLE [AX2009].[METSALESCREDITREASONTABLE_CausaleFido]
    ADD CONSTRAINT [PK_METSALESCREDITREASONTABLE_CausaleFido] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [REASONID] ASC);
GO

