CREATE TABLE [AX2009].[METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio] (
    [DATAAREAID] CHAR (4)         NOT NULL,
    [MNGTYPE]    SMALLINT         NOT NULL,
    [FROMDATE]   DATE             NOT NULL,
    [RECID]      BIGINT           NOT NULL,
    [AMOUNT]     DECIMAL (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio]
    ADD CONSTRAINT [PK_METTHERMALASSEMBLYPRICELIST_CriterioCalcoloCostiAssemblaggio] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [MNGTYPE] ASC, [FROMDATE] ASC);
GO

