CREATE TABLE [AX2009].[METVENDPROJECT_CommessaFornitore] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [VENDACCOUNT]         NVARCHAR (20)    NOT NULL,
    [VENDPROJECTID]       NVARCHAR (20)    NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [ENABLECUSTPROJECT]   BIT              NOT NULL,
    [DOCUMENTDESCRIPTION] NVARCHAR (70)    NOT NULL,
    [REQUESTDATE]         DATE             NOT NULL,
    [CUSTACCOUNT]         NVARCHAR (20)    NOT NULL,
    [DATEEND]             DATE             NOT NULL,
    [DATESTART]           DATE             NOT NULL,
    [SUPPLYTYPE]          SMALLINT         NOT NULL,
    [UNITID]              NVARCHAR (10)    NOT NULL,
    [TOTALQTY]            NUMERIC (28, 12) NOT NULL,
    [CURRENCYCODE]        NVARCHAR (3)     NOT NULL,
    [METALCOVERPRICE]     NUMERIC (28, 12) NOT NULL,
    [PRICEUNIT]           NUMERIC (28, 12) NOT NULL,
    [METCOVERAGETYPE]     SMALLINT         NOT NULL
);
GO

ALTER TABLE [AX2009].[METVENDPROJECT_CommessaFornitore]
    ADD CONSTRAINT [PK_METVENDPROJECT_CommessaFornitore] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [VENDACCOUNT] ASC, [VENDPROJECTID] ASC);
GO

