CREATE TABLE [AX2009].[NPOBOETOTALTABLEMONTH_Insoluti_Mese] (
    [DATAAREAID]      CHAR (4)         NOT NULL,
    [YR]              SMALLINT         NOT NULL,
    [MONTH]           TINYINT          NOT NULL,
    [CUSTACCOUNT]     NVARCHAR (20)    NOT NULL,
    [MACROAREA]       NVARCHAR (10)    NOT NULL,
    [EMPLID]          NVARCHAR (20)    NOT NULL,
    [TRANSTYPE]       SMALLINT         NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    [NUMBERDRAWN]     INT              NOT NULL,
    [NUMBERPROTESTED] INT              NOT NULL,
    [AMOUNTDRAWN]     NUMERIC (28, 12) NOT NULL,
    [AMOUNTPROTESTED] NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOBOETOTALTABLEMONTH_Insoluti_Mese]
    ADD CONSTRAINT [PK_NPOBOETOTALTABLEMONTH_Insoluti_Mese] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [MONTH] ASC, [YR] ASC, [CUSTACCOUNT] ASC, [MACROAREA] ASC, [EMPLID] ASC, [TRANSTYPE] ASC);
GO

