CREATE TABLE [AX2009].[NPOBOXPALLETRELATION_RelazioneCestaPallet] (
    [DATAAREAID]       CHAR (4)         NOT NULL,
    [NPOBOXID]         NVARCHAR (20)    NOT NULL,
    [NPOPACKINGID]     NVARCHAR (18)    NOT NULL,
    [PRODID]           NVARCHAR (20)    NOT NULL,
    [OPRNUM]           INT              NOT NULL,
    [INBOX]            BIT              NOT NULL,
    [RECID]            BIGINT           NOT NULL,
    [OPRID]            NVARCHAR (10)    NOT NULL,
    [QTY]              NUMERIC (28, 12) NOT NULL,
    [NPOSECONDUNITQTY] NUMERIC (28, 12) NOT NULL
);
GO

CREATE STATISTICS [OPRNUM]
    ON [AX2009].[NPOBOXPALLETRELATION_RelazioneCestaPallet]([OPRNUM]);
GO

ALTER TABLE [AX2009].[NPOBOXPALLETRELATION_RelazioneCestaPallet]
    ADD CONSTRAINT [PK_NPOBOXPALLETRELATION_RelazioneCestaPallet] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [NPOBOXID] ASC, [NPOPACKINGID] ASC, [PRODID] ASC, [OPRNUM] ASC, [INBOX] ASC);
GO

