CREATE TABLE [AX2009].[NPOBOETOTALTABLE_Insoluti] (
    [DATAAREAID]      CHAR (4)         NOT NULL,
    [CUSTACCOUNT]     NVARCHAR (20)    NOT NULL,
    [MACROAREA]       NVARCHAR (10)    NOT NULL,
    [EMPLID]          NVARCHAR (20)    NOT NULL,
    [TRANSTYPE]       SMALLINT         NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    [STARTYRMTHDATE]  DATE             NOT NULL,
    [NUMBERPROTESTED] INT              NOT NULL,
    [NUMBERDRAWN]     INT              NOT NULL,
    [AMOUNTDRAWN]     NUMERIC (28, 12) NOT NULL,
    [AMOUNTPROTESTED] NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOBOETOTALTABLE_Insoluti]
    ADD CONSTRAINT [PK_NPOBOETOTALTABLE_Insoluti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CUSTACCOUNT] ASC, [MACROAREA] ASC, [EMPLID] ASC, [TRANSTYPE] ASC) WITH (FILLFACTOR = 100);
GO

CREATE STATISTICS [EMPLID]
    ON [AX2009].[NPOBOETOTALTABLE_Insoluti]([EMPLID]);
GO

CREATE STATISTICS [TRANSTYPE]
    ON [AX2009].[NPOBOETOTALTABLE_Insoluti]([TRANSTYPE]);
GO

