CREATE TABLE [AX2009].[NPOBICOLORWEBSETUP_FinituraBicolore] (
    [DATAAREAID]          CHAR (4)      NOT NULL,
    [BICOLORCODE]         NVARCHAR (5)  NOT NULL,
    [RECID]               BIGINT        NOT NULL,
    [INTERNALFINISHINGID] NVARCHAR (10) NOT NULL,
    [EXTERNALFINISHINGID] NVARCHAR (10) NOT NULL,
    [NAME]                NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOBICOLORWEBSETUP_FinituraBicolore]
    ADD CONSTRAINT [PK_NPOBICOLORWEBSETUP_FinituraBicolore] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BICOLORCODE] ASC) WITH (FILLFACTOR = 100);
GO

