CREATE TABLE [AX2009].[NPOCUSTPROJECT_Commessa] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [CUSTACCOUNT]         NVARCHAR (20)    NOT NULL,
    [PROJECTCODE]         NVARCHAR (40)    NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [DOCUMENTDESCRIPTION] NVARCHAR (70)    NOT NULL,
    [VENDPROJECTID]       NVARCHAR (20)    NOT NULL,
    [TOTALQTY]            NUMERIC (28, 12) NOT NULL,
    [METCOVERAGETYPE]     SMALLINT         NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOCUSTPROJECT_Commessa]
    ADD CONSTRAINT [PK_NPOCUSTPROJECT_Commessa] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CUSTACCOUNT] ASC, [PROJECTCODE] ASC);
GO

