CREATE TABLE [AX2009].[NPOCRSTABLE_RiepilogoCRS] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [CRSNUM]           NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [EXPEDITIONSTATUS] SMALLINT      NOT NULL,
    [CREATEDDATETIME]  DATETIME      NOT NULL,
    [COVERINGBASIS]    SMALLINT      NOT NULL,
    [STATIONID]        NVARCHAR (10) NOT NULL,
    [AREAID]           NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOCRSTABLE_RiepilogoCRS]
    ADD CONSTRAINT [PK_NPOCRSTABLE_RiepilogoCRS] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CRSNUM] ASC);
GO

