CREATE TABLE [AX2009].[NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating] (
    [PARTYID]       NVARCHAR (20) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    [RATINGREFTYPE] SMALLINT      NOT NULL,
    [RATINGREFID]   NVARCHAR (20) NOT NULL,
    [RATINGID]      NVARCHAR (20) NOT NULL,
    [DATEFROM]      DATE          NOT NULL,
    [DATETO]        DATE          NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating]
    ADD CONSTRAINT [PK_NPOCUSTVENDRATINGRELATION_ClienteFornitoreGruppoRating] PRIMARY KEY CLUSTERED ([PARTYID] ASC, [RECID] ASC);
GO

