CREATE TABLE [AX2009].[NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi] (
    [DATAAREAID]         CHAR (4)      NOT NULL,
    [PBAFINISHINGID]     NVARCHAR (10) NOT NULL,
    [RECID]              BIGINT        NOT NULL,
    [ITEMPRICEGROUPID]   NVARCHAR (10) NOT NULL,
    [REVITEMID]          NVARCHAR (20) NOT NULL,
    [ITEMTYPE]           NVARCHAR (20) NOT NULL,
    [NCEREFERENCEITEMID] NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi]
    ADD CONSTRAINT [PK_NPOFINISHINGPRICEGROUP_FinituraGruppoPrezzi] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PBAFINISHINGID] ASC, [RECID] ASC) WITH (FILLFACTOR = 100);
GO

