CREATE TABLE [AX2009].[NPOITEMFAMILIES_FamigliaArticolo] (
    [FAMILYID] NVARCHAR (20) NOT NULL,
    [RECID]    BIGINT        NOT NULL,
    [NAME]     NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOITEMFAMILIES_FamigliaArticolo]
    ADD CONSTRAINT [PK_NPOITEMFAMILIES_FamigliaArticolo] PRIMARY KEY CLUSTERED ([FAMILYID] ASC);
GO

