CREATE TABLE [AX2009].[NPOITEMPRICEGROUP_ArticoloGruppoPrezzi] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [ITEMID]           NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [ITEMPRICEGROUPID] NVARCHAR (10) NOT NULL,
    [REVITEMID]        NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOITEMPRICEGROUP_ArticoloGruppoPrezzi]
    ADD CONSTRAINT [PK_NPOITEMPRICEGROUP_ArticoloGruppoPrezzi] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [RECID] ASC);
GO

