CREATE TABLE [AX2009].[NPOITEMSERIES_Serie] (
    [SERIESID]      NVARCHAR (20) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    [NAME]          NVARCHAR (60) NOT NULL,
    [SYSTEMID]      NVARCHAR (20) NOT NULL,
    [SERIESIDAS400] NVARCHAR (20) NOT NULL,
    [OBSOLETE]      BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOITEMSERIES_Serie]
    ADD CONSTRAINT [PK_NPOITEMSERIES_Serie] PRIMARY KEY CLUSTERED ([SERIESID] ASC);
GO

