CREATE TABLE [AX2009].[NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia] (
    [ITEMID]      NVARCHAR (20) NOT NULL,
    [SUBFAMILYID] NVARCHAR (20) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [FAMILYID]    NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia]
    ADD CONSTRAINT [PK_NPOINTERCOMPANYINVENTTABLE_ArticoloGruppoFamiglia] PRIMARY KEY CLUSTERED ([ITEMID] ASC, [SUBFAMILYID] ASC) WITH (FILLFACTOR = 100);
GO

