CREATE TABLE [AX2009].[NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [DELIVERYDATE]        DATE             NOT NULL,
    [INVENTPACKINGSLIPID] NVARCHAR (20)    NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [TRANSFERID]          NVARCHAR (20)    NOT NULL,
    [DELIVERYNAME]        NVARCHAR (60)    NOT NULL,
    [DELIVERYADDRESS]     NVARCHAR (250)   NOT NULL,
    [DLVMODE]             NVARCHAR (10)    NOT NULL,
    [JOURNEYID]           NVARCHAR (20)    NOT NULL,
    [REFDATAAREAID]       NVARCHAR (4)     NOT NULL,
    [WEIGHT]              NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna]
    ADD CONSTRAINT [PK_NPOINVENTTRANSFERPACKINGS20089_DDTCliente_DatiConsegna] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [DELIVERYDATE] ASC, [INVENTPACKINGSLIPID] ASC, [RECID] ASC);
GO

