CREATE TABLE [AX2009].[NPOITEMSUBFAMILIES_SottofamigliaArticolo] (
    [SUBFAMILYID] NVARCHAR (20) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [NAME]        NVARCHAR (60) NOT NULL,
    [FAMILYID]    NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOITEMSUBFAMILIES_SottofamigliaArticolo]
    ADD CONSTRAINT [PK_NPOITEMSUBFAMILIES_SottofamigliaArticolo] PRIMARY KEY CLUSTERED ([SUBFAMILYID] ASC);
GO

