CREATE TABLE [AX2009].[NPOITEMTYPE_ArticoloGruppoTipoArticolo] (
    [DATAAREAID]     CHAR (4)      NOT NULL,
    [ITEMTYPE]       NVARCHAR (20) NOT NULL,
    [RECID]          BIGINT        NOT NULL,
    [NAME]           NVARCHAR (60) NOT NULL,
    [STRUCTUALGROUP] SMALLINT      NOT NULL,
    [ACCESSORYITEM]  BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOITEMTYPE_ArticoloGruppoTipoArticolo]
    ADD CONSTRAINT [PK_NPOITEMTYPE_ArticoloGruppoTipoArticolo] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMTYPE] ASC);
GO

