CREATE TABLE [AX2009].[NPOITEMSERIESRELATION_ArticoliSerie] (
    [ITEMID]        NVARCHAR (20) NOT NULL,
    [SERIESID]      NVARCHAR (20) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    [PRODUCTTYPEID] NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOITEMSERIESRELATION_ArticoliSerie]
    ADD CONSTRAINT [PK_NPOITEMSERIESRELATION_ArticoliSerie] PRIMARY KEY CLUSTERED ([ITEMID] ASC, [SERIESID] ASC) WITH (FILLFACTOR = 100);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_NPOITEMSERIESRELATION_ArticoliSerie_SERIESID_ITEMID_INCLUDE]
    ON [AX2009].[NPOITEMSERIESRELATION_ArticoliSerie]([SERIESID] ASC, [ITEMID] ASC)
    INCLUDE([PRODUCTTYPEID]) WITH (FILLFACTOR = 100);
GO

