CREATE TABLE [AX2009].[NPOITEMSYSTEM_Sistema] (
    [SYSTEMID]   NVARCHAR (20) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL,
    [SECTORTYPE] SMALLINT      NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOITEMSYSTEM_Sistema]
    ADD CONSTRAINT [PK_NPOITEMSYSTEM_Sistema] PRIMARY KEY CLUSTERED ([SYSTEMID] ASC);
GO

