CREATE TABLE [AX2009].[NPOJOURNEYTABLE_Viaggi] (
    [DATAAREAID]    CHAR (4)         NOT NULL,
    [JOURNEYID]     NVARCHAR (20)    NOT NULL,
    [RECID]         BIGINT           NOT NULL,
    [DELIVERYDATE]  DATETIME         NOT NULL,
    [DLVMODE]       NVARCHAR (10)    NOT NULL,
    [DELIVERYNUM]   INT              NOT NULL,
    [FUELSURCHARGE] NUMERIC (28, 12) NOT NULL,
    [JOURNEYKM]     INT              NOT NULL,
    [JOURNEYCOST]   NUMERIC (28, 12) NOT NULL,
    [REFCHANNEL]    SMALLINT         NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOJOURNEYTABLE_Viaggi]
    ADD CONSTRAINT [PK_NPOJOURNEYTABLE_Viaggi] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [JOURNEYID] ASC);
GO

