CREATE TABLE [AX2009].[NPOPACKINGSLIPEXTERNAL_DDTTerzeParti] (
    [DATAAREAID]              CHAR (4)         NOT NULL,
    [DELIVERYDATE]            DATE             NOT NULL,
    [PACKINGCODE]             NVARCHAR (10)    NOT NULL,
    [RECID]                   BIGINT           NOT NULL,
    [REFDATAAREAID]           NVARCHAR (4)     NOT NULL,
    [DELIVERYNAME]            NVARCHAR (60)    NOT NULL,
    [DELIVERYADDRESS]         NVARCHAR (250)   NOT NULL,
    [JOURNEYID]               NVARCHAR (20)    NOT NULL,
    [DLVMODEID]               NVARCHAR (10)    NOT NULL,
    [DELIVERYCOUNTY]          NVARCHAR (10)    NOT NULL,
    [DELIVERYCOUNTRYREGIONID] NVARCHAR (10)    NOT NULL,
    [DELIVERYSTATEID]         NVARCHAR (10)    NOT NULL,
    [WEIGHT]                  NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPACKINGSLIPEXTERNAL_DDTTerzeParti]
    ADD CONSTRAINT [PK_NPOPACKINGSLIPEXTERNAL_DDTTerzeParti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [DELIVERYDATE] ASC, [PACKINGCODE] ASC, [RECID] ASC) WITH (FILLFACTOR = 100);
GO

