CREATE TABLE [AX2009].[NPOPACKINGITEMS_Pacchi_Riga] (
    [DATAAREAID]         CHAR (4)         NOT NULL,
    [PACKINGID]          NVARCHAR (18)    NOT NULL,
    [SALESLINENUM]       INT              NOT NULL,
    [RECID]              BIGINT           NOT NULL,
    [SALESID]            NVARCHAR (20)    NOT NULL,
    [BARLENGTH]          NUMERIC (28, 12) NOT NULL,
    [ITEMID]             NVARCHAR (20)    NOT NULL,
    [WMSORDERTRANSRECID] BIGINT           NOT NULL,
    [INVENTREFID]        NVARCHAR (20)    NOT NULL,
    [INVENTREFTYPE]      SMALLINT         NOT NULL,
    [SALESLINERECID]     BIGINT           NOT NULL,
    [PURCHLINERECID]     BIGINT           NOT NULL,
    [INVENTTRANSID]      NVARCHAR (20)    NOT NULL,
    [BOMITEMID]          NVARCHAR (20)    NOT NULL,
    [PAINTINGTHICKNESS]  NUMERIC (28, 12) NOT NULL,
    [SALESUNIT]          NVARCHAR (10)    NOT NULL,
    [QTYGOOD]            NUMERIC (28, 12) NOT NULL,
    [QTYERROR]           NUMERIC (28, 12) NOT NULL,
    [BALANCEDKG]         NUMERIC (28, 12) NOT NULL,
    [INVENTTRANSKG]      NUMERIC (28, 12) NOT NULL,
    [PAINTINGHOOKS]      INT              NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPACKINGITEMS_Pacchi_Riga]
    ADD CONSTRAINT [PK_NPOPACKINGITEMS_Pacchi_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PACKINGID] ASC, [SALESLINENUM] ASC, [RECID] ASC);
GO

