CREATE TABLE [AX2009].[NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA] (
    [DATAAREAID]        CHAR (4)      NOT NULL,
    [NPOPBAFINISHINGID] NVARCHAR (10) NOT NULL,
    [ITEMIDDEFAULT]     NVARCHAR (20) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [DEFAULT_]          BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA]
    ADD CONSTRAINT [PK_NPOPBAFINISHINGDETAILSBOM_FinituraArticoloDBA] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [NPOPBAFINISHINGID] ASC, [ITEMIDDEFAULT] ASC) WITH (FILLFACTOR = 100);
GO

