CREATE TABLE [AX2009].[NPOPRODUCTIONLOT_Lotti] (
    [DATAAREAID]     CHAR (4)         NOT NULL,
    [LOTID]          NVARCHAR (15)    NOT NULL,
    [RECID]          BIGINT           NOT NULL,
    [MASTERWRKCTRID] NVARCHAR (10)    NOT NULL,
    [LINEARKG]       NUMERIC (28, 12) NOT NULL,
    [LOTDATE]        DATE             NOT NULL,
    [LOTDATETIME]    DATETIME         NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPRODUCTIONLOT_Lotti]
    ADD CONSTRAINT [PK_NPOPRODUCTIONLOT_Lotti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [LOTID] ASC);
GO

