CREATE TABLE [AX2009].[NPOPBAFINISHINGLEADTIME_LeadTimeFinitura] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [FINISHINGID]      NVARCHAR (10) NOT NULL,
    [SECTORTYPE]       SMALLINT      NOT NULL,
    [VENDACCOUNT]      NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [LEADTIME]         INT           NOT NULL,
    [STOCKMANAGEDITEM] BIT           NOT NULL
);
GO

CREATE STATISTICS [FINISHINGID]
    ON [AX2009].[NPOPBAFINISHINGLEADTIME_LeadTimeFinitura]([FINISHINGID]);
GO

CREATE STATISTICS [VENDACCOUNT]
    ON [AX2009].[NPOPBAFINISHINGLEADTIME_LeadTimeFinitura]([VENDACCOUNT]);
GO

ALTER TABLE [AX2009].[NPOPBAFINISHINGLEADTIME_LeadTimeFinitura]
    ADD CONSTRAINT [PK_NPOPBAFINISHINGLEADTIME_LeadTimeFinitura] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [FINISHINGID] ASC, [SECTORTYPE] ASC, [VENDACCOUNT] ASC);
GO

