CREATE TABLE [AX2009].[NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione] (
    [DATAAREAID]      CHAR (4)         NOT NULL,
    [LOTID]           NVARCHAR (15)    NOT NULL,
    [PRODID]          NVARCHAR (20)    NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    [SALESID]         NVARCHAR (20)    NOT NULL,
    [LOTLENGTH]       NUMERIC (28, 12) NOT NULL,
    [SALESNPOLINENUM] INT              NOT NULL,
    [ASSIGNEDQTY]     NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione]
    ADD CONSTRAINT [PK_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [LOTID] ASC, [PRODID] ASC);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_AX2009_NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione_DATAAREAID_PRODID_LOTID]
    ON [AX2009].[NPOPRODUCTIONLOTLENGTHPROD_LottiOrdiniProduzione]([DATAAREAID] ASC, [PRODID] ASC, [LOTID] ASC);
GO

