CREATE TABLE [AX2009].[NPOPACKINGSLIPPALLETINFO_DDTPallet] (
    [DATAAREAID]    CHAR (4)         NOT NULL,
    [DELIVERYDATE]  DATE             NOT NULL,
    [PACKINGSLIPID] NVARCHAR (20)    NOT NULL,
    [INVENTTRANSID] NVARCHAR (20)    NOT NULL,
    [WMSPALLETID]   NVARCHAR (18)    NOT NULL,
    [RECID]         BIGINT           NOT NULL,
    [TRANSREFID]    NVARCHAR (20)    NOT NULL,
    [REFTABLEID]    INT              NOT NULL,
    [INVOICERECID]  BIGINT           NOT NULL,
    [WEIGHT]        NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPACKINGSLIPPALLETINFO_DDTPallet]
    ADD CONSTRAINT [PK_NPOPACKINGSLIPPALLETINFO_DDTPallet] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [DELIVERYDATE] ASC, [PACKINGSLIPID] ASC, [INVENTTRANSID] ASC, [WMSPALLETID] ASC, [RECID] ASC);
GO

