CREATE TABLE [AX2009].[NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [ITEMID]      NVARCHAR (20) NOT NULL,
    [FINISHINGID] NVARCHAR (10) NOT NULL,
    [OPRNUM]      INT           NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [OPRID]       NVARCHAR (10) NOT NULL,
    [WRKCTRID]    NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo]
    ADD CONSTRAINT [PK_NPOPBAROUTEFINISHING_ArticoloFinituraValoriCiclo] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [FINISHINGID] ASC, [OPRNUM] ASC) WITH (FILLFACTOR = 100);
GO

