CREATE TABLE [AX2009].[NPOPBAFINISHINGRELATION_FinituraAttributo] (
    [FINISHINGID]       NVARCHAR (10) NOT NULL,
    [IDDETAIL]          NVARCHAR (10) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [DETAILDESCRIPTION] NVARCHAR (60) NOT NULL,
    [DETAILLEVEL]       INT           NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOPBAFINISHINGRELATION_FinituraAttributo]
    ADD CONSTRAINT [PK_NPOPBAFINISHINGRELATION_FinituraAttributo] PRIMARY KEY CLUSTERED ([FINISHINGID] ASC, [IDDETAIL] ASC, [RECID] ASC);
GO

