CREATE TABLE [AX2009].[NPOREVENUEGROUP_GruppoRicavi] (
    [REVENUEGROUPID] NVARCHAR (10) NOT NULL,
    [RECID]          BIGINT        NOT NULL,
    [NAME]           NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOREVENUEGROUP_GruppoRicavi]
    ADD CONSTRAINT [PK_NPOREVENUEGROUP_GruppoRicavi] PRIMARY KEY CLUSTERED ([REVENUEGROUPID] ASC);
GO

