CREATE TABLE [AX2009].[NPOSCRAPCAUSEGROUP_GruppoCausaleScarto] (
    [SCRAPCAUSEGROUPID] NVARCHAR (3)  NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [NAME]              NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOSCRAPCAUSEGROUP_GruppoCausaleScarto]
    ADD CONSTRAINT [PK_NPOSCRAPCAUSEGROUP_GruppoCausaleScarto] PRIMARY KEY CLUSTERED ([SCRAPCAUSEGROUPID] ASC);
GO

