CREATE TABLE [AX2009].[NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [INVENTTRANSID]       NVARCHAR (20)    NOT NULL,
    [DELIVERYDATE]        DATE             NOT NULL,
    [PACKINGSLIPID]       NVARCHAR (20)    NOT NULL,
    [WMSPALLETID]         NVARCHAR (18)    NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [COMPANYSALESID]      NVARCHAR (20)    NOT NULL,
    [INTERCOMPANYSALESID] NVARCHAR (20)    NOT NULL,
    [ITEMID]              NVARCHAR (20)    NOT NULL,
    [QTY]                 NUMERIC (28, 12) NOT NULL,
    [QTY2UM]              NUMERIC (28, 12) NOT NULL,
    [PACKEDQTY]           NUMERIC (28, 12) NOT NULL,
    [PACKEDQTY2UM]        NUMERIC (28, 12) NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet_DATAAREAID_WMSPALLETID_DELIVERYDATE]
    ON [AX2009].[NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet]([DATAAREAID] ASC, [WMSPALLETID] ASC, [DELIVERYDATE] ASC);
GO

ALTER TABLE [AX2009].[NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet]
    ADD CONSTRAINT [PK_NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [INVENTTRANSID] ASC, [DELIVERYDATE] ASC, [PACKINGSLIPID] ASC, [WMSPALLETID] ASC, [RECID] ASC);
GO

CREATE STATISTICS [PACKINGSLIPID]
    ON [AX2009].[NPOSALESLINEWMSPALLETLINK_OrdiniCliente_Riga_DatiPallet]([PACKINGSLIPID]);
GO

