CREATE TABLE [AX2009].[NPOSCRAPCAUSE_CausaleScarto] (
    [DATAAREAID]        CHAR (4)      NOT NULL,
    [SCRAPCAUSEID]      NVARCHAR (10) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [DESCRIPTION]       NVARCHAR (60) NOT NULL,
    [SCRAPCAUSEGROUPID] NVARCHAR (3)  NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOSCRAPCAUSE_CausaleScarto]
    ADD CONSTRAINT [PK_NPOSCRAPCAUSE_CausaleScarto] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SCRAPCAUSEID] ASC);
GO

