CREATE TABLE [AX2009].[NPOSALESCREDITGROUP_ClienteFidoDiGruppo] (
    [CUSTOMERCODE]     SMALLINT         NOT NULL,
    [CUSTOMERRELATION] NVARCHAR (20)    NOT NULL,
    [DATEFROM]         DATE             NOT NULL,
    [DATETO]           DATE             NOT NULL,
    [RECID]            BIGINT           NOT NULL,
    [REASONID]         NVARCHAR (10)    NOT NULL,
    [AMOUNT]           NUMERIC (28, 12) NOT NULL,
    [INSURANCEAMOUNT]  NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOSALESCREDITGROUP_ClienteFidoDiGruppo]
    ADD CONSTRAINT [PK_NPOSALESCREDITGROUP_ClienteFidoDiGruppo] PRIMARY KEY CLUSTERED ([CUSTOMERCODE] ASC, [CUSTOMERRELATION] ASC, [DATEFROM] ASC, [DATETO] ASC, [RECID] ASC);
GO

