CREATE TABLE [AX2009].[NPOSCRAP_DichiarazioniScarto] (
    [DATAAREAID]       CHAR (4)         NOT NULL,
    [LOTID]            NVARCHAR (15)    NOT NULL,
    [PACKINGID]        NVARCHAR (18)    NOT NULL,
    [RECID]            BIGINT           NOT NULL,
    [WMSLOCATIONID]    NVARCHAR (10)    NOT NULL,
    [INVENTLOCATIONID] NVARCHAR (10)    NOT NULL,
    [SCRAPCAUSEID]     NVARCHAR (10)    NOT NULL,
    [ITEMID]           NVARCHAR (20)    NOT NULL,
    [BASKETNO]         NVARCHAR (18)    NOT NULL,
    [WORKSTATIONID]    NVARCHAR (20)    NOT NULL,
    [SCRAPTYPE]        SMALLINT         NOT NULL,
    [INVENTREFID]      NVARCHAR (20)    NOT NULL,
    [INVENTREFTYPE]    SMALLINT         NOT NULL,
    [CREATEDDATETIME]  DATETIME         NOT NULL,
    [ITEMLENGTH]       NUMERIC (28, 12) NOT NULL,
    [QTY]              NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOSCRAP_DichiarazioniScarto]
    ADD CONSTRAINT [PK_NPOSCRAP_DichiarazioniScarto] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [LOTID] ASC, [PACKINGID] ASC, [RECID] ASC);
GO

