CREATE TABLE [AX2009].[NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido] (
    [DATAAREAID]      CHAR (4)      NOT NULL,
    [SALESID]         NVARCHAR (10) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [CONFIRMBLOCKED]  BIT           NOT NULL,
    [UNLOCKCAUSAL]    NVARCHAR (10) NOT NULL,
    [PACKINGBLOCKED]  BIT           NOT NULL,
    [PICKINGBLOCKED]  BIT           NOT NULL,
    [INVOICEBLOCKED]  BIT           NOT NULL,
    [CREATEDDATETIME] DATETIME      NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido]
    ADD CONSTRAINT [PK_NPOSALESTABLECREDITCONTROLINFO_OrdiniCliente_DatiFido] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SALESID] ASC, [RECID] ASC);
GO

