CREATE TABLE [AX2009].[NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro] (
    [DATAAREAID]  CHAR (4)         NOT NULL,
    [WRKCTRID]    NVARCHAR (10)    NOT NULL,
    [YR]          INT              NOT NULL,
    [WEEK]        INT              NOT NULL,
    [ITEMID]      NVARCHAR (20)    NOT NULL,
    [CUSTACCOUNT] NVARCHAR (20)    NOT NULL,
    [RECID]       BIGINT           NOT NULL,
    [PRODID]      NVARCHAR (20)    NOT NULL,
    [KG]          NUMERIC (28, 12) NOT NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_AX2009_NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro_DATAAREAID_PRODID_FILTERED]
    ON [AX2009].[NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro]([DATAAREAID] ASC, [PRODID] ASC) WHERE ([PRODID]<>N'');
GO

ALTER TABLE [AX2009].[NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro]
    ADD CONSTRAINT [PK_NPOWRKCTRCAPTABLE_CapacitaCentroDiLavoro] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [WRKCTRID] ASC, [YR] ASC, [WEEK] ASC, [ITEMID] ASC, [CUSTACCOUNT] ASC);
GO

