CREATE TABLE [AX2009].[NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione] (
    [DATAAREAID]      CHAR (4)         NOT NULL,
    [MASTERWRKCTRID]  NVARCHAR (10)    NOT NULL,
    [WRKCTRID]        NVARCHAR (10)    NOT NULL,
    [BARLENGTH]       NUMERIC (28, 12) NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    [ESTRBACKLENGTH]  NUMERIC (28, 12) NOT NULL,
    [ISGROUP]         BIT              NOT NULL,
    [FIRSTBILLLENGTH] NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione]
    ADD CONSTRAINT [PK_NPOWRKCTRPRESET_CentroDiLavoroDatiEstrusione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [MASTERWRKCTRID] ASC, [WRKCTRID] ASC, [BARLENGTH] ASC);
GO

