CREATE TABLE [AX2009].[NPOWORKSTATIONAREA_AreaDiLavoro] (
    [DATAAREAID]   CHAR (4)      NOT NULL,
    [AREAID]       NVARCHAR (25) NOT NULL,
    [RECID]        BIGINT        NOT NULL,
    [DEPARTMENTID] NVARCHAR (30) NOT NULL
);
GO

ALTER TABLE [AX2009].[NPOWORKSTATIONAREA_AreaDiLavoro]
    ADD CONSTRAINT [PK_NPOWORKSTATIONAREA_AreaDiLavoro] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [AREAID] ASC);
GO

