CREATE TABLE [AX2009].[NPOWORKSTATION_PostazioneDiLavoro] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [WORKSTATIONID]    NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [WMSLOCATIONID]    NVARCHAR (10) NOT NULL,
    [EMPLID]           NVARCHAR (20) NOT NULL,
    [INVENTLOCATIONID] NVARCHAR (10) NOT NULL,
    [WRKCTRID]         NVARCHAR (10) NOT NULL,
    [GROUPWRKCTRID]    NVARCHAR (10) NOT NULL,
    [AREAID]           NVARCHAR (25) NOT NULL,
    [INVENTSITEID]     NVARCHAR (10) NOT NULL,
    [WORKSTATIONNAME]  NVARCHAR (60) NOT NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_AX2009_NPOWORKSTATION_PostazioneDiLavoro_DATAREAID_WORKSTATIONID]
    ON [AX2009].[NPOWORKSTATION_PostazioneDiLavoro]([DATAAREAID] ASC, [WORKSTATIONID] ASC);
GO

ALTER TABLE [AX2009].[NPOWORKSTATION_PostazioneDiLavoro]
    ADD CONSTRAINT [PK_NPOWORKSTATION_PostazioneDiLavoro] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [WORKSTATIONID] ASC, [RECID] ASC);
GO

