CREATE TABLE [AX2009].[PAYMTERM_TerminiPagamento] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [PAYMTERMID]  NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [DESCRIPTION] NVARCHAR (60) NOT NULL,
    [NUMOFMONTHS] TINYINT       NOT NULL
);
GO

ALTER TABLE [AX2009].[PAYMTERM_TerminiPagamento]
    ADD CONSTRAINT [PK_PAYMTERM_TerminiPagamento] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PAYMTERMID] ASC) WITH (FILLFACTOR = 100);
GO

