CREATE TABLE [AX2009].[PBAREUSEBOMROUTE_StringaDiRicerca] (
    [DATAAREAID]    CHAR (4)       NOT NULL,
    [BOMID]         NVARCHAR (20)  NOT NULL,
    [ROUTEID]       NVARCHAR (20)  NOT NULL,
    [RECID]         BIGINT         NOT NULL,
    [INVENTTRANSID] NVARCHAR (20)  NOT NULL,
    [ITEMID]        NVARCHAR (20)  NOT NULL,
    [SEARCHSTRING]  NVARCHAR (870) NOT NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_AX2009_PBAREUSEBOMROUTE_StringaDiRicerca_DATAAREAID_ITEMID]
    ON [AX2009].[PBAREUSEBOMROUTE_StringaDiRicerca]([DATAAREAID] ASC, [ITEMID] ASC);
GO

CREATE STATISTICS [BOMID]
    ON [AX2009].[PBAREUSEBOMROUTE_StringaDiRicerca]([BOMID]);
GO

CREATE STATISTICS [ROUTEID]
    ON [AX2009].[PBAREUSEBOMROUTE_StringaDiRicerca]([ROUTEID]);
GO

ALTER TABLE [AX2009].[PBAREUSEBOMROUTE_StringaDiRicerca]
    ADD CONSTRAINT [PK_PBAREUSEBOMROUTE_StringaDiRicerca] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BOMID] ASC, [ROUTEID] ASC);
GO

