CREATE TABLE [AX2009].[PRICEDISCTABLE_AccordiPrezzi] (
    [DATAAREAID]      CHAR (4)         NOT NULL,
    [RELATION]        INT              NOT NULL,
    [ITEMCODE]        SMALLINT         NOT NULL,
    [ACCOUNTCODE]     SMALLINT         NOT NULL,
    [ITEMRELATION]    NVARCHAR (20)    NOT NULL,
    [ACCOUNTRELATION] NVARCHAR (20)    NOT NULL,
    [QUANTITYAMOUNT]  NUMERIC (28, 12) NOT NULL,
    [FROMDATE]        DATE             NOT NULL,
    [TODATE]          DATE             NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    [UNITID]          NVARCHAR (10)    NOT NULL,
    [INVENTDIMID]     NVARCHAR (20)    NOT NULL,
    [PERCENT1]        NUMERIC (28, 12) NOT NULL,
    [PERCENT2]        NUMERIC (28, 12) NOT NULL,
    [CURRENCY]        NVARCHAR (3)     NOT NULL,
    [AMOUNT]          NUMERIC (28, 12) NOT NULL,
    [PRICEUNIT]       NUMERIC (28, 12) NOT NULL,
    [MARKUP]          NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[PRICEDISCTABLE_AccordiPrezzi]
    ADD CONSTRAINT [PK_PRICEDISCTABLE_AccordiPrezzi] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [RELATION] ASC, [ITEMCODE] ASC, [ACCOUNTCODE] ASC, [ITEMRELATION] ASC, [ACCOUNTRELATION] ASC, [QUANTITYAMOUNT] ASC, [FROMDATE] ASC, [TODATE] ASC, [RECID] ASC) WITH (FILLFACTOR = 100);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_PRICEDISCTABLE_AccordiPrezzi_RELATION_AMOUNT_INCLUDE]
    ON [AX2009].[PRICEDISCTABLE_AccordiPrezzi]([RELATION] ASC, [AMOUNT] ASC)
    INCLUDE([DATAAREAID], [ITEMCODE], [FROMDATE], [TODATE], [PRICEUNIT]) WITH (FILLFACTOR = 100);
GO

CREATE STATISTICS [RECID]
    ON [AX2009].[PRICEDISCTABLE_AccordiPrezzi]([RECID]);
GO

CREATE STATISTICS [QUANTITYAMOUNT]
    ON [AX2009].[PRICEDISCTABLE_AccordiPrezzi]([QUANTITYAMOUNT]);
GO

