CREATE TABLE [AX2009].[PRICEDISCGROUP_GruppoPrezzi] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [MODULE]     INT           NOT NULL,
    [GROUPID]    NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[PRICEDISCGROUP_GruppoPrezzi]
    ADD CONSTRAINT [PK_PRICEDISCGROUP_GruppoPrezzi] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [MODULE] ASC, [GROUPID] ASC) WITH (FILLFACTOR = 100);
GO

