CREATE TABLE [AX2009].[PRODBOM_OrdiniProduzione_DBA] (
    [DATAAREAID]           CHAR (4)         NOT NULL,
    [PRODID]               NVARCHAR (20)    NOT NULL,
    [LINENUM]              NUMERIC (28, 12) NOT NULL,
    [RECID]                BIGINT           NOT NULL,
    [PRODLINETYPE]         SMALLINT         NOT NULL,
    [ITEMID]               NVARCHAR (20)    NOT NULL,
    [OPRNUM]               INT              NOT NULL,
    [INVENTTRANSID]        NVARCHAR (20)    NOT NULL,
    [INVENTREFTYPE]        SMALLINT         NOT NULL,
    [INVENTREFID]          NVARCHAR (20)    NOT NULL,
    [INVENTREFTRANSID]     NVARCHAR (20)    NOT NULL,
    [INVENTDIMID]          NVARCHAR (20)    NOT NULL,
    [BOMQTY]               NUMERIC (28, 12) NOT NULL,
    [REMAINBOMPHYSICAL]    NUMERIC (28, 12) NOT NULL,
    [QTYBOMSTUP]           NUMERIC (28, 12) NOT NULL,
    [REMAININVENTPHYSICAL] NUMERIC (28, 12) NOT NULL,
    [QTYBOMCALC]           NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[PRODBOM_OrdiniProduzione_DBA]
    ADD CONSTRAINT [PK_PRODBOM_OrdiniProduzione_DBA] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PRODID] ASC, [LINENUM] ASC, [RECID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_PRODBOM_OrdiniProduzione_DBA_PRODLINETYPE_REMAINBOMPHYSICAL_INCLUDE]
    ON [AX2009].[PRODBOM_OrdiniProduzione_DBA]([PRODLINETYPE] ASC, [REMAINBOMPHYSICAL] ASC)
    INCLUDE([ITEMID], [INVENTTRANSID]);
GO

CREATE STATISTICS [RECID]
    ON [AX2009].[PRODBOM_OrdiniProduzione_DBA]([RECID]);
GO

CREATE STATISTICS [LINENUM]
    ON [AX2009].[PRODBOM_OrdiniProduzione_DBA]([LINENUM]);
GO

