CREATE TABLE [AX2009].[PURCHPOOL_PoolAcquisti] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [PURCHPOOLID] NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [NAME]        NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[PURCHPOOL_PoolAcquisti]
    ADD CONSTRAINT [PK_PURCHPOOL_PoolAcquisti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PURCHPOOLID] ASC);
GO

