CREATE TABLE [AX2009].[REQITEMTABLE_CoperturaArticoli] (
    [DATAAREAID]              CHAR (4)         NOT NULL,
    [ITEMID]                  NVARCHAR (20)    NOT NULL,
    [RECID]                   BIGINT           NOT NULL,
    [MININVENTONHAND]         NUMERIC (28, 12) NOT NULL,
    [LEADTIMEPURCHASE]        INT              NOT NULL,
    [REQGROUPID]              NVARCHAR (10)    NOT NULL,
    [INVENTLOCATIONIDREQMAIN] NVARCHAR (10)    NOT NULL,
    [LEADTIMEPURCHASEACTIVE]  BIT              NOT NULL
);
GO

ALTER TABLE [AX2009].[REQITEMTABLE_CoperturaArticoli]
    ADD CONSTRAINT [PK_REQITEMTABLE_CoperturaArticoli] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [RECID] ASC);
GO

