CREATE TABLE [AX2009].[RETURNREASONCODEGROUP_GruppoMotivoReso] (
    [DATAAREAID]        CHAR (4)      NOT NULL,
    [REASONCODEGROUPID] NVARCHAR (10) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [DESCRIPTION]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[RETURNREASONCODEGROUP_GruppoMotivoReso]
    ADD CONSTRAINT [PK_RETURNREASONCODEGROUP_GruppoMotivoReso] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [REASONCODEGROUPID] ASC);
GO

