CREATE TABLE [AX2009].[RETURNDISPOSITIONCODE_CodiceSmaltimento] (
    [DATAAREAID]        CHAR (4)      NOT NULL,
    [DISPOSITIONCODEID] NVARCHAR (10) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [DESCRIPTION]       NVARCHAR (60) NOT NULL,
    [DISPOSITIONACTION] SMALLINT      NOT NULL
);
GO

ALTER TABLE [AX2009].[RETURNDISPOSITIONCODE_CodiceSmaltimento]
    ADD CONSTRAINT [PK_RETURNDISPOSITIONCODE_CodiceSmaltimento] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [DISPOSITIONCODEID] ASC);
GO

