CREATE TABLE [AX2009].[RETURNREASONCODE_MotivoReso] (
    [DATAAREAID]        CHAR (4)      NOT NULL,
    [REASONCODEID]      NVARCHAR (10) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [REASONCODEGROUPID] NVARCHAR (10) NOT NULL,
    [DESCRIPTION]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[RETURNREASONCODE_MotivoReso]
    ADD CONSTRAINT [PK_RETURNREASONCODE_MotivoReso] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [REASONCODEID] ASC);
GO

