CREATE TABLE [AX2009].[ROUTEVERSION_Ciclo] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [ROUTEID]    NVARCHAR (20) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [FROMDATE]   DATE          NOT NULL,
    [ITEMID]     NVARCHAR (20) NOT NULL,
    [TODATE]     DATE          NOT NULL
);
GO

ALTER TABLE [AX2009].[ROUTEVERSION_Ciclo]
    ADD CONSTRAINT [PK_ROUTEVERSION_Ciclo] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ROUTEID] ASC, [RECID] ASC);
GO

