CREATE TABLE [AX2009].[ROUTEOPR_RelazioneOperativa] (
    [DATAAREAID]    CHAR (4)      NOT NULL,
    [ITEMCODE]      INT           NOT NULL,
    [ITEMRELATION]  NVARCHAR (20) NOT NULL,
    [ROUTECODE]     INT           NOT NULL,
    [ROUTERELATION] NVARCHAR (20) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    [OPRID]         NVARCHAR (10) NOT NULL,
    [WRKCTRID]      NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[ROUTEOPR_RelazioneOperativa]
    ADD CONSTRAINT [PK_ROUTEOPR_RelazioneOperativa] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMCODE] ASC, [ITEMRELATION] ASC, [ROUTECODE] ASC, [ROUTERELATION] ASC, [RECID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_ROUTEOPR_RelazioneOperativa_DATAAREAID_ITEMRELATION_ROUTECODE_ROUTERELATION]
    ON [AX2009].[ROUTEOPR_RelazioneOperativa]([DATAAREAID] ASC, [ITEMRELATION] ASC, [ROUTECODE] ASC, [ROUTERELATION] ASC)
    INCLUDE([OPRID], [WRKCTRID]);
GO

