CREATE TABLE [AX2009].[ROUTE_Ciclo_Riga] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [ROUTEID]    NVARCHAR (20) NOT NULL,
    [OPRNUM]     INT           NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [OPRID]      NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[ROUTE_Ciclo_Riga]
    ADD CONSTRAINT [PK_ROUTE_Ciclo_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ROUTEID] ASC, [OPRNUM] ASC, [RECID] ASC);
GO

