CREATE TABLE [AX2009].[ROUTEOPRTABLE_Operazione] (
    [DATAAREAID]      CHAR (4)      NOT NULL,
    [OPRID]           NVARCHAR (10) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [NAME]            NVARCHAR (60) NOT NULL,
    [NPOREVENUEGROUP] NVARCHAR (10) NOT NULL
);
GO

ALTER TABLE [AX2009].[ROUTEOPRTABLE_Operazione]
    ADD CONSTRAINT [PK_ROUTEOPRTABLE_Operazione] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [OPRID] ASC);
GO

