CREATE TABLE [AX2009].[SALESPOOL_PoolVendite] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [SALESPOOLID] NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [NAME]        NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[SALESPOOL_PoolVendite]
    ADD CONSTRAINT [PK_SALESPOOL_PoolVendite] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SALESPOOLID] ASC);
GO

