CREATE TABLE [AX2009].[SHIPCARRIERCOMPANY_SocietaSpedizioni] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [CARRIERNAME] NVARCHAR (20) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [VENDACCOUNT] NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[SHIPCARRIERCOMPANY_SocietaSpedizioni]
    ADD CONSTRAINT [PK_SHIPCARRIERCOMPANY_SocietaSpedizioni] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CARRIERNAME] ASC);
GO

