CREATE TABLE [AX2009].[SHIPCARRIERTABLE_Vettore] (
    [DATAAREAID]  CHAR (4)      NOT NULL,
    [CARRIERID]   NVARCHAR (10) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    [CARRIERNAME] NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[SHIPCARRIERTABLE_Vettore]
    ADD CONSTRAINT [PK_SHIPCARRIERTABLE_Vettore] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [CARRIERID] ASC);
GO

