CREATE TABLE [AX2009].[SMMBUSSECTORGROUP_SettoreCommerciale] (
    [DATAAREAID]       CHAR (4)       NOT NULL,
    [BUSINESSSECTORID] NVARCHAR (20)  NOT NULL,
    [RECID]            BIGINT         NOT NULL,
    [DESCRIPTION]      NVARCHAR (255) NOT NULL
);
GO

ALTER TABLE [AX2009].[SMMBUSSECTORGROUP_SettoreCommerciale]
    ADD CONSTRAINT [PK_SMMBUSSECTORGROUP_SettoreCommerciale] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BUSINESSSECTORID] ASC);
GO

