CREATE TABLE [AX2009].[SMMBUSRELSEGMENTGROUP_Segmento] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [SEGMENTID]        NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [DESCRIPTION]      NVARCHAR (60) NOT NULL,
    [BUSINESSSECTORID] NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[SMMBUSRELSEGMENTGROUP_Segmento]
    ADD CONSTRAINT [PK_SMMBUSRELSEGMENTGROUP_Segmento] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SEGMENTID] ASC);
GO

