CREATE TABLE [AX2009].[SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [PARTYID]          NVARCHAR (20) NOT NULL,
    [BUSINESSSECTORID] NVARCHAR (20) NOT NULL,
    [RECID]            BIGINT        NOT NULL
);
GO

ALTER TABLE [AX2009].[SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale]
    ADD CONSTRAINT [PK_SMMBUSRELSECTORTABLE_RubricaSettoreCommerciale] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PARTYID] ASC, [BUSINESSSECTORID] ASC);
GO

