CREATE TABLE [AX2009].[SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita] (
    [DATAAREAID]      CHAR (4)      NOT NULL,
    [SALESDISTRICTID] NVARCHAR (20) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [DESCRIPTION]     NVARCHAR (60) NOT NULL
);
GO

CREATE STATISTICS [SALESDISTRICTID]
    ON [AX2009].[SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita]([SALESDISTRICTID]);
GO

ALTER TABLE [AX2009].[SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita]
    ADD CONSTRAINT [PK_SMMBUSRELSALESDISTRICTGROUP_ZonaDiVendita] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SALESDISTRICTID] ASC);
GO

