CREATE TABLE [AX2009].[SMMBUSRELSUBSEGMENTGROUP_Sottosegmento] (
    [DATAAREAID]            CHAR (4)      NOT NULL,
    [SEGMENTID]             NVARCHAR (20) NOT NULL,
    [SUBSEGMENTID]          NVARCHAR (20) NOT NULL,
    [RECID]                 BIGINT        NOT NULL,
    [SUBSEGMENTDESCRIPTION] NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[SMMBUSRELSUBSEGMENTGROUP_Sottosegmento]
    ADD CONSTRAINT [PK_SMMBUSRELSUBSEGMENTGROUP_Sottosegmento] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SEGMENTID] ASC, [SUBSEGMENTID] ASC);
GO

