CREATE TABLE [AX2009].[SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [EMPLID]           NVARCHAR (20) NOT NULL,
    [RESPONSIBILITYID] NVARCHAR (20) NOT NULL,
    [REFTABLEID]       INT           NOT NULL,
    [REFRECID]         BIGINT        NOT NULL,
    [RECID]            BIGINT        NOT NULL
);
GO

ALTER TABLE [AX2009].[SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente]
    ADD CONSTRAINT [PK_SMMRESPONSIBILITIESEMPLTABLE_ResponsabilitaDipendente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [EMPLID] ASC, [RESPONSIBILITYID] ASC, [REFTABLEID] ASC, [REFRECID] ASC) WITH (FILLFACTOR = 100);
GO

