CREATE TABLE [AX2009].[SYSCOMPANYUSERINFO_RelazioneUtente] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [USERID]     NVARCHAR (5)  NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [EMPLID]     NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[SYSCOMPANYUSERINFO_RelazioneUtente]
    ADD CONSTRAINT [PK_SYSCOMPANYUSERINFO_RelazioneUtente] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [USERID] ASC);
GO

