CREATE TABLE [AX2009].[TAXBOOKSECTION_SezionaleIVA] (
    [DATAAREAID]       CHAR (4)      NOT NULL,
    [TAXBOOKSECTIONID] NVARCHAR (10) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [NAME]             NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[TAXBOOKSECTION_SezionaleIVA]
    ADD CONSTRAINT [PK_TAXBOOKSECTION_SezionaleIVA] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TAXBOOKSECTIONID] ASC);
GO

