CREATE TABLE [AX2009].[TAXDATA_DettaglioIVA] (
    [DATAAREAID]   CHAR (4)         NOT NULL,
    [TAXCODE]      NVARCHAR (10)    NOT NULL,
    [TAXFROMDATE]  DATE             NOT NULL,
    [TAXTODATE]    DATE             NOT NULL,
    [RECID]        BIGINT           NOT NULL,
    [VATEXEMPTPCT] NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[TAXDATA_DettaglioIVA]
    ADD CONSTRAINT [PK_TAXDATA_DettaglioIVA] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TAXCODE] ASC, [TAXFROMDATE] ASC, [TAXTODATE] ASC);
GO

