CREATE TABLE [AX2009].[TAXTABLE_CodiceIVA] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [TAXCODE]    NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [TAXNAME]    NVARCHAR (30) NOT NULL
);
GO

ALTER TABLE [AX2009].[TAXTABLE_CodiceIVA]
    ADD CONSTRAINT [PK_TAXTABLE_CodiceIVA] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TAXCODE] ASC) WITH (FILLFACTOR = 100);
GO

