CREATE TABLE [AX2009].[TIMEZONESLIST_FusoOrario] (
    [TZENUM]          INT           NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    [TIMEZONEKEYNAME] NVARCHAR (64) NOT NULL,
    [ENUMNAME]        NVARCHAR (64) NOT NULL
);
GO

ALTER TABLE [AX2009].[TIMEZONESLIST_FusoOrario]
    ADD CONSTRAINT [PK_TIMEZONESLIST_FusoOrario] PRIMARY KEY CLUSTERED ([TZENUM] ASC);
GO

