CREATE TABLE [AX2009].[UNITCONVERT_ConversioneUnitaDiMisura] (
    [DATAAREAID] CHAR (4)         NOT NULL,
    [ITEMID]     NVARCHAR (20)    NOT NULL,
    [FROMUNIT]   NVARCHAR (10)    NOT NULL,
    [TOUNIT]     NVARCHAR (10)    NOT NULL,
    [RECID]      BIGINT           NOT NULL,
    [FACTOR]     NUMERIC (28, 12) NOT NULL,
    [MARKUP]     NUMERIC (28, 12) NOT NULL,
    [ROUNDOFF]   SMALLINT         NOT NULL
);
GO

ALTER TABLE [AX2009].[UNITCONVERT_ConversioneUnitaDiMisura]
    ADD CONSTRAINT [PK_UNITCONVERT_ConversioneUnitaDiMisura] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ITEMID] ASC, [FROMUNIT] ASC, [TOUNIT] ASC);
GO

