CREATE TABLE [AX2009].[UNIT_UnitaDiMisura] (
    [DATAAREAID]     CHAR (4)      NOT NULL,
    [UNITID]         NVARCHAR (10) NOT NULL,
    [RECID]          BIGINT        NOT NULL,
    [TXT]            NVARCHAR (60) NOT NULL,
    [UNITDECIMALS]   TINYINT       NOT NULL,
    [NPOTYPEUNITPCS] BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[UNIT_UnitaDiMisura]
    ADD CONSTRAINT [PK_UNIT_UnitaDiMisura] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [UNITID] ASC);
GO

