CREATE TABLE [AX2009].[USERINFO_Utente] (
    [ID]           NVARCHAR (5)  NOT NULL,
    [NAME]         NVARCHAR (40) NOT NULL,
    [RECID]        BIGINT        NOT NULL,
    [NETWORKALIAS] NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[USERINFO_Utente]
    ADD CONSTRAINT [PK_USERINFO_Utente] PRIMARY KEY CLUSTERED ([ID] ASC, [NAME] ASC) WITH (FILLFACTOR = 100);
GO

