CREATE TABLE [AX2009].[VENDINVOICETRANS_FattureFornitore_Riga] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [PURCHID]             NVARCHAR (20)    NOT NULL,
    [INVOICEID]           NVARCHAR (20)    NOT NULL,
    [INVOICEDATE]         DATETIME         NOT NULL,
    [NUMBERSEQUENCEGROUP] NVARCHAR (10)    NOT NULL,
    [INTERNALINVOICEID]   NVARCHAR (20)    NOT NULL,
    [LINENUM]             NUMERIC (28, 12) NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [INVENTTRANSID]       NVARCHAR (20)    NOT NULL,
    [ITEMID]              NVARCHAR (20)    NOT NULL,
    [DIMENSION]           NVARCHAR (10)    NOT NULL,
    [DIMENSION2_]         NVARCHAR (10)    NOT NULL,
    [DIMENSION3_]         NVARCHAR (10)    NOT NULL,
    [ORIGPURCHID]         NVARCHAR (20)    NOT NULL,
    [INVENTDIMID]         NVARCHAR (20)    NOT NULL,
    [DIMENSION4_]         NVARCHAR (10)    NOT NULL,
    [DIMENSION5_]         NVARCHAR (10)    NOT NULL,
    [DIMENSION6_]         NVARCHAR (10)    NOT NULL,
    [PURCHUNIT]           NVARCHAR (10)    NOT NULL,
    [QTY]                 NUMERIC (28, 12) NOT NULL,
    [INVENTQTY]           NUMERIC (28, 12) NOT NULL,
    [CURRENCYCODE]        NVARCHAR (3)     NOT NULL,
    [LINEAMOUNT]          NUMERIC (28, 12) NOT NULL,
    [LINEAMOUNTMST]       NUMERIC (28, 12) NOT NULL,
    [PURCHPRICE]          NUMERIC (28, 12) NOT NULL,
    [PRICEUNIT]           NUMERIC (28, 12) NOT NULL,
    [DISCPERCENT]         NUMERIC (28, 12) NOT NULL,
    [DISCAMOUNT]          NUMERIC (28, 12) NOT NULL
);
GO

CREATE NONCLUSTERED INDEX [IX_AX2009_VENDINVOICETRANS_FattureFornitore_Riga_DATAAREAID_INVENTTRANSID_ORIGPURCHID]
    ON [AX2009].[VENDINVOICETRANS_FattureFornitore_Riga]([DATAAREAID] ASC, [INVENTTRANSID] ASC, [ORIGPURCHID] ASC);
GO

ALTER TABLE [AX2009].[VENDINVOICETRANS_FattureFornitore_Riga]
    ADD CONSTRAINT [PK_VENDINVOICETRANS_FattureFornitore_Riga] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PURCHID] ASC, [INVOICEID] ASC, [INVOICEDATE] ASC, [NUMBERSEQUENCEGROUP] ASC, [INTERNALINVOICEID] ASC, [LINENUM] ASC);
GO

