CREATE TABLE [AX2009].[VENDSETTLEMENT_LiquidazioniFornitore] (
    [DATAAREAID]         CHAR (4)         NOT NULL,
    [TRANSDATE]          DATE             NOT NULL,
    [OFFSETTRANSVOUCHER] NVARCHAR (20)    NOT NULL,
    [ACCOUNTNUM]         NVARCHAR (20)    NOT NULL,
    [RECID]              BIGINT           NOT NULL,
    [TRANSRECID]         BIGINT           NOT NULL,
    [DUEDATE]            DATE             NOT NULL,
    [TRANSCOMPANY]       CHAR (4)         NOT NULL,
    [SETTLEAMOUNTCUR]    NUMERIC (28, 12) NOT NULL,
    [SETTLEAMOUNTMST]    NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[VENDSETTLEMENT_LiquidazioniFornitore]
    ADD CONSTRAINT [PK_VENDSETTLEMENT_LiquidazioniFornitore] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSDATE] ASC, [OFFSETTRANSVOUCHER] ASC, [ACCOUNTNUM] ASC, [RECID] ASC);
GO

