CREATE TABLE [AX2009].[VENDPAYMMODETABLE_MetodoPagamentoFornitore] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [PAYMMODE]   NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[VENDPAYMMODETABLE_MetodoPagamentoFornitore]
    ADD CONSTRAINT [PK_VENDPAYMMODETABLE_MetodoPagamentoFornitore] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PAYMMODE] ASC);
GO

