CREATE TABLE [AX2009].[VENDGROUP_FornitoreGruppo] (
    [DATAAREAID] CHAR (4)      NOT NULL,
    [VENDGROUP]  NVARCHAR (10) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    [NAME]       NVARCHAR (60) NOT NULL
);
GO

ALTER TABLE [AX2009].[VENDGROUP_FornitoreGruppo]
    ADD CONSTRAINT [PK_VENDGROUP_FornitoreGruppo] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [VENDGROUP] ASC);
GO

