CREATE TABLE [AX2009].[VENDTRANSOPEN_TransazioniFornitoreAperte] (
    [DATAAREAID] CHAR (4)         NOT NULL,
    [TRANSDATE]  DATE             NOT NULL,
    [ACCOUNTNUM] NVARCHAR (20)    NOT NULL,
    [RECID]      BIGINT           NOT NULL,
    [REFRECID]   BIGINT           NOT NULL,
    [DUEDATE]    DATE             NOT NULL,
    [AMOUNTCUR]  NUMERIC (28, 12) NOT NULL,
    [AMOUNTMST]  NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[VENDTRANSOPEN_TransazioniFornitoreAperte]
    ADD CONSTRAINT [PK_VENDTRANSOPEN_TransazioniFornitoreAperte] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSDATE] ASC, [ACCOUNTNUM] ASC, [RECID] ASC) WITH (FILLFACTOR = 100);
GO

