CREATE TABLE [AX2009].[VENDINVOICEJOUR_FattureFornitore] (
    [DATAAREAID]          CHAR (4)         NOT NULL,
    [PURCHID]             NVARCHAR (20)    NOT NULL,
    [INVOICEID]           NVARCHAR (20)    NOT NULL,
    [INVOICEDATE]         DATE             NOT NULL,
    [NUMBERSEQUENCEGROUP] NVARCHAR (10)    NOT NULL,
    [INTERNALINVOICEID]   NVARCHAR (20)    NOT NULL,
    [RECID]               BIGINT           NOT NULL,
    [ORDERACCOUNT]        NVARCHAR (20)    NOT NULL,
    [INVOICEACCOUNT]      NVARCHAR (20)    NOT NULL,
    [LEDGERVOUCHER]       NVARCHAR (20)    NOT NULL,
    [CURRENCYCODE]        NVARCHAR (3)     NOT NULL,
    [EXCHRATE]            NUMERIC (28, 12) NOT NULL,
    [INVOICEAMOUNT]       NUMERIC (28, 12) NOT NULL,
    [INVOICEAMOUNTMST]    NUMERIC (28, 12) NOT NULL,
    [SALESBALANCE]        NUMERIC (28, 12) NOT NULL,
    [SUMMARKUP]           NUMERIC (28, 12) NOT NULL,
    [SUMMARKUPMST]        NUMERIC (28, 12) NOT NULL,
    [SUMTAX]              NUMERIC (28, 12) NOT NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_AX2009_VENDINVOICEJOUR_FattureFornitore_RECID]
    ON [AX2009].[VENDINVOICEJOUR_FattureFornitore]([RECID] ASC);
GO

ALTER TABLE [AX2009].[VENDINVOICEJOUR_FattureFornitore]
    ADD CONSTRAINT [PK_VENDINVOICEJOUR_FattureFornitore] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PURCHID] ASC, [INVOICEID] ASC, [INVOICEDATE] ASC, [NUMBERSEQUENCEGROUP] ASC, [INTERNALINVOICEID] ASC);
GO

