CREATE TABLE [AX2009].[WMSORDER_OrdiniMagazzino] (
    [DATAAREAID]    CHAR (4)         NOT NULL,
    [ORDERID]       NVARCHAR (20)    NOT NULL,
    [RECID]         BIGINT           NOT NULL,
    [INVENTTRANSID] NVARCHAR (20)    NOT NULL,
    [ITEMID]        NVARCHAR (20)    NOT NULL,
    [INVENTDIMID]   NVARCHAR (20)    NOT NULL,
    [STATUS]        SMALLINT         NOT NULL,
    [QTY]           NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[WMSORDER_OrdiniMagazzino]
    ADD CONSTRAINT [PK_WMSORDER_OrdiniMagazzino] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [ORDERID] ASC);
GO

