CREATE TABLE [AX2009].[WMSPICKINGROUTE_CicloPrelievo] (
    [DATAAREAID]          CHAR (4)      NOT NULL,
    [PICKINGROUTEID]      NVARCHAR (10) NOT NULL,
    [RECID]               BIGINT        NOT NULL,
    [EXPEDITIONSTATUS]    SMALLINT      NOT NULL,
    [CURRENTPICKPALLETID] NVARCHAR (18) NOT NULL,
    [NPOWORKSPACE]        INT           NOT NULL,
    [NPODLVSTATIONID]     NVARCHAR (10) NOT NULL,
    [NPOCRSNUMID]         NVARCHAR (20) NOT NULL
);
GO

ALTER TABLE [AX2009].[WMSPICKINGROUTE_CicloPrelievo]
    ADD CONSTRAINT [PK_WMSPICKINGROUTE_CicloPrelievo] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PICKINGROUTEID] ASC);
GO

