CREATE TABLE [AX2009].[WMSPALLET_Pallet] (
    [DATAAREAID]                     CHAR (4)         NOT NULL,
    [WMSPALLETID]                    NVARCHAR (18)    NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    [WMSLOCATIONID]                  NVARCHAR (10)    NOT NULL,
    [INVENTLOCATIONID]               NVARCHAR (10)    NOT NULL,
    [NPOBUILDDATE]                   DATE             NOT NULL,
    [NPODESTROYED]                   BIT              NOT NULL,
    [NPOLASTINVENTLOCATIONIDWEIGHT]  NVARCHAR (10)    NOT NULL,
    [NPOLASTWORKSTATIONIDWEIGHT]     NVARCHAR (20)    NOT NULL,
    [NPOLASTWORKSTATIONAREAIDWEIGHT] NVARCHAR (25)    NOT NULL,
    [NPOPALLETNETWEIGHT]             NUMERIC (28, 12) NOT NULL,
    [NPOPALLETGROSSWEIGHT]           NUMERIC (28, 12) NOT NULL,
    [NPOPALLETTAREWEIGHT]            NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[WMSPALLET_Pallet]
    ADD CONSTRAINT [PK_WMSPALLET_Pallet] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [WMSPALLETID] ASC);
GO

