CREATE TABLE [AX2009].[WMSSHIPMENT_Spedizioni] (
    [DATAAREAID]            CHAR (4)      NOT NULL,
    [SHIPMENTID]            NVARCHAR (10) NOT NULL,
    [RECID]                 BIGINT        NOT NULL,
    [NPOWMSSHIPMENTSTAGING] BIT           NOT NULL
);
GO

ALTER TABLE [AX2009].[WMSSHIPMENT_Spedizioni]
    ADD CONSTRAINT [PK_WMSSHIPMENT_Spedizioni] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [SHIPMENTID] ASC);
GO

