CREATE TABLE [AX2009].[WMSTRANSPORT_TrasportiPallet] (
    [DATAAREAID]           CHAR (4)         NOT NULL,
    [TRANSPORTID]          NVARCHAR (10)    NOT NULL,
    [WMSPALLETID]          NVARCHAR (18)    NOT NULL,
    [RECID]                BIGINT           NOT NULL,
    [FROMLOCATION]         NVARCHAR (10)    NOT NULL,
    [TOLOCATION]           NVARCHAR (10)    NOT NULL,
    [OPERATOR]             NVARCHAR (20)    NOT NULL,
    [EXPEDITIONSTATUS]     SMALLINT         NOT NULL,
    [SHIPMENTID]           NVARCHAR (10)    NOT NULL,
    [FROMINVENTLOCATIONID] NVARCHAR (10)    NOT NULL,
    [TOINVENTLOCATIONID]   NVARCHAR (10)    NOT NULL,
    [TOTALQTY]             NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AX2009].[WMSTRANSPORT_TrasportiPallet]
    ADD CONSTRAINT [PK_WMSTRANSPORT_TrasportiPallet] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [TRANSPORTID] ASC, [WMSPALLETID] ASC);
GO

