CREATE TABLE [AX2009].[WRKCTRTABLE_CentroDiLavoro] (
    [DATAAREAID]       CHAR (4)         NOT NULL,
    [WRKCTRID]         NVARCHAR (10)    NOT NULL,
    [RECID]            BIGINT           NOT NULL,
    [WRKCTRGROUPID]    NVARCHAR (10)    NOT NULL,
    [NAME]             NVARCHAR (60)    NOT NULL,
    [WRKCTRTYPE]       INT              NOT NULL,
    [ISGROUP]          INT              NOT NULL,
    [CALENDARID]       NVARCHAR (10)    NOT NULL,
    [NPOERRORPCT]      NUMERIC (28, 12) NOT NULL,
    [NPOWRKCTRTYPE]    INT              NOT NULL,
    [NPOALLOYDIAMETER] NVARCHAR (10)    NOT NULL,
    [METITEMID]        NVARCHAR (20)    NOT NULL
);
GO

ALTER TABLE [AX2009].[WRKCTRTABLE_CentroDiLavoro]
    ADD CONSTRAINT [PK_WRKCTRTABLE_CentroDiLavoro] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [WRKCTRID] ASC);
GO

