SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   VIEW [Dim].[VATCodeView]
AS
SELECT DISTINCT
    CONVERT(VARCHAR(2), CAST(F.[% IVA] * 100.0 AS INT)) AS VatCode,
    CONVERT(DECIMAL(5, 2), F.[% IVA] * 100.0) AS VATPercent

FROM dbo.[Fatture$] F
WHERE F.[% IVA] IS NOT NULL;
GO
