CREATE TABLE [AS400].[KLDADB_ANPAR00F_Articolo] (
    [CDPAR]  CHAR (15)       NOT NULL,
    [TRB08]  CHAR (3)        NOT NULL,
    [ATB08]  CHAR (1)        NOT NULL,
    [NRB08]  NUMERIC (9)     NOT NULL,
    [DAB08]  NUMERIC (8)     NOT NULL,
    [AGB08]  CHAR (1)        NOT NULL,
    [DEPAR]  CHAR (30)       NOT NULL,
    [NMDIS]  CHAR (10)       NOT NULL,
    [NMCAT]  CHAR (10)       NOT NULL,
    [CLMER]  CHAR (2)        NOT NULL,
    [CLAPP]  CHAR (4)        NOT NULL,
    [TPPRA]  CHAR (1)        NOT NULL,
    [TPPRB]  CHAR (1)        NOT NULL,
    [TPPRC]  CHAR (1)        NOT NULL,
    [PESUN]  NUMERIC (9, 3)  NOT NULL,
    [UNPES]  CHAR (2)        NOT NULL,
    [UNMIS]  CHAR (2)        NOT NULL,
    [UNTEC]  CHAR (2)        NOT NULL,
    [UMFAT]  NUMERIC (9, 4)  NOT NULL,
    [UMALT]  CHAR (2)        NOT NULL,
    [UMFAA]  NUMERIC (9, 4)  NOT NULL,
    [CDPAF]  CHAR (4)        NOT NULL,
    [CONEM]  CHAR (12)       NOT NULL,
    [CONAC]  CHAR (12)       NOT NULL,
    [RECFL]  CHAR (1)        NOT NULL,
    [LIVMN]  NUMERIC (2)     NOT NULL,
    [NRCOM]  NUMERIC (5)     NOT NULL,
    [NRASS]  NUMERIC (5)     NOT NULL,
    [NROPE]  NUMERIC (5)     NOT NULL,
    [HLVMN]  NUMERIC (2)     NOT NULL,
    [DTSTR]  NUMERIC (8)     NOT NULL,
    [DTCIC]  NUMERIC (8)     NOT NULL,
    [AGCIC]  CHAR (1)        NOT NULL,
    [PREUP]  NUMERIC (15, 4) NOT NULL,
    [SCART]  NUMERIC (4, 2)  NOT NULL,
    [ALIVA]  CHAR (2)        NOT NULL,
    [PROVP]  NUMERIC (4, 2)  NOT NULL,
    [PROCP]  NUMERIC (4, 2)  NOT NULL,
    [CRRIO]  CHAR (1)        NOT NULL,
    [CRIMP]  CHAR (1)        NOT NULL,
    [CRTPR]  CHAR (1)        NOT NULL,
    [PRLOT]  NUMERIC (7)     NOT NULL,
    [TPROD]  NUMERIC (3)     NOT NULL,
    [TPROV]  NUMERIC (5, 2)  NOT NULL,
    [TREVO]  NUMERIC (3)     NOT NULL,
    [TECOP]  NUMERIC (3)     NOT NULL,
    [QMNPL]  NUMERIC (7)     NOT NULL,
    [QMXPL]  NUMERIC (7)     NOT NULL,
    [QARPL]  NUMERIC (5)     NOT NULL,
    [MGIMP]  CHAR (2)        NOT NULL,
    [INDGC]  CHAR (1)        NOT NULL,
    [CFCAL]  NUMERIC (5, 4)  NOT NULL,
    [CPROP]  CHAR (1)        NOT NULL,
    [NPROP]  NUMERIC (2)     NOT NULL,
    [GPROP]  NUMERIC (3)     NOT NULL,
    [QPROP]  NUMERIC (7)     NOT NULL,
    [CRIMT]  CHAR (1)        NOT NULL,
    [TPROE]  NUMERIC (3)     NOT NULL,
    [INDXC]  CHAR (2)        NOT NULL,
    [INDXR]  CHAR (2)        NOT NULL,
    [INDXD]  CHAR (2)        NOT NULL,
    [AS101]  CHAR (1)        NOT NULL,
    [AS102]  CHAR (1)        NOT NULL,
    [AS103]  CHAR (1)        NOT NULL,
    [AS104]  CHAR (1)        NOT NULL,
    [AS105]  CHAR (1)        NOT NULL,
    [AS201]  CHAR (2)        NOT NULL,
    [AS202]  CHAR (2)        NOT NULL,
    [AS203]  CHAR (2)        NOT NULL,
    [AS301]  CHAR (3)        NOT NULL,
    [AS302]  CHAR (3)        NOT NULL,
    [APRCO]  NUMERIC (11, 5) NOT NULL,
    [APRUM]  CHAR (2)        NOT NULL,
    [SVIAN]  NUMERIC (5)     NOT NULL,
    [SVIVE]  NUMERIC (5)     NOT NULL,
    [SVILU]  NUMERIC (5)     NOT NULL,
    [STIRA]  NUMERIC (7)     NOT NULL,
    [GIUNT]  NUMERIC (7)     NOT NULL,
    [FONDE]  NUMERIC (7)     NOT NULL,
    [FPXX1]  CHAR (1)        NOT NULL,
    [FPXX2]  CHAR (1)        NOT NULL,
    [FPXX3]  CHAR (1)        NOT NULL,
    [FPXX4]  CHAR (1)        NOT NULL,
    [FPX1X]  CHAR (2)        NOT NULL,
    [FEWA1]  CHAR (1)        NOT NULL,
    [FEWA2]  CHAR (1)        NOT NULL,
    [FEWA3]  CHAR (1)        NOT NULL,
    [FEWA4]  CHAR (1)        NOT NULL,
    [FEWA5]  CHAR (1)        NOT NULL,
    [COMEDE] CHAR (2)        NOT NULL,
    [PATNS]  NUMERIC (3)     NOT NULL,
    [PATFR]  NUMERIC (3)     NOT NULL,
    [PATTA]  NUMERIC (3)     NOT NULL,
    [PATK]   NUMERIC (3, 2)  NOT NULL,
    [CODFA]  CHAR (2)        NOT NULL,
    [FLABL]  CHAR (1)        NOT NULL,
    [IPNOC]  CHAR (8)        NOT NULL,
    [IPPEU]  NUMERIC (11, 5) NOT NULL,
    [IPSUP]  NUMERIC (11, 5) NOT NULL,
    [COIMB]  CHAR (6)        NOT NULL,
    [CDRGR]  CHAR (15)       NOT NULL,
    [CLMEX]  CHAR (2)        NOT NULL,
    [§FLG1]  CHAR (1)        NOT NULL,
    [§FLG2]  CHAR (1)        NOT NULL,
    [§FLG3]  CHAR (1)        NOT NULL,
    [§FLG4]  CHAR (1)        NOT NULL,
    [§FLG5]  CHAR (1)        NOT NULL,
    [SFAAC]  CHAR (3)        NOT NULL
);
GO

ALTER TABLE [AS400].[KLDADB_ANPAR00F_Articolo]
    ADD CONSTRAINT [PK_AS400_KLDADB_ANPAR00F_Articolo] PRIMARY KEY CLUSTERED ([CDPAR] ASC);
GO

