CREATE TABLE [AS400].[SVIBAPMET_ANCLI00F_Cliente_Metra] (
    [CDCLI]  CHAR (6)        NOT NULL,
    [TRB02]  CHAR (3)        NOT NULL,
    [ATB02]  CHAR (1)        NOT NULL,
    [NRB02]  NUMERIC (9)     NOT NULL,
    [DAB02]  NUMERIC (8)     NOT NULL,
    [AGB02]  CHAR (1)        NOT NULL,
    [RASCL]  CHAR (35)       NOT NULL,
    [INDCL]  CHAR (35)       NOT NULL,
    [LOCCL]  CHAR (20)       NOT NULL,
    [PROVN]  CHAR (2)        NOT NULL,
    [CAPAA]  CHAR (5)        NOT NULL,
    [NAZNE]  CHAR (20)       NOT NULL,
    [NAZNL]  CHAR (1)        NOT NULL,
    [CDLIN]  CHAR (3)        NOT NULL,
    [CDFIS]  CHAR (16)       NOT NULL,
    [TFATT]  CHAR (1)        NOT NULL,
    [ECONT]  CHAR (1)        NOT NULL,
    [CDLIS]  CHAR (2)        NOT NULL,
    [CDVAL]  CHAR (3)        NOT NULL,
    [FIDOC]  NUMERIC (6)     NOT NULL,
    [PRIOR]  CHAR (1)        NOT NULL,
    [RAGBF]  NUMERIC (1)     NOT NULL,
    [NRCOB]  NUMERIC (2)     NOT NULL,
    [CLISP]  CHAR (6)        NOT NULL,
    [MODSP]  CHAR (2)        NOT NULL,
    [MODCO]  CHAR (2)        NOT NULL,
    [COPAG]  CHAR (3)        NOT NULL,
    [SCOCL]  NUMERIC (4, 2)  NOT NULL,
    [SCOMD]  NUMERIC (4, 2)  NOT NULL,
    [CBAAP]  CHAR (3)        NOT NULL,
    [CAGAP]  CHAR (3)        NOT NULL,
    [CBASC]  CHAR (3)        NOT NULL,
    [IVSOS]  CHAR (1)        NOT NULL,
    [CAESE]  CHAR (2)        NOT NULL,
    [CZONA]  CHAR (2)        NOT NULL,
    [CDAGE]  CHAR (2)        NOT NULL,
    [PROVG]  NUMERIC (4, 2)  NOT NULL,
    [CATEG]  CHAR (2)        NOT NULL,
    [CLPAR]  CHAR (1)        NOT NULL,
    [VALOR]  NUMERIC (13, 2) NOT NULL,
    [PROFA]  NUMERIC (13, 2) NOT NULL,
    [IMINS]  NUMERIC (13, 2) NOT NULL,
    [NUINS]  NUMERIC (3)     NOT NULL,
    [DULFA]  NUMERIC (8)     NOT NULL,
    [DULPA]  NUMERIC (8)     NOT NULL,
    [TOTES]  NUMERIC (13, 2) NOT NULL,
    [FCLIO]  CHAR (1)        NOT NULL,
    [CPAIV]  CHAR (11)       NOT NULL,
    [NUEL1]  NUMERIC (3)     NOT NULL,
    [NUEL2]  NUMERIC (3)     NOT NULL,
    [CLFOE]  CHAR (1)        NOT NULL,
    [CATFI]  CHAR (2)        NOT NULL,
    [RASC1]  CHAR (35)       NOT NULL,
    [INDC1]  CHAR (35)       NOT NULL,
    [LOCC1]  CHAR (15)       NOT NULL,
    [BAAPP]  CHAR (40)       NOT NULL,
    [COSCL]  CHAR (2)        NOT NULL,
    [MMP01]  NUMERIC (2)     NOT NULL,
    [MMP02]  NUMERIC (2)     NOT NULL,
    [MMP03]  NUMERIC (2)     NOT NULL,
    [GGP01]  NUMERIC (2)     NOT NULL,
    [GGP02]  NUMERIC (2)     NOT NULL,
    [GGP03]  NUMERIC (2)     NOT NULL,
    [TELNR]  CHAR (20)       NOT NULL,
    [TLXNR]  CHAR (20)       NOT NULL,
    [FAXNR]  CHAR (20)       NOT NULL,
    [CAABI]  NUMERIC (5)     NOT NULL,
    [CACAB]  NUMERIC (5)     NOT NULL,
    [CLIMB]  CHAR (2)        NOT NULL,
    [CS101]  CHAR (1)        NOT NULL,
    [CS102]  CHAR (1)        NOT NULL,
    [CS103]  CHAR (1)        NOT NULL,
    [CS104]  CHAR (1)        NOT NULL,
    [CS105]  CHAR (1)        NOT NULL,
    [CS201]  CHAR (2)        NOT NULL,
    [CS202]  CHAR (2)        NOT NULL,
    [CS203]  CHAR (2)        NOT NULL,
    [CS301]  CHAR (3)        NOT NULL,
    [CS302]  CHAR (3)        NOT NULL,
    [CLSEI]  CHAR (35)       NOT NULL,
    [CLS1I]  CHAR (35)       NOT NULL,
    [CLSEL]  CHAR (20)       NOT NULL,
    [CLS1L]  CHAR (15)       NOT NULL,
    [CLSEP]  CHAR (2)        NOT NULL,
    [CLSEC]  CHAR (5)        NOT NULL,
    [TIPCLX] CHAR (1)        NOT NULL,
    [FIACC]  CHAR (1)        NOT NULL,
    [NOTRI]  CHAR (10)       NOT NULL,
    [TIPCL]  CHAR (1)        NOT NULL,
    [TEWA1]  CHAR (1)        NOT NULL,
    [TEWA2]  CHAR (1)        NOT NULL,
    [EWA21]  CHAR (1)        NOT NULL,
    [EWA22]  CHAR (1)        NOT NULL,
    [EWA23]  CHAR (1)        NOT NULL,
    [EWA31]  CHAR (1)        NOT NULL,
    [EWA32]  CHAR (1)        NOT NULL,
    [EWA33]  CHAR (1)        NOT NULL,
    [EWA41]  CHAR (1)        NOT NULL,
    [EWA42]  CHAR (1)        NOT NULL,
    [EWA43]  CHAR (1)        NOT NULL,
    [EWA51]  CHAR (1)        NOT NULL,
    [EWA52]  CHAR (1)        NOT NULL,
    [EWA53]  CHAR (1)        NOT NULL,
    [CDGRU]  CHAR (2)        NOT NULL,
    [P1OEWA] CHAR (3)        NOT NULL,
    [P2OEWA] CHAR (3)        NOT NULL,
    [P3OEWA] CHAR (3)        NOT NULL,
    [P4OEWA] CHAR (3)        NOT NULL,
    [P5OEWA] CHAR (3)        NOT NULL,
    [AODLO]  CHAR (5)        NOT NULL,
    [FCFL1]  CHAR (1)        NOT NULL,
    [FCFL2]  CHAR (1)        NOT NULL,
    [FCFL3]  CHAR (1)        NOT NULL,
    [FCFL4]  CHAR (1)        NOT NULL,
    [FCFL5]  CHAR (1)        NOT NULL,
    [CDCAN]  CHAR (1)        NOT NULL
);
GO

ALTER TABLE [AS400].[SVIBAPMET_ANCLI00F_Cliente_Metra]
    ADD CONSTRAINT [PK_AS400_SVIBAPMET_ANCLI00F_Cliente_Metra] PRIMARY KEY CLUSTERED ([CDCLI] ASC);
GO

