CREATE TABLE [AS400].[SVIBAPMET_ANFOR00F_Fornitore_Metra] (
    [CDFOR] CHAR (6)        NOT NULL,
    [TRB05] CHAR (3)        NOT NULL,
    [ATB05] CHAR (1)        NOT NULL,
    [NRB05] NUMERIC (9)     NOT NULL,
    [DAB05] NUMERIC (8)     NOT NULL,
    [AGB05] CHAR (1)        NOT NULL,
    [RASFO] CHAR (35)       NOT NULL,
    [INDFO] CHAR (35)       NOT NULL,
    [LOCFO] CHAR (20)       NOT NULL,
    [PROVN] CHAR (2)        NOT NULL,
    [CAPAA] CHAR (5)        NOT NULL,
    [NAZNE] CHAR (20)       NOT NULL,
    [NAZNL] CHAR (1)        NOT NULL,
    [CDFIS] CHAR (16)       NOT NULL,
    [CDVAL] CHAR (3)        NOT NULL,
    [MODSP] CHAR (2)        NOT NULL,
    [MODCO] CHAR (2)        NOT NULL,
    [COPAG] CHAR (3)        NOT NULL,
    [CATEG] CHAR (2)        NOT NULL,
    [FOPAR] CHAR (1)        NOT NULL,
    [PROFA] NUMERIC (13, 2) NOT NULL,
    [DULFA] NUMERIC (8)     NOT NULL,
    [DULPA] NUMERIC (8)     NOT NULL,
    [TOTES] NUMERIC (13, 2) NOT NULL,
    [FFORN] CHAR (1)        NOT NULL,
    [CPAIV] CHAR (11)       NOT NULL,
    [NUEL1] NUMERIC (3)     NOT NULL,
    [NUEL2] NUMERIC (3)     NOT NULL,
    [CBAPA] CHAR (3)        NOT NULL,
    [CAGPA] CHAR (3)        NOT NULL,
    [CLFOE] CHAR (1)        NOT NULL,
    [FODOG] CHAR (1)        NOT NULL,
    [CATFI] CHAR (2)        NOT NULL,
    [RASF1] CHAR (35)       NOT NULL,
    [INDF1] CHAR (35)       NOT NULL,
    [LOCF1] CHAR (15)       NOT NULL,
    [TELNR] CHAR (20)       NOT NULL,
    [TLXNR] CHAR (20)       NOT NULL,
    [FAXNR] CHAR (20)       NOT NULL,
    [XCABI] NUMERIC (5)     NOT NULL,
    [XCCAB] NUMERIC (5)     NOT NULL,
    [XCONT] CHAR (12)       NOT NULL,
    [XBABO] CHAR (35)       NOT NULL,
    [FLIMB] CHAR (2)        NOT NULL,
    [FS101] CHAR (1)        NOT NULL,
    [FS102] CHAR (1)        NOT NULL,
    [FS103] CHAR (1)        NOT NULL,
    [FS104] CHAR (1)        NOT NULL,
    [FS105] CHAR (1)        NOT NULL,
    [FS201] CHAR (2)        NOT NULL,
    [FS202] CHAR (2)        NOT NULL,
    [FS203] CHAR (2)        NOT NULL,
    [FS301] CHAR (3)        NOT NULL,
    [FS302] CHAR (3)        NOT NULL,
    [CAESE] CHAR (2)        NOT NULL
);
GO

ALTER TABLE [AS400].[SVIBAPMET_ANFOR00F_Fornitore_Metra]
    ADD CONSTRAINT [PK_AS400_SVIBAPMET_ANFOR00F_Fornitore_Metra] PRIMARY KEY CLUSTERED ([CDFOR] ASC);
GO

