CREATE TABLE [AS400].[UNICA_MET_CSFAT00F_Fatture_Metra] (
    [IDAzienda] VARCHAR (4)     NOT NULL,
    [FTCDAZ]    CHAR (3)        NOT NULL,
    [FTCONT]    CHAR (12)       NOT NULL,
    [FTESER]    CHAR (4)        NOT NULL,
    [FTANNO]    NUMERIC (4)     NOT NULL,
    [FTMESE]    NUMERIC (2)     NOT NULL,
    [FTTCLF]    CHAR (1)        NOT NULL,
    [FTCLIF]    CHAR (9)        NOT NULL,
    [FTCOST]    CHAR (3)        NOT NULL,
    [FTVALU]    CHAR (3)        NOT NULL,
    [FTDIVI]    CHAR (3)        NOT NULL,
    [FTIMPD]    NUMERIC (15, 2) NOT NULL,
    [FTIMPE]    NUMERIC (15, 2) NOT NULL,
    [FTIMPR]    NUMERIC (15, 2) NOT NULL,
    [FTIMCD]    NUMERIC (15, 2) NOT NULL,
    [FTIMCE]    NUMERIC (15, 2) NOT NULL,
    [FTIMCR]    NUMERIC (15, 2) NOT NULL,
    [FTVALE]    CHAR (3)        NOT NULL,
    [FTVALR]    CHAR (3)        NOT NULL,
    [FTCDAG]    CHAR (3)        NOT NULL,
    [FTBLKF]    CHAR (3)        NOT NULL,
    [FTBLKV]    CHAR (3)        NOT NULL
);
GO

CREATE STATISTICS [FTCDAG]
    ON [AS400].[UNICA_MET_CSFAT00F_Fatture_Metra]([FTCDAG]);
GO

CREATE STATISTICS [FTVALU]
    ON [AS400].[UNICA_MET_CSFAT00F_Fatture_Metra]([FTVALU]);
GO

CREATE STATISTICS [FTCDAZ]
    ON [AS400].[UNICA_MET_CSFAT00F_Fatture_Metra]([FTCDAZ]);
GO

CREATE STATISTICS [FTDIVI]
    ON [AS400].[UNICA_MET_CSFAT00F_Fatture_Metra]([FTDIVI]);
GO

CREATE STATISTICS [FTCONT]
    ON [AS400].[UNICA_MET_CSFAT00F_Fatture_Metra]([FTCONT]);
GO

ALTER TABLE [AS400].[UNICA_MET_CSFAT00F_Fatture_Metra]
    ADD CONSTRAINT [PK_AS400_UNICA_MET_CSFAT00F_Fatture_Metra] PRIMARY KEY CLUSTERED ([IDAzienda] ASC, [FTCDAZ] ASC, [FTTCLF] ASC, [FTANNO] ASC, [FTMESE] ASC, [FTCLIF] ASC, [FTDIVI] ASC, [FTCDAG] ASC, [FTVALU] ASC, [FTCONT] ASC);
GO

