CREATE TABLE [AXBETA].[NPOCRMPROPOSALITEM_ArticoliProposti] (
    [DATAAREAID] CHAR (4)         NOT NULL,
    [PROJID]     NVARCHAR (10)    NOT NULL,
    [PRODLINEID] NVARCHAR (40)    NOT NULL,
    [RECID]      BIGINT           NOT NULL,
    [QTY]        NUMERIC (28, 12) NOT NULL,
    [MQ]         NUMERIC (28, 12) NOT NULL,
    [KG]         NUMERIC (28, 12) NOT NULL,
    [EURO]       NUMERIC (28, 12) NOT NULL
);
GO

ALTER TABLE [AXBETA].[NPOCRMPROPOSALITEM_ArticoliProposti]
    ADD CONSTRAINT [PK_NPOCRMPROPOSALITEM_ArticoliProposti] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PROJID] ASC, [PRODLINEID] ASC, [RECID] ASC);
GO

