CREATE TABLE [AXBETA].[NPOCRMPROJBUSREL_Soggetto] (
    [DATAAREAID]    CHAR (4)      NOT NULL,
    [PROJID]        NVARCHAR (10) NOT NULL,
    [BUSRELTYPE]    SMALLINT      NOT NULL,
    [BUSRELACCOUNT] NVARCHAR (20) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    [CHOSEN]        BIT           NOT NULL
);
GO

ALTER TABLE [AXBETA].[NPOCRMPROJBUSREL_Soggetto]
    ADD CONSTRAINT [PK_NPOCRMPROJBUSREL_Soggetto] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PROJID] ASC, [BUSRELTYPE] ASC, [BUSRELACCOUNT] ASC);
GO

