CREATE TABLE [AXBETA].[PROJTABLE_Targa] (
    [DATAAREAID]                 CHAR (4)      NOT NULL,
    [PROJID]                     NVARCHAR (10) NOT NULL,
    [RECID]                      BIGINT        NOT NULL,
    [NAME]                       NVARCHAR (60) NOT NULL,
    [NPOCRMACQUISITION]          SMALLINT      NOT NULL,
    [NPOCRMCONTRACTACQUIRED]     SMALLINT      NOT NULL,
    [NPOCRMCONTRACTTYPE]         SMALLINT      NOT NULL,
    [NPOCRMSTATUS]               SMALLINT      NOT NULL,
    [NPOCRMYEAREND]              INT           NOT NULL,
    [NPOCRMEMPLNAME_MAP]         NVARCHAR (60) NOT NULL,
    [NPOCRMEMPL_MAP]             NVARCHAR (20) NOT NULL,
    [NPOCRMCREATEDDATETIME]      DATETIME      NOT NULL,
    [NPOCRMMODIFIEDDATETIME]     DATETIME      NOT NULL,
    [NPOCRMACQUISITIONFAILCAUSE] SMALLINT      NOT NULL
);
GO

ALTER TABLE [AXBETA].[PROJTABLE_Targa]
    ADD CONSTRAINT [PK_PROJTABLE_Targa] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [PROJID] ASC);
GO

