CREATE TABLE [AXBETA].[SMMBUSRELTABLE_RelazioneCommerciale] (
    [DATAAREAID]    CHAR (4)       NOT NULL,
    [BUSRELACCOUNT] NVARCHAR (20)  NOT NULL,
    [RECID]         BIGINT         NOT NULL,
    [NAME]          NVARCHAR (100) NOT NULL
);
GO

ALTER TABLE [AXBETA].[SMMBUSRELTABLE_RelazioneCommerciale]
    ADD CONSTRAINT [PK_SMMBUSRELTABLE_RelazioneCommerciale] PRIMARY KEY CLUSTERED ([DATAAREAID] ASC, [BUSRELACCOUNT] ASC);
GO

