CREATE TABLE [AXBETA].[SRSANALYSISENUMS_Etichetta] (
    [ENUMNAME]      NVARCHAR (100) NOT NULL,
    [ENUMITEMVALUE] INT            NOT NULL,
    [LANGUAGEID]    NVARCHAR (7)   NOT NULL,
    [RECID]         BIGINT         NOT NULL,
    [ENUMITEMLABEL] NVARCHAR (255) NOT NULL
);
GO

ALTER TABLE [AXBETA].[SRSANALYSISENUMS_Etichetta]
    ADD CONSTRAINT [PK_SRSANALYSISENUMS_Etichetta] PRIMARY KEY CLUSTERED ([ENUMNAME] ASC, [ENUMITEMVALUE] ASC, [LANGUAGEID] ASC);
GO

