USE tools;
GO

/*
SET NOEXEC OFF;
--*/ SET NOEXEC ON;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = N'Common')
BEGIN
	EXEC ('CREATE SCHEMA Common AUTHORIZATION dbo;');
END;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = N'Administration')
BEGIN
	EXEC ('CREATE SCHEMA Administration AUTHORIZATION dbo;');
END;
GO
