CREATE PARTITION SCHEME [ups_BOMCalcTables]
    AS PARTITION [upf_BOMCalcTables]
    TO ([PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY]);
GO

