CREATE TABLE [dbo].[original$]
(
[Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Given Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Additional Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Family Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Yomi Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Given Name Yomi] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Additional Name Yomi] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Family Name Yomi] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name Prefix] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name Suffix] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Initials] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nickname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Short Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Maiden Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [datetime] NULL,
[Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Location] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing Information] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Directory Server] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mileage] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Hobby] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sensitivity] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Priority] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Photo] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Membership] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 1 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 1 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 2 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 2 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 3 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 3 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 4 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 4 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 5 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 5 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 6 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail 6 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IM 1 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IM 1 - Service] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IM 1 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 1 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 1 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 2 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 2 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 3 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 3 - Value] [float] NULL,
[Phone 4 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 4 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 5 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 5 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 6 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone 6 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - Formatted] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - PO Box] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - Region] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - Postal Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1 - Extended Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - Formatted] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - Street] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - PO Box] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - Region] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - Postal Code] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - Country] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 2 - Extended Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Yomi Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Symbol] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Location] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 1 - Job Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Yomi Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Department] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Symbol] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Location] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Organization 2 - Job Description] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website 1 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website 1 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website 2 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website 2 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Event 1 - Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Event 1 - Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
