CREATE TABLE [Dim].[VATCode]
(
[VATCodeKey] [int] NOT NULL IDENTITY(1, 1),
[VATCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VATPercent] [decimal] (5, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [Dim].[VATCode] ADD CONSTRAINT [PK_Dim_VATCode] PRIMARY KEY CLUSTERED  ([VATCodeKey]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Dim_VATCode_VATCode] ON [Dim].[VATCode] ([VATCode]) ON [PRIMARY]
GO
