
CREATE PROCEDURE AXBETA.usp_Create_SRSANALYSISENUMS_Etichetta
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AXBETA.SRSANALYSISENUMS_Etichetta (
    -- Chiavi
    ENUMNAME        NVARCHAR(100) NOT NULL,
    ENUMITEMVALUE        INT NOT NULL,
    LANGUAGEID        NVARCHAR(7) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni
    ENUMITEMLABEL        NVARCHAR(255) NOT NULL


    -- Constraint
    CONSTRAINT PK_SRSANALYSISENUMS_Etichetta PRIMARY KEY CLUSTERED (
        ENUMNAME,
        ENUMITEMVALUE,
        LANGUAGEID
    )
);

END;
GO

