
CREATE PROCEDURE AXBETA.usp_AddIndexes_SMMBUSRELTABLE_RelazioneCommerciale
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AXBETA_SMMBUSRELTABLE_RelazioneCommerciale_ ON AXBETA.SMMBUSRELTABLE_RelazioneCommerciale () INCLUDE();

END;
GO

