
CREATE PROCEDURE AXBETA.usp_Merge_NPOCRMCONFIRMEDITEM_ArticoliConfermati
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AXBETA.NPOCRMCONFIRMEDITEM_ArticoliConfermati', N'U') IS NULL
BEGIN
    EXEC AXBETA.usp_Create_NPOCRMCONFIRMEDITEM_ArticoliConfermati;
    EXEC AXBETA.usp_AddIndexes_NPOCRMCONFIRMEDITEM_ArticoliConfermati;
END;

MERGE INTO AXBETA.NPOCRMCONFIRMEDITEM_ArticoliConfermati AS TGT
USING AXBETA.NPOCRMCONFIRMEDITEM_ArticoliConfermatiView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PROJID = TGT.PROJID AND SRC.PRODLINEID = TGT.PRODLINEID AND SRC.RECID = TGT.RECID
WHEN MATCHED AND (TGT.QTY <> SRC.QTY OR TGT.MQ <> SRC.MQ OR TGT.KG <> SRC.KG OR TGT.EURO <> SRC.EURO)
  THEN UPDATE SET TGT.QTY = SRC.QTY, TGT.MQ = SRC.MQ, TGT.KG = SRC.KG, TGT.EURO = SRC.EURO
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PROJID, PRODLINEID, RECID, QTY, MQ, KG, EURO)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AXBETA.NPOCRMCONFIRMEDITEM_ArticoliConfermati' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PROJID = ' + CAST(COALESCE(inserted.PROJID, deleted.PROJID) AS NVARCHAR) + ' - ' + 'PRODLINEID = ' + CAST(COALESCE(inserted.PRODLINEID, deleted.PRODLINEID) AS NVARCHAR) + ' - ' + 'RECID = ' + CAST(COALESCE(inserted.RECID, deleted.RECID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

