
CREATE PROCEDURE AXBETA.usp_Merge_NPOCRMPROJBUSREL_Soggetto
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AXBETA.NPOCRMPROJBUSREL_Soggetto', N'U') IS NULL
BEGIN
    EXEC AXBETA.usp_Create_NPOCRMPROJBUSREL_Soggetto;
    EXEC AXBETA.usp_AddIndexes_NPOCRMPROJBUSREL_Soggetto;
END;

MERGE INTO AXBETA.NPOCRMPROJBUSREL_Soggetto AS TGT
USING AXBETA.NPOCRMPROJBUSREL_SoggettoView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PROJID = TGT.PROJID AND SRC.BUSRELTYPE = TGT.BUSRELTYPE AND SRC.BUSRELACCOUNT = TGT.BUSRELACCOUNT
WHEN MATCHED AND (TGT.CHOSEN <> SRC.CHOSEN)
  THEN UPDATE SET TGT.CHOSEN = SRC.CHOSEN
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PROJID, BUSRELTYPE, BUSRELACCOUNT, RECID, CHOSEN)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AXBETA.NPOCRMPROJBUSREL_Soggetto' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PROJID = ' + CAST(COALESCE(inserted.PROJID, deleted.PROJID) AS NVARCHAR) + ' - ' + 'BUSRELTYPE = ' + CAST(COALESCE(inserted.BUSRELTYPE, deleted.BUSRELTYPE) AS NVARCHAR) + ' - ' + 'BUSRELACCOUNT = ' + CAST(COALESCE(inserted.BUSRELACCOUNT, deleted.BUSRELACCOUNT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

