
CREATE PROCEDURE AXBETA.usp_AddIndexes_NPOCRMPROJBUSREL_Soggetto
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AXBETA_NPOCRMPROJBUSREL_Soggetto_ ON AXBETA.NPOCRMPROJBUSREL_Soggetto () INCLUDE();

END;
GO

