
CREATE PROCEDURE AXBETA.usp_AddIndexes_NPOCRMCONFIRMEDITEM_ArticoliConfermati
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AXBETA_NPOCRMCONFIRMEDITEM_ArticoliConfermati_ ON AXBETA.NPOCRMCONFIRMEDITEM_ArticoliConfermati () INCLUDE();

END;
GO

