
CREATE PROCEDURE AXBETA.usp_AddIndexes_SRSANALYSISENUMS_Etichetta
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AXBETA_SRSANALYSISENUMS_Etichetta_ ON AXBETA.SRSANALYSISENUMS_Etichetta () INCLUDE();

END;
GO

