
CREATE PROCEDURE AXBETA.usp_AddIndexes_NPOCRMPROPOSALITEM_ArticoliProposti
AS
BEGIN
SET NOCOUNT ON;

--CREATE NONCLUSTERED INDEX IX_AXBETA_NPOCRMPROPOSALITEM_ArticoliProposti_ ON AXBETA.NPOCRMPROPOSALITEM_ArticoliProposti () INCLUDE();

END;
GO

