
CREATE PROCEDURE AXBETA.usp_Merge_PROJTABLE_Targa
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AXBETA.PROJTABLE_Targa', N'U') IS NULL
BEGIN
    EXEC AXBETA.usp_Create_PROJTABLE_Targa;
    EXEC AXBETA.usp_AddIndexes_PROJTABLE_Targa;
END;

MERGE INTO AXBETA.PROJTABLE_Targa AS TGT
USING AXBETA.PROJTABLE_TargaView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.PROJID = TGT.PROJID
WHEN MATCHED AND (TGT.NAME <> SRC.NAME OR TGT.NPOCRMACQUISITION <> SRC.NPOCRMACQUISITION OR TGT.NPOCRMCONTRACTACQUIRED <> SRC.NPOCRMCONTRACTACQUIRED OR TGT.NPOCRMCONTRACTTYPE <> SRC.NPOCRMCONTRACTTYPE OR TGT.NPOCRMSTATUS <> SRC.NPOCRMSTATUS OR TGT.NPOCRMYEAREND <> SRC.NPOCRMYEAREND OR TGT.NPOCRMEMPLNAME_MAP <> SRC.NPOCRMEMPLNAME_MAP OR TGT.NPOCRMEMPL_MAP <> SRC.NPOCRMEMPL_MAP OR TGT.NPOCRMCREATEDDATETIME <> SRC.NPOCRMCREATEDDATETIME OR TGT.NPOCRMMODIFIEDDATETIME <> SRC.NPOCRMMODIFIEDDATETIME OR TGT.NPOCRMACQUISITIONFAILCAUSE <> SRC.NPOCRMACQUISITIONFAILCAUSE)
  THEN UPDATE SET TGT.NAME = SRC.NAME, TGT.NPOCRMACQUISITION = SRC.NPOCRMACQUISITION, TGT.NPOCRMCONTRACTACQUIRED = SRC.NPOCRMCONTRACTACQUIRED, TGT.NPOCRMCONTRACTTYPE = SRC.NPOCRMCONTRACTTYPE, TGT.NPOCRMSTATUS = SRC.NPOCRMSTATUS, TGT.NPOCRMYEAREND = SRC.NPOCRMYEAREND, TGT.NPOCRMEMPLNAME_MAP = SRC.NPOCRMEMPLNAME_MAP, TGT.NPOCRMEMPL_MAP = SRC.NPOCRMEMPL_MAP, TGT.NPOCRMCREATEDDATETIME = SRC.NPOCRMCREATEDDATETIME, TGT.NPOCRMMODIFIEDDATETIME = SRC.NPOCRMMODIFIEDDATETIME, TGT.NPOCRMACQUISITIONFAILCAUSE = SRC.NPOCRMACQUISITIONFAILCAUSE
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, PROJID, RECID, NAME, NPOCRMACQUISITION, NPOCRMCONTRACTACQUIRED, NPOCRMCONTRACTTYPE, NPOCRMSTATUS, NPOCRMYEAREND, NPOCRMEMPLNAME_MAP, NPOCRMEMPL_MAP, NPOCRMCREATEDDATETIME, NPOCRMMODIFIEDDATETIME, NPOCRMACQUISITIONFAILCAUSE)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AXBETA.PROJTABLE_Targa' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'PROJID = ' + CAST(COALESCE(inserted.PROJID, deleted.PROJID) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

