
CREATE PROCEDURE AXBETA.usp_Merge_SMMBUSRELTABLE_RelazioneCommerciale
AS
BEGIN
SET NOCOUNT ON;

IF OBJECT_ID(N'AXBETA.SMMBUSRELTABLE_RelazioneCommerciale', N'U') IS NULL
BEGIN
    EXEC AXBETA.usp_Create_SMMBUSRELTABLE_RelazioneCommerciale;
    EXEC AXBETA.usp_AddIndexes_SMMBUSRELTABLE_RelazioneCommerciale;
END;

MERGE INTO AXBETA.SMMBUSRELTABLE_RelazioneCommerciale AS TGT
USING AXBETA.SMMBUSRELTABLE_RelazioneCommercialeView (nolock) AS SRC
ON SRC.DATAAREAID = TGT.DATAAREAID AND SRC.BUSRELACCOUNT = TGT.BUSRELACCOUNT
WHEN MATCHED AND (TGT.NAME <> SRC.NAME)
  THEN UPDATE SET TGT.NAME = SRC.NAME
WHEN NOT MATCHED
  THEN INSERT VALUES (DATAAREAID, BUSRELACCOUNT, RECID, NAME)
WHEN NOT MATCHED BY SOURCE
  THEN DELETE
OUTPUT
    CURRENT_TIMESTAMP AS merge_datetime,
    $action AS merge_action,
    'AXBETA.SMMBUSRELTABLE_RelazioneCommerciale' AS full_olap_table_name,
    'DATAAREAID = ' + CAST(COALESCE(inserted.DATAAREAID, deleted.DATAAREAID) AS NVARCHAR) + ' - ' + 'BUSRELACCOUNT = ' + CAST(COALESCE(inserted.BUSRELACCOUNT, deleted.BUSRELACCOUNT) AS NVARCHAR) AS primary_key_description
INTO audit.merge_log_details;

END;
GO

