
CREATE PROCEDURE AXBETA.usp_Create_NPOCRMPROJBUSREL_Soggetto
AS
BEGIN
SET NOCOUNT ON;

CREATE TABLE AXBETA.NPOCRMPROJBUSREL_Soggetto (
    -- Chiavi
    DATAAREAID        CHAR(4) NOT NULL,
    PROJID        NVARCHAR(10) NOT NULL,
    BUSRELTYPE        SMALLINT NOT NULL,
    BUSRELACCOUNT        NVARCHAR(20) NOT NULL,
    RECID        BIGINT NOT NULL,

    -- Dimensioni

    -- Misure
    CHOSEN        BIT NOT NULL

    -- Constraint
    CONSTRAINT PK_NPOCRMPROJBUSREL_Soggetto PRIMARY KEY CLUSTERED (
        DATAAREAID,
        PROJID,
        BUSRELTYPE,
        BUSRELACCOUNT
    )
);

END;
GO

